Repository SatelliteQE/robottelo, pull requests merged in 2018-11, with the labels that each got.

#6432 UI port compute resource EC2 tests
  tests/foreman/ui/test_computeresource_ec2.py
  tests/foreman/ui_airgun/test_computeresource_ec2.py
Labels: 6.4, UI, review

#6411 Added deploy method to cli.VirtWhoConfig
  robottelo/cli/virt_who_config.py
Labels: review

#6353 added tests for custom cron sync plan 6.5 feature
  robottelo/cli/factory.py
  robottelo/constants.py
  robottelo/datafactory.py
  tests/foreman/api/test_syncplan.py
  tests/foreman/cli/test_syncplan.py
  tests/robottelo/test_datafactory.py
Labels: 6.5, review

#6454 Async key error fix 6.2.z
  tests/upgrades/test_client.py
Labels: review

#6453 Fix async key error in 6.3.z
  tests/upgrades/test_client.py
Labels: review

#6455 ansible rex setupclass update
  tests/foreman/cli/test_remoteexecution.py
Labels: 6.5, CLI, test-failure

#6445 fixed cli subnet queries
  tests/foreman/cli/test_location.py
  tests/foreman/cli/test_subnet.py
Labels: 6.5, CLI, review

#6447 fix duplicate help test
  tests/foreman/cli/test_organization.py
Labels: 6.5, CLI, review

#6425 Port all sync plan tests
  robottelo/api/utils.py
  tests/foreman/ui/test_syncplan.py
  tests/foreman/ui_airgun/test_syncplan.py
Labels: review

#6252 [6.5] UI port airgun discovered hosts tests
  robottelo/api/utils.py
  tests/foreman/ui/test_discoveredhost.py
  tests/foreman/ui_airgun/conftest.py
  tests/foreman/ui_airgun/test_discoveredhost.py
Labels: 6.5, UI, review

#6466 [6.3.z] Remove Transitions settings (removed since Sat6.3)
  robottelo.properties.sample
  robottelo/config/base.py
Labels: review

#6465 [6.4.z] Remove Transitions settings (removed since Sat6.3)
  robottelo.properties.sample
  robottelo/config/base.py
Labels: review

#6464 Remove Transitions settings
  robottelo.properties.sample
  robottelo/config/base.py
Labels: review

#6458 subnet keyword errors
  tests/foreman/cli/test_location.py
  tests/foreman/cli/test_subnet.py
Labels: 6.5, CLI, review

#6470 Automation tools requirement as Upgrade dependency
  requirements.txt
Labels: review

#6469 Automation tools requirement as Upgrade dependency
  requirements.txt
Labels: review

#6468 Automation tools requirement as Upgrade dependency
  requirements.txt
Labels: review

#6449 Port more CV tests
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui_airgun/test_contentview.py
Labels: review

#6463 Added Sync Plan Migration Scenario for 6.5 migrating from Pulp to Ka…
  tests/upgrades/test_syncplan.py
Labels: review

#6461 updated asserts for cli activationkeys
  tests/foreman/cli/test_activationkey.py
Labels: 6.5, CLI, review, test-failure

#6460 fixed default interval for make_syncplan
  robottelo/cli/factory.py
Labels: 6.5, CLI, review

#6478 Fixes #6462 "update fedora ostree repos used in automation" for 6.4.z branch
  robottelo/constants.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_ostreebranch.py
  tests/foreman/cli/test_repository.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui_airgun/test_sync.py
Labels: review

#6476 Fixes #6462 "update fedora ostree repos used in automation"
  robottelo/constants.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_ostreebranch.py
  tests/foreman/cli/test_repository.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui_airgun/test_contentview.py
  tests/foreman/ui_airgun/test_repository.py
  tests/foreman/ui_airgun/test_sync.py
Labels: review

#6474 Add product end to end scenario
  tests/foreman/ui_airgun/test_product.py
Labels: review

#6264 Added one test for compliance policies
  tests/foreman/cli/test_oscap.py
Labels: 6.4, CLI, DO NOT MERGE, review

#6480 Revert "Added one test for compliance policies"
  tests/foreman/cli/test_oscap.py
Labels: review

#6481 Added one test for compliance policies
  tests/foreman/cli/test_oscap.py
Labels: review

#6471 In Satellite 6.2, bug 1427192 was resolved as CLOSED(NEXTRELEASE)
  tests/foreman/api/test_host.py
Labels: 6.2, review

#6482 Add lce end to end scenario + 1 port
  tests/foreman/ui/test_lifecycleenvironment.py
  tests/foreman/ui_airgun/test_lifecycleenvironment.py
Labels: review

#6491 Fix 6.5 syncplan scenario failing
  tests/upgrades/test_syncplan.py
Labels: review

#6499 fixing assert in test_negative_rename_sat_wrong_passwd
  tests/foreman/sys/test_rename.py
Labels: 6.5, SYS, review

#6417 Update index.rst
  docs/index.rst
Labels: review

#6496 Fix user group test case
  tests/foreman/ui_airgun/test_usergroup.py
Labels: review

#6500 More loc fixes
  tests/foreman/ui_airgun/test_dashboard.py
  tests/foreman/ui_airgun/test_subnet.py
Labels: review

#6467 [6.5 Feature] [ETE] Content View Export Import Automated
  robottelo/cli/contentview.py
  tests/foreman/cli/test_satellitesync.py
Labels: review

#6506 fixes #6257 - fixing the sed expression
  tests/foreman/cli/test_discoveredhost.py
Labels: pending-cherry-pick, review

#6507 [6.4.z] fixes #6257 - fixing the sed expression
  tests/foreman/cli/test_discoveredhost.py
Labels: review

#6493 Automated 'tests/upgrades/test_user.py' for scenario_positive_create_sshkey_in_existing_users
  tests/upgrades/test_user.py
Labels: review

#6510 Updated installer options as per 6.4.z version
  tests/foreman/installer/test_installer.py
Labels: review

#6472 Fixes the reposets breakage without product id
  robottelo/api/utils.py
  tests/foreman/api/test_repository_set.py
Labels: 6.5, API, Bug, review

#6504 handle occasional race condition when deleting org
  tests/foreman/cli/test_organization.py
Labels: 6.5, CLI, review

#6300 Added test_rhai_navigation
  tests/foreman/rhai/test_rhai.py
Labels: UI, review
