Repository SatelliteQE/robottelo, pull requests merged in 2018-05, with the labels that each got.

#5935 Moved 5 UI AK tests to ui_airgun; small fixes for better airgun support
  Makefile
  robottelo.properties.sample
  robottelo/config/base.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui_airgun/test_activationkey.py
Labels: review

#5738 [6.3] add bulk install packages
  tests/foreman/api/test_errata.py
Labels: 6.3, API, qe_test_coverage, review

#5938 adding make test-foreman-upgrade
  Makefile
Labels: review

#5942 Move some User tests to new framework
  robottelo/constants.py
  tests/foreman/ui/test_user.py
  tests/foreman/ui_airgun/test_user.py
Labels: review

#5934 Ansible REX stubs
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/ui/test_remoteexecution.py
Labels: review

#5951 [6.3.z] AttributeError: 'dict' object has no attribute 'iteritems'
  robottelo/test.py
  tests/foreman/api/test_classparameters.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_docker.py
  tests/foreman/cli/test_domain.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_subnet.py
  tests/foreman/installer/test_installer.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_classparameters.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_setting.py
  tests/foreman/ui/test_template.py
Labels: 6.3, python3, review

#5946 fixed subnet-related assertions to point to the correct entity keys
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/cli/test_hostgroup.py
Labels: 6.4, CLI, test-failure

#5864 Add the ability to run robottelo in a container!
  Dockerfile
Labels: enhancement

#5967 Updates the requirements as per the feature name
  tests/foreman/ui/test_computeresource_aws_govcloud.py
Labels: 6.4, ready, review

#5968 [6.3.z] fix invalid value for Integer
  tests/foreman/cli/test_role.py
Labels: 6.3, CLI, python3, review

#5972 Rhev testcase fixes issue #5971
  tests/foreman/ui/test_computeresource_rhev.py
Labels: 6.3, UI, test-failure

#5991 Insights Deployment via Ansible stubs
  tests/foreman/rhai/test_rhai.py
Labels: review

#5990 Added new types and permissions
  robottelo/constants.py
Labels: 6.4, review

#5975 Ported first UI CV test with publish & promote to airgun
  robottelo/api/utils.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui_airgun/test_contentview.py
Labels: 6.4, UI

#5987 [6.3] cherry-pick hammer auth test for upgrade
  tests/foreman/cli/test_auth.py
Labels: 6.3

#6000 updated 2 assertion messages for cli tests to match again
  tests/foreman/cli/test_activationkey.py
  tests/foreman/cli/test_realm.py
Labels: 6.4, Low, test-failure

#5999 Ported 7 UI CV tests to airgun; refactored tests according to recent airgun changes; small fixes
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui_airgun/test_activationkey.py
  tests/foreman/ui_airgun/test_architecture.py
  tests/foreman/ui_airgun/test_computeprofiles.py
  tests/foreman/ui_airgun/test_contentcredential.py
  tests/foreman/ui_airgun/test_contentview.py
  tests/foreman/ui_airgun/test_hostcollection.py
  tests/foreman/ui_airgun/test_operatingsystem.py
  tests/foreman/ui_airgun/test_provisioningtemplate.py
  tests/foreman/ui_airgun/test_subnet.py
  tests/foreman/ui_airgun/test_syncplan.py
  tests/foreman/ui_airgun/test_user.py
Labels: 6.4, UI

#5985 [6.3.z] cherry-pick adding make test-foreman-upgrade
  Makefile
Labels: 6.3

#6027 ssh - dump stdout and stderr on command timeout (for better debugging)
  robottelo/ssh.py
Labels: RFE, review

#5823 Added automation coverage for t1 osp compute resource
  robottelo.properties.sample
  robottelo/config/base.py
  tests/foreman/cli/test_computeresource_osp.py
Labels: 6.4, CLI, ready, review

#5986 [6.2.z] cherry-pick adding make test-foreman-upgrade
  Makefile
Labels: 6.2
