Repository SatelliteQE/robottelo, pull requests merged in 2018-06, with the labels that each got.

#6040 Fix test_multiple_paths for negative unauthorised tests
  tests/foreman/api/test_multiple_paths.py
Labels: 6.4, API, Urgent, nightly, review, test-failure

#6019 fix test long name CV publish
  tests/foreman/api/test_contentview.py
Labels: 6.4, API

#6044 test inc update - added errata applicability
  tests/foreman/longrun/test_inc_updates.py
Labels: 6.4, CLI, test-failure

#6042 Ported 10 CV tests to airgun
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui_airgun/test_activationkey.py
  tests/foreman/ui_airgun/test_contentview.py
Labels: 6.4, UI, review

#5939 First attempt to implement tests for compute resource
  tests/foreman/ui_airgun/test_computeresource.py
Labels: review

#6058 Ported 3 repository sync tests to airgun
  tests/foreman/ui/test_repository.py
  tests/foreman/ui_airgun/test_repository.py
Labels: 6.4, UI, review

#6069 Bump cryptography==2.0 since anything older fails to build/install
  requirements.txt
Labels: review

#6049 [6.3.z] cherry pick - test inc update - added errata applicability
  tests/foreman/longrun/test_inc_updates.py
Labels: 6.3, API

#6082 unstubbed test remote file repo
  robottelo/constants.py
  tests/foreman/cli/test_repository.py
Labels: 6.4, CLI

#6072 Ported 5 repo tests to airgun
  robottelo/datafactory.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui_airgun/test_domain.py
  tests/foreman/ui_airgun/test_repository.py
Labels: 6.4, UI, review

#6083 Fix image_dir default to implicit /var/lib/libvirt/images
  robottelo.properties.sample
  robottelo/config/base.py
Labels: review

#6084 [6.3.z] Fix image_dir default to implicit /var/lib/libvirt/images
  robottelo.properties.sample
  robottelo/config/base.py
Labels: review
