Repository SatelliteQE/robottelo, pull requests merged in 2018-04, with the labels that each got.

#5900 fixes #5885 [py3.6] TypeError: 'float' object cannot be interpreted as an integer
  tests/foreman/api/test_errata.py
Labels: review

#5901 Fix test for py3 #5884
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_errata.py
Labels: review

#5898 exception.message was deprecated in Python 2.6, removed in 3. str in …
  robottelo/test.py
  tests/foreman/api/test_classparameters.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_docker.py
  tests/foreman/cli/test_host.py
  tests/foreman/installer/test_installer.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_classparameters.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_setting.py
  tests/foreman/ui/test_template.py
Labels: review

#5912 move some sync plans test coverage to ui_airgun
  tests/foreman/ui/test_syncplan.py
  tests/foreman/ui_airgun/test_syncplan.py
Labels: review

#5916 Automated BZ 1475121 'Support for Docker Private Registry'
  .gitignore
  robottelo.properties.sample
  robottelo/config/base.py
  tests/foreman/api/test_repository.py
Labels: 6.3, 6.4, API, DO NOT MERGE, review

#5927 Moved 3 UI AK tests to ui_airgun; updated chrome workaround in datafactory
  robottelo/datafactory.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui_airgun/test_activationkey.py
Labels: review

#5917 Add locations/organizations options to hammer architecture subcommands
  tests/foreman/data/hammer_commands.json
Labels: review

#5903 Fix issue 5883: AttributeError: 'dict' object has no attribute 'iteritems'
  tests/foreman/cli/test_domain.py
  tests/foreman/cli/test_subnet.py
Labels: review

#5919 Updates/Adds the requirements for compute resource
  tests/foreman/api/test_computeresource_libvirt.py
  tests/foreman/cli/test_computeresource_ec2.py
  tests/foreman/cli/test_computeresource_libvirt.py
  tests/foreman/cli/test_computeresource_rhev.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/ui/test_computeresource_azure.py
  tests/foreman/ui/test_computeresource_ec2.py
  tests/foreman/ui/test_computeresource_libvirt.py
  tests/foreman/ui/test_computeresource_openstack.py
  tests/foreman/ui/test_computeresource_rhev.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: 6.4, High, ready, review

#5932 make use of six.iteritems
  robottelo/config/base.py
Labels: review

#5796 updated rhel-server repo to always point to the recent released RHEL version
  robottelo/constants.py
Labels: DO NOT MERGE

#5923 [6.4 Feature] Foreman Templates out of Tech Preview Stubs
  tests/foreman/api/test_template.py
  tests/foreman/cli/test_template.py
Labels: review

#5933 Moved 10 more t2-t3 AK tests to ui_airgun folder
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui_airgun/conftest.py
  tests/foreman/ui_airgun/test_activationkey.py
Labels: review

#5931 Move provisioning template test to new framework
  tests/foreman/ui/test_template.py
  tests/foreman/ui_airgun/test_provisioningtemplate.py
Labels: review

#5940 Added RHV ca_cert parameter to robottelo config
  robottelo.properties.sample
  robottelo/config/base.py
Labels: 6.4, Bug, Urgent, review

#5943 Temp fix for xdist test collection
  robottelo/datafactory.py
Labels: 6.4, High, UI, review
