Repository SatelliteQE/robottelo, pull requests merged in 2018-07, with the labels that each got.

#6104 Added and removed tests to/from upgrade
  tests/foreman/api/test_contentaccess.py
  tests/foreman/api/test_foremantask.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_subnet.py
  tests/foreman/api/test_subscription.py
  tests/foreman/cli/test_capsule.py
  tests/foreman/cli/test_capsule_installer.py
  tests/foreman/cli/test_computeresource_ec2.py
  tests/foreman/cli/test_computeresource_osp.py
  tests/foreman/cli/test_computeresource_rhev.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/cli/test_contentaccess.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_syncplan.py
Labels: 6.4, review

#6092 New permission in 6.4.0 snap 9
  robottelo/constants.py
Labels: review

#6020 [6.3] cherry-pick fix test long name CV publish
  tests/foreman/api/test_contentview.py
Labels: 6.3, API

#6038 Updated assertions for CLI tests - fixes 6026
  tests/foreman/cli/test_hostgroup.py
Labels: 6.4, test-failure

#6113 Updated tests affected by BZs
  tests/foreman/ui_airgun/test_activationkey.py
  tests/foreman/ui_airgun/test_contentcredential.py
Labels: 6.4, UI, test-failure

#5807 RFE Implement Products repositories distro abstraction
  robottelo/constants.py
  robottelo/products.py
  tests/foreman/cli/test_vm_install_products_package.py
Labels: 6.3, CLI, Infrastructure, RFE

#6091 [6.3.z] Stick to 6.3.z branch of nailgun
  requirements.txt
Labels: review

#6103 [cherry pick 6.3.z] updated rhel-server repo
  robottelo/constants.py
Labels: review, test-failure

#6126 Remove -r option for katello-certs-check
  tests/foreman/sys/test_katello_certs_check.py
Labels: 6.4, SYS, test-failure

#6088 [6.3] cherry-pick unstubbed test remote file repo (#6082)
  robottelo/constants.py
  tests/foreman/cli/test_repository.py
Labels: 6.3, CLI, review

#6095 Updating hammer command definitions
  tests/foreman/data/hammer_commands.json
Labels: 6.4, test-failure

#6133 Added documentation for using Robottelo in a container.
  docs/index.rst
Labels: review

#6078 add cli test for ignorable content in yum repos
  robottelo/cli/factory.py
  robottelo/constants.py
  tests/foreman/cli/test_repository.py
Labels: 6.4, CLI

#6134 More permissions were changed
  robottelo/constants.py
Labels: review

#6137 added ovirt-quota options to test_hammer_all_options test
  tests/foreman/data/hammer_commands.json
Labels: 6.4, review

#6136 updated test assertion to point to a correct column: puppet-ca-proxy
  tests/foreman/cli/test_hostgroup.py
Labels: review

#6129 Port User Groups test to AirGun
  tests/foreman/ui/test_usergroup.py
  tests/foreman/ui_airgun/test_usergroup.py
Labels: review

#6138 Add puppet class and smart variable functionality
  tests/foreman/ui_airgun/test_puppetclass.py
  tests/foreman/ui_airgun/test_smartvariable.py
Labels: review

#6140 Change OS module according to new standard
  robottelo/constants.py
  tests/foreman/ui_airgun/test_operatingsystem.py
Labels: review

#6143 update cli.discovered_host tests
  robottelo/cli/factory.py
  robottelo/constants.py
  tests/foreman/cli/test_discoveredhost.py
Labels: review

#6145 Workarounding the issue with our automation where the RHEV instance supplies incorrect cert so the connection fails.
  tests/foreman/ui_airgun/test_computeresource.py
Labels: review

#6146 Fix assertion message in ContentViewTestCase/test_positive_sub_host_with_restricted_user_perm_at_default_loc
  tests/foreman/cli/test_contentview.py
Labels: 6.4, review

#6144 Port LDAP auth tests
  tests/foreman/ui/test_ldapauthsource.py
  tests/foreman/ui_airgun/test_ldap_authentication.py
Labels: review

#6130 refactor capsule tests
  robottelo/cli/factory.py
  robottelo/config/base.py
  robottelo/constants.py
  robottelo/helpers.py
  robottelo/ssh.py
  robottelo/vm.py
  robottelo/vm_capsule.py
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/cli/test_capsule_installer.py
  tests/foreman/cli/test_contentview.py
Labels: 6.4, test-failure

#6147 New RHAI pages
  robottelo/ui/locators/base.py
  robottelo/ui/locators/menu.py
  robottelo/ui/navigator.py
  robottelo/ui/rhai.py
  robottelo/ui/session.py
  tests/foreman/rhai/test_rhai.py
Labels: review

#6150 Port most of smart class parameters tests
  tests/foreman/ui/test_classparameters.py
  tests/foreman/ui_airgun/test_smartclassparameter.py
Labels: review

#6148 Added Some File Repositories test cases
  robottelo/cli/file.py
  robottelo/constants.py
  tests/foreman/cli/test_repository.py
Labels: 6.4, CLI, review
