Repository SatelliteQE/robottelo, pull requests merged in 2020-06, with the labels that each got.

#7806 Fix fake 9 security erratum constant
  robottelo/constants.py
  tests/foreman/ui/test_hostcollection.py
Labels: GoodStarterIssue

#7822 Fix AttributeError: module 'nailgun.entities' has no attribute 'ConfigTemplate'
  robottelo/api/entity_fixtures.py
  robottelo/api/utils.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_location.py
  tests/foreman/api/test_multiple_paths.py
  tests/foreman/api/test_operatingsystem.py
  tests/foreman/api/test_template_combination.py
  tests/foreman/cli/test_location.py
  tests/foreman/ui/test_discoveredhost.py
  tests/foreman/ui/test_host.py
Labels: High Priority

#7807 Remove utf-8 encoding statements as file headers
  conftest.py
  robottelo/api/utils.py
  robottelo/cli/base.py
  robottelo/datafactory.py
  robottelo/decorators/__init__.py
  robottelo/decorators/func_locker.py
Labels: python3

#7825 [Fixes Travis Failing] Removed hammer options help from factory helper docstrings
  robottelo/cli/factory.py
Labels: High Priority

#7823 Add erratum count constants
  tests/foreman/api/test_errata.py
Labels: GoodStarterIssue

#7800 E2E Foreman Templates Sync UI Tests
  robottelo/constants.py
  tests/foreman/ui/test_sync_templates.py
Labels: DO NOT MERGE, review

#7828 convert api user tests to pytest
  tests/foreman/api/test_user.py
Labels: API, pytestConversion

#7841 Change allowed_distros to contain distros instead of images
  robottelo/vm.py
Labels: Urgent Priority

#7801 remove all occurences of config templates from robottelo
  robottelo/api/entity_fixtures.py
  robottelo/api/utils.py
  robottelo/cli/base.py
  robottelo/cli/factory.py
  robottelo/cli/location.py
  robottelo/cli/operatingsys.py
  robottelo/cli/org.py
  robottelo/cli/template.py
  tests/foreman/api/test_location.py
  tests/foreman/api/test_operatingsystem.py
  tests/foreman/api/test_template_combination.py
  tests/foreman/cli/test_location.py
  tests/foreman/cli/test_operatingsystem.py
  tests/foreman/cli/test_organization.py
  tests/foreman/conftest.py
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/ui/test_host.py
  tests/robottelo/test_cli_method_calls.py
Labels: 6.8, Tier 1 ACK, review, test-failure

#7804 Pluged in Pytest API fixtures
  conftest.py
  pytest_fixtures/api_fixtures.py
  tests/foreman/api/test_computeresource_azurerm.py
  tests/foreman/api/test_computeresource_gce.py
  tests/foreman/cli/test_computeresource_azurerm.py
  tests/foreman/conftest.py
  tests/foreman/ui/test_computeresource_azurerm.py
  tox.ini
Labels: pytestConversion

#7846 Fix travis-tox for fixture plugins PR
  tox.ini
Labels: review

#7810 test rename conv to pytest
  tests/foreman/sys/test_rename.py
Labels: 6.8, pytestConversion, test-failure
