Repository SatelliteQE/robottelo, pull requests merged in 2020-08, with the labels that each got.

#7906 Re-organize test cases for the virt-who plugin as per the new structure
  tests/foreman/virtwho/api/__init__.py
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_hyperv.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_libvirt.py
  tests/foreman/virtwho/api/test_rhevm.py
  tests/foreman/virtwho/api/test_xen.py
  tests/foreman/virtwho/cli/__init__.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_hyperv.py
  tests/foreman/virtwho/cli/test_kubevirt.py
  tests/foreman/virtwho/cli/test_libvirt.py
  tests/foreman/virtwho/cli/test_rhevm.py
  tests/foreman/virtwho/cli/test_xen.py
  tests/foreman/virtwho/test_ui_virtwho.py
  tests/foreman/virtwho/ui/__init__.py
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_hyperv.py
  tests/foreman/virtwho/ui/test_kubevirt.py
  tests/foreman/virtwho/ui/test_libvirt.py
  tests/foreman/virtwho/ui/test_rhevm.py
  tests/foreman/virtwho/ui/test_xen.py
Labels: Tier 1 ACK, ready

#7882 Add RH Cloud - Inventory E2E test
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: Tier 1 ACK

#7809 Create robottelo.utils, move issue_handler helpers
  conftest.py
  pytest_fixtures/api_fixtures.py
  pytest_plugins/issue_handlers.py
  pytest_plugins/markers.py
  robottelo/helpers.py
  robottelo/utils/__init__.py
  robottelo/utils/issue_handlers/README.md
  robottelo/utils/issue_handlers/__init__.py
  robottelo/utils/issue_handlers/bugzilla.py
  robottelo/utils/version.py
  robottelo/vm_capsule.py
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/api/test_multiple_paths.py
  tests/foreman/api/test_operatingsystem.py
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_syncplan.py
  tests/foreman/cli/test_activationkey.py
  tests/foreman/cli/test_hammer.py
  tests/foreman/cli/test_repository.py
  tests/foreman/conftest.py
  tests/foreman/longrun/test_provisioning_computeresource.py
  tests/foreman/sys/test_katello_certs_check.py
  tests/foreman/ui/test_bookmarks.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/virtwho/test_api_virtwho.py
  tests/foreman/virtwho/test_cli_virtwho.py
  tests/robottelo/test_helpers.py
  tests/robottelo/test_issue_handlers.py
  tests/upgrades/test_virtwho.py
Labels: pytestConversion

#7900 fix job template creation
  tests/foreman/ui/test_jobtemplate.py
Labels: 6.8, Tier 1 ACK, UI, test-failure

#7911 adding BZ tag for sc_param tests
  tests/foreman/cli/test_classparameters.py
Labels: CLI

#7917 Use Http proxy in ec2 and gce CR ui tests.
  robottelo/constants.py
  tests/foreman/ui/test_computeresource_ec2.py
  tests/foreman/ui/test_computeresource_gce.py
Labels: Tier 1 ACK

#7916 Fix case test_positive_post_hypervisors
  robottelo/virtwho_utils.py
  tests/foreman/virtwho/test_cli_virtwho.py
Labels: Tier 1 ACK, ready, review

#7913 Add automation coverage for BZ1653386
  robottelo/virtwho_utils.py
  tests/foreman/ui/test_contenthost.py
Labels: Customer Case, Tier 1 ACK, qe_test_coverage, ready, review

#7904 pytest conversion PR for auth source tests
  tests/foreman/cli/test_ldapauthsource.py
Labels: CLI, Tier 2 ACK, ready, review

#7827 updated permissions
  robottelo/constants.py
Labels: 6.8, test-failure

#7879 Test: Attempt to login in Satellite an IDM user with the wrong password
  tests/foreman/ui/test_ldap_authentication.py
Labels: 6.8, Tier 1 ACK, UI, ready, review

#7886 6.8 reporting fixes
  tests/foreman/cli/test_reporttemplates.py
Labels: Tier 1 ACK

#7885 Fix API permission search for name and resource_type
  robottelo/api/utils.py
Labels: GoodStarterIssue, Tier 1 ACK

#7881 Test: Login should fail in satellite server when the user is disable in IPA Server
  pytest_fixtures/satellite_auth.py
  robottelo.properties.sample
  robottelo/config/base.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: 6.8, UI, ready, review

#7928 Filter: Resourch Type changes for roles
  robottelo/api/utils.py
  tests/foreman/ui/test_lifecycleenvironment.py
  tests/foreman/ui/test_repository.py
Labels: 6.8

#7878 added the external auth AD server scenario
  pytest_fixtures/satellite_auth.py
  robottelo.properties.sample
  robottelo/config/base.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: qe_test_coverage, ready, review

#7933 Test: Email of the user to be copied to satellite (from IDM)
  pytest_fixtures/satellite_auth.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: 6.8, UI, review

#7934 Fix CRUD failure
  tests/foreman/cli/test_product.py
Labels: 6.8, CLI

#7935 Fixed a failed test in polarion
  tests/foreman/ui/test_contentview.py
Labels: 6.8

#7918 Refactor few tests from tests/foreman/cli/test_oscap.py.
  tests/foreman/cli/test_oscap.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_host.py
Labels: Tier 1 ACK, Tier 2 ACK

#7939 convert partition table tests to pytest
  tests/foreman/api/test_partitiontable.py
  tests/foreman/cli/test_partitiontable.py
Labels: pytestConversion

#7942 convert cli/model to pytest
  tests/foreman/cli/test_model.py
Labels: 6.8, CLI, pytestConversion

#7944 Update tox pycurl installation
  .travis.yml
  tox.ini
Labels: Bug

#7951 Convert architecture cli test to pytest
  tests/foreman/cli/test_architecture.py
Labels: CLI, pytestConversion

#7943 Stubbed test cases for capsule loadbalancer
  tests/foreman/longrun/test_capsule_loadbalancer.py
Labels: 6.8, Manual Test, review

#7969 usergroup name not happy with html tags
  tests/foreman/cli/test_usergroup.py
Labels: 6.8, CLI, test-failure
