Repository SatelliteQE/robottelo, pull requests merged in 2020-10, with the labels that each got.

#7937 Close Loop 1 and fix of 1856287
  pytest_fixtures/api_fixtures.py
  tests/foreman/api/test_templatesync.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_templatesync.py
  tests/foreman/ui/test_templatesync.py
Labels: Tier 1 ACK

#7925 added rh_sso cli tests, refactored some common code
  pytest_fixtures/satellite_auth.py
  requirements.txt
  robottelo/api/utils.py
  robottelo/rhsso_utils.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: 6.8, CLI, Tier 1 ACK, qe_test_coverage, ready, review

#8029 Update failure message
  tests/foreman/cli/test_repository.py
Labels: GoodStarterIssue

#8027 qe_test_coverage for BZ:1670397
  tests/foreman/ui/test_ldap_authentication.py
Labels: UI, qe_test_coverage

#8008 Pytest conversion for api/lifecycleenvironment
  tests/foreman/api/test_lifecycleenvironment.py
Labels: 6.8, API, pytestConversion

#8048 Remove confusingly named test case in cv
  tests/foreman/ui/test_contentview.py
Labels: 6.8, review

#8040 Fix valid_data_list() usage in test_organization
  tests/foreman/cli/test_organization.py
Labels: CLI, test-failure

#8053 [6.7.z] Make pytest-xdist mandatory
  requirements-optional.txt
  requirements.txt
Labels: 6.7, Urgent Priority

#7941 Refactor BZ Markers
  pytest_plugins/issue_handlers.py
  pytest_plugins/rerun_rp/rerun_rp.py
  tests/robottelo/test_issue_handlers.py
Labels: enhancement

#8044 Fix test: PingTestCase::test_positive_ping
  tests/foreman/cli/test_ping.py
Labels: ready, review, test-failure

#8054 [6.6.z] Make pytest-xdist mandatory
  requirements-optional.txt
  requirements.txt
Labels: 6.6

#8028 Improve and simplify SCA test
  robottelo/constants/__init__.py
  tests/foreman/cli/test_contentaccess.py
Labels: enhancement

#8023 test fix test_negative_without_attach_with_lce
  tests/foreman/cli/test_host.py
Labels: 6.8, Tier 2 ACK, ready, test-failure

#8031 Robottelo Pytest Package Update to 5.4.3
  requirements.txt
  tests/foreman/conftest.py
Labels: High Priority, enhancement, pytestConversion

#8025 Fix returned data because format changed
  tests/foreman/cli/test_gpgkey.py
Labels: Urgent Priority

#8020 Update the virt-who upgrade cases based on the virt-who new structure
  tests/upgrades/test_virtwho.py
Labels: Tier 2 ACK, Upgrade Scenario, ready, review

#8007 pytest conversion for test_subscription
  tests/foreman/api/test_subscription.py
  tests/foreman/cli/test_subscription.py
Labels: 6.8, API, CLI, Tier 2 ACK, pytestConversion

#8043 api product-fix 229
  tests/foreman/api/test_product.py
Labels: 6.8, Tier 1 ACK, review

#8049 Let's update the system before capsule installation.
  robottelo/vm.py
  robottelo/vm_capsule.py
Labels: Tier 1 ACK

#7976 Report Portal and Rerun Plugin improvements
  pytest_plugins/rerun_rp/rerun_rp.py
  robottelo/report_portal/portal.py
Labels: Tier 1 ACK, Tier 2 ACK, enhancement

#8064 Fix build_time assertion
  tests/foreman/ui/test_package.py
Labels: 6.8, Tier 1 ACK

#8063 cherry pick test fix test_negative_without_attach_with_lce
  tests/foreman/cli/test_host.py
Labels: 6.7, pending-cherry-pick, ready

#8062 cherry pick - satellite tools constants changed to 6.7
  robottelo/constants.py
  tests/foreman/cli/test_host.py
Labels: 6.7, pending-cherry-pick, ready

#8061 cherry pick - test syspurpose fix
  tests/foreman/cli/test_host.py
Labels: 6.7, pending-cherry-pick, ready

#8058 Changing expected API endpoints.
  tests/foreman/endtoend/test_api_endtoend.py
Labels: ready

#7987 api/test_host pytest conversion, some test were squashed, to another tests there were additions
  pytest_fixtures/api_fixtures.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_host.py
Labels: 6.8, pytestConversion, ready

#8060 Segregate katello-agent tests from test_hosts
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_katello_agent.py
Labels: CLI, ready, review

#8016 added open ldap end to end tests
  pytest_fixtures/satellite_auth.py
  robottelo.properties.sample
  robottelo/config/base.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: Tier 2 ACK, qe_test_coverage, ready, review

#8079 fixing testsuite start_time junit xml property recording to be compatible with pytest v4.5+
  tests/foreman/conftest.py
Labels: High Priority

#8045 added bugzilla automation for 1812688
  robottelo.properties.sample
  robottelo/config/base.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: qe_test_coverage, ready, review

#8011 pytest conversion for tests/foreman/cli/test_oscap.py
  conftest.py
  pytest_fixtures/ansible_fixtures.py
  pytest_fixtures/api_fixtures.py
  pytest_fixtures/oscap_fixtures.py
  pytest_fixtures/smartproxy_fixtures.py
  pytest_fixtures/user_fixtures.py
  tests/foreman/api/test_oscappolicy.py
  tests/foreman/cli/test_oscap.py
  tests/foreman/ui/conftest.py
  tests/foreman/ui/test_bookmarks.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_host.py
Labels: Tier 1 ACK

#8056 Make Rerun RP plugins `fail threshold` configurable
  pytest_plugins/rerun_rp/rerun_rp.py
  robottelo.properties.sample
  robottelo/config/base.py
  robottelo/report_portal/portal.py
Labels: branching_nonblocker

#8082 Fix automation failure where newly added organizations appeared for existing report templates. + New asserts.
  tests/foreman/ui/test_reporttemplates.py
Labels: ready

#8071 pytest conversion for lifecycleenvironment cli
  tests/foreman/cli/test_lifecycleenvironment.py
Labels: Tier 1 ACK

#8073 Add stubs for newer features in RH Cloud - Inventory plugin
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: Tier 1 ACK

#8069 added the user-group sync test with external auth rhsso
  robottelo/cli/factory.py
  robottelo/cli/ldapauthsource.py
  robottelo/constants/__init__.py
  robottelo/rhsso_utils.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: 6.8

#8046 Use update_payload when updating, not create_payload; requires fixes in nailgun to be pulled first
  tests/foreman/api/test_multiple_paths.py
Labels: ready

#8091 Fix duplicate fixture definition
  tests/foreman/ui/test_ldap_authentication.py
Labels: Bug

#8081 Pytest conversion for settings CLI test cases
  tests/foreman/cli/test_setting.py
Labels: ready

#8078 Pytest conversion for settings API test cases.
  pytest_fixtures/api_fixtures.py
  tests/foreman/api/test_setting.py
Labels: Tier 1 ACK, ready

#8099 Update nailgun/airgun/sat6-upgrade requirements branches
  requirements.txt
Labels: 6.8

#8093 Added Parametrization support in Setting UI Test cases
  pytest_fixtures/api_fixtures.py
  tests/foreman/ui/test_settings.py
Labels: ready

#8109 Fix Reruning all failed tests check
  pytest_plugins/rerun_rp/rerun_rp.py
Labels: Bug
