Repository SatelliteQE/robottelo, pull requests merged in 2020-01, with the labels that each got.

#7552 Added pre-upgrade and post-upgrade test scenarios for performance & Tuning
  tests/upgrades/test_performance_tuning.py
Labels: 6.7

#7381 separate organization and default manifest for rename tests
  tests/foreman/sys/test_rename.py
Labels: 6.6, SYS, branching_nonblocker

#7586 6.6 cherry-pick -- separate org and default manifest for rename tests
  tests/foreman/sys/test_rename.py
Labels: 6.6

#7575 test_positive_bulk_delete_host fix
  tests/foreman/ui/test_host.py
Labels: 6.7, UI

#7592 removed the unwanted code making test failure
  tests/foreman/ui/test_contenthost.py
Labels: test-failure

#7594 styling changes in hammer help tables
  tests/foreman/cli/test_organization.py
Labels: 6.7, CLI, test-failure

#7608 Added support for AzureRM properties
  robottelo.properties.sample
  robottelo/config/base.py
  robottelo/constants.py
  tests/foreman/data/uri.sh
Labels: 6.7, enhancement

#7616 Fix redundant call to read_json() (#7615)
  tests/foreman/longrun/test_inc_updates.py
Labels: GoodStarterIssue

#7617 do not look at first organization and location if the test is running parallel
  tests/foreman/ui/test_partitiontable.py
Labels: UI, review
