Repository SatelliteQE/robottelo, pull requests merged in 2020-07, with the labels that each got.

#7860 fix for cli roles tests
  tests/foreman/cli/test_filter.py
  tests/foreman/cli/test_reporttemplates.py
  tests/foreman/cli/test_role.py
Labels: 6.8, CLI, test-failure

#7868 fix api premission search by resource type
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_filter.py
  tests/foreman/api/test_permission.py
  tests/foreman/api/test_role.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_errata.py
  tests/upgrades/test_role.py
Labels: 6.8, API, test-failure

#7863 Add test install errata to one host in a hc
  tests/foreman/cli/test_errata.py
Labels: GoodStarterIssue

#7873 Remove virt-who plugin cases from longrun folder
  tests/foreman/longrun/test_virtwho_config.py
Labels: Tier 1 ACK, ready, review

#7845 Fix assert to handle new "clear" link (#7843)
  tests/foreman/ui/test_errata.py
Labels: GoodStarterIssue

#7876 fixes in usergroup cli tests
  tests/foreman/cli/test_usergroup.py
Labels: 6.8, CLI, test-failure

#7874 skip test_positive_download_tailoring_file test
  tests/foreman/cli/test_oscap_tailoringfiles.py
  tests/foreman/ui/test_oscappolicy.py
Labels: 6.8, Tier 2 ACK, ready, review

#7870 Fix puppet command and taxonomy issue for scap longrun tests
  robottelo/vm.py
  tests/foreman/longrun/test_oscap.py
Labels: 6.8, Tier 1 ACK, ready, review

#7814 convert api organization test to pytest
  tests/foreman/api/test_organization.py
Labels: API, pytestConversion

#7895 Adding skip until BZ:1470083 is fixed
  tests/foreman/api/test_setting.py
  tests/foreman/ui/test_settings.py
Labels: API, Bug, UI, ready, review

#7902 Add missing import
  tests/foreman/api/test_setting.py
Labels: Bug

#7903 Fix unwanted end-of-line space
  tests/foreman/ui/test_contentcredential.py
Labels: GoodStarterIssue

#7898 Fix returned data because format changed (gpgkeys)
  tests/foreman/cli/test_gpgkey.py
Labels: GoodStarterIssue

#7901 Fix returned data because format changed (HC)
  tests/foreman/cli/test_host_collection.py
Labels: GoodStarterIssue

#7808 Improve errata test pos c-host search type
  tests/foreman/ui/test_errata.py
Labels: GoodStarterIssue

#7880 Fixed installer test failure
  tests/foreman/installer/test_installer.py
Labels: Tier 1 ACK, review

#7877 fixes in cli user tests
  tests/foreman/cli/test_user.py
Labels: 6.8, CLI, test-failure

#7875 fix permissions test
  robottelo/constants.py
  tests/foreman/api/test_permission.py
Labels: 6.8, API, Tier 1 ACK, test-failure

#7887 Include tests as parametrized in polarion
  testimony.yaml
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_user.py
  tests/foreman/api/test_usergroup.py
  tests/foreman/cli/test_computeresource_azurerm.py
  tests/foreman/cli/test_setting.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/rhai/test_rhai.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_computeresource.py
  tests/foreman/ui/test_domain.py
  tests/foreman/ui/test_product.py
Labels: enhancement, review
