Repository SatelliteQE/robottelo, pull requests merged in 2020-04, with the labels that each got.

#7712 test manipulates with default settings and this is causing problems to tests which run in paralel
  tests/foreman/cli/test_product.py
Labels: review, test-failure

#7714 Fixing repo path for capsule sync test
  robottelo/helpers.py
  tests/foreman/api/test_contentmanagement.py
Labels: Tier 1 ACK

#7729 Added synchronous false to avoid wait on delete
  tests/foreman/ui/test_computeresource_azurerm.py
Labels: review

#7742 Missing code, after wrong squash 2 months ago causing error in automation
  robottelo/vm.py
Labels: ready, test-failure

#7752 [6.7.z] re-adding changes to robottelo vm after wrong squash
  robottelo/vm.py
Labels: 6.7

#7741 we used capsule repo for katello-agent installation
  robottelo/constants.py
  tests/foreman/cli/test_host.py
Labels: ready
