Repository SatelliteQE/robottelo, pull requests merged in 2021-09, with the labels that each got.

#8859 Get GCE cert details from json
  conf/gce.yaml.template
  pytest_fixtures/api_fixtures.py
  pytest_fixtures/sys_fixtures.py
  robottelo/config/validators.py
  robottelo/helpers.py
  tests/foreman/api/test_computeresource_gce.py
  tests/foreman/ui/test_computeresource_gce.py
  tests/foreman/ui/test_host.py
  tests/upgrades/test_host.py
Labels: PytestConversion

#8921 [cherrypick] Get GCE cert details from json (#8859)
  conf/gce.yaml.template
  pytest_fixtures/api_fixtures.py
  pytest_fixtures/sys_fixtures.py
  robottelo/config/validators.py
  robottelo/helpers.py
  tests/foreman/api/test_computeresource_gce.py
  tests/foreman/ui/test_computeresource_gce.py
  tests/foreman/ui/test_host.py
  tests/upgrades/test_host.py
Labels: 6.9

#8795 Updated satellite installer test cases
  tests/foreman/cli/test_installer.py
  tests/foreman/installer/test_installer.py
Labels: Manual Test, TestMetadata

#8847 Convert test hostcollection to use REX
  robottelo/constants/__init__.py
  tests/foreman/ui/test_hostcollection.py
Labels: 6.10

#8922 puppet test removal in api contentmanagemenet
  tests/foreman/api/test_contentmanagement.py
Labels: TestFailure, 6.10

#8915 puppet test parts removed in upgrade tests
  tests/upgrades/test_capsule.py
  tests/upgrades/test_contentview.py
Labels: TestFailure, Upgrade Scenario, 6.10

#8782 Moving fedorapeople repo constants to repos.yaml
  conf/repos.yaml.template
  robottelo/api/utils.py
  robottelo/cli/factory.py
  robottelo/constants/__init__.py
  robottelo/constants/repos.py
  robottelo/products.py
  tests/foreman/api/test_classparameters.py
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_contentviewversion.py
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_activationkey.py
  tests/foreman/cli/test_classparameters.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_katello_agent.py
  tests/foreman/cli/test_logging.py
  tests/foreman/cli/test_product.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_reporttemplates.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/longrun/test_inc_updates.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_contentcredential.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_hostcollection.py
  tests/foreman/ui/test_http_proxy.py
  tests/foreman/ui/test_lifecycleenvironment.py
  tests/foreman/ui/test_modulestreams.py
  tests/foreman/ui/test_package.py
  tests/foreman/ui/test_product.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
  tests/upgrades/test_classparameter.py
  tests/upgrades/test_client.py
  tests/upgrades/test_contentview.py
  tests/upgrades/test_errata.py
Labels: enhancement, Dynaconf

#8869 [Cherry-pick] Moving fedorapeople repo constants to repos.yaml
  conf/repos.yaml.template
  pytest_fixtures/api_fixtures.py
  robottelo/api/utils.py
  robottelo/cli/factory.py
  robottelo/constants/__init__.py
  robottelo/constants/repos.py
  robottelo/products.py
  tests/foreman/api/test_classparameters.py
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_contentviewversion.py
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_activationkey.py
  tests/foreman/cli/test_classparameters.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_environment.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_hostgroup.py
  tests/foreman/cli/test_katello_agent.py
  tests/foreman/cli/test_product.py
  tests/foreman/cli/test_puppetclass.py
  tests/foreman/cli/test_puppetmodule.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_reporttemplates.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
  tests/foreman/longrun/test_inc_updates.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_contentcredential.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_hostcollection.py
  tests/foreman/ui/test_hostgroup.py
  tests/foreman/ui/test_http_proxy.py
  tests/foreman/ui/test_lifecycleenvironment.py
  tests/foreman/ui/test_modulestreams.py
  tests/foreman/ui/test_package.py
  tests/foreman/ui/test_product.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_smartclassparameter.py
  tests/foreman/ui/test_sync.py
  tests/upgrades/test_capsule.py
  tests/upgrades/test_classparameter.py
  tests/upgrades/test_client.py
  tests/upgrades/test_contentview.py
  tests/upgrades/test_errata.py
Labels: enhancement, 6.9, Dynaconf

#8920 Puppet workaround upgrade classparameter
  tests/upgrades/test_classparameter.py
Labels: TestFailure, Upgrade Scenario, 6.10

#8884 updated the certs tests to use host class
  robottelo/hosts.py
  tests/foreman/sys/test_katello_certs_check.py
Labels: enhancement

#8924 additional rex cli fixes
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, TestFailure, 6.10

#8880 Added test coverage for BZ#1960801, BZ#1860519
  robottelo/hosts.py
  tests/foreman/installer/test_installer.py
Labels: CustomerCase

#8923 Workaround for classparameters puppet module
  tests/foreman/api/test_classparameters.py
  tests/foreman/cli/test_classparameters.py
Labels: CLI, API, TestFailure, 6.10

#8835 Add test modular errata default CV
  tests/foreman/api/test_errata.py
Labels: 6.10

#8889 [Cherry-Pick] Move helper methods onto ContentHost/Capsule/Satellite
  pytest_fixtures/broker.py
  robottelo/config/__init__.py
  robottelo/constants/__init__.py
  robottelo/helpers.py
  robottelo/hosts.py
  robottelo/products.py
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_hostcollection.py
  tests/foreman/api/test_permission.py
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/api/test_subscription.py
  tests/foreman/api/test_template.py
  tests/foreman/cli/test_activationkey.py
  tests/foreman/cli/test_contentaccess.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_docker.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_katello_agent.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_reporttemplates.py
  tests/foreman/cli/test_subscription.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
  tests/foreman/endtoend/utils.py
  tests/foreman/installer/test_installer.py
  tests/foreman/longrun/test_inc_updates.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/rhai/conftest.py
  tests/foreman/rhai/test_rhai_client.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_hostcollection.py
  tests/foreman/ui/test_jobinvocation.py
  tests/foreman/ui/test_remoteexecution.py
  tests/foreman/ui/test_reporttemplates.py
  tests/foreman/ui/test_subscription.py
  tests/robottelo/test_helpers.py
  tests/upgrades/test_remoteexecution.py
  tests/upgrades/test_repository.py
Labels: Bug, enhancement, 6.9, Dynaconf

#8912 Added test coverage for BZ#1863597 and BZ#1920072
  tests/foreman/installer/test_installer.py
Labels: CustomerCase

#8932 Package name change regression
  tests/foreman/ui/test_hostcollection.py
Labels: 6.9, Easy Fix :)

#8935 Fix typeerror in join statement
  tests/foreman/ui/test_activationkey.py
Labels: TestFailure, 6.9

#8936 Fix to match changes in master branch
  tests/foreman/ui/test_hostcollection.py
Labels: 6.9, Easy Fix :)

#8937 Remove puppet and fix failures in api contentview
  tests/foreman/api/test_contentview.py
Labels: API, 6.10

#8939 Removed swid test because file path doesn't exist anymore
  tests/foreman/api/test_contentviewfilter.py
Labels: API, TestFailure, 6.10

#8938 Removed puppet modules in contentviewversion
  tests/foreman/api/test_contentviewversion.py
Labels: API, TestFailure, 6.10

#8942 fixed UI CR_vmware pwr mgmt which failed on power off
  tests/foreman/ui/test_computeresource_vmware.py
Labels: TestFailure

#8864 global registration feature automation pr_1
  conf/repos.yaml.template
  tests/foreman/ui/test_host.py
Labels: DO NOT MERGE, QETestCoverage, 6.10

#8817 Update test ui test_contenthost to use REX
  tests/foreman/ui/test_contenthost.py
Labels: GoodStarterIssue, 6.10

#8904 Azure CLI test fixes with 2 new context managers
  robottelo/api/utils.py
  robottelo/hosts.py
  tests/foreman/api/test_computeresource_azurerm.py
  tests/foreman/cli/test_computeresource_azurerm.py
  tests/foreman/ui/test_computeresource_azurerm.py
  tests/foreman/ui/test_host.py
  tests/upgrades/test_host.py
Labels: Bug, CLI, High Priority, enhancement, 6.10

#8931 ansible collection repo sync from hub
  conf/ansible_hub.yaml.template
  robottelo/cli/factory.py
  robottelo/config/validators.py
  tests/foreman/cli/test_repository.py
Labels: CLI, 6.10

#8943 fix template sync asserts
  pytest_fixtures/templatesync_fixtures.py
  robottelo/constants/__init__.py
  tests/foreman/api/test_templatesync.py
  tests/foreman/cli/test_templatesync.py
  tests/foreman/ui/test_templatesync.py
Labels: TestFailure, 6.10

#8934 Include of puppet classes for Sat-6.10
  tests/foreman/cli/test_hostgroup.py
Labels: TestFailure, 6.10

#8951 test_positive_assign_taxonomies fixed
  tests/foreman/ui/test_host.py
Labels: UI, TestFailure, 6.10, Easy Fix :)

#8947 Fixing assertion failures for cli/test_operatingsystem::test_positive_add_template
  tests/foreman/cli/test_operatingsystem.py
Labels: TestFailure

#8948 Remove puppet from contentview in cli
  tests/foreman/cli/test_contentview.py
Labels: CLI, TestFailure, 6.10

#8953 Improve CLI and API sync tests
  tests/foreman/api/test_syncplan.py
  tests/foreman/cli/test_syncplan.py
  tests/foreman/ui/test_syncplan.py
Labels: 6.9, 6.10

#8956 some tests fixed connected to airgun locators
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_smartclassparameter.py
Labels: UI, TestFailure, 6.10

#8962 pull function names in fixture marker
  pytest_plugins/fixture_markers.py
Labels: Bug

#8955 import/export ansible collections repo
  tests/foreman/cli/test_repository.py
Labels: CLI, 6.10

#8944 Add test mirror-on-sync removes rpm
  tests/foreman/cli/test_repository.py
Labels: TestAutomation

#8941 Automated stubbed test case for Products feature
  tests/foreman/cli/test_product.py
Labels: TestAutomation

#8974 [6.9.z] Update top key references of libvirt.yaml
  conf/libvirt.yaml.template
  robottelo/api/utils.py
  robottelo/config/validators.py
  robottelo/libvirt_discovery.py
  tests/foreman/api/test_computeresource_libvirt.py
  tests/foreman/cli/test_computeresource_libvirt.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_organization.py
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
  tests/foreman/ui/test_computeresource_libvirt.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
  tests/foreman/ui/test_subscription.py
  tests/upgrades/test_remoteexecution.py
Labels: 6.9

#8945 Fix OpenSCAP longrun tests
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/longrun/test_oscap.py
Labels: TestFailure

#8959 fixed tests and moved the ui steps to api steps
  pytest_fixtures/satellite_auth.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: TestFailure

#8985 fix the ldap api test, updated because of module loc was not called from auth fixture
  tests/foreman/api/test_ldapauthsource.py
Labels: TestFailure, Easy Fix :)

#8988 Address BoxKeyErrors in unstable branch
  pytest_fixtures/broker.py
  robottelo/hosts.py
  tests/foreman/api/test_product.py
Labels: Dynaconf

#8987 Replacing CUSTOM_KICKSTART_REPO with Red Hat Kickstart repo
  robottelo/constants/__init__.py
  tests/foreman/api/test_contentmanagement.py
Labels: TestFailure

#8964 Automated stubbed test case for activationkey feature
  tests/foreman/cli/test_activationkey.py
Labels: CLI, 6.10

#8994 Fixed `host_conf` fixture called in high scope fixtures
  pytest_fixtures/content_hosts.py
Labels: Bug, TestFailure

#8993 Consolidate module_loc and module_org fixtures
  pytest_fixtures/api_fixtures.py
  pytest_fixtures/satellite_auth.py
  tests/foreman/cli/test_environment.py
  tests/foreman/ui/conftest.py
  tests/foreman/ui/test_audit.py
  tests/foreman/ui/test_bookmarks.py
  tests/foreman/ui/test_computeprofiles.py
  tests/foreman/ui/test_computeresource.py
  tests/foreman/ui/test_computeresource_ec2.py
  tests/foreman/ui/test_computeresource_gce.py
  tests/foreman/ui/test_computeresource_libvirt.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_discoveredhost.py
  tests/foreman/ui/test_discoveryrule.py
  tests/foreman/ui/test_domain.py
  tests/foreman/ui/test_hardwaremodel.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_hostcollection.py
  tests/foreman/ui/test_hostgroup.py
  tests/foreman/ui/test_http_proxy.py
  tests/foreman/ui/test_jobinvocation.py
  tests/foreman/ui/test_ldap_authentication.py
  tests/foreman/ui/test_media.py
  tests/foreman/ui/test_oscappolicy.py
  tests/foreman/ui/test_partitiontable.py
  tests/foreman/ui/test_provisioningtemplate.py
  tests/foreman/ui/test_puppetclass.py
  tests/foreman/ui/test_puppetenvironment.py
  tests/foreman/ui/test_remoteexecution.py
  tests/foreman/ui/test_reporttemplates.py
  tests/foreman/ui/test_role.py
  tests/foreman/ui/test_smartclassparameter.py
  tests/foreman/ui/test_subnet.py
  tests/foreman/ui/test_user.py
  tests/foreman/ui/test_usergroup.py
  tests/foreman/virtwho/conftest.py
Labels: enhancement, PytestConversion

#8995 test_vm_install_package puppet removal
  tests/foreman/cli/test_vm_install_products_package.py
Labels: TestFailure

#8996 added the test coverage for bz 1996077
  tests/foreman/ui/test_hostgroup.py
Labels: QETestCoverage, CustomerCase

#8970 Automated stubbed testcase in repository feature
  tests/foreman/cli/test_repository.py
Labels: CLI, TestAutomation, 6.10

#8999 Missed module_loc changes
  pytest_fixtures/satellite_auth.py
Labels: TestFailure

#8998 Update virt-who config file path and options
  robottelo/virtwho_utils.py
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/ui/test_esx.py
Labels: 6.10

#9003 Remove make_gpg_key and fix test cases to use make_content_credential
  robottelo/cli/factory.py
  tests/foreman/cli/test_product.py
  tests/foreman/cli/test_repository.py
Labels: CLI, TestFailure, 6.10

#9002 katello-agent still required for HC in 6.9.z
  tests/foreman/ui/test_hostcollection.py
Labels: 6.9, Easy Fix :)

#9000 Update `ncat` use, address hanging pytest
  pytest_fixtures/smartproxy_fixtures.py
  robottelo/helpers.py
  tests/foreman/cli/test_realm.py
Labels: Bug, TestFailure

#8972 Raise DependantTestFailed error in post_upgrade if pre_upgrade test failed
  tests/upgrades/conftest.py
Labels: enhancement, Upgrade Scenario

#8990 Test coverage on http proxy feature
  tests/foreman/ui/test_http_proxy.py
Labels: UI, 6.10

#9009 Remove multiplication of timeout
  robottelo/hosts.py
Labels: Bug, Urgent Priority

#9006 katello agent is no longer enabled by default
  tests/foreman/cli/test_host.py
Labels: TestFailure, 6.10

#9020 Update expected API endpoints for 6.10
  tests/foreman/endtoend/test_api_endtoend.py
Labels: API, 6.10
