Repository SatelliteQE/robottelo, pull requests merged in 2021-04, with the labels that each got.

#8416 Errata cli test fixes
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/cli/test_errata.py
Labels: TestFailure

#8430 Refactor test_api_endtoend and endtoend/utils for pytest
  tests/foreman/endtoend/test_api_endtoend.py
Labels: PytestConversion

#8475 Dynaconf conversion for http_proxy and oscap section
  conf/http_proxy.yaml.template
  conf/oscap.yaml.template
Labels: Dynaconf

#8477 fixed caps in fake_manifest
  conf/fake_manifest.yaml.template
Labels: Dynaconf

#8441 Refactor cli/test_reporttemplates, pytest fixtures
  tests/foreman/cli/test_reporttemplates.py
Labels: PytestConversion

#8472 Removed parametrization causing errors in cli/test_repository.py
  tests/foreman/cli/test_repository.py
Labels: CLI, TestFailure

#8492 Small test fix for reporttemplates
  tests/foreman/cli/test_reporttemplates.py
Labels: TestFailure

#8495 Add missing fixture to errata cli test
  tests/foreman/cli/test_errata.py
Labels: PytestConversion, TestFailure

#8451 Convert cli/test_discoveryrule to pytest
  pytest_fixtures/api_fixtures.py
  tests/foreman/cli/test_discoveryrule.py
Labels: PytestConversion

#8303 Add the ability for Robottelo to dynamically request test targets
  .gitignore
  conf/server.yaml.template
  pytest_fixtures/broker.py
  pytest_fixtures/xdist.py
  robottelo/config/facade.py
  robottelo/config/validators.py
  robottelo/utils/issue_handlers/bugzilla.py
  tests/upgrades/conftest.py
Labels: Dynaconf, enhancement

#8481 migrate discovery settings to dynaconf
  conf/discovery.yaml.template
Labels: Dynaconf

#8499 dynaconf - add report portal config
  conf/report_portal.yaml.template
Labels: Dynaconf

#8498 adding hammer defaults check
  tests/foreman/cli/test_hammer.py
Labels: CLI

#8504 clarify current server.yaml behavior
  conf/server.yaml.template
Labels: Dynaconf

#8494 [DynaConf] Performance settings conversion
  conf/performance.yaml.template
  robottelo/config/validators.py
Labels: Dynaconf

#8488 jobtemplate pytest conversion
  tests/foreman/cli/test_jobtemplate.py
Labels: PytestConversion

#8482 pytest conversion of tests/foreman/cli/test_computeresource_osp.py
  tests/foreman/cli/test_computeresource_osp.py
Labels: PytestConversion

#8483 cli ostreeebranch to pytest
  tests/foreman/cli/test_ostreebranch.py
Labels: 6.9, PytestConversion

#8500 Replace old custom kickstarter repo
  robottelo/constants/repos.py
Labels: 6.9

#8491 Add certs.yaml.template
  conf/certs.yaml.template
Labels: Dynaconf

#8497 md5 signed repo test
  robottelo/constants/repos.py
  tests/foreman/cli/test_repository.py
Labels: 6.10, 6.9, CLI

#8490 u2p cli satellite_sync
  tests/foreman/cli/test_satellitesync.py
Labels: PytestConversion

#8510 Add skip to modulestream test case due to bz
  tests/foreman/ui/test_modulestreams.py
Labels: 6.9

#8175 ContentViewVersion Pytest Conversion
  tests/foreman/api/test_contentviewversion.py
Labels: PytestConversion, Tier 1 ACK

#8493 tests/robottelo/test_func_shared.py fix and pytest conversion
  tests/robottelo/test_func_shared.py
Labels: Bug, PytestConversion, UnitTests

#8511 convert cli/test_discoveredhost to pytest
  tests/foreman/cli/test_discoveredhost.py
Labels: PytestConversion

#8512 convert test_virtwho upgrade cases to pytest
  tests/upgrades/test_virtwho.py
Labels: PytestConversion, Tier 2 ACK

#8420 Convert cli contentaccess to pytest
  pytest_fixtures/api_fixtures.py
  robottelo/constants/__init__.py
  tests/foreman/cli/test_contentaccess.py
Labels: PytestConversion

#8503 convert inc updates to pytest
  pytest_fixtures/broker.py
  robottelo/hosts.py
  tests/foreman/longrun/test_inc_updates.py
Labels: PytestConversion

#8523 [VM -> Broker] Conversion of api/test_hostcollection
  pytest_fixtures/xdist.py
  robottelo/config/facade.py
  tests/foreman/api/test_hostcollection.py
Labels: VMBroker

#8521 move vlan settings to dynaconf
  conf/vlan.yaml.template
Labels: Dynaconf

#8532 Remove nitpicky and adjust makefiles for docs
  Makefile
  docs/Makefile
  docs/conf.py
Labels: Documentation

#8537 Handle server.hostnames being empty in xdist
  pytest_fixtures/xdist.py
Labels: Bug

#8531 closed loop, check org api
  tests/foreman/api/test_organization.py
Labels: API

#8546 Set ROBOTTELO_DIR automatically
  robottelo/config/__init__.py
Labels: Bug

#8514 migrate capsule settings to dynaconf
  conf/capsule.yaml.template
  pytest_fixtures/broker.py
  robottelo/config/validators.py
Labels: Dynaconf

#8550 broker conv of ui/test_jobinvocation.py
  tests/foreman/ui/test_jobinvocation.py
Labels: VMBroker

#8530 dynaconf conversion for OSP compute resource
  conf/osp.yaml.template
Labels: Dynaconf
