Repository SatelliteQE/robottelo, pull requests merged in 2021-06, with the labels that each got.

#8652 vm2br_ui_test_dashboard
  tests/foreman/ui/test_dashboard.py
Labels: 6.10, 6.9, VMBroker

#8620 code coverage for bz 1922134
  tests/foreman/api/test_contentview.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/ui/test_contentview.py
Labels: QETestCoverage

#8654 Subscription UI vm broker
  tests/foreman/ui/test_subscription.py
Labels: VMBroker

#8638 cli rex fixes
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI

#8639 Add test downgrade applicable package
  robottelo/constants/repos.py
  tests/foreman/cli/test_errata.py
Labels: TestAutomation

#8659 Contentmanagement api vm broker
  tests/foreman/api/test_contentmanagement.py
Labels: VMBroker

#8657 VMBroker conversion rex in upgrades
  tests/upgrades/test_remoteexecution.py
Labels: Upgrade Scenario, VMBroker

#8666 vm2br_ui_test_contenthost
  robottelo/cli/factory.py
  tests/foreman/ui/test_contenthost.py
Labels: 6.10, 6.9, VMBroker

#8661 Convert UI hostcollection to VMBroker
  tests/foreman/ui/test_hostcollection.py
Labels: VMBroker

#8668 fips client rex tests
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI

#8669 Convert ui.test_activationkey to VMBroker
  tests/foreman/ui/test_activationkey.py
Labels: VMBroker

#8678 Reassign repository tests
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_repository_set.py
  tests/foreman/cli/test_docker.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_repository_set.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
  tests/upgrades/test_repository.py
  tests/upgrades/test_yum_plugins.py
Labels: TestMetadata

#8679 Update :CaseComponent and :Assignee for API tests
  tests/foreman/api/test_audit.py
  tests/foreman/api/test_computeresource_libvirt.py
  tests/foreman/api/test_multiple_paths.py
  tests/foreman/api/test_remoteexecution.py
  tests/foreman/endtoend/test_api_endtoend.py
  tests/upgrades/test_remoteexecution.py
Labels: TestMetadata

#8672 Add stubbed test for file content in Pulp3
  tests/foreman/cli/test_repository.py
Labels: Manual Test

#8674 Add new manual BZ tests for repositories and products
  tests/foreman/cli/test_product.py
  tests/foreman/cli/test_repository.py
  tests/foreman/ui/test_product.py
  tests/foreman/ui/test_repository.py
Labels: Manual Test

#8682 Remove check for static file
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: TestFailure

#8683 Revert "Update pytest-reportportal to 5.0.9"
  requirements.txt
Labels: Bug, dependencies

#8665 Removing VirtualMachine class and methods
  conf/broker.yaml.template
  pytest_fixtures/broker.py
  robottelo/cleanup.py
  robottelo/cli/factory.py
  robottelo/config/facade.py
  robottelo/hosts.py
  robottelo/products.py
  robottelo/vm.py
  robottelo/vm_capsule.py
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/api/test_remoteexecution.py
  tests/foreman/cli/test_activationkey.py
  tests/foreman/cli/test_computeresource_azurerm.py
  tests/foreman/cli/test_computeresource_libvirt.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_organization.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_subscription.py
  tests/foreman/rhai/test_rhai.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_remoteexecution.py
  tests/foreman/ui/test_reporttemplates.py
  tests/foreman/ui/test_subscription.py
  tests/robottelo/test_vm.py
Labels: DO NOT MERGE, VMBroker

#8670 stubbed cases for PAT
  tests/foreman/api/test_user.py
  tests/foreman/cli/test_user.py
  tests/foreman/ui/test_user.py
Labels: 6.10, Manual Test

#8673 Add test install applicable package to a registerd host
  tests/foreman/cli/test_errata.py
Labels: enhancement

#8690 Add test downgrade package shows errata
  tests/foreman/cli/test_errata.py
Labels: GoodStarterIssue

#8502 [RFE] Upgrade Scenarios sharing workers between pre and post part
  tests/upgrades/conftest.py
  tests/upgrades/scenario_workers.py
Labels: Upgrade Scenario

#8699 Fix modified gpgkey init
  robottelo/config/__init__.py
Labels: Easy Fix :), TestFailure, Urgent Priority

#8664 Fix crud infrastructure tests for 6.10
  tests/foreman/ui/test_computeresource.py
  tests/foreman/ui/test_domain.py
  tests/foreman/ui/test_http_proxy.py
Labels: 6.10

#8695 Stub test case to verify pulp3 logs are captured
  tests/foreman/cli/test_logging.py
Labels: 6.10, Manual Test

#8698 qe test coverage bz 1910314
  tests/foreman/cli/test_host.py
Labels: 6.10, QETestCoverage

#8696 6.10 ansible feature stubs
  tests/foreman/ui/test_remoteexecution.py
Labels: 6.10, Manual Test

#8684 Adding stubbed tests for RPM content
  tests/foreman/cli/test_repository.py
Labels: Manual Test

#8686 Edit stubbed tests for Inter Satellite Sync (ISS)
  tests/foreman/cli/test_satellitesync.py
Labels: Manual Test

#8706 Fix datetime serialization
  tests/foreman/api/test_syncplan.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_syncplan.py
Labels: PytestConversion, TestAutomation

#8709 [cherry-pick] Fix positive recommend repos test
  robottelo/constants/__init__.py
  tests/foreman/ui/test_repository.py
Labels: 6.9, TestFailure

#8711 Update reqs for nailgun/airgun
  requirements.txt
Labels: dependencies

#8710 [cherry-pick] Syspurpose: Role and usage type reversed
  tests/foreman/ui/test_contenthost.py
Labels: 6.9, TestFailure

#8712 Update hammer_commands.json for 6.10
  tests/foreman/data/hammer_commands.json
Labels: 6.10, CLI

#8650 Content Credential changes for 6.10
  robottelo/cli/factory.py
  tests/foreman/cli/test_content_credentials.py
Labels: 6.10

#8676 Remove XenServer from virt-who config plugin
  conf/virtwho.yaml.template
  tests/foreman/virtwho/api/test_xen.py
  tests/foreman/virtwho/cli/test_xen.py
  tests/foreman/virtwho/ui/test_xen.py
Labels: 6.10

#8021 Automate stubbed test : test_positive_discover_module_stream_repo_via_existing_product
  tests/foreman/ui/test_repository.py
Labels: Tier 2 ACK, UI

#8708 Automated stubbed test case for logging of pulp3
  tests/foreman/cli/test_logging.py
Labels: 6.10, TestAutomation

#8715 parameter ids for cli rex tests
  tests/foreman/cli/test_remoteexecution.py
Labels: 6.10, CLI

#8716 [cherry-pick] parameter ids for cli rex tests
  tests/foreman/cli/test_remoteexecution.py
Labels: 6.9, CLI

#8717 Backport fix datetime serialization
  tests/foreman/api/test_syncplan.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_syncplan.py
Labels: PytestConversion, TestAutomation

#8718 Remove stray comma and redundant brackets
  tests/foreman/api/test_syncplan.py
Labels: TestFailure

#8722 fix `_setup_vm_client_host 6.10`
  tests/foreman/ui/test_remoteexecution.py
Labels: 6.10, TestFailure, VMBroker

#8724 fixed couple of bz tags
  tests/foreman/cli/test_subscription.py
  tests/foreman/ui/test_subscription.py
Labels: 6.10

#8719 [cherry-pick] Fix typo in api syncplan 6 9 branch
  tests/foreman/api/test_syncplan.py
Labels: TestFailure

#8721 fix `_setup_vm_client_host 6.9.z`
  tests/foreman/ui/test_remoteexecution.py
Labels: 6.9, TestFailure, VMBroker

#8726 Update pre-commit hooks
  .pre-commit-config.yaml
  pytest_fixtures/ansible_fixtures.py
  pytest_fixtures/api_fixtures.py
  pytest_fixtures/oscap_fixtures.py
  pytest_plugins/markers.py
  robottelo/api/utils.py
  robottelo/cli/auth.py
  robottelo/cli/base.py
  robottelo/cli/globalparam.py
  robottelo/cli/proxy.py
  robottelo/cli/srpm.py
  robottelo/decorators/func_shared/shared.py
  robottelo/helpers.py
  robottelo/host_info.py
  robottelo/libvirt_discovery.py
  robottelo/ssh.py
  robottelo/system_facts.py
  robottelo/upgrade_utility.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_user.py
  tests/foreman/api/test_usergroup.py
  tests/foreman/cli/test_computeresource_azurerm.py
  tests/foreman/cli/test_filter.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_role.py
  tests/foreman/cli/test_syncplan.py
  tests/foreman/cli/test_user.py
  tests/foreman/cli/test_usergroup.py
  tests/foreman/longrun/test_inc_updates.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_computeresource_azurerm.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_discoveryrule.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_jobinvocation.py
  tests/foreman/ui/test_organization.py
  tests/robottelo/test_cli.py
  tests/robottelo/test_func_shared.py
  tests/robottelo/test_host_info.py
  tests/upgrades/conftest.py
  tests/upgrades/test_client.py
  tests/upgrades/test_satellitesync.py
  tests/upgrades/test_yum_plugins.py
Labels: dependencies

#8730 Update broker to 0.1.20
  requirements.txt
Labels: dependencies

#8707 Fix syspurpose usage and role
  tests/foreman/ui/test_contenthost.py
Labels: GoodStarterIssue, TestFailure, UI

#8732 Apply workaround for BZ#1695733
  tests/foreman/api/test_syncplan.py
Labels: TestAutomation

#8703 Fix positive recommend repos test
  robottelo/constants/__init__.py
  tests/foreman/ui/test_repository.py
Labels: GoodStarterIssue, TestFailure, UI

#8737 Removing test cases that relies on /var/lib/pulp/
  tests/foreman/api/test_contentview.py
  tests/foreman/cli/test_contentview.py
Labels: 6.10, API, CLI

#8720 Fix test positive install modular errata
  robottelo/constants/__init__.py
  tests/foreman/ui/test_hostcollection.py
Labels: 6.9, TestFailure

#8714 Stop using wait for sync plan tasks
  tests/foreman/api/test_syncplan.py
  tests/foreman/cli/test_syncplan.py
  tests/foreman/ui/test_syncplan.py
Labels: 6.10, TestFailure

#8734 [cherry-pick] Apply workaround for BZ#1695733
  tests/foreman/api/test_syncplan.py
Labels: 6.9

#8701 Remove manual connection for broker-based hosts
  robottelo/hosts.py
Labels: Easy Fix :)
