Repository SatelliteQE/robottelo, pull requests merged in 2021-12, with the labels that each got.

#9210 ui host tests 2 small fixes
  pytest_fixtures/core/sys.py
  tests/foreman/ui/test_host.py
Labels: UI, 6.10, Easy Fix :)

#9206 fixes in rex ui tests
  tests/foreman/ui/test_remoteexecution.py
Labels: TestFailure, 6.10

#9207 Fix for puppet-related UI tests
  robottelo/hosts.py
  tests/foreman/ui/test_puppetclass.py
  tests/foreman/ui/test_smartclassparameter.py
Labels: UI, 6.10, Easy Fix :)

#9203 Fix and update api/cli endtoend tests to use rhel7 client
  robottelo/api/utils.py
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: CLI, API, TestFailure, 6.10

#9099 Adding a location to all sessions in test_contenthost.py
  tests/foreman/ui/test_contenthost.py
Labels: 6.10

#9183 Automation qe_test_coverage_1785146
  tests/foreman/cli/test_errata.py
Labels: QETestCoverage, 6.10

#9217 [VirtWho tests skip impact] Skip non sat-ci components tests Plugin
  pytest_plugins/infra_dependent_markers.py
  pytest_plugins/marker_deselection.py
Labels: Question, enhancement

#9005 Fix katello agent tests to run on different satellite
  pytest_fixtures/core/broker.py
  pytest_fixtures/core/sys.py
  robottelo/cli/base.py
  robottelo/hosts.py
  tests/foreman/cli/test_contentaccess.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_host_collection.py
  tests/foreman/cli/test_katello_agent.py
Labels: CLI, TestFailure, 6.10

#9219 Add test to sync ansible-collection repo to capsule
  robottelo/hosts.py
  tests/foreman/api/test_contentmanagement.py
Labels: QETestCoverage, 6.10

#9218 Update the organization to module_manifest_org for virtwho plugin cases
  robottelo/virtwho_utils.py
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_hyperv.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_libvirt.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_hyperv.py
  tests/foreman/virtwho/cli/test_kubevirt.py
  tests/foreman/virtwho/cli/test_libvirt.py
  tests/foreman/virtwho/conftest.py
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_hyperv.py
  tests/foreman/virtwho/ui/test_kubevirt.py
  tests/foreman/virtwho/ui/test_libvirt.py
Labels: Bug, TestFailure, Tier 2 ACK, 6.10

#9204 Test: positive create with new location and organization
  tests/foreman/cli/test_repository.py
Labels: CLI, 6.10

#9228 Deploy Arguments Lowered
  pytest_fixtures/core/broker.py
Labels: Tier 2 ACK

#9230 Closed-loop for BZ 2025494
  tests/foreman/api/test_contentmanagement.py
Labels: Bug, QETestCoverage, 6.10

#9192 host traces test introduced
  pytest_fixtures/component/host.py
  pytest_fixtures/core/contenthosts.py
  robottelo/cli/host.py
  robottelo/hosts.py
  tests/foreman/api/test_host.py
  tests/foreman/cli/test_host.py
Labels: CLI, 6.10

#9114 Add test positive toggle subscription status
  tests/foreman/ui/test_contenthost.py
Labels: QETestCoverage, 6.10

#9149 Add file-type repo sync to capsule test
  robottelo/constants/__init__.py
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/data/emanuel.iso
Labels: API, QETestCoverage, 6.10

#9156 fix contentview cli failures
  tests/foreman/ui/test_contentview.py
Labels: UI, TestFailure, 6.10

#9190 Adding test coverage around rh_cloud stubbed cases
  robottelo/rh_cloud_utils.py
  tests/foreman/api/test_rhcloud_inventory.py
Labels: API, QETestCoverage, 6.10

#9169 Remove use of pre-made repofiles in favor of repofile construction
  robottelo/config/validators.py
  robottelo/hosts.py
  robottelo/products.py
  tests/foreman/installer/test_installer.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_host.py
Labels: 6.10

#9196 Fix guardtime, improve sync tests
  tests/foreman/cli/test_syncplan.py
  tests/foreman/ui/test_syncplan.py
Labels: 6.10

#9231 Added tests to satellitesync
  tests/foreman/cli/test_satellitesync.py
Labels: 6.10

#9234 encapsulate the cockpit sat installer under the Sat class
  pytest_fixtures/core/sys.py
  robottelo/hosts.py
Labels: 6.10, Easy Fix :)

#9263 Removing osp hostname from osp.yaml.template
  conf/osp.yaml.template
Labels: Easy Fix :)

#9251 added the customer scenarios for hg
  robottelo/cli/factory.py
  tests/foreman/cli/test_hostgroup.py
Labels: QETestCoverage, 7.0
