Repository SatelliteQE/robottelo, pull requests merged in 2021-02, with the labels that each got.

#8319 fixing "Taxonomy has already been taken" in various UI host tests
  tests/foreman/ui/test_host.py
Labels: 6.9, TestFailure, UI

#8324 Add temporary reportportal-client requirement
  requirements.txt
Labels: dependencies

#8288 Add test for bootstrap.py
  pytest_fixtures/api_fixtures.py
  tests/foreman/cli/test_bootstrap_script.py
Labels: CLI

#8320 updated the fix for missed test
  tests/foreman/ui/test_ldap_authentication.py
Labels: TestFailure

#8325 Month format change
  tests/foreman/ui/test_syncplan.py
Labels: TestFailure

#8326 skip rename due to 1897360
  tests/foreman/sys/test_rename.py
Labels: 6.9, SYS, TestFailure

#8314 [6.8.z] add reportportal agent to dependencies to enable live logging
  requirements.txt
Labels: 6.8

#8328 rex stubs cleanup
  tests/foreman/cli/test_remoteexecution.py
Labels: 6.9, UI

#8161 Convert api gpgkey unittest to pytest
  tests/foreman/api/test_content_credentials.py
  tests/foreman/api/test_gpgkey.py
Labels: PytestConversion

#8193 Pytest conversion for /api/test_computeprofile.py
  tests/foreman/api/test_computeprofile.py
Labels: API, PytestConversion, Tier 1 ACK

#8278 Rewrite to pytest
  tests/foreman/longrun/test_provisioning_computeresource.py
Labels: PytestConversion

#8331 Fix reporting 69
  tests/foreman/ui/test_reporttemplates.py
Labels: 6.9

#8184 cli test host rewritten to pytest
  pytest_fixtures/api_fixtures.py
  pytest_plugins/markers.py
  tests/foreman/api/test_host.py
  tests/foreman/cli/test_host.py
Labels: 6.9, PytestConversion

#8197 convert api host-collection unittest to pytest
  tests/foreman/api/test_hostcollection.py
Labels: PytestConversion

#8300 Dynaconf CI changes including native configuration for Airgun and Nailgun
  robottelo.properties.sample
  robottelo/cli/factory.py
  robottelo/config/__init__.py
  robottelo/config/base.py
  robottelo/config/facade.py
  robottelo/hosts.py
  robottelo/vm.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_contenthost.py
Labels: enhancement

#8363 Remove the rp client requirement
  requirements.txt
Labels: dependencies

#8366 Update to broker 0.1.9
  requirements.txt
Labels: dependencies

#8368 Fix xdist worker logging
  pyproject.toml
  tests/foreman/conftest.py
Labels: Bug

#8369 Add fixture to disable BFA
  conftest.py
  pytest_fixtures/sys_fixtures.py
  tests/foreman/conftest.py
Labels: TestFailure

#8377 Ignore pytest-reportportal client errors
  pyproject.toml
Labels: PytestConversion

#8376 syspurpose bulk action test
  tests/foreman/ui/test_contenthost.py
Labels: 6.9, UI

#8347 Update README with some links to airgun/nailgun/ssh2-python
  README.rst
Labels: Documentation

#8352 skip rename on different bz
  tests/foreman/sys/test_rename.py
Labels: TestFailure

#8356 global registration test
  tests/foreman/ui/test_host.py
Labels: 6.9, UI
