Repository SatelliteQE/robottelo, pull requests merged in 2022-03, with the labels that each got.

#9400 Use host's os_version instead of conf
  robottelo/hosts.py
Labels: Easy Fix :), 7.0

#9374 Fix incorrect file naming after refactor. Use org with manifest.
  tests/foreman/ui/test_reporttemplates.py
Labels: UI, 6.10

#9406 Remove unittest2 dependency
  requirements.txt
  tests/robottelo/test_cli.py
Labels: Easy Fix :)

#9201 Port/refactor of backup/restore tests from testfm
  pytest_fixtures/component/maintain.py
  robottelo/hosts.py
  tests/foreman/maintain/test_backup_restore.py
Labels: RFE

#9383 [cherrypick] Port/refactor of backup/restore tests from testfm
  pytest_fixtures/component/maintain.py
  robottelo/hosts.py
  tests/foreman/maintain/test_backup_restore.py
Labels: CLI, 6.10

#9408 unskip effective user rex test
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, 7.0

#9380 Add test update packages checkbox
  tests/foreman/ui/test_host.py
Labels: enhancement, TestFailure

#9414 Fixing test case with mirroring policy
  tests/foreman/api/test_contentmanagement.py
Labels: API, TestFailure, 6.10

#9411 Fix rhel_version param in capsule_setup
  robottelo/hosts.py
Labels: Tier 2 ACK, Easy Fix :)

#9415 removing NA test case
  tests/foreman/ui/test_contentview.py
Labels: 6.10, Easy Fix :)

#9392 Skip katello-agent tests from automation
  tests/foreman/cli/test_katello_agent.py
Labels: Tier 2 ACK

#9418 Fix failed test case for satellite sync for 6.10.z
  tests/foreman/cli/test_satellitesync.py
Labels: CLI, 6.10

#9420 Update component ownership
  tests/foreman/api/test_role.py
  tests/foreman/api/test_user.py
  tests/foreman/api/test_usergroup.py
  tests/foreman/cli/test_computeresource_osp.py
  tests/foreman/cli/test_role.py
  tests/foreman/cli/test_user.py
  tests/foreman/cli/test_usergroup.py
  tests/foreman/ui/test_role.py
  tests/foreman/ui/test_user.py
  tests/foreman/ui/test_usergroup.py
  tests/upgrades/test_role.py
  tests/upgrades/test_user.py
  tests/upgrades/test_usergroup.py
Labels: Tier 1 ACK

#9419 Fixing CV failures for 6.10
  tests/foreman/ui/test_contentview.py
Labels: 6.10

#9413 Add test for puppet bootstraping
  pytest_fixtures/component/puppet.py
  tests/foreman/api/test_puppetbootstrap.py
Labels: API, 7.0

#9416 Adding test for FAM import/sync and run on Satellite
  robottelo/cli/ansible.py
  robottelo/cli/host.py
  robottelo/constants/__init__.py
  tests/foreman/sys/test_fam.py
Labels: CLI, 7.0

#9423 add rhel9 fips host to supportability matrix
  conf/supportability.yaml
  tests/foreman/cli/test_remoteexecution.py
Labels: 7.0

#9393 Add test upgrade katello consumer rpm
  tests/foreman/cli/test_registration.py
Labels: QETestCoverage

#9328 Api testhost run puppet tests on destructive satellite with enabled puppet
  tests/foreman/api/test_host.py
Labels: API, 7.0

#9399 new simple ui test host introduced
  robottelo/ui/utils.py
  tests/foreman/ui/test_host.py
Labels: UI, 7.0

#9429 Test failures fix
  tests/foreman/cli/test_location.py
  tests/foreman/cli/test_setting.py
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
Labels: TestFailure

#9427 Simple fix for a cv test case
  tests/foreman/ui/test_contentview.py
Labels: 6.10, Easy Fix :)

#9432 [6.10.z] cherrypick setings test fix
  tests/foreman/ui/test_settings.py
Labels: UI, Tier 1 ACK, 6.10

#9433 test_errata fix api and cli
  robottelo/cli/host.py
  tests/foreman/api/test_errata.py
  tests/foreman/cli/test_errata.py
Labels: CLI, API, TestFailure

#9444 Cherry-pick repo test fixes
  tests/foreman/api/test_repository.py
Labels: API, 6.10

#9410 test rex against capsule permissions
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, 7.0

#9448 Fixing BZ Authorization
  robottelo/utils/issue_handlers/bugzilla.py
Labels: Bug, dependencies

#9449 Fixing BZ Authorization (6.10.z backport)
  robottelo/utils/issue_handlers/bugzilla.py
Labels: 6.10

#9452 Fixing BZ Authorization (6.9.z Backport)
  robottelo/utils/issue_handlers/bugzilla.py
Labels: 6.9

#9455 Refixing BZ Auth
  robottelo/utils/issue_handlers/bugzilla.py
Labels: Bug

#9457 Refixing BZ Auth (6.9.z backport)
  robottelo/utils/issue_handlers/bugzilla.py
Labels: 6.9

#9456 Refixing BZ Auth (6.10.z backport)
  robottelo/utils/issue_handlers/bugzilla.py
Labels: 6.10

#9454 Size is now enforced in MB
  tests/foreman/ui/test_computeresource_libvirt.py
Labels: TestFailure

#9462 test search for infrastructure hosts
  tests/foreman/cli/test_host.py
Labels: CLI, 7.0

#9447 automation for bz:1747177
  tests/foreman/api/test_contentmanagement.py
Labels: QETestCoverage, Tier 1 ACK, 6.10
