Repository SatelliteQE/robottelo, pull requests merged in 2022-10, with the labels that each got.

#10128 Fix override of deploy args settings
  pytest_fixtures/core/broker.py
Labels: Urgent Priority, CherryPick

#10132 Update expected installer flags for 6.12
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/installer/test_installer.py
  tests/foreman/longrun/test_capsule_loadbalancer.py
Labels: TestFailure, Easy Fix :), No-CherryPick

#10033 fixed: rhsso tests for RHEL8 and certificate tests
  pytest_fixtures/component/satellite_auth.py
  robottelo/rhsso_utils.py
  robottelo/utils/issue_handlers/bugzilla.py
  tests/foreman/destructive/test_katello_certs_check.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/sys/test_katello_certs_check.py
Labels: TestFailure, CherryPick, 6.12.z

#10070 Fix puppet configure test
  robottelo/hosts.py
  tests/foreman/destructive/test_puppetplugin.py
Labels: TestFailure, CherryPick

#10092 rex effective user fix
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, TestFailure, Tier 1 ACK, No-CherryPick, 6.12.z

#10035 Add coverage for hammer negotiate auth (IDM)
  pytest_fixtures/component/satellite_auth.py
  robottelo/cli/auth.py
  robottelo/constants/__init__.py
  tests/foreman/destructive/test_ldap_authentication.py
Labels: No-CherryPick

#10136 Fix RHSSO multi-group test
  tests/foreman/destructive/test_ldap_authentication.py
Labels: TestFailure, Tier 1 ACK, CherryPick

#10134 Fix resolv.conf hacking for AD setup
  pytest_fixtures/component/satellite_auth.py
Labels: TestFailure, Tier 1 ACK, CherryPick

#10139 [6.11.z] Do not pin the release to the latest one explicitly
  robottelo/hosts.py
Labels: Tier 1 ACK, 6.11.z, CherryPick, Auto_Cherry_Picked

#10129 [6.11.z] Remove system_facts
  robottelo/system_facts.py
Labels: Tier 1 ACK, 6.11.z, CherryPick, Auto_Cherry_Picked

#9676 Automating Satellite capsule loadbalancer
  pytest_fixtures/component/activationkey.py
  pytest_fixtures/component/contentview.py
  pytest_fixtures/core/broker.py
  robottelo/hosts.py
  tests/foreman/data/99-haproxy.conf
  tests/foreman/data/haproxy.cfg
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/longrun/test_capsule_loadbalancer.py
Labels: No-CherryPick

#10059 Test fixes for errata
  tests/foreman/api/test_errata.py
  tests/foreman/ui/test_errata.py
Labels: UI, API, Tier 1 ACK, CherryPick

#10148 Make sure snap version is string
  robottelo/host_helpers/contenthost_mixins.py
Labels: Easy Fix :), No-CherryPick

#10149 [6.11.z] Bump sphinx-autoapi from 1.9.0 to 2.0.0
  requirements-optional.txt
Labels: Tier 1 ACK, 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10144 [6.10.z] [6.11.z] Remove system_facts
  robottelo/system_facts.py
Labels: Tier 1 ACK, No-CherryPick, Auto_Cherry_Picked

#10143 [6.10.z] [6.11.z] Do not pin the release to the latest one explicitly
  robottelo/hosts.py
Labels: Tier 1 ACK, No-CherryPick, Auto_Cherry_Picked

#10142 fix 10141: release can be float but needs casting to string object
  robottelo/host_helpers/contenthost_mixins.py
Labels: Easy Fix :), CherryPick

#10146 [6.11.z] Fix resolv.conf hacking for AD setup
  pytest_fixtures/component/satellite_auth.py
Labels: TestFailure, Tier 1 ACK, Tier 2 ACK, 6.11.z, No-CherryPick

#10133 [6.11.z] Fix puppet configure test
  robottelo/hosts.py
  tests/foreman/destructive/test_puppetplugin.py
Labels: Tier 1 ACK, 6.11.z, No-CherryPick

#10150 Webhook password bug
  tests/foreman/ui/test_webhook.py
Labels: CherryPick

#10137 Debug and fix failing DHCPDNS tests
  tests/foreman/destructive/test_infoblox.py
Labels: CherryPick

#10158 [6.11.z] Bump cryptography from 38.0.1 to 38.0.2
  requirements.txt
Labels: 6.11.z, CherryPick, Auto_Cherry_Picked

#10157 adding no_contaiers tags for a couple of rex tests
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, Easy Fix :), No-CherryPick

#10084 async ssh rex provider test
  pytest_fixtures/core/broker.py
  robottelo/hosts.py
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, Tier 1 ACK, No-CherryPick, 6.12.z

#10161 Cluster instead of datacenter. Used to work when those were equal.
  tests/foreman/ui/test_computeresource.py
Labels: Tier 1 ACK, Easy Fix :), No-CherryPick

#10159 fixing KeyError in parametrized fixture
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, Easy Fix :), No-CherryPick, 6.12.z

#10153 Extend sync timeout for a docker image
  tests/foreman/api/test_contentmanagement.py
Labels: TestFailure, Tier 1 ACK, Easy Fix :), CherryPick

#10165 [6.11.z] Extend sync timeout for a docker image
  tests/foreman/api/test_contentmanagement.py
Labels: 6.11.z, CherryPick, Auto_Cherry_Picked

#10168 sat-clone: Enable modules on RHEL 8+
  tests/foreman/destructive/test_clone.py
Labels: TestFailure, Easy Fix :), 6.11.z, No-CherryPick

#10171 [6.11.z] Fix override of deploy args settings
  pytest_fixtures/core/broker.py
Labels: CherryPick

#10147 [6.11.z] Fix RHSSO multi-group test
  pytest_fixtures/component/satellite_auth.py
  robottelo/rhsso_utils.py
  tests/foreman/destructive/test_ldap_authentication.py
Labels: TestFailure, 6.11.z, No-CherryPick

#10172 fix runtime error introduced by 884fb93
  pytest_fixtures/core/broker.py
Labels: CherryPick

#10167 [6.10.z] [6.11.z] Extend sync timeout for a docker image
  tests/foreman/api/test_contentmanagement.py
Labels: Tier 1 ACK, No-CherryPick, Auto_Cherry_Picked

#10174 [6.11.z] fix runtime error introduced by 884fb93
  pytest_fixtures/core/broker.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10176 Automation coverage for BZ 1908478 and 1962842
  robottelo/cli/sm_maintenance_mode.py
  tests/foreman/maintain/test_backup_restore.py
Labels: QETestCoverage, CherryPick

#10180 [6.11.z] Automation coverage for BZ 1908478 and 1962842
  robottelo/cli/sm_maintenance_mode.py
  tests/foreman/maintain/test_backup_restore.py
Labels: 6.11.z, CherryPick, Auto_Cherry_Picked

#10177 Use another user for IDM tests
  pytest_fixtures/component/satellite_auth.py
Labels: TestFailure, CherryPick

#10189 Delete old satellite hostname
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick

#10185 Redundant code cleaning.
  robottelo/hosts.py
Labels: Easy Fix :), CherryPick

#10191 [6.11.z] Redundant code cleaning.
  robottelo/hosts.py
Labels: 6.11.z, CherryPick, Auto_Cherry_Picked

#10193 Fix selinux test failing on RHEL8
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: TestFailure, Easy Fix :), CherryPick

#10196 [6.11.z] Fix selinux test failing on RHEL8
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10194 Add a test to check pulp status via pulp-cli
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: QETestCoverage, No-CherryPick, 6.12.z

#10198 [6.11.z] Use another user for IDM tests (#10177)
  pytest_fixtures/component/satellite_auth.py
Labels: 6.11.z, No-CherryPick

#10184 Take over the LDAP and Auth components
  tests/foreman/api/test_ldapauthsource.py
  tests/foreman/cli/test_auth.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/cli/test_sso.py
  tests/foreman/destructive/test_auth.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: Easy Fix :), CherryPick

#10203 [6.11.z] Take over the LDAP and Auth components
  tests/foreman/api/test_ldapauthsource.py
  tests/foreman/cli/test_auth.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/cli/test_sso.py
  tests/foreman/destructive/test_auth.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: 6.11.z, CherryPick, Auto_Cherry_Picked

#10178 Activation key test fixes
  robottelo/utils/sso.py
Labels: Easy Fix :), CherryPick

#10173 fixes in capsule upgrade playbook tests
  tests/foreman/api/test_remoteexecution.py
  tests/foreman/destructive/test_remoteexecution.py
Labels: TestFailure, Easy Fix :), CherryPick, 6.12.z

#10145 Adding PXE-based API discovery test
  pytest_fixtures/component/provision_pxe.py
  pytest_fixtures/core/broker.py
  tests/foreman/api/test_discoveredhost.py
Labels: CherryPick

#10206 [6.10.z] [6.11.z] Bump manifester from 0.0.8 to 0.0.9
  requirements.txt
Labels: Tier 1 ACK, 6.10.z, No-CherryPick, Auto_Cherry_Picked

#10207 Fix TypeError when using api property for user_nailgun_config
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_template.py
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/ui/test_bookmarks.py
Labels: No-CherryPick

#10208 [6.11.z] Bump deepdiff from 5.8.1 to 6.2.1
  requirements.txt
Labels: Tier 1 ACK, 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10200 Parametrize KS repo syncing test
  robottelo/host_helpers/satellite_mixins.py
  tests/foreman/api/test_contentmanagement.py
Labels: Tier 1 ACK, CherryPick

#10212 [6.11] [Cherry-pick] Fix fake yum on rhel6
  tests/foreman/cli/test_host.py
  tests/foreman/ui/test_host.py
Labels: 6.11.z, No-CherryPick

#10190 added test coverage for clone host-group
  tests/foreman/ui/test_hostgroup.py
Labels: UI, QETestCoverage, Tier 1 ACK, CherryPick

#10188 Closed loop BZ#1830403
  tests/foreman/api/test_contentmanagement.py
Labels: QETestCoverage, CherryPick

#10197 fixing KeyError in parametrized fixture
  tests/foreman/cli/test_remoteexecution.py
Labels: Tier 1 ACK, 6.11.z, No-CherryPick

#10205 [6.11.z] fixes in capsule upgrade playbook tests
  tests/foreman/api/test_remoteexecution.py
  tests/foreman/destructive/test_remoteexecution.py
Labels: Tier 1 ACK, 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10210 [6.11.z] Parametrize KS repo syncing test
  robottelo/host_helpers/satellite_mixins.py
  tests/foreman/api/test_contentmanagement.py
Labels: Tier 1 ACK, 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10215 [6.11.z] added test coverage for clone host-group
  tests/foreman/ui/test_hostgroup.py
Labels: Tier 1 ACK, 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10192 Test fix for e2e provisioning_template test
  tests/foreman/ui/test_provisioningtemplate.py
Labels: CherryPick

#10211 GHA: Added support to handle auto-cherry-pick failure & create issue
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick

#10221 [6.11.z] Fix setup_custom_repo function
  tests/foreman/cli/test_host.py
Labels: 6.11.z, No-CherryPick
