Repository SatelliteQE/robottelo, pull requests merged in 2022-05, with the labels that each got.

#9540 [6.10.z] Changing assignee for gsulliva
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_discoveryrule.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/cli/test_discoveryrule.py
  tests/foreman/ui/test_discoveredhost.py
  tests/foreman/ui/test_discoveryrule.py
Labels: 6.10

#9527 cockpit: test coverage for #1876220
  tests/foreman/ui/test_host.py
Labels: UI, 6.11

#9435 [Merge with CI PR] Secrets from vault via DynaConf
  .env
  .env.example
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  .gitignore
  Makefile
  docs/index.rst
  requirements.txt
  robottelo/config/__init__.py
  robottelo/config/validators.py
  robottelo/errors.py
  scripts/vault_login.py
Labels: enhancement, High Complexity, Dynaconf, Framework Changes, CherryPick

#9541 [6.9.z] Changing assignee for gsulliva
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_discoveryrule.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/cli/test_discoveryrule.py
  tests/foreman/ui/test_discoveredhost.py
  tests/foreman/ui/test_discoveryrule.py
Labels: 6.9

#9547 Bring back changes around Satellite api/cli/ui_session properties
  robottelo/hosts.py
Labels: Bug, 6.9

#9575 [6.10.z] Update Ansible Collection assignee
  tests/foreman/sys/test_fam.py
Labels: 6.10

#9573 fixed activation key test for deleting subs
  tests/foreman/cli/test_activationkey.py
Labels: CLI, Easy Fix :)

#9568 install_katello_ca does not raise ContentHostError
  robottelo/hosts.py
Labels: 6.11

#9569 [6.10] install_katello_ca does not raise ContentHostError
  robottelo/hosts.py
Labels: 6.10

#9559 clean deploy_script and delete host before register to avoid can not register different org
  robottelo/virtwho_utils.py
  tests/foreman/virtwho/ui/test_esx.py
Labels: Easy Fix :)

#9574 [6.9.z] Update Ansible Collection assignee
  tests/foreman/sys/test_fam.py
Labels: 6.9

#9577 closed loop bz for 2041497 for 6.10.z
  tests/foreman/cli/test_contentview.py
  tests/foreman/ui/test_contentview.py
Labels: CLI, UI, 6.10

#9588 Rearrange uuid test case to correct class in file
  tests/foreman/api/test_contentmanagement.py
Labels: API, Easy Fix :), 6.11

#9556 Add sleep time after get virtwho status to get the complete mapping info in rhsm.log
  robottelo/virtwho_utils.py
Labels: Easy Fix :)

#9587 closed loop 2041497 for 6.11
  tests/foreman/cli/test_contentview.py
  tests/foreman/ui/test_contentview.py
Labels: CLI, UI, 6.11

#9593 [6.9.z] Update assignees to the component owners
  tests/foreman/sys/test_sat_clone.py
Labels: 6.9

#9592 [6.10.z] Update assignees to the component owners
  tests/foreman/maintain/test_backup_restore.py
  tests/foreman/sys/test_sat_clone.py
Labels: 6.10

#9571 katello-ca installation for rhel8,9 fips hosts
  robottelo/hosts.py
Labels: TestFailure, 6.11

#9594 [6.10] katello-ca installation for rhel8,9 fips hosts
  robottelo/hosts.py
Labels: TestFailure, 6.10

#9560 Fix puppet class teardown
  robottelo/api/utils.py
  robottelo/hosts.py
  tests/foreman/api/test_classparameters.py
  tests/foreman/cli/test_classparameters.py
  tests/upgrades/test_classparameter.py
Labels: 6.11

#9570 [6.9] install_katello_ca does not raise ContentHostError
  robottelo/hosts.py
Labels: 6.9

#9595 Update missing API endpoints for 6.10.z
  tests/foreman/endtoend/test_api_endtoend.py
Labels: API, 6.10, Easy Fix :)

#9598 Update missing API endpoints for BZ 2028377
  tests/foreman/endtoend/test_api_endtoend.py
Labels: TestFailure, Easy Fix :)

#9601 strip newline from stdout in rename tests
  tests/foreman/sys/test_rename.py
Labels: TestFailure, 6.11

#9602 [6.10] strip newline from stdout in rename tests
  tests/foreman/sys/test_rename.py
Labels: TestFailure, 6.10

#9564 Fix puppet cli
  robottelo/host_helpers/cli_factory.py
  tests/foreman/cli/test_classparameters.py
Labels: TestFailure, 6.11

#9476 Add/Remove installer options to fix the installer test
  tests/foreman/installer/test_installer.py
Labels: TestFailure, 6.11

#9608 Removed `skip tests for bug 1850934` and UI test teardown fix
  tests/foreman/api/test_computeresource_azurerm.py
  tests/foreman/cli/test_computeresource_azurerm.py
  tests/foreman/ui/test_computeresource_azurerm.py
Labels: Bug, TestFailure

#9551 Adding some branding tests
  tests/foreman/ui/test_branding.py
Labels: Documentation

#9609 [6.10.z] Adding some branding tests
  tests/foreman/ui/test_branding.py
Labels: 6.10

#9611 Fixed Anisble Collection Test
  tests/foreman/cli/test_repository.py
Labels: CLI, Easy Fix :)

#9613 Fixing srpm duplicate assertion for 6.10.z
  tests/foreman/api/test_repository.py
Labels: 6.10, Easy Fix :)

#9616 API Factory for satellites API based helpers
  robottelo/host_helpers/api_factory.py
  robottelo/host_helpers/satellite_mixins.py
Labels: API, enhancement, Framework Changes

#9610 marking rex infra tests for fips pipeline inclusion
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, 6.11

#9591 Settings test fix
  tests/foreman/api/test_settings.py
  tests/foreman/cli/test_settings.py
  tests/foreman/ui/test_settings.py
Labels: TestFailure

#9584 Fix e2e bulk update test failure
  tests/foreman/ui/test_contenthost.py
Labels: TestFailure

#9583 Fix puppet class import on a fake-capsule
  pytest_fixtures/core/sys.py
  tests/foreman/api/test_smartproxy.py
  tests/foreman/cli/test_capsule.py
Labels: TestFailure, 6.11

#9617 Remove deprecated entities from test_multiple_paths
  tests/foreman/api/test_multiple_paths.py
Labels: API, TestFailure, Easy Fix :)

#9604 updated packages for rhel8/9 fips install
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, TestFailure, 6.11

#9618 Fix api role tests
  tests/foreman/api/test_role.py
Labels: API, TestFailure

#9565 rh_cloud test fix for package version.
  tests/foreman/api/test_rhcloud_inventory.py
Labels: API, Tier 1 ACK, 6.11

#9580 Add test for deleting rhrepo
  tests/foreman/ui/test_repository.py
Labels: UI, 6.10

#9600 rh_cloud test coverage
  tests/foreman/api/test_rhcloud_inventory.py
Labels: API, QETestCoverage, 6.11

#9622 [cherrypick] [6.10z] backport new contenthost config
  conf/content_host.yaml.template
  pytest_fixtures/core/contenthosts.py
Labels: 6.10, Easy Fix :)

#9623 [cherrypick] [6.9z] backport new contenthost config
  conf/content_host.yaml.template
  pytest_fixtures/content_hosts.py
Labels: 6.9, Easy Fix :), CherryPick

#9630 [6.10 CherryPick] Removed skip test for bug 1850934 and UI test teardown fix
  tests/foreman/api/test_computeresource_azurerm.py
  tests/foreman/cli/test_computeresource_azurerm.py
  tests/foreman/ui/test_computeresource_azurerm.py
Labels: Bug, CherryPick

#9629 Speed up capsule-content tests
  pytest_fixtures/component/lce.py
  pytest_fixtures/core/broker.py
  tests/foreman/api/test_contentmanagement.py
Labels: enhancement, 6.11

#9637 remove the tests has entities no endpoints
  tests/foreman/ui/test_hostgroup.py
Labels: Easy Fix :), 6.11
