Repository SatelliteQE/robottelo, pull requests merged in 2022-11, with the labels that each got.

#10223 GHA: Added support to handle auto-cherry-pick failure & create issue …
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick

#10182 [6.10.z] [6.11.z] Automation coverage for BZ 1908478 and 1962842
  robottelo/cli/sm_maintenance_mode.py
  tests/foreman/maintain/test_backup_restore.py
Labels: 6.10.z, No-CherryPick, Auto_CherryPicked

#10213 Make sure erratum is reported
  tests/foreman/cli/test_host.py
Labels: 6.10.z, No-CherryPick

#10225 [6.10.z] GHA: Added support to handle auto-cherry-pick failure & create issue …
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick

#10220 [6.11.z] Test fix for e2e provisioning_template test
  tests/foreman/ui/test_provisioningtemplate.py
Labels: 6.11.z, No-CherryPick, Auto_CherryPicked

#10219 [6.11.z] Bump pytest-xdist from 2.5.0 to 3.0.2
  requirements.txt
Labels: Tier 1 ACK, 6.11.z, No-CherryPick, Auto_CherryPicked

#10233 Host content ownership
  tests/foreman/cli/test_contentaccess.py
  tests/foreman/destructive/test_contenthost.py
  tests/foreman/longrun/test_inc_updates.py
  tests/foreman/ui/test_contenthost.py
  tests/upgrades/test_client.py
  tests/upgrades/test_hostcontent.py
Labels: CherryPick

#10235 [6.11.z] Host content ownership
  tests/foreman/cli/test_contentaccess.py
  tests/foreman/destructive/test_contenthost.py
  tests/foreman/longrun/test_inc_updates.py
  tests/foreman/ui/test_contenthost.py
  tests/upgrades/test_client.py
  tests/upgrades/test_hostcontent.py
Labels: 6.11.z, CherryPick, Auto_Cherry_Picked

#9915 RHEV provisioning fix for new fixtures
  conf/rhev.yaml.template
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/cli/test_computeresource_rhev.py
Labels: No-CherryPick

#10166 Companion to Broker #170
  requirements.txt
  robottelo/hosts.py
Labels: Tier 1 ACK, CherryPick

#10239 Do not install dogfood certs as we use CDN
  tests/foreman/destructive/test_katello_certs_check.py
Labels: Tier 1 ACK, CherryPick

#10241 fixing auto assigning to correct user rather SATQE bot
  .github/auto_assign.yml
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/pull_request.yml
Labels: CherryPick

#10244 [6.11.z] Companion to Broker #170
  requirements.txt
  robottelo/hosts.py
Labels: Tier 1 ACK, 6.11.z, CherryPick, Auto_Cherry_Picked

#10255 [6.11.z] added missing customerscenario tag
  tests/foreman/api/test_contentmanagement.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10257 Fix collection of SatelliteContentManagement cases
  tests/foreman/api/test_contentmanagement.py
Labels: TestFailure, Easy Fix :), CherryPick

#10258 [6.11.z] Fix collection of SatelliteContentManagement cases
  tests/foreman/api/test_contentmanagement.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10248 [6.11.z] Do not install dogfood certs as we use CDN
  tests/foreman/destructive/test_katello_certs_check.py
Labels: Tier 1 ACK, 6.11.z, No-CherryPick

#10251 fix the broken create issue with adding needs
  .github/workflows/auto_assignment.yaml
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/pull_request.yml
Labels: No-CherryPick

#10249 assertion fix in capsule upgrade test
  tests/foreman/api/test_remoteexecution.py
Labels: API, Tier 1 ACK, CherryPick, 6.12.z

#9778 RHSSO Helper Refactor
  pytest_fixtures/component/satellite_auth.py
  robottelo/api/utils.py
  robottelo/hosts.py
  robottelo/rhsso_utils.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: in progress, CherryPick, Branching Blocker

#10263 [6.11.z] Bump manifester from 0.0.9 to 0.0.10
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10261 Convert partitiontable test to use target_sat
  tests/foreman/api/test_partitiontable.py
Labels: API, Easy Fix :), CherryPick

#10237 Parametrizing provisioning tests[BIOS/UEFI]
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_provisioning.py
Labels: CherryPick

#10274 Fix Create Issue failing for sequence not expected
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick

#10162 Convert manifest-dependent API tests to manifester
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_convert2rhel.py
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_organization.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_repository_set.py
  tests/foreman/api/test_subscription.py
  tests/foreman/api/test_syncplan.py
Labels: enhancement, CherryPick

#10266 Subscription must be divisible be 2 on containers
  tests/foreman/cli/test_host.py
Labels: TestFailure, CherryPick

#10280 Cherry-pick #10162 to 6.11.z
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_convert2rhel.py
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_organization.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_repository_set.py
  tests/foreman/api/test_subscription.py
  tests/foreman/api/test_syncplan.py
Labels: No-CherryPick

#10262 [6.11.z] Bump python-box from 6.0.2 to 6.1.0
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10265 [6.11.z] Convert partitiontable test to use target_sat
  tests/foreman/api/test_partitiontable.py
Labels: 6.11.z, CherryPick, Auto_Cherry_Picked

#10281 Add marker and select initial end-to-end tests
  pytest_plugins/markers.py
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/api/test_discoveryrule.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_subscription.py
  tests/foreman/api/test_template.py
  tests/foreman/api/test_webhook.py
  tests/foreman/cli/test_docker.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_hostcollection.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/cli/test_oscap.py
  tests/foreman/cli/test_reporttemplates.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_role.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_webhook.py
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: CherryPick

#10279 [6.11.z] Subscription must be divisible be 2 on containers
  tests/foreman/cli/test_host.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10282 [6.10.z] [6.11.z] Convert partitiontable test to use target_sat
  tests/foreman/api/test_partitiontable.py
Labels: 6.10.z, No-CherryPick, Auto_Cherry_Picked

#10259 [6.11.z] assertion fix in capsule upgrade test
  tests/foreman/api/test_remoteexecution.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10119 [POC] Upgrade Scenarios moving to use broker container hosts object and its methods
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/hosts.py
  tests/upgrades/test_repository.py
Labels: Framework Changes, CherryPick

#10250 Cherry pick 10241 and fixed the needs
  .github/auto_assign.yml
  .github/workflows/auto_assignment.yml
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, Failed_AutoCherryPick

#10234 Added test for leapp wf
  tests/foreman/destructive/test_leapp_satellite.py
Labels: 6.11.z, CherryPick

#10285 Cherry pick of satellite leapp upgrade tests from master
  tests/foreman/destructive/test_leapp_satellite.py
Labels: 6.11.z, No-CherryPick

#10187 Cleaning up Libvirt Discovery tests
  pytest_fixtures/component/subnet.py
  robottelo/cli/factory.py
  robottelo/host_helpers/cli_factory.py
  robottelo/libvirt_discovery.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/destructive/test_discoveredhost.py
  tests/foreman/ui/test_discoveredhost.py
Labels: CherryPick

#10290 Cherry-pick RHSSO Helper Refactor (#9778)
  pytest_fixtures/component/satellite_auth.py
  robottelo/api/utils.py
  robottelo/hosts.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: 6.11.z, No-CherryPick

#10272 Rhcloud plugin integration tests with capsule
  pytest_fixtures/component/rh_cloud.py
  tests/foreman/ui/test_rhcloud_insights.py
Labels: UI, QETestCoverage, CherryPick

#10296 Missing Cherrypicks for upgrade scenario and ACP GHA fixes
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/hosts.py
  tests/upgrades/test_repository.py
Labels: No-CherryPick, Failed_AutoCherryPick

#10301 Isolate Capsule KS test with another org
  tests/foreman/api/test_contentmanagement.py
Labels: TestFailure, Easy Fix :), CherryPick

#10304 [6.10.z cherrypick] Host content ownership
  tests/foreman/cli/test_contentaccess.py
  tests/foreman/longrun/test_inc_updates.py
  tests/foreman/ui/test_contenthost.py
  tests/upgrades/test_client.py
Labels: No-CherryPick

#10298 Don't use containers
  tests/foreman/ui/test_host.py
Labels: Easy Fix :), CherryPick

#10231 Port/refactor of f-m service tests from testfm
  pytest_fixtures/component/maintain.py
  robottelo/cli/base.py
  robottelo/cli/sm_service.py
  robottelo/constants/__init__.py
  tests/foreman/maintain/test_service.py
Labels: CherryPick, Branching Blocker

#10306 [6.11.z] Don't use containers
  tests/foreman/ui/test_host.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10003 Automate Bug 1834897 on virt-who plugin CLI/API/UI
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/ui/test_esx.py
Labels: Tier 1 ACK, No-CherryPick

#10016 Nutanix Prism Central CLI cases automation support for virt-who plugin
  tests/foreman/virtwho/cli/test_nutanix.py
Labels: Tier 1 ACK, No-CherryPick

#10017 Nutanix Prism Central API cases automation support for virt-who plugin
  tests/foreman/virtwho/api/test_nutanix.py
Labels: Tier 1 ACK, No-CherryPick

#10302 [6.11.z] Add f-m upgrade tests to robottelo with capsule parametrization
  pytest_fixtures/component/maintain.py
  pytest_fixtures/core/broker.py
  pytest_plugins/fixture_markers.py
  pytest_plugins/markers.py
  robottelo/cli/base.py
  robottelo/cli/sm_upgrade.py
  robottelo/hosts.py
  tests/foreman/maintain/test_upgrade.py
Labels: 6.11.z, No-CherryPick, Failed_AutoCherryPick

#10309 [6.11.z] Cherry pick manifester fixtures
  conf/manifest.yaml.example
  pytest_fixtures/component/taxonomy.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/ui/test_activationkey.py
Labels: No-CherryPick

#10313 Adding e2e markers
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_rhcloud_inventory.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_rhcloud_inventory.py
Labels: CLI, API, No-CherryPick

#10310 Automation coverage for BZ 2053843
  tests/foreman/cli/test_hammer.py
Labels: CLI, QETestCoverage, CherryPick

#10315 [6.11.z] Automation coverage for BZ 2053843
  tests/foreman/cli/test_hammer.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10236 Port/refactor of f-m packages tests from testfm
  robottelo/cli/base.py
  robottelo/cli/sm_packages.py
  tests/foreman/maintain/test_packages.py
Labels: CherryPick, Branching Blocker

#10312 [6.11.z] Port/refactor of f-m service tests from testfm
  robottelo/cli/sm_service.py
  robottelo/constants/__init__.py
  tests/foreman/maintain/test_service.py
Labels: 6.11.z, No-CherryPick

#10316 [6.11.z] Port/refactor of f-m packages tests from testfm
  robottelo/cli/sm_packages.py
  tests/foreman/maintain/test_packages.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10295 [6.11.z] Rhcloud plugin integration tests with capsule
  pytest_fixtures/component/rh_cloud.py
  tests/foreman/ui/test_rhcloud_insights.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10322 [6.11.z] Bump manifester from 0.0.10 to 0.0.11
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10308 [GHA]:Added support to copy the PRT comment in auto-cherry-pick pr's
  .github/workflows/auto_assignment.yaml
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick

#10325 fix the google chat using right branch master
  .github/workflows/auto_cherry_pick.yml
Labels: Easy Fix :), No-CherryPick

#10319 Warn and Close Stale Issues and PRs
  .github/workflows/stale.yml
Labels: No-CherryPick

#10305 [6.11.z] Isolate Capsule KS test with another org
  tests/foreman/api/test_contentmanagement.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10326 [cherrypick fix] [GHA]:Added support to copy the PRT comment in auto-cherry-pick pr's
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, Failed_AutoCherryPick

#10331 [6.11.z] Add SystemInfo class in satellite_mixins
  robottelo/host_helpers/__init__.py
Labels: 6.11.z, No-CherryPick

#10332 Org should not be an array
  tests/foreman/ui/test_computeresource.py
Labels: CherryPick

#10328 Remove rp_ignore_errors from pytest config
  pyproject.toml
Labels: CherryPick

#10333 [6.11.z] Org should not be an array
  tests/foreman/ui/test_computeresource.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10216 Test for disabling a repository when attached to a contentview
  tests/foreman/api/test_repositories.py
Labels: API, in progress, enhancement, CherryPick

#10336 [6.11.z] Test for disabling a repository when attached to a contentview
  tests/foreman/api/test_repositories.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10297 Implementing PXE-less Discovery test
  pytest_fixtures/component/provision_pxe.py
  pytest_fixtures/core/broker.py
  tests/foreman/api/test_discoveredhost.py
Labels: CherryPick

#10344 Add bz check
  tests/foreman/cli/test_host.py
Labels: Easy Fix :), No-CherryPick

#10345 Make sure postfix is running
  tests/foreman/ui/test_reporttemplates.py
Labels: No-CherryPick

#10335 Check for more columns plus fix assert failure due to caps
  tests/foreman/api/test_reporttemplates.py
Labels: No-CherryPick

#10346 Automation coverage for BZ 2077824
  tests/foreman/api/test_smartproxy.py
Labels: QETestCoverage, No-CherryPick

#10288 Port/refactor of f-m health tests from testfm
  robottelo/cli/sm_health.py
  tests/foreman/maintain/test_health.py
Labels: CherryPick

#10242 Port/refactor of f-m advanced tests from testfm
  Makefile
  pytest_fixtures/component/maintain.py
  robottelo/cli/sm_advanced.py
  robottelo/cli/sm_advanced_by_tag.py
  robottelo/hosts.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_backup_restore.py
  tests/foreman/maintain/test_service.py
  tests/foreman/maintain/test_upgrade.py
Labels: No-CherryPick, Branching Blocker

#10351 Skip manifest import when running test against stage console.redhat.com
  conf/rh_cloud.yaml.template
  tests/foreman/maintain/test_health.py
  tests/foreman/ui/test_rhc.py
Labels: CherryPick

#10354 Fixes #10352 - [cherry-pick] skip manifest import when running test against stage env
  conf/rh_cloud.yaml.template
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick

#10353 [6.11.z] Port/refactor of f-m advanced tests from testfm
  Makefile
  pytest_fixtures/component/maintain.py
  robottelo/cli/sm_advanced.py
  robottelo/cli/sm_advanced_by_tag.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_backup_restore.py
  tests/foreman/maintain/test_service.py
  tests/foreman/maintain/test_upgrade.py
Labels: 6.11.z, No-CherryPick

#10357 updating the bot user to satqe bot
  .github/workflows/auto_assignment.yaml
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick

#10359 cherry-pick for PR #10357
  .github/workflows/auto_assignment.yml
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick

#10360 Fix host creation issue for test_positive_create_with_inherited_params
  tests/foreman/ui/test_host.py
Labels: Easy Fix :), No-CherryPick, 6.12.z

#10363 [6.11.z] Bump cryptography from 38.0.3 to 38.0.4
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10151 Add test for repo sets in new host details ui
  tests/foreman/ui/test_host.py
Labels: No-CherryPick

#10364 Add e2e marker for rh_cloud and oscap tests
  tests/foreman/api/test_oscap_tailoringfiles.py
  tests/foreman/api/test_oscappolicy.py
  tests/foreman/api/test_product.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_rhc.py
  tests/foreman/ui/test_rhcloud_insights.py
Labels: No-CherryPick

#10365 Run fixture for adding selinux port policy on puppet sat
  tests/foreman/cli/test_host.py
Labels: Easy Fix :), CherryPick

#10367 [6.11.z] Run fixture for adding selinux port policy on puppet sat
  tests/foreman/cli/test_host.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10327 [cherry-pick 6.11] Ohsnap repositories
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/hosts.py
  robottelo/utils/ohsnap.py
  scripts/vault_login.py
Labels: 6.11.z, No-CherryPick, Failed_AutoCherryPick

#10246 Port/refactor of f-m maintenance-mode tests from testfm
  tests/foreman/maintain/test_backup_restore.py
  tests/foreman/maintain/test_maintenance_mode.py
Labels: No-CherryPick, Branching Blocker

#10337 Test for creating EPEL Repositories with different mirroring policies
  pytest_fixtures/component/repository.py
  tests/foreman/api/test_repositories.py
Labels: API, enhancement, CherryPick

#10370 Fix typo in Upgrades component name
  tests/foreman/destructive/test_leapp_satellite.py
Labels: CherryPick

#10371 [6.11.z] Fix typo in Upgrades component name
  tests/foreman/destructive/test_leapp_satellite.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10348 Parametrize backup/restore tests to run on capsule
  pytest_fixtures/component/maintain.py
  robottelo/hosts.py
  tests/foreman/maintain/test_backup_restore.py
Labels: CherryPick
