Repository SatelliteQE/robottelo, pull requests merged in 2022-06, with the labels that each got.

#9634 RP module moved to utils and docs are fixed
  pytest_plugins/rerun_rp/README.adoc
  pytest_plugins/rerun_rp/rerun_rp.py
  robottelo/report_portal/README.adoc
  robottelo/utils/report_portal/README.adoc
  robottelo/utils/report_portal/__init__.py
  robottelo/utils/report_portal/portal.py
Labels: Documentation, Framework Changes

#9642 Fix puppet-related api/cli hostgroup tests
  tests/foreman/api/test_hostgroup.py
  tests/foreman/cli/test_hostgroup.py
Labels: TestFailure, 6.11

#9633 Fix for broker teardown error
  robottelo/hosts.py
Labels: enhancement, CherryPick

#9643 fixing negative rename test
  tests/foreman/sys/test_rename.py
Labels: TestFailure, 6.11

#9652 wait with fips rhel9 client tesing
  conf/supportability.yaml
  tests/foreman/cli/test_remoteexecution.py
Labels: 6.11

#9650 [6.10] fixing negative rename test
  tests/foreman/sys/test_rename.py
Labels: TestFailure, 6.10

#9653 Fix puppetclass UI test
  tests/foreman/ui/test_puppetclass.py
Labels: UI, 6.11

#9655 Fixed mirror on sync tests
  tests/foreman/cli/test_repository.py
Labels: CLI, Easy Fix :)

#9659 moving to module_capsule_configured in rex tests
  tests/foreman/api/test_remoteexecution.py
  tests/foreman/cli/test_remoteexecution.py
Labels: 6.11

#9658 fixes in enroll idm fixture
  pytest_fixtures/component/satellite_auth.py
Labels: TestFailure, 6.11

#9665 Fix capsule_setup
  robottelo/hosts.py
Labels: 6.11

#9666 Fix date foremat
  tests/foreman/ui/test_syncplan.py
Labels: Easy Fix :)

#9671 Update pytest-ibutsu integration
  pytest_plugins/metadata_markers.py
  requirements.txt
Labels: dependencies

#9553 entities and cli removal from ui host module
  conftest.py
  pytest_fixtures/component/architecture.py
  pytest_fixtures/component/contentview.py
  pytest_fixtures/component/host.py
  pytest_fixtures/component/lce.py
  pytest_fixtures/component/os.py
  pytest_fixtures/component/partition_table.py
  pytest_fixtures/component/repository.py
  pytest_fixtures/component/smartproxy.py
  pytest_fixtures/component/taxonomy.py
  robottelo/constants/__init__.py
  robottelo/ui/utils.py
  tests/foreman/ui/test_host.py
Labels: UI, TestFailure, 6.11

#9664 Restructuring rh_cloud test cases based on cert auth
  pytest_fixtures/component/rh_cloud.py
  tests/foreman/api/test_rhcloud_inventory.py
  tests/foreman/cli/test_rhcloud_inventory.py
  tests/foreman/ui/test_rhcloud_insights.py
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: CLI, UI, API, 6.11

#9679 Add timezone info to date check
  tests/foreman/ui/test_host.py
Labels: TestFailure, Easy Fix :)

#9683 Fixing DiscoveryPlugin tests
  tests/foreman/cli/test_discoveryrule.py
  tests/foreman/ui/test_discoveredhost.py
  tests/foreman/ui/test_discoveryrule.py
Labels: TestFailure

#9694 using module_target sat with rename tests
  tests/foreman/sys/test_rename.py
Labels: TestFailure, 6.11

#9660 katello-ca installation from rhel7 sat to rhel8 fips client
  robottelo/hosts.py
Labels: CLI, TestFailure, 6.11

#9691 Fixed UI tests in test_subscription.py
  tests/foreman/ui/test_subscription.py
Labels: UI, 6.11

#9695 Remove unused module_proxy param
  tests/foreman/ui/test_host.py
Labels: TestFailure, Easy Fix :)

#9681 Install capsule using CDN repos for RHSCL and AE
  pytest_fixtures/core/broker.py
  robottelo/hosts.py
Labels: 6.11

#9701 Update module streams fixture to use satutils repo for 6.11+
  tests/foreman/ui/test_contenthost.py
Labels: TestFailure, Easy Fix :)

#9707 Remove newline from the timezone offset
  tests/foreman/ui/test_host.py
Labels: TestFailure, Easy Fix :)

#9706 [6.10] fix rpm check for katello-ca-consumer
  robottelo/hosts.py
Labels: Tier 1 ACK, 6.10

#9625 Create upgrade test for db seed mismatch failure
  tests/upgrades/test_hostcontent.py
Labels: Upgrades

#9678 Rewrite Host subscription tests without helper class
  pytest_fixtures/component/repository.py
  pytest_fixtures/component/subscription.py
  pytest_fixtures/component/taxonomy.py
  tests/foreman/api/test_convert2rhel.py
  tests/foreman/cli/test_host.py
  tests/foreman/ui/test_host.py
Labels: TestFailure

#9696 Fix cli hosts erratum tests
  robottelo/constants/__init__.py
  tests/foreman/cli/test_host.py
Labels: TestFailure

#8252 disable repo sync after test completion
  robottelo/api/utils.py
  tests/foreman/api/test_syncplan.py
  tests/foreman/cli/test_syncplan.py
  tests/foreman/ui/test_syncplan.py
Labels: enhancement

#9726 Remove BZ check
  tests/foreman/cli/test_host.py
Labels: Easy Fix :), 6.11

#9731 Fixing hostname execute order on 6.10
  robottelo/cli/base.py
Labels: 6.10

#9716 Fixed docker tags whitelist tests and updated helper function
  robottelo/cli/factory.py
  tests/foreman/cli/test_repository.py
Labels: CLI, 6.11

#9740 Skip OS create/update tests if BZ open
  tests/foreman/api/test_operatingsystem.py
Labels: Bug, Easy Fix :), 6.11

#9590 automation for closed loop bz 2044631 for 6.11
  robottelo/constants/__init__.py
  tests/foreman/ui/test_contentview.py
Labels: UI, 6.11

#9747 [6.10] adding name parameter to register_contenthost
  robottelo/hosts.py
Labels: CLI, TestFailure, 6.10

#9680 Remove puppet and randomness from the test_positive_end_to_end
  robottelo/constants/__init__.py
  tests/foreman/ui/test_bookmarks.py
Labels: TestFailure, QETestCoverage

#9497 Robottelo/product.py Helpers refactor
  pytest_fixtures/component/repository.py
  robottelo/constants/__init__.py
  robottelo/errors.py
  robottelo/host_helpers/cli_factory.py
  robottelo/host_helpers/repository_mixins.py
  tests/foreman/api/test_errata.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_discoveredhost.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_hostcollection.py
  tests/foreman/ui/test_organization.py
  tests/foreman/ui/test_package.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_subscription.py
  tests/foreman/ui/test_sync.py
Labels: enhancement, High Complexity, Framework Changes

#9751 Fix installer tests for 6.10.z
  tests/foreman/installer/test_installer.py
Labels: TestFailure, 6.10

#9700 [6.10] fix in rex alternate dir test
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, 6.10

#9729 [6.10.z] Fix katello-agent tests to use tools repo and register to cdn
  conf/supportability.yaml
  robottelo/hosts.py
  tests/foreman/cli/test_katello_agent.py
Labels: TestFailure, 6.10

#9753 [Cherrypick] Add bugzilla key to pull request and merge actions
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_request.yml
Labels: 6.9
