Repository SatelliteQE/robottelo, pull requests merged in 2022-02, with the labels that each got.

#9337 Add test for importing templates with puppet
  pytest_fixtures/component/puppet.py
  tests/foreman/api/test_templatesync.py
Labels: API, 7.0

#9340 [cherry-pick] add token for github api calls
  conf/git.yaml.template
  tests/foreman/api/test_templatesync.py
Labels: 6.10, Easy Fix :)

#9342 Fix cli classparameters tests
  robottelo/hosts.py
  tests/foreman/cli/test_classparameters.py
Labels: CLI, 7.0

#9327 expand content_host.yml to support custom deploy workflows per nick
  conf/capsule.yaml.template
  conf/content_host.yaml.template
  conf/repos.yaml.template
  pytest_fixtures/core/contenthosts.py
  pytest_plugins/fixture_markers.py
Labels: RFE, High Priority, in progress, blocked

#9336 [backport] 6.10.z rhel versions
  conf/capsule.yaml.template
  conf/content_host.yaml.template
  conf/repos.yaml.template
  pytest_fixtures/core/contenthosts.py
  pytest_plugins/fixture_markers.py
Labels: blocked

#9334 add rhel_contenthost-specific marks to filter os version parametrization
  pytest_plugins/fixture_markers.py
  pytest_plugins/markers.py
Labels: enhancement

#9339 Check popover status of host for RH cloud related fields.
  tests/foreman/api/test_rhcloud_inventory.py
  tests/foreman/ui/test_rhcloud_insights.py
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: 7.0

#9347 Removing a puppet test case that was failing in 6.10
  tests/foreman/ui/test_contentview.py
Labels: 6.10, Easy Fix :), 7.0

#9293 Add test coverage for BZ#1876220
  pytest_fixtures/core/sys.py
  tests/foreman/ui/test_host.py
Labels: 6.10

#9353 Isolate rhel support, params, and deploy
  .gitignore
  conf/content_host.yaml.template
  conf/supportability.yaml
  pytest_fixtures/core/contenthosts.py
  pytest_plugins/fixture_markers.py
  robottelo/config/validators.py
Labels: Urgent Priority, enhancement, Dynaconf

#9360 Update reqs for nailgun/airgun/upgrade for 6.10.z
  requirements.txt
Labels: dependencies, 6.10

#9354 Add test to check that OS was created after KS sync
  robottelo/constants/__init__.py
  tests/foreman/api/test_contentmanagement.py
Labels: API, 7.0

#9352 rex against satellite permissions test
  robottelo/cli/factory.py
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, 7.0

#9362 Refactor tracer test to use rhel_contenthost fixture
  conf/repos.yaml.template
  pytest_fixtures/core/contenthosts.py
  robottelo/hosts.py
  tests/foreman/api/test_host.py
  tests/foreman/cli/test_host.py
Labels: High Priority, API

#9343 Update Global Reg form for Sat7
  tests/foreman/ui/test_host.py
Labels: TestFailure

#9370 Removing legacy resolver and updating wrapanapi
  .github/workflows/pull_request.yml
  requirements.txt
Labels: dependencies

#9389 [cherry-pick] Removing legacy resolver and updating wrapanapi
  requirements.txt
Labels: dependencies, 6.10, Easy Fix :)

#9394 Replace 'package' with 'rpm'
  tests/foreman/api/test_contentmanagement.py
Labels: Easy Fix :), 7.0

#9395 Pull requirements from master
  requirements.txt
Labels: dependencies

#9368 package_install doesn't work by default anymore, using a direct execu…
  tests/foreman/cli/test_reporttemplates.py
Labels: CLI, 6.10

#9397 Add Broker's logs into robottelo.log
  robottelo/logging.py
Labels: enhancement
