Repository SatelliteQE/robottelo, pull requests merged in 2022-08, with the labels that each got.

#9851 Update the Sat version fallback to 6.12
  robottelo/constants/__init__.py
Labels: No-CherryPick, 6.12

#9852 [6.11.z] Update nailgun and airgun requirements to point to 6.11.z branches
  requirements.txt
Labels: 6.11, No-CherryPick

#9854 `test_rhel_pxe_provisioning` requires the fixture to provide OS
  .gitignore
  pytest_fixtures/component/provision_pxe.py
Labels: TestFailure, Easy Fix :), 6.11, No-CherryPick

#9836 SSH provider renamed to Script
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/destructive/test_remoteexecution.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_jobinvocation.py
  tests/foreman/ui/test_jobtemplate.py
  tests/foreman/ui/test_remoteexecution.py
Labels: No-CherryPick, 6.12

#9858 Constants cleanup
  pytest_fixtures/component/os.py
  pytest_fixtures/component/puppet.py
  pytest_fixtures/component/repository.py
  pytest_fixtures/component/taxonomy.py
  pytest_plugins/manual_skipped.py
  robottelo/api/utils.py
  robottelo/cli/factory.py
  robottelo/constants/__init__.py
  robottelo/constants/repos.py
  robottelo/host_helpers/cli_factory.py
  robottelo/host_helpers/repository_mixins.py
  robottelo/hosts.py
  robottelo/manifests.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_activationkey.py
  tests/foreman/cli/test_computeresource_rhev.py
  tests/foreman/cli/test_contentaccess.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_rhcloud_insights.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/destructive/test_contenthost.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_hostcollection.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_rhcloud_insights.py
  tests/foreman/ui/test_subscription.py
  tests/foreman/ui/test_sync.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_subscription.py
  tests/upgrades/test_yum_plugins.py
Labels: No-CherryPick

#9863 Fix issue with creating cli object
  robottelo/cli/factory.py
Labels: TestFailure, Easy Fix :), 6.11, CherryPick, 6.12

#9865 Replace Pyup-bot with dependabot
  .github/dependabot.yml
  .pyup.yml
Labels: dependencies, CherryPick

#9870 Constant cleanup
  tests/upgrades/test_yum_plugins.py
Labels: Easy Fix :), No-CherryPick

#9849 Replace instances of dogfood registration with repofile downloads
  pytest_fixtures/core/sys.py
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/hosts.py
  tests/foreman/destructive/test_infoblox.py
  tests/foreman/destructive/test_katello_certs_check.py
  tests/foreman/destructive/test_puppetplugin.py
Labels: No-CherryPick, 6.12

#9862 Fix tasks pagination issue
  tests/foreman/ui/test_dashboard.py
Labels: UI, No-CherryPick, 6.12

#9893 Remove unused codecov config files
  .codecov.yml
  .coveragerc
Labels: CherryPick

#9898 Update PERMISSIONS constant
  robottelo/constants/__init__.py
Labels: No-CherryPick, 6.12

#9899 [6.11]Update PERMISSIONS constant
  robottelo/constants/__init__.py
Labels: 6.11, No-CherryPick

#9864 Fixed file downloading by avoiding SFTP
  pytest_fixtures/component/maintain.py
  pytest_fixtures/component/rh_cloud.py
  robottelo/hosts.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: Bug, Urgent Priority, TestFailure, 6.11, CherryPick, 6.12

#9907 Updated Assignee name for branding component
  tests/foreman/ui/test_branding.py
Labels: Easy Fix :), CherryPick

#9798 automation coverage for bz-2066899 and 2076684
  testimony.yaml
  tests/foreman/ui/test_subscription.py
Labels: UI, QETestCoverage, CherryPick

#9896 Add check subscription startdate displayed
  tests/foreman/ui/test_contenthost.py
Labels: No-CherryPick

#9906 [Best for PRT] Select tests based on fixtures they are using
  conftest.py
  pytest_plugins/fixture_collection.py
Labels: enhancement, Framework Changes, CherryPick

#9850 Automation for bz-2040870
  tests/foreman/cli/test_satellitesync.py
Labels: CLI, QETestCoverage, CherryPick

#9900 fixed the auth tests for RHSSO
  pytest_fixtures/component/satellite_auth.py
  robottelo/api/utils.py
  robottelo/rhsso_utils.py
  tests/foreman/destructive/test_katello_certs_check.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
Labels: No-CherryPick, 6.12

#9686 Stubbing the host Ansible tests
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_jobinvocation.py
Labels: CherryPick

#9927 Automation for bz-1832858
  tests/foreman/cli/test_satellitesync.py
Labels: CLI, QETestCoverage, CherryPick

#9933 fixed the auth tests for RHSSO
  pytest_fixtures/component/satellite_auth.py
  robottelo/api/utils.py
  robottelo/rhsso_utils.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
Labels: 6.11, No-CherryPick

#9780 Add setup for iqe remediation tests.
  conf/rh_cloud.yaml.template
  conftest.py
  tests/foreman/ui/test_remoteexecution.py
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick

#9910 Automation for bz-2024889
  robottelo/constants/repos.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
  tests/foreman/ui/test_repository.py
Labels: CLI, UI, API, QETestCoverage, CherryPick

#9940 Remove RHEL9 from supportability matrix
  conf/supportability.yaml
Labels: CherryPick

#9944 Adding missing customerscenario docstring to test case
  tests/foreman/cli/test_satellitesync.py
Labels: Easy Fix :), CherryPick

#9892 Test for checking null contents_changed after repo sync
  tests/foreman/api/test_repository.py
Labels: API, CherryPick

#9950 Smoothing Teardown in Azure Host provisioning
  tests/foreman/cli/test_computeresource_azurerm.py
Labels: CherryPick

#9949 Remove Inflector dependency
  requirements.txt
  robottelo/api/utils.py
  tests/foreman/api/test_environment.py
  tests/foreman/api/test_smartproxy.py
  tests/robottelo/test_api_utils.py
Labels: Framework Changes, CherryPick

#9953 RHEL9 template is available again
  conf/supportability.yaml
Labels: CherryPick

#9959 Use subscription-manager refresh
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick

#9962 Fixing inheriting labels and cherrypicking commit history using my fork
  .github/workflows/auto_cherry_pick.yml
Labels: enhancement, Framework Changes, CherryPick

#9968 Automation for bz-1848111
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: CLI, QETestCoverage, CherryPick

#9969 Add docstring coverage for bz-1944733
  tests/foreman/cli/test_satellitesync.py
Labels: CLI, Easy Fix :), CherryPick

#9976 rhel9_fips returning
  conf/supportability.yaml
Labels: CherryPick, 6.12

#9977 Docstring for automation coverage for bz-1995827
  tests/foreman/cli/test_satellitesync.py
Labels: CLI, Easy Fix :), CherryPick

#9714 Fixes for test failures
  tests/foreman/api/test_location.py
  tests/foreman/ui/test_settings.py
Labels: CherryPick

#9981 Improvising tests & also aims feature automation
  tests/foreman/ui/test_branding.py
  tests/foreman/ui/test_settings.py
Labels: UI, No-CherryPick, 6.12

#9920 rex pull-provider tests
  pytest_fixtures/core/broker.py
  robottelo/hosts.py
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, 6.12

#9987 Move Http Proxy api tests from test_repository.py to test_http_proxy.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_repository.py
Labels: No-CherryPick

#9984 Update hypervisor attach to Automatic mode for virtwho plugin cases
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_hyperv.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_libvirt.py
  tests/foreman/virtwho/api/test_nutanix.py
Labels: No-CherryPick

#9978 Automation coverage for bz-1920511
  robottelo/constants/repos.py
  tests/foreman/cli/test_repository.py
  tests/foreman/ui/test_repository.py
Labels: CLI, UI, QETestCoverage, CherryPick

#9988 Fix content tests with content upload
  tests/foreman/api/test_contentmanagement.py
Labels: Easy Fix :), CherryPick

#9822 Automate tests for new UI content tab
  tests/foreman/ui/test_host.py
Labels: UI, No-CherryPick, 6.12

#9995 Update LOCALES Constant
  robottelo/constants/__init__.py
Labels: TestFailure, No-CherryPick, 6.12

#9994 rex cli slight refactor
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, No-CherryPick, 6.12

#9998 Update hypervisor attach to Automatic mode for virtwho plugin cases
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_hyperv.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_libvirt.py
  tests/foreman/virtwho/api/test_nutanix.py
Labels: No-CherryPick

#9997 Skip Ansible Collection sync to Caps test
  tests/foreman/api/test_contentmanagement.py
Labels: Bug, Easy Fix :), No-CherryPick, 6.12

#9992 Automate Bug1870816 and Bug1959136 for virt-who plugin CLI
  robottelo/virtwho_utils.py
  tests/foreman/virtwho/cli/test_esx.py
Labels: No-CherryPick
