Repository SatelliteQE/robottelo, pull requests merged in 2022-04, with the labels that each got.

#9426 Mirroring policy for 7.0
  tests/foreman/api/test_contentmanagement.py
Labels: TestFailure, Easy Fix :), 7.0

#9473 bump black version in pre-commit
  .pre-commit-config.yaml
Labels: 6.9

#9484 removing unwanted skip from cli rex
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, 6.11

#9480 Add check update packages
  tests/foreman/ui/test_host.py
Labels: UI, 6.11

#9485 Update expected API endpoints for 6.11
  tests/foreman/endtoend/test_api_endtoend.py
Labels: API, 6.11

#9486 fix search for infrastructure hosts
  tests/foreman/cli/test_host.py
Labels: 6.11

#9481 Update hammer-cli options for 6.11
  robottelo/cli/hammer.py
  scripts/hammer_command_tree.py
  tests/foreman/cli/test_hammer.py
  tests/foreman/data/hammer_commands.json
Labels: CLI, Tier 2 ACK, 6.11

#9446 Fix azure test cases with puppet_enabled sat[API & CLI]
  pytest_fixtures/component/architecture.py
  pytest_fixtures/component/provision_azure.py
  pytest_fixtures/component/puppet.py
  tests/foreman/api/test_computeresource_azurerm.py
  tests/foreman/cli/test_computeresource_azurerm.py
Labels: API, 7.0

#9477 [6.9] reverting rex refactoring cherry-pick
  conf/supportability.yaml
  tests/foreman/cli/test_remoteexecution.py
Labels: 6.9

#9479 Fixing UI test_errata
  tests/foreman/ui/test_errata.py
Labels: UI, TestFailure, QETestCoverage

#9500 hotfix, installer colors breaking CI pipeline
  robottelo/hosts.py
Labels: High Priority, Easy Fix :)

#9493 changing scope for rex infra user fixtures
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, 6.11

#9453 automation for bz:1747177 for 6.11
  tests/foreman/api/test_contentmanagement.py
Labels: QETestCoverage, 7.0

#9319 disabled and enabled puppet tests fixes in 7.0
  pytest_fixtures/component/puppet.py
  pytest_plugins/markers.py
  robottelo/host_helpers/__init__.py
  robottelo/host_helpers/capsule_mixins.py
  robottelo/host_helpers/cli_factory.py
  robottelo/hosts.py
  tests/foreman/cli/test_host.py
Labels: CLI, 7.0

#9508 Downgrade dynaconf
  requirements.txt
Labels: Bug, Urgent Priority

#9502 Test fixes for CR-GCE
  pytest_fixtures/component/provision_gce.py
  tests/foreman/api/test_computeresource_gce.py
Labels: API

#9495 rex dashboard check
  tests/foreman/ui/test_remoteexecution.py
Labels: UI, 6.11

#9004 Positive test scenarios for Organization
  tests/foreman/ui/test_organization.py
Labels: QETestCoverage

#9511 Separate broker logs into corresponding xdist worker logs
  pytest_plugins/logging_hooks.py
Labels: Urgent Priority

#9514 proper fixture rename in rex cli
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, 6.11

#9516 Solved an issue with Satellite objects modifying classes
  robottelo/hosts.py
Labels: Bug, Urgent Priority, 6.9, 6.10, 6.11

#9509 Add tests for puppet availability on upgraded setup
  robottelo/cli/report.py
  tests/foreman/cli/test_report.py
  tests/upgrades/test_puppet.py
Labels: Upgrades, 6.11

#9515 Test fix for container management-content
  tests/foreman/api/test_repository.py
Labels: API

#9522 [6.10.z] add optional 'strict' flag for failing on 409 for reposet enable
  robottelo/api/utils.py
Labels: RFE, 6.10

#9526 Update virt-who cases to default_org
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_hyperv.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_libvirt.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_hyperv.py
  tests/foreman/virtwho/cli/test_kubevirt.py
  tests/foreman/virtwho/cli/test_libvirt.py
  tests/foreman/virtwho/conftest.py
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_hyperv.py
  tests/foreman/virtwho/ui/test_kubevirt.py
  tests/foreman/virtwho/ui/test_libvirt.py
Labels: 6.10

#9524 Fix list comprehension of org help command
  tests/foreman/cli/test_organization.py
Labels: CLI, TestFailure, 6.10
