Repository SatelliteQE/robottelo, pull requests merged in 2022-07, with the labels that each got.

#9715 Add a test for puppet-agent install/config/run
  robottelo/hosts.py
  tests/foreman/cli/test_puppetplugin.py
Labels: 6.11

#9760 Update assignee for provisioning tests
  tests/foreman/api/test_template.py
  tests/foreman/api/test_template_combination.py
  tests/foreman/cli/test_provisioning.py
  tests/foreman/cli/test_template.py
  tests/foreman/ui/test_provisioningtemplate.py
Labels: Tier 1 ACK

#9770 Make CR tests run even without VLAN_NETWORKING specified where possible
  conf/rhev.yaml.template
  conf/vmware.yaml.template
  tests/foreman/cli/test_computeresource_rhev.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/ui/test_computeresource.py
  tests/foreman/ui/test_computeresource_libvirt.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: Easy Fix :)

#9771 add Katello::Repository to search string
  tests/foreman/api/test_syncplan.py
  tests/foreman/cli/test_syncplan.py
  tests/foreman/ui/test_syncplan.py
Labels: TestFailure

#9756 [backport] Install capsule using CDN repos
  pytest_fixtures/core/broker.py
  robottelo/constants/__init__.py
  robottelo/hosts.py
Labels: 6.10

#9776 fixing the ldap tests
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/cli/test_ldapauthsource.py
Labels: TestFailure

#9765 Test for Verifying Checksum
  tests/foreman/ui/test_repository.py
Labels: UI, in progress

#9783 Fix typo in pytest mark
  tests/foreman/cli/test_host.py
Labels: Easy Fix :)

#9788 missed the fixture statement causing failure
  pytest_fixtures/component/satellite_auth.py
Labels: TestFailure, Easy Fix :)

#9794 fixing typo in destructive realm test
  tests/foreman/destructive/test_realm.py
Labels: TestFailure, 6.11

#9752 Adding Webhooks API tests
  tests/foreman/api/test_webhook.py
Labels: API, QETestCoverage, No-CherryPick

#9762 [GHA] Enforcing CherryPick labels on PR
  .github/workflows/required_labels.yml
Labels: Framework Changes, CherryPick

#9757 [GHA] Auto CherryPick Pull Requests using branch-matrices
  .github/workflows/auto_cherry_pick.yml
Labels: enhancement, High Complexity, Framework Changes, CherryPick

#9801 Fix autoCherryPick conditional for matrix
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick

#9803 Moving from push event to pull request event for AC GHA
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick

#9804 [6.10.z] Missing CherryPicks due to AutoCherryPick Issue
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/required_labels.yml
  tests/foreman/ui/test_contentview.py
Labels: CherryPick

#9805 Move test_backup_restore to maintain dir
  tests/foreman/maintain/test_backup_restore.py
Labels: Easy Fix :), No-CherryPick

#9106 Add test for negative api ping
  tests/foreman/api/test_ping.py
  tests/foreman/cli/test_ping.py
  tests/foreman/destructive/test_ping.py
  tests/foreman/endtoend/test_api_endtoend.py
Labels: API, Easy Fix :), No-CherryPick

#9807 Fixing the lce creation that requires "prior" as a param and adding more skip markers
  robottelo/host_helpers/cli_factory.py
  tests/foreman/ui/test_contentview.py
Labels: Easy Fix :), No-CherryPick

#9768 Remove cleanup.py
  pytest_fixtures/component/smartproxy.py
  robottelo/cleanup.py
  tests/foreman/api/test_location.py
  tests/foreman/api/test_smartproxy.py
  tests/foreman/cli/test_capsule.py
  tests/foreman/cli/test_hostgroup.py
  tests/foreman/cli/test_organization.py
  tests/foreman/destructive/test_realm.py
  tests/foreman/ui/test_settings.py
Labels: CherryPick, Branching Blocker

#9806 Change bootstrap and registration tests to sbible
  tests/foreman/cli/test_bootstrap_script.py
  tests/foreman/cli/test_registration.py
Labels: CherryPick

#9810 adding PR write Permissions to GHA APick job
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick

#9736 Update bootstrap test support rhel8
  tests/foreman/cli/test_bootstrap_script.py
Labels: 6.10, Easy Fix :), CherryPick

#9813 Fixing permission issue with pull_request_target event
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick

#9779 Adding UI Webhook tests
  tests/foreman/ui/test_webhook.py
Labels: UI, QETestCoverage, No-CherryPick

#9814 Removing job level permissions to use global
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick

#9816 CherryPick all missing fixes of ACP GHA
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick

#9791 Automation for bz-2032098
  tests/foreman/ui/test_contentview.py
Labels: UI, QETestCoverage, No-CherryPick

#9709 Fix katello-agent tests to use client repo and register to cdn
  pytest_fixtures/component/subscription.py
  pytest_fixtures/core/contenthosts.py
  pytest_plugins/markers.py
  robottelo/host_helpers/capsule_mixins.py
  robottelo/hosts.py
  tests/foreman/destructive/test_katello_agent.py
  tests/foreman/destructive/test_ldap_authentication.py
Labels: TestFailure, No-CherryPick, Branching Blocker

#9823 Change ownership of syncplans to sbible
  tests/foreman/api/test_syncplan.py
  tests/foreman/cli/test_syncplan.py
  tests/foreman/ui/test_syncplan.py
  tests/upgrades/test_syncplan.py
Labels: CherryPick

#9821 Fixed fixture scope
  tests/foreman/ui/test_organization.py
Labels: TestFailure, CherryPick

#9789 location selection for UI job invocation test
  tests/foreman/ui/test_jobinvocation.py
Labels: TestFailure, No-CherryPick

#9820 Remove closed skip Bug 1735540 - Virt-who-config for kubevirt does not support in API and hammer CLI
  tests/foreman/virtwho/cli/test_kubevirt.py
Labels: No-CherryPick

#9651 General improvements to Vault Login script
  robottelo/constants/__init__.py
  robottelo/utils/__init__.py
  scripts/vault_login.py
Labels: Easy Fix :), Framework Changes, CherryPick

#9749 Add ansible roles and vars tests
  tests/foreman/ui/test_ansible.py
Labels: QETestCoverage, 6.11, No-CherryPick

#9785 Change foreman service teardown
  pytest_fixtures/core/sys.py
Labels: No-CherryPick

#9832 Abandon DF registration for puppet_enabled_sat
  pytest_fixtures/component/puppet.py
Labels: TestFailure, Easy Fix :), No-CherryPick

#9792 Expand Search tests to more components.
  tests/foreman/ui/test_bookmarks.py
Labels: No-CherryPick

#9831 remove hypervisorId from hypervisor json file
  robottelo/virtwho_utils.py
Labels: No-CherryPick

#9834 Round correctly, i.e. to 2 significant digits
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick

#9835 Add test name to be part of screenshot name
  robottelo/hosts.py
Labels: Easy Fix :), No-CherryPick, Branching Blocker

#9246 PXE Provisioning fixtures and test using new infra
  conf/provisioning.yaml.template
  conftest.py
  pytest_fixtures/component/provision_pxe.py
  pytest_fixtures/core/broker.py
  pytest_fixtures/core/xdist.py
  pytest_plugins/fixture_markers.py
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/api/test_provisioning.py
Labels: enhancement, QETestCoverage, 6.11, No-CherryPick, Branching Blocker

#9800 fixes in satellite-change-hostname tests
  tests/foreman/destructive/test_rename.py
Labels: TestFailure, 6.11, No-CherryPick

#9837 Adding and testing new roles
  robottelo/constants/__init__.py
Labels: QETestCoverage, No-CherryPick

#9817 Fix 6.11 InterSatelliteSync tests
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick

#9833 Adjust facts tests to support ignored facts
  tests/foreman/cli/test_fact.py
Labels: QETestCoverage, No-CherryPick

#9793 fixed rex dashboard check
  tests/foreman/ui/test_remoteexecution.py
Labels: TestFailure, 6.11, No-CherryPick

#9767 Add script to start selenium grid for parallel testing locally.
  docs/index.rst
  selenium_grid.sh
Labels: CherryPick

#9840 Remove deprecated tomcat6 service from installer tests
  tests/foreman/installer/test_installer.py
Labels: Easy Fix :), No-CherryPick

#9841 Fix capsule related tests
  tests/foreman/api/test_smartproxy.py
  tests/foreman/cli/test_capsule.py
Labels: TestFailure, No-CherryPick, Branching Blocker

#9843 Fix and take over puppet-related report tests
  tests/foreman/cli/test_report.py
Labels: CLI, TestFailure, No-CherryPick

#9844 Automation for bz-2030101
  robottelo/cli/factory.py
  tests/foreman/cli/test_satellitesync.py
Labels: CLI, QETestCoverage, No-CherryPick

#9847 Replace puppet input with variable
  tests/foreman/ui/test_partitiontable.py
Labels: TestFailure, Tier 1 ACK, Easy Fix :), 6.11, No-CherryPick

#9846 [UI] - Minor test fixes
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/ui/test_rhcloud_insights.py
Labels: Easy Fix :), No-CherryPick

#9845 Removed deprecated permission from test cases
  tests/foreman/cli/test_contentview.py
Labels: CLI, TestFailure, Tier 1 ACK, Easy Fix :), 6.11, No-CherryPick

#9848 Fix capsule KS sync test
  tests/foreman/api/test_contentmanagement.py
Labels: TestFailure, Easy Fix :), No-CherryPick

#9839 Automation for bz-2038388
  tests/foreman/cli/test_activationkey.py
  tests/foreman/ui/test_activationkey.py
Labels: CLI, UI, QETestCoverage, No-CherryPick

#9782 [Part-1] Helpers refactor of helpers.py helpers :)
  pytest_fixtures/component/maintain.py
  pytest_fixtures/component/oscap.py
  pytest_fixtures/component/rh_cloud.py
  robottelo/cli/factory.py
  robottelo/cli/report_template.py
  robottelo/constants/__init__.py
  robottelo/errors.py
  robottelo/helpers.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
  robottelo/utils/__init__.py
  tests/foreman/api/test_contentcredentials.py
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/api/test_contentviewversion.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_user.py
  tests/foreman/cli/test_contentcredentials.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_hammer.py
  tests/foreman/cli/test_logging.py
  tests/foreman/cli/test_oscap_tailoringfiles.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_user.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_contentcredentials.py
  tests/foreman/ui/test_ldap_authentication.py
  tests/foreman/ui/test_oscapcontent.py
  tests/foreman/ui/test_package.py
  tests/foreman/ui/test_partitiontable.py
  tests/foreman/ui/test_product.py
  tests/foreman/ui/test_provisioningtemplate.py
  tests/foreman/ui/test_repository.py
  tests/robottelo/test_helpers.py
  tests/upgrades/test_contentview.py
Labels: No-CherryPick
