Repository SatelliteQE/robottelo, pull requests merged in 2023-11, with the labels that each got.

#13023 [6.14.z] Bump dynaconf[vault] from 3.2.3 to 3.2.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13024 [6.13.z] Bump dynaconf[vault] from 3.2.3 to 3.2.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13022 [6.12.z] Bump dynaconf[vault] from 3.2.3 to 3.2.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12522 [6.13.z] Convert2Rhel test fixes
  tests/foreman/api/test_convert2rhel.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12524 [6.12.z] Convert2Rhel test fixes
  tests/foreman/api/test_convert2rhel.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13025 remove accidentally cherry-picked file
  tests/foreman/api/test_notifications.py
Labels: TestFailure, No-CherryPick, 6.13.z

#13028 [6.14.z] ISS refactor - batch 4
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13030 [6.13.z] ISS refactor - batch 4
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13029 [6.12.z] ISS refactor - batch 4
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13026 added custom-cdn-auth-enabled hammer option
  tests/foreman/data/hammer_commands.json
Labels: CLI, Easy Fix :), No-CherryPick, 6.13.z

#13016 Check if VAULT_ADDR env var exists before deleting it
  robottelo/utils/vault.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#12521 PRT comment adding using curl more standard way
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#13020 [6.12.z] ISS refactor - batch 3
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13031 [6.12.z] Check if VAULT_ADDR env var exists before deleting it
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13033 [6.13.z] Check if VAULT_ADDR env var exists before deleting it
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13032 [6.14.z] Check if VAULT_ADDR env var exists before deleting it
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12958 Adding the image config details in the docker config
  conf/docker.yaml.template
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#13044 update markdown file name
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Easy Fix :), Framework Changes, No-CherryPick

#13042 [6.13.z] Adding the image config details in the docker config
  conf/docker.yaml.template
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13041 [6.14.z] Adding the image config details in the docker config
  conf/docker.yaml.template
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13040 [6.12.z] Adding the image config details in the docker config
  conf/docker.yaml.template
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12926 [6.13.z] Fixing Discovery tests
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
Labels: No-CherryPick, 6.13.z

#13046 Add monitoring install params and sections
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Stream

#12959 Fix convert2rhel tests by CVV sort and other fixes
  tests/foreman/api/test_convert2rhel.py
Labels: TestFailure, Easy Fix :), No-CherryPick, Stream

#12989 removing the from nailgun import entities and moving target_sat, module_target_sat
  tests/foreman/api/test_activationkey.py
  tests/foreman/api/test_architecture.py
  tests/foreman/api/test_audit.py
  tests/foreman/api/test_bookmarks.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_computeprofile.py
  tests/foreman/api/test_contentcredentials.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_contentviewversion.py
  tests/foreman/api/test_discoveryrule.py
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_filter.py
  tests/foreman/api/test_foremantask.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_hostcollection.py
  tests/foreman/api/test_hostgroup.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_ldapauthsource.py
  tests/foreman/api/test_lifecycleenvironment.py
  tests/foreman/api/test_media.py
  tests/foreman/api/test_multiple_paths.py
  tests/foreman/api/test_organization.py
  tests/foreman/api/test_oscap_tailoringfiles.py
  tests/foreman/api/test_oscappolicy.py
  tests/foreman/api/test_permission.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/api/test_repositories.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_repository_set.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_settings.py
  tests/foreman/api/test_subnet.py
  tests/foreman/api/test_subscription.py
  tests/foreman/api/test_syncplan.py
  tests/foreman/api/test_templatesync.py
  tests/foreman/api/test_user.py
  tests/foreman/api/test_usergroup.py
  tests/foreman/api/test_webhook.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#13059 [6.12.z] Bump deepdiff from 6.6.1 to 6.7.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13057 [6.14.z] Bump deepdiff from 6.6.1 to 6.7.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13058 [6.13.z] Bump deepdiff from 6.6.1 to 6.7.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12978 Stream fix errata:UI (test_end_to_end)
  robottelo/cli/factory.py
  robottelo/host_helpers/cli_factory.py
  tests/foreman/ui/test_errata.py
Labels: No-CherryPick, Stream

#13056 [6.15] Add test coverage for setting display_fqdn_for_hosts
  tests/foreman/ui/test_settings.py
Labels: UI, QETestCoverage, No-CherryPick, Stream

#13048 improved webhook event trigger test
  tests/foreman/api/test_webhook.py
Labels: API, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#13070 updating the fedora image to 38 as latest using python 3.12
  Dockerfile
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#13075 [6.14.z] updating the fedora image to 38 as latest using python 3.12
  Dockerfile
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13074 [6.13.z] updating the fedora image to 38 as latest using python 3.12
  Dockerfile
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13073 [6.12.z] updating the fedora image to 38 as latest using python 3.12
  Dockerfile
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13060 [6.14.z] - removing the import entities from nailgun and moving target_sat
  tests/foreman/api/test_activationkey.py
  tests/foreman/api/test_architecture.py
  tests/foreman/api/test_audit.py
  tests/foreman/api/test_bookmarks.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_computeprofile.py
  tests/foreman/api/test_contentcredentials.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_contentviewversion.py
  tests/foreman/api/test_discoveryrule.py
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_filter.py
  tests/foreman/api/test_foremantask.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_hostcollection.py
  tests/foreman/api/test_hostgroup.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_ldapauthsource.py
  tests/foreman/api/test_lifecycleenvironment.py
  tests/foreman/api/test_media.py
  tests/foreman/api/test_multiple_paths.py
  tests/foreman/api/test_organization.py
  tests/foreman/api/test_oscap_tailoringfiles.py
  tests/foreman/api/test_oscappolicy.py
  tests/foreman/api/test_permission.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/api/test_repositories.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_repository_set.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_settings.py
  tests/foreman/api/test_subnet.py
  tests/foreman/api/test_subscription.py
  tests/foreman/api/test_syncplan.py
  tests/foreman/api/test_templatesync.py
  tests/foreman/api/test_user.py
  tests/foreman/api/test_usergroup.py
  tests/foreman/api/test_webhook.py
Labels: No-CherryPick

#13077 [6.14] improved webhook event trigger test
  tests/foreman/api/test_webhook.py
Labels: No-CherryPick, 6.14.z

#12341 Add SharedResource class to robottelo.utils
  robottelo/utils/shared_resource.py
  scripts/config_helpers.py
  tests/robottelo/test_shared_resource.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z, 6.14.z

#13068 Add API tests for capsule content counts
  requirements.txt
  robottelo/constants/__init__.py
  robottelo/host_helpers/repository_mixins.py
  tests/foreman/api/test_capsulecontent.py
Labels: API, No-CherryPick, Stream

#13085 [6.12.z] Add SharedResource class to robottelo.utils
  robottelo/utils/shared_resource.py
  scripts/config_helpers.py
  tests/robottelo/test_shared_resource.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13086 [6.13.z] Add SharedResource class to robottelo.utils
  robottelo/utils/shared_resource.py
  scripts/config_helpers.py
  tests/robottelo/test_shared_resource.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13087 [6.14.z] Add SharedResource class to robottelo.utils
  robottelo/utils/shared_resource.py
  scripts/config_helpers.py
  tests/robottelo/test_shared_resource.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13092 [6.14.z] Bump deepdiff from 6.7.0 to 6.7.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13093 [6.13.z] Bump deepdiff from 6.7.0 to 6.7.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13066 [6.13.z] - removing the import entities from nailgun and moving target_sat
  tests/foreman/api/test_activationkey.py
  tests/foreman/api/test_architecture.py
  tests/foreman/api/test_audit.py
  tests/foreman/api/test_bookmarks.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_computeprofile.py
  tests/foreman/api/test_contentcredentials.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_contentviewversion.py
  tests/foreman/api/test_discoveryrule.py
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_filter.py
  tests/foreman/api/test_foremantask.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_hostcollection.py
  tests/foreman/api/test_hostgroup.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_ldapauthsource.py
  tests/foreman/api/test_lifecycleenvironment.py
  tests/foreman/api/test_media.py
  tests/foreman/api/test_multiple_paths.py
  tests/foreman/api/test_organization.py
  tests/foreman/api/test_oscap_tailoringfiles.py
  tests/foreman/api/test_oscappolicy.py
  tests/foreman/api/test_permission.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/api/test_repositories.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_repository_set.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_settings.py
  tests/foreman/api/test_subnet.py
  tests/foreman/api/test_subscription.py
  tests/foreman/api/test_syncplan.py
  tests/foreman/api/test_templatesync.py
  tests/foreman/api/test_user.py
  tests/foreman/api/test_usergroup.py
  tests/foreman/api/test_webhook.py
Labels: No-CherryPick, 6.13.z

#13094 [6.12.z] Bump deepdiff from 6.7.0 to 6.7.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13027 Remove BROKER_DIRECTORY from robottelo config
  conf/broker.yaml.template
  robottelo/config/__init__.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#12840 Add a mechanism to swap nailgun versions on demand
  robottelo/hosts.py
Labels: enhancement, Upgrades, Framework Changes, CherryPick, 6.12.z, 6.13.z, 6.14.z

#13097 [6.14.z] Remove BROKER_DIRECTORY from robottelo config
  conf/broker.yaml.template
  robottelo/config/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13095 [6.13.z] Remove BROKER_DIRECTORY from robottelo config
  conf/broker.yaml.template
  robottelo/config/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13096 [6.12.z] Remove BROKER_DIRECTORY from robottelo config
  conf/broker.yaml.template
  robottelo/config/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13099 [6.12.z] Add a mechanism to swap nailgun versions on demand
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13098 [6.13.z] Add a mechanism to swap nailgun versions on demand
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13067 [6.12.z] removing the import entities from nailgun and moving target_sat
  tests/foreman/api/test_activationkey.py
  tests/foreman/api/test_architecture.py
  tests/foreman/api/test_audit.py
  tests/foreman/api/test_bookmarks.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_computeprofile.py
  tests/foreman/api/test_contentcredentials.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_contentviewversion.py
  tests/foreman/api/test_discoveryrule.py
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_filter.py
  tests/foreman/api/test_foremantask.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_hostcollection.py
  tests/foreman/api/test_hostgroup.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_ldapauthsource.py
  tests/foreman/api/test_lifecycleenvironment.py
  tests/foreman/api/test_media.py
  tests/foreman/api/test_multiple_paths.py
  tests/foreman/api/test_organization.py
  tests/foreman/api/test_oscap_tailoringfiles.py
  tests/foreman/api/test_oscappolicy.py
  tests/foreman/api/test_permission.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/api/test_repositories.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_repository_set.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_settings.py
  tests/foreman/api/test_subnet.py
  tests/foreman/api/test_subscription.py
  tests/foreman/api/test_syncplan.py
  tests/foreman/api/test_templatesync.py
  tests/foreman/api/test_user.py
  tests/foreman/api/test_usergroup.py
  tests/foreman/api/test_webhook.py
Labels: No-CherryPick

#13106 [6.12.z] Bump pre-commit from 3.4.0 to 3.5.0 (#12910)
  requirements-optional.txt
Labels: No-CherryPick, 6.12.z

#13105 [6.14.z] Bump actions/github-script from 6 to 7 (#13078)
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, 6.14.z

#13103 [6.12.z] Bump actions/github-script from 6 to 7 (#13078)
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, 6.12.z

#13069 Bump el9 kickstart version to 9.3
  robottelo/constants/__init__.py
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#13102 Test fix for discovery reboot_all scenario
  tests/foreman/api/test_discoveredhost.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#13112 [6.14.z] Test fix for discovery reboot_all scenario
  tests/foreman/api/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13113 [6.13.z] Test fix for discovery reboot_all scenario
  tests/foreman/api/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13114 [6.12.z] Bump pytest-xdist from 3.3.1 to 3.4.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13064 Stream fix for e2e api http_proxy failure
  tests/foreman/api/test_http_proxy.py
Labels: Easy Fix :), CherryPick, 6.12.z, 6.13.z, 6.14.z

#13118 [6.14.z] Stream fix for e2e api http_proxy failure
  tests/foreman/api/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13117 [6.13.z] Stream fix for e2e api http_proxy failure
  tests/foreman/api/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13119 [6.12.z] Stream fix for e2e api http_proxy failure
  tests/foreman/api/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13109 [6.14.z] Bump el9, el8 kickstart version to 9.3, 8.9 respectively
  robottelo/constants/__init__.py
Labels: Easy Fix :), No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13110 [6.12.z] Bump el9, el8 kickstart version to 9.3, 8.9 respectively
  robottelo/constants/__init__.py
Labels: Easy Fix :), No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13108 [6.13.z] Bump el9, el8 kickstart version to 9.3, 8.9 respectively
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13107 use one fixture instead of multiple and remove problematic one
  pytest_fixtures/component/repository.py
  tests/foreman/cli/test_contentaccess.py
Labels: TestFailure, CherryPick, 6.13.z, Stream, 6.14.z

#13122 [6.14.z] use one fixture instead of multiple and remove problematic one
  pytest_fixtures/component/repository.py
  tests/foreman/cli/test_contentaccess.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13123 [6.13.z] use one fixture instead of multiple and remove problematic one
  pytest_fixtures/component/repository.py
  tests/foreman/cli/test_contentaccess.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13128 Bump el8 kickstart version to 8.9
  robottelo/constants/__init__.py
Labels: Easy Fix :), No-CherryPick, Stream

#12908 Add UEFI HTTP Boot provisioning test
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_provisioning.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#13134 [6.14.z] Add UEFI HTTP Boot provisioning test
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13121 Fix Date assertion failure in CI errata:e2e
  tests/foreman/ui/test_errata.py
Labels: Easy Fix :), No-CherryPick, Stream

#12991 Discovery Provisioning UI coverage
  pytest_fixtures/component/discovery.py
  tests/foreman/ui/test_discoveredhost.py
Labels: UI, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#13142 [6.14.z] satellite and capsule installation improvements
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13141 Yield details always, no need to check for SCA eligibility
  tests/foreman/cli/test_host.py
Labels: CherryPick, 6.13.z, 6.14.z

#13047 Add abstraction for debian repo
  robottelo/constants/__init__.py
  robottelo/host_helpers/repository_mixins.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#13136 [RFE] RHEL Lifecycle Support status - for ReportTemplate column
  tests/foreman/api/test_reporttemplates.py
Labels: RFE, Easy Fix :), No-CherryPick, Stream

#12519 Component Audit Part-2
  pytest_fixtures/component/activationkey.py
  tests/foreman/api/test_registration.py
  tests/foreman/ui/test_host.py
Labels: QETestCoverage, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#13147 [6.14.z] Add abstraction for debian repo
  robottelo/constants/__init__.py
  robottelo/host_helpers/repository_mixins.py
Labels: No-CherryPick, 6.14.z

#13146 [6.13.z] Add abstraction for debian repo
  robottelo/constants/__init__.py
  robottelo/host_helpers/repository_mixins.py
Labels: No-CherryPick, 6.13.z

#13145 [6.12.z] Add abstraction for debian repo
  robottelo/constants/__init__.py
  robottelo/host_helpers/repository_mixins.py
Labels: No-CherryPick, 6.12.z

#13152 Parametrize Satellite and Capsule deployments
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/hosts.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#13148 remove test_installer_inventory_plugin_update
  tests/foreman/destructive/test_installer.py
Labels: CherryPick, 6.14.z

#13153 [6.12.z] Parametrize Satellite and Capsule deployments
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13154 [6.14.z] Parametrize Satellite and Capsule deployments
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13155 [6.13.z] Parametrize Satellite and Capsule deployments
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13156 [6.14.z] remove test_installer_inventory_plugin_update
  tests/foreman/destructive/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13139 [6.14.z] Discovery Provisioning UI coverage
  pytest_fixtures/component/discovery.py
  tests/foreman/ui/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13140 [6.13.z] Discovery Provisioning UI coverage
  pytest_fixtures/component/discovery.py
  tests/foreman/ui/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13133 [6.13.z] Add UEFI HTTP Boot provisioning test
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13159 [6.13.z] Component Audit Part-2
  pytest_fixtures/component/activationkey.py
  tests/foreman/api/test_registration.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.13.z

#13158 [6.14.z] Component Audit Part-2
  pytest_fixtures/component/activationkey.py
  tests/foreman/api/test_registration.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#13160 Update vlan paramater template test for BZ:2075358
  tests/foreman/api/test_provisioningtemplate.py
Labels: API, QETestCoverage, No-CherryPick, Stream

#13101 Add basic fixture cli
  pytest_plugins/fspath_plugins.py
  pytest_plugins/issue_handlers.py
  scripts/fixture_cli.py
Labels: enhancement, CherryPick, 6.12.z, 6.13.z, 6.14.z

#13164 [6.13.z] Add basic fixture cli
  pytest_plugins/fspath_plugins.py
  pytest_plugins/issue_handlers.py
  scripts/fixture_cli.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13166 [6.14.z] Add basic fixture cli
  pytest_plugins/fspath_plugins.py
  pytest_plugins/issue_handlers.py
  scripts/fixture_cli.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13165 [6.12.z] Add basic fixture cli
  pytest_plugins/fspath_plugins.py
  pytest_plugins/issue_handlers.py
  scripts/fixture_cli.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13137 [6.14.z] Check upgrade warning when KA enabled
  robottelo/constants/__init__.py
  tests/foreman/destructive/test_katello_agent.py
Labels: QETestCoverage, No-CherryPick, 6.14.z

#13167 fix for remote execution cli tests
  tests/foreman/cli/test_remoteexecution.py
Labels: TestFailure, CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13049 [6.15] negative test for webhook task
  tests/foreman/api/test_webhook.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13055 recording ui-session-id for report portal logging
  pytest_fixtures/core/ui.py
  robottelo/hosts.py
  tests/foreman/conftest.py
  tests/foreman/destructive/conftest.py
Labels: Framework Changes, CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13178 [6.12.z] Bump pytest-xdist from 3.4.0 to 3.5.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13180 [6.13.z] Bump pytest-xdist from 3.4.0 to 3.5.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13181 [6.14.z] Bump pytest-xdist from 3.4.0 to 3.5.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13179 [6.15.z] Bump pytest-xdist from 3.4.0 to 3.5.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13182 [6.14.z] recording ui-session-id for report portal logging
  pytest_fixtures/core/ui.py
  robottelo/hosts.py
  tests/foreman/conftest.py
  tests/foreman/destructive/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13184 [6.13.z] recording ui-session-id for report portal logging
  pytest_fixtures/core/ui.py
  robottelo/hosts.py
  tests/foreman/conftest.py
  tests/foreman/destructive/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13172 [6.15.z] fix for remote execution cli tests
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13175 [6.15.z] [6.15] negative test for webhook task
  tests/foreman/api/test_webhook.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13169 Changes to Master due to new 6.15 and 6.16
  .github/dependabot.yml
  conf/robottelo.yaml.template
  robottelo/constants/__init__.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/destructive/test_infoblox.py
  tests/foreman/maintain/test_service.py
  tests/foreman/ui/test_settings.py
Labels: No-CherryPick

#13168 Changes for 6.15.z new branch
  .github/dependabot.yml
  .github/workflows/dispatch_release.yml
  requirements.txt
  robottelo/constants/__init__.py
  setup.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/destructive/test_infoblox.py
  tests/foreman/maintain/test_service.py
  tests/foreman/ui/test_settings.py
Labels: No-CherryPick, 6.15.z

#13120 First tests for new All Hosts page
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Stream

#13191 [6.14.z] Bump cryptography from 41.0.5 to 41.0.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13192 [6.12.z] Bump cryptography from 41.0.5 to 41.0.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13193 [6.13.z] Bump cryptography from 41.0.5 to 41.0.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13190 [6.15.z] Bump cryptography from 41.0.5 to 41.0.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13170 fix for webhook event trigger test
  tests/foreman/api/test_webhook.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#13199 [6.15.z] Intermittent failure of api::errata::e2e
  tests/foreman/api/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13194 [6.15.z] fix for webhook event trigger test
  tests/foreman/api/test_webhook.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13195 [6.14.z] fix for webhook event trigger test
  tests/foreman/api/test_webhook.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13196 Add default content type as yum for make_repository helper
  robottelo/host_helpers/cli_factory.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13176 Pytest FixtureCollection external plugin
  conftest.py
  pytest_plugins/fixture_collection.py
  requirements.txt
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13212 added the missing direcotry path for ui_session
  tests/foreman/conftest.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13210 Add test scenario for disconnected option of rh_cloud report
  robottelo/hosts.py
  tests/foreman/api/test_rhcloud_inventory.py
Labels: CherryPick, 6.15.z

#13200 [6.14.z] Cherrypick test for invalid repositories
  tests/foreman/cli/test_repositories.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#12945 [6.12.z] Cherrypick test sync multiple large repos 6.12.z
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, 6.12.z

#12947 [6.13.z] Cherrypick test sync large multiple repos 6.13.z
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, 6.13.z

#13204 [6.15.z] Add default content type as yum for make_repository helper
  robottelo/host_helpers/cli_factory.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13213 [6.15.z] added the missing directory path for ui_session
  tests/foreman/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13216 [6.14.z] added the missing directory path for ui_session
  tests/foreman/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#13215 [6.13.z] added the missing directory path for ui_session
  tests/foreman/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13188 [6.12.z] recording ui-session-id for report portal logging
  pytest_fixtures/core/ui.py
  robottelo/hosts.py
  tests/foreman/conftest.py
  tests/foreman/destructive/conftest.py
Labels: No-CherryPick

#13219 [6.15.z] Add test scenario for disconnected option of rh_cloud report
  robottelo/hosts.py
  tests/foreman/api/test_rhcloud_inventory.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#12946 [6.14.z] Cherrypick test sync multiple large repos 6.14.z
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, 6.14.z

#13206 [6.15.z] Pytest FixtureCollection external plugin
  conftest.py
  pytest_plugins/fixture_collection.py
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13207 [6.14.z] Pytest FixtureCollection external plugin
  conftest.py
  pytest_plugins/fixture_collection.py
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13208 [6.13.z] Pytest FixtureCollection external plugin
  conftest.py
  pytest_plugins/fixture_collection.py
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13205 [6.12.z] Pytest FixtureCollection external plugin
  conftest.py
  pytest_plugins/fixture_collection.py
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13201 [6.13.z] Cherrypick test for invalid repositories
  tests/foreman/cli/test_repositories.py
Labels: No-CherryPick, 6.13.z

#12619 fixture support for virt-who config cli : data_form deploy_type virtwho_config delete_host& manifest content move
  conftest.py
  pytest_fixtures/component/virtwho_config.py
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_nutanix.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_esx_sca.py
  tests/foreman/virtwho/cli/test_hyperv.py
  tests/foreman/virtwho/cli/test_hyperv_sca.py
  tests/foreman/virtwho/cli/test_kubevirt.py
  tests/foreman/virtwho/cli/test_kubevirt_sca.py
  tests/foreman/virtwho/cli/test_libvirt.py
  tests/foreman/virtwho/cli/test_libvirt_sca.py
  tests/foreman/virtwho/cli/test_nutanix.py
  tests/foreman/virtwho/cli/test_nutanix_sca.py
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#13198 Check that concurrency level is honored
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13228 [6.14.z] fixture support for virt-who config cli : data_form deploy_type virtwho_config delete_host& manifest content move
  conftest.py
  pytest_fixtures/component/virtwho_config.py
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_nutanix.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_esx_sca.py
  tests/foreman/virtwho/cli/test_hyperv.py
  tests/foreman/virtwho/cli/test_hyperv_sca.py
  tests/foreman/virtwho/cli/test_kubevirt.py
  tests/foreman/virtwho/cli/test_kubevirt_sca.py
  tests/foreman/virtwho/cli/test_libvirt.py
  tests/foreman/virtwho/cli/test_libvirt_sca.py
  tests/foreman/virtwho/cli/test_nutanix.py
  tests/foreman/virtwho/cli/test_nutanix_sca.py
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13187 Add coverage for BZ#2092039 and update few docstrings
  tests/foreman/cli/test_satellitesync.py
Labels: CLI, QETestCoverage, CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z
