Repository SatelliteQE/robottelo, pull requests merged in 2023-06, with the labels that each got.

#11528 [6.13.z] Fix for PytestAssertRewriteWarning
  pytest_fixtures/component/satellite_auth.py
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/hosts.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11577 [6.14.z] Bump cryptography from 40.0.2 to 41.0.0
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11576 [6.13.z] Bump cryptography from 40.0.2 to 41.0.0
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11574 [6.12.z] Bump cryptography from 40.0.2 to 41.0.0
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11514 Adding better coverage to enable/disable stream test
  tests/foreman/maintain/test_service.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#11482 Add Infoblox end to end test
  conf/infoblox.yaml.template
  tests/foreman/destructive/test_infoblox.py
  tests/foreman/installer/test_infoblox.py
Labels: 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, Stream, 6.14.z

#11526 [6.13.z] Http-Proxy cacert automation coverage
  tests/foreman/api/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11586 [6.12.z] Bump cryptography from 41.0.0 to 41.0.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11588 [6.13.z] Bump cryptography from 41.0.0 to 41.0.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11587 [6.11.z] Bump cryptography from 41.0.0 to 41.0.1
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11578 [6.14.z] Adding better coverage to enable/disable stream test
  tests/foreman/maintain/test_service.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11570 Close looop BZ1896628
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11590 [6.12.z] Close looop BZ1896628
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11591 [6.13.z] Close looop BZ1896628
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11569 remove rhel6 support from scap test and skip test due to bz 2211437
  tests/foreman/longrun/test_oscap.py
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11542 Add CLI test for applied filters
  tests/foreman/cli/test_contentviewfilter.py
Labels: CLI, CherryPick, AutoMerge_Cherry_Picked, Stream, 6.14.z

#11596 Remove @stream decorator
  tests/foreman/cli/test_contentviewfilter.py
Labels: Easy Fix :), CherryPick, 6.14.z

#11595 [6.14.z] Add CLI test for applied filters
  tests/foreman/cli/test_contentviewfilter.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11599 [6.14.z] Remove @stream decorator
  tests/foreman/cli/test_contentviewfilter.py
Labels: Easy Fix :), No-CherryPick, 6.14.z

#11597 Remove unnecessary failing assertion api/test_http_proxy.py
  tests/foreman/api/test_http_proxy.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#11491 Close loop - Ansible job invocation shows wrong info after remote execution job
  pytest_fixtures/core/contenthosts.py
  tests/foreman/api/test_ansible.py
Labels: API, QETestCoverage, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11603 [6.13.z] Close loop - Ansible job invocation shows wrong info after remote execution job
  pytest_fixtures/core/contenthosts.py
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11600 [6.14.z] Remove unnecessary failing assertion api/test_http_proxy.py
  tests/foreman/api/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11567 Fix configure_puppet
  robottelo/hosts.py
Labels: TestFailure, Easy Fix :), 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11594 [6.12.z] remove rhel6 support from scap test and skip test due to bz 2211437
  tests/foreman/longrun/test_oscap.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11613 [6.13.z] Fix configure_puppet
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11557 Automate BZ 1969263
  tests/foreman/api/test_host.py
Labels: QETestCoverage, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11616 [6.13.z] Automate BZ 1969263
  tests/foreman/api/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11618 [6.12.z] Automate BZ 1969263
  tests/foreman/api/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11615 [6.12.z] Fix configure_puppet
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11612 [6.14.z] Fix configure_puppet
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11620 must_succeed flag for task intended to pass/fail
  robottelo/api/utils.py
  robottelo/host_helpers/capsule_mixins.py
Labels: No-CherryPick, 6.12.z

#11614 [6.11.z] Fix configure_puppet
  robottelo/hosts.py
Labels: Easy Fix :), 6.11.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#11602 [6.12.z] Close loop - Ansible job invocation shows wrong info after remote execution job
  pytest_fixtures/core/contenthosts.py
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11609 Close-loop 1757394
  tests/foreman/api/test_user.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#11546 Fix RHSSO bugs.
  pytest_fixtures/component/satellite_auth.py
  robottelo/hosts.py
  tests/foreman/destructive/test_ldapauthsource.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#11632 [6.14.z] Add Infoblox end to end test
  conf/infoblox.yaml.template
  tests/foreman/destructive/test_infoblox.py
  tests/foreman/installer/test_infoblox.py
Labels: No-CherryPick, 6.14.z

#11628 [6.12.z] Fix RHSSO bugs.
  pytest_fixtures/component/satellite_auth.py
  robottelo/hosts.py
  tests/foreman/destructive/test_ldapauthsource.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11625 [6.14.z] Close-loop 1757394
  tests/foreman/api/test_user.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11624 [6.12.z] Close-loop 1757394
  tests/foreman/api/test_user.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11631 Add customercase
  tests/foreman/api/test_host.py
Labels: Easy Fix :), CherryPick, 6.12.z, 6.13.z, 6.14.z

#11643 [6.14.z] Add customercase
  tests/foreman/api/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11642 [6.13.z] Add customercase
  tests/foreman/api/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11640 [6.12.z] Bump mheap/github-action-required-labels from 4 to 5
  .github/workflows/required_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11641 [6.11.z] Bump mheap/github-action-required-labels from 4 to 5
  .github/workflows/required_labels.yml
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11656 [6.14.z] Bump pytest from 7.3.1 to 7.3.2
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11653 [6.13.z] Bump pytest from 7.3.1 to 7.3.2
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11655 [6.12.z] Bump pytest from 7.3.1 to 7.3.2
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11654 [6.11.z] Bump pytest from 7.3.1 to 7.3.2
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11651 [6.13.z] Bump sphinx-autoapi from 2.1.0 to 2.1.1
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11650 [6.12.z] Bump sphinx-autoapi from 2.1.0 to 2.1.1
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11563 [Req Assist] Update more reqs names deviation and other improvements
  pytest_plugins/requirements/req_updater.py
  pytest_plugins/requirements/update_requirements.py
  requirements-optional.txt
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z, 6.14.z

#11660 [6.13.z] [Req Assist] Update more reqs names deviation and other improvements
  pytest_plugins/requirements/req_updater.py
  pytest_plugins/requirements/update_requirements.py
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11661 [6.11.z] [Req Assist] Update more reqs names deviation and other improvements
  pytest_plugins/requirements/req_updater.py
  pytest_plugins/requirements/update_requirements.py
  requirements-optional.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11659 [6.14.z] [Req Assist] Update more reqs names deviation and other improvements
  pytest_plugins/requirements/req_updater.py
  pytest_plugins/requirements/update_requirements.py
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11608 Add Closed loop BZ#2173199
  robottelo/cli/bootdisk.py
  robottelo/constants/__init__.py
  tests/foreman/cli/test_bootdisk.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11658 [6.12.z] [Req Assist] Update more reqs names deviation and other improvements
  pytest_plugins/requirements/req_updater.py
  pytest_plugins/requirements/update_requirements.py
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11662 [6.13.z] adding support for parameterization upgrade scenarios
  tests/upgrades/conftest.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_remoteexecution.py
  tests/upgrades/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11566 [6.13.z] autodetect and add prt tests for dependabot PR's
  .github/dependency_tests.yaml
  .github/workflows/auto_cherry_pick_merge.yaml
  .github/workflows/dependency_merge.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11564 [6.12.z] autodetect and add prt tests for dependabot PR's
  .github/dependency_tests.yaml
  .github/workflows/auto_cherry_pick_merge.yaml
  .github/workflows/dependency_merge.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11565 [6.11.z] autodetect and add prt tests for dependabot PR's
  .github/dependency_tests.yaml
  .github/workflows/auto_cherry_pick_merge.yaml
  .github/workflows/dependency_merge.yml
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11646 [6.14.z] autodetect and add prt tests for dependabot PR's
  .github/dependabot.yml
  .github/dependency_tests.yaml
  .github/workflows/dependency_merge.yml
Labels: No-CherryPick, 6.14.z

#11664 [6.13.z] Add Closed loop BZ#2173199
  robottelo/cli/bootdisk.py
  robottelo/constants/__init__.py
  tests/foreman/cli/test_bootdisk.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11665 [6.14.z] Add Closed loop BZ#2173199
  robottelo/cli/bootdisk.py
  robottelo/constants/__init__.py
  tests/foreman/cli/test_bootdisk.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11593 [6.14.z] remove rhel6 support from scap test and skip test due to bz 2211437
  tests/foreman/longrun/test_oscap.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11592 [6.13.z] remove rhel6 support from scap test and skip test due to bz 2211437
  tests/foreman/longrun/test_oscap.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11636 [6.14.z] Bump pytest-reportportal from 5.1.8 to 5.1.9
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11639 [6.11.z] Bump pytest-reportportal from 5.1.8 to 5.1.9
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11627 [6.14.z] Fix RHSSO bugs.
  pytest_fixtures/component/satellite_auth.py
  robottelo/hosts.py
  tests/foreman/destructive/test_ldapauthsource.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11667 Fix activation key setup
  pytest_fixtures/component/repository.py
  robottelo/host_helpers/repository_mixins.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#11670 [6.14.z] Fix activation key setup
  pytest_fixtures/component/repository.py
  robottelo/host_helpers/repository_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11668 [6.13.z] Fix activation key setup
  robottelo/host_helpers/repository_mixins.py
Labels: No-CherryPick, 6.13.z

#11674 [6.14.z] Bump pre-commit from 3.3.2 to 3.3.3
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11678 `rp_api_key` replaced `rp_uuid` in RP pytest plugin config
  pytest_plugins/rerun_rp/rerun_rp.py
Labels: Easy Fix :), 6.11.z, CherryPick, 6.12.z, 6.13.z, 6.14.z

#11679 [6.14.z] `rp_api_key` replaced `rp_uuid` in RP pytest plugin config
  pytest_plugins/rerun_rp/rerun_rp.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11681 [6.13.z] `rp_api_key` replaced `rp_uuid` in RP pytest plugin config
  pytest_plugins/rerun_rp/rerun_rp.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11682 [6.12.z] `rp_api_key` replaced `rp_uuid` in RP pytest plugin config
  pytest_plugins/rerun_rp/rerun_rp.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11680 [6.11.z] `rp_api_key` replaced `rp_uuid` in RP pytest plugin config
  pytest_plugins/rerun_rp/rerun_rp.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11529 [6.12.z] Fix for PytestAssertRewriteWarning
  pytest_fixtures/component/satellite_auth.py
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/hosts.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11685 [6.12.z] Close-loop BZ 1955421
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11530 [6.11.z] Fix for PytestAssertRewriteWarning
  pytest_fixtures/component/satellite_auth.py
  robottelo/hosts.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: 6.11.z, No-CherryPick

#11687 [6.13.z] Close-loop BZ 1955421
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11573 Add treeinfo ignore test
  tests/foreman/api/test_repository.py
Labels: API, No-CherryPick, 6.14.z

#11677 CI declines colorcodes and so for req assist plugin
  pytest_plugins/requirements/update_requirements.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z, 6.14.z

#11701 [6.13.z] CI declines colorcodes and so for req assist plugin
  pytest_plugins/requirements/update_requirements.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11700 [6.14.z] CI declines colorcodes and so for req assist plugin
  pytest_plugins/requirements/update_requirements.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11699 [6.11.z] CI declines colorcodes and so for req assist plugin
  pytest_plugins/requirements/update_requirements.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11698 [6.12.z] CI declines colorcodes and so for req assist plugin
  pytest_plugins/requirements/update_requirements.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11690 [6.14.z] Bump pytest-mock from 3.10.0 to 3.11.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11691 [6.12.z] Bump pytest-mock from 3.10.0 to 3.11.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11693 [6.13.z] Bump pytest-mock from 3.10.0 to 3.11.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11692 [6.11.z] Bump pytest-mock from 3.10.0 to 3.11.1
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11704 [6.13.z] Add test for orphaned content removal from capsule
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11703 [6.14.z] Add test for orphaned content removal from capsule
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11705 [6.14.z] Add treeinfo ignore test
  tests/foreman/api/test_repository.py
Labels: API, No-CherryPick, 6.14.z

#11709 [6.14.z] Update foreman-installer command line options list
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11710 [6.13.z] Fix failing foreman/maintain/advanced test
  tests/foreman/maintain/test_advanced.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11711 [6.14.z] Fix failing foreman/maintain/advanced test
  tests/foreman/maintain/test_advanced.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11708 Fix Katello-tracer component case
  testimony.yaml
  tests/foreman/cli/test_host.py
  tests/foreman/ui/test_host.py
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11714 [6.13.z] Fix Katello-tracer component case
  testimony.yaml
  tests/foreman/cli/test_host.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11694 [6.14.z] - added the fix for the automerge cherry-pick dependabot PR's
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/dependency_merge.yml
Labels: No-CherryPick, 6.14.z

#11695 [6.13.z] - added the fix for the automerge cherry-pick dependabot PR's
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/dependency_merge.yml
Labels: No-CherryPick, 6.13.z

#11696 [6.12.z] - added the fix for the automerge cherry-pick dependabot PR's
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/dependency_merge.yml
Labels: No-CherryPick, 6.12.z

#11697 [6.11.z]- added the fix for the automerge cherry-pick dependabot PR's
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/dependency_merge.yml
Labels: 6.11.z, No-CherryPick

#11433 Content View Audit Tests
  tests/foreman/api/test_contentview.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#11663 [6.12.z] Add Closed loop BZ#2173199
  robottelo/cli/bootdisk.py
  robottelo/constants/__init__.py
  tests/foreman/cli/test_bootdisk.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11669 Convert remaining tests to manifester
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
  tests/foreman/longrun/test_inc_updates.py
Labels: 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11722 [6.13.z] Convert remaining tests to manifester
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
  tests/foreman/longrun/test_inc_updates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11720 [6.14.z] Convert remaining tests to manifester
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
  tests/foreman/longrun/test_inc_updates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11724 [6.12.z] Fix Katello-tracer component case
  testimony.yaml
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, 6.12.z

#11716 Adding service status coverage to backup and restore
  tests/foreman/maintain/test_backup_restore.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11725 hammer commands updated for 6.14
  tests/foreman/data/hammer_commands.json
Labels: CLI, No-CherryPick, 6.14.z

#11731 [6.13.z] Bump testimony from 2.2.0 to 2.3.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11733 [6.11.z] Bump testimony from 2.2.0 to 2.3.0
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11732 [6.12.z] Bump testimony from 2.2.0 to 2.3.0
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11728 [6.13.z] Adding service status coverage to backup and restore
  tests/foreman/maintain/test_backup_restore.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11719 api changes in 6.14
  tests/foreman/endtoend/test_api_endtoend.py
Labels: API, TestFailure, No-CherryPick, 6.14.z

#11726 [6.14.z] Adding service status coverage to backup and restore
  tests/foreman/maintain/test_backup_restore.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11706 add delete org before run virt-who config upgrade cases
  tests/upgrades/test_virtwho.py
Labels: Upgrades, CherryPick, 6.12.z, 6.13.z, 6.14.z

#11740 [6.13.z] add delete org before run virt-who config upgrade cases
  tests/upgrades/test_virtwho.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11739 [6.12.z] add delete org before run virt-who config upgrade cases
  tests/upgrades/test_virtwho.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11741 Fix repo scraping
  robottelo/content_info.py
Labels: TestFailure, Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11743 [6.13.z] Fix repo scraping
  robottelo/content_info.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11744 [6.12.z] Fix repo scraping
  robottelo/content_info.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11742 [6.14.z] Fix repo scraping
  robottelo/content_info.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11734 [6.14.z] extended cronline tests for rex
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#10424 Add test for the Capsule sync deadlock issue
  conf/capsule.yaml.template
  conf/flavors.yaml.template
  pytest_fixtures/core/contenthosts.py
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
  tests/foreman/destructive/test_capsulecontent.py
Labels: QETestCoverage, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11755 [6.14.z] Bump pytest from 7.3.2 to 7.4.0
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11757 [6.13.z] Bump pytest from 7.3.2 to 7.4.0
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11756 [6.12.z] Bump pytest from 7.3.2 to 7.4.0
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11754 [6.11.z] Bump pytest from 7.3.2 to 7.4.0
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11745 [6.14.z] Add test for the Capsule sync deadlock issue
  conf/capsule.yaml.template
  conf/flavors.yaml.template
  pytest_fixtures/core/contenthosts.py
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
  tests/foreman/destructive/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11758 [6.13.z] Add test for the Capsule sync deadlock issue
  conf/capsule.yaml.template
  conf/flavors.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
  tests/foreman/destructive/test_capsulecontent.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.13.z

#11761 [6.13.z] Remove stream marker from Infoblox test
  tests/foreman/destructive/test_infoblox.py
Labels: Easy Fix :), No-CherryPick, 6.13.z

#11702 Pulp test fix
  tests/foreman/api/test_repositories.py
Labels: Easy Fix :), 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11763 [6.14.z] Pulp test fix
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11561 Applied errata template test and custom product fix
  robottelo/cli/factory.py
  robottelo/host_helpers/cli_factory.py
  tests/foreman/api/test_reporttemplates.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#11768 [6.14.z] Applied errata template test and custom product fix
  robottelo/cli/factory.py
  robottelo/host_helpers/cli_factory.py
  tests/foreman/api/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11735 Enable client_repo in AK for provisioning
  pytest_fixtures/component/provision_pxe.py
Labels: TestFailure, Tier 1 ACK, CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#11737 Remove redundant rhev provisioning test
  pytest_fixtures/component/settings.py
  tests/foreman/cli/test_computeresource_rhev.py
  tests/foreman/longrun/test_provisioning_computeresource.py
  tests/foreman/ui/test_host.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z, 6.14.z

#11773 [6.13.z] Remove redundant rhev provisioning test
  pytest_fixtures/component/settings.py
  tests/foreman/cli/test_computeresource_rhev.py
  tests/foreman/longrun/test_provisioning_computeresource.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11771 Fix container repo tests
  tests/foreman/api/test_repository.py
  tests/foreman/ui/test_containerimagetag.py
Labels: TestFailure, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11770 [6.14.z] Enable client_repo in AK for provisioning
  pytest_fixtures/component/provision_pxe.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11777 [6.14.z] Fix container repo tests
  tests/foreman/api/test_repository.py
  tests/foreman/ui/test_containerimagetag.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11778 [6.13.z] Fix container repo tests
  tests/foreman/api/test_repository.py
  tests/foreman/ui/test_containerimagetag.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11465 e2e tests updated a bit
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11780 [6.14.z] e2e tests updated a bit
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11781 [6.13.z] e2e tests updated a bit
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11767 check recurring logic cli keys
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#11782 [6.14.z] check recurring logic cli keys
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z
