Repository SatelliteQE/robottelo, pull requests merged in 2023-12, with the labels that each got.

#13237 RHEL Lifecycle status column, RFE for 6.15.0
  tests/foreman/ui/test_host.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z

#13238 [6.15.z] RHEL Lifecycle status column, RFE for 6.15.0
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13231 [6.15.z] Check that concurrency level is honored
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#12578 Fix test_negative_pre_upgrade_tuning_profile_check
  robottelo/constants/__init__.py
  tests/foreman/maintain/test_upgrade.py
Labels: No-CherryPick, Stream

#13250 [6.12.z] Fix capsule download policy update
  robottelo/hosts.py
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13252 adding customerscenario tag to libvirt e2e provision test
  tests/foreman/cli/test_computeresource_libvirt.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#13260 [6.12.z] Bump navmazing from 1.1.6 to 1.2.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13262 [6.13.z] Bump navmazing from 1.1.6 to 1.2.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13256 [6.15.z] adding customerscenario tag to libvirt e2e provision test
  tests/foreman/cli/test_computeresource_libvirt.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13258 [6.14.z] adding customerscenario tag to libvirt e2e provision test
  tests/foreman/cli/test_computeresource_libvirt.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13257 [6.13.z] adding customerscenario tag to libvirt e2e provision test
  tests/foreman/cli/test_computeresource_libvirt.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13261 [6.15.z] Bump navmazing from 1.1.6 to 1.2.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13263 [6.14.z] Bump navmazing from 1.1.6 to 1.2.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13255 Add rex cockpit ensure install option
  tests/foreman/installer/test_installer.py
Labels: API, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13265 [6.15.z] Add rex cockpit ensure install option
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13267 Add test to verify supported provisioning templates
  tests/foreman/ui/test_provisioningtemplate.py
Labels: UI, QETestCoverage, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13203 Notifications: new failed repo sync test
  robottelo/cli/user.py
  tests/foreman/api/test_notifications.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13268 [6.13.z] Add test to verify supported provisioning templates
  tests/foreman/ui/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13271 [6.12.z] Add test to verify supported provisioning templates
  tests/foreman/ui/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13269 [6.14.z] Add test to verify supported provisioning templates
  tests/foreman/ui/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13270 [6.15.z] Add test to verify supported provisioning templates
  tests/foreman/ui/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13186 Add custom pytest hook for test result handling and video cleanup
  conftest.py
  pytest_plugins/video_cleanup.py
Labels: enhancement, Framework Changes, CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13242 [6.15.z] Add coverage for BZ#2092039 and update few docstrings
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13245 [6.14.z] Add coverage for BZ#2092039 and update few docstrings
  robottelo/host_helpers/satellite_mixins.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#13246 [6.13.z] Add coverage for BZ#2092039 and update few docstrings
  robottelo/host_helpers/satellite_mixins.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.13.z

#13247 [6.12.z] Add coverage for BZ#2092039 and update few docstrings
  robottelo/host_helpers/satellite_mixins.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, 6.12.z, AutoMerge_Cherry_Picked

#13284 Fix subnet tests
  tests/foreman/cli/test_subnet.py
Labels: TestFailure, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13292 [6.15.z] Fix subnet tests
  tests/foreman/cli/test_subnet.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13293 [6.14.z] Fix subnet tests
  tests/foreman/cli/test_subnet.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13294 [6.12.z] Fix subnet tests
  tests/foreman/cli/test_subnet.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13279 [6.15.z] Add custom pytest hook for test result handling and video cleanup
  conftest.py
  pytest_plugins/video_cleanup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13280 [6.14.z] Add custom pytest hook for test result handling and video cleanup
  conftest.py
  pytest_plugins/video_cleanup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13281 [6.12.z] Add custom pytest hook for test result handling and video cleanup
  conftest.py
  pytest_plugins/video_cleanup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13289 [6.14] fix for remote execution cli tests
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#13291 [6.15.z] Fix copy PRT comment action in autocherrypick workflow
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13299 [6.13.z] Bump pytest-reportportal from 5.3.0 to 5.3.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13301 [6.12.z] Bump pytest-reportportal from 5.3.0 to 5.3.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13305 [6.15.z] Bump actions/setup-python from 4 to 5
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13298 [6.15.z] Bump pytest-reportportal from 5.3.0 to 5.3.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13300 [6.14.z] Bump pytest-reportportal from 5.3.0 to 5.3.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13307 Update error message in negative settings test
  tests/foreman/ui/test_settings.py
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13283 Add default provider/url for make_compute_resource helper
  robottelo/host_helpers/cli_factory.py
Labels: TestFailure, Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13282 Add closed loop for BZ#1841048
  tests/foreman/api/test_registration.py
Labels: QETestCoverage, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13209 Test Coverage for FDI version verification
  tests/upgrades/test_discovery.py
Labels: QETestCoverage, Upgrades, CherryPick, 6.13.z, 6.14.z, 6.15.z

#13322 [6.15.z] Test Coverage for FDI version verification
  tests/upgrades/test_discovery.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13318 [6.13.z] Add closed loop for BZ#1841048
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13319 [6.15.z] Add closed loop for BZ#1841048
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13311 [6.15.z] Update error message in negative settings test
  tests/foreman/ui/test_settings.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13274 [6.15.z] Create distinction between the product-ready OS and the product WFs
  conf/capsule.yaml.template
  conf/dynaconf_hooks.py
  conf/migrations.py
  conf/server.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13275 [6.14.z] Create distinction between the product-ready OS and the product WFs
  conf/capsule.yaml.template
  conf/dynaconf_hooks.py
  conf/migrations.py
  conf/server.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13314 [6.15.z] Add default provider/url for make_compute_resource helper
  robottelo/host_helpers/cli_factory.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13310 [6.13.z] Update error message in negative settings test
  tests/foreman/ui/test_settings.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13243 Multiple enhancements to scripts/fixture_cli.py
  scripts/fixture_cli.py
Labels: enhancement, CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13327 [6.12.z] Multiple enhancements to scripts/fixture_cli.py
  scripts/fixture_cli.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13329 [6.13.z] Multiple enhancements to scripts/fixture_cli.py
  scripts/fixture_cli.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13330 [6.14.z] Multiple enhancements to scripts/fixture_cli.py
  scripts/fixture_cli.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13333 [6.13.z] Bump productmd from 1.37 to 1.38
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13334 [6.12.z] Bump productmd from 1.37 to 1.38
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13336 [6.14.z] Bump productmd from 1.37 to 1.38
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13337 [6.14.z] Bump actions/stale from 8 to 9
  .github/workflows/stale.yml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13335 [6.15.z] Bump productmd from 1.37 to 1.38
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13339 [6.15.z] Bump actions/stale from 8 to 9
  .github/workflows/stale.yml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13340 [6.13.z] Bump actions/stale from 8 to 9
  .github/workflows/stale.yml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13286 Fix incremental update longrun 6 14 z
  tests/foreman/longrun/test_inc_updates.py
Labels: TestFailure, CherryPick, 6.13.z, 6.14.z

#13343 Remove unnecessary on_premises_provisioning marker
  tests/foreman/ui/test_location.py
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13345 [6.14.z] Remove unnecessary on_premises_provisioning marker
  tests/foreman/ui/test_location.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13346 [6.13.z] Remove unnecessary on_premises_provisioning marker
  tests/foreman/ui/test_location.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13344 [6.15.z] Remove unnecessary on_premises_provisioning marker
  tests/foreman/ui/test_location.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13347 [6.12.z] Remove unnecessary on_premises_provisioning marker
  tests/foreman/ui/test_location.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13227 Use module_extra_rhel_entitlement_manifest for cloud connector test
  tests/foreman/ui/test_rhc.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13348 [6.15.z] Use module_extra_rhel_entitlement_manifest for cloud connector test
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13349 [6.14.z] Use module_extra_rhel_entitlement_manifest for cloud connector test
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13350 [6.13.z] Use module_extra_rhel_entitlement_manifest for cloud connector test
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13324 Test markers as test fields in polarion
  scripts/polarion-test-case-upload.sh
Labels: Framework Changes, CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13004 [6.15 RFE] Prepare for SCA Only Update Web UI
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_organization.py
  tests/foreman/ui/test_subscription.py
Labels: RFE, UI, CherryPick, 6.15.z

#13352 [6.14.z] Test markers as test fields in polarion
  scripts/polarion-test-case-upload.sh
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13355 [6.13.z] Test markers as test fields in polarion
  scripts/polarion-test-case-upload.sh
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13354 [6.12.z] Test markers as test fields in polarion
  scripts/polarion-test-case-upload.sh
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13358 [6.13.z] Bump pre-commit from 3.5.0 to 3.6.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13360 [6.12.z] Bump pre-commit from 3.5.0 to 3.6.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13361 [6.14.z] Bump pre-commit from 3.5.0 to 3.6.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13364 Fix AK update tests - org required
  tests/foreman/api/test_activationkey.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#13367 [6.15.z] Fix AK update tests - org required
  tests/foreman/api/test_activationkey.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13370 Fix missing api param in target_sat call in SyncPlan test
  tests/foreman/api/test_syncplan.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#13368 fixed api audit tests
  tests/foreman/api/test_audit.py
Labels: TestFailure, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13371 [6.15.z] Fix missing api param in target_sat call in SyncPlan test
  tests/foreman/api/test_syncplan.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13372 [6.14.z] Fix missing api param in target_sat call in SyncPlan test
  tests/foreman/api/test_syncplan.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13373 [6.13.z] Fix missing api param in target_sat call in SyncPlan test
  tests/foreman/api/test_syncplan.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13369 Automation for BZ 2119112 - subpaths field is mandatory while creating ACS in the UI
  tests/foreman/ui/test_acs.py
Labels: CherryPick, 6.14.z, 6.15.z

#13362 fixing the prt comment copy to cherry-pick branch
  .github/workflows/auto_cherry_pick.yml
Labels: High Priority, CherryPick, 6.13.z, 6.14.z, 6.15.z

#13359 [6.15.z] Bump pre-commit from 3.5.0 to 3.6.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13385 [6.15.z] Remove LCE option from register helper and assert in form test
  robottelo/hosts.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13365 Update yum repo for ACSes
  robottelo/constants/repos.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13082 Added SCA enabled manifest in activation key and removed duplicate fixture
  pytest_fixtures/component/activationkey.py
  tests/foreman/api/test_registration.py
  tests/foreman/cli/test_registration.py
  tests/foreman/ui/test_host.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13386 [6.14.z] Update yum repo for ACSes
  robottelo/constants/repos.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13390 [6.13.z] Added SCA enabled manifest in activation key and removed duplicate fixture
  pytest_fixtures/component/activationkey.py
  tests/foreman/api/test_registration.py
  tests/foreman/cli/test_registration.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13389 [6.15.z] Added SCA enabled manifest in activation key and removed duplicate fixture
  pytest_fixtures/component/activationkey.py
  tests/foreman/api/test_registration.py
  tests/foreman/cli/test_registration.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13388 [6.15.z] Update yum repo for ACSes
  robottelo/constants/repos.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13381 [6.15.z] Automation for BZ 2119112 - subpaths field is mandatory while creating ACS in the UI
  tests/foreman/ui/test_acs.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13380 [6.14.z] Automation for BZ 2119112 - subpaths field is mandatory while creating ACS in the UI
  tests/foreman/ui/test_acs.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13363 [6.14] added available_remote_execution_features apipath
  tests/foreman/endtoend/test_api_endtoend.py
Labels: TestFailure, No-CherryPick, 6.14.z

#13376 [6.15.z] fixed api audit tests
  tests/foreman/api/test_audit.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13377 [6.14.z] fixed api audit tests
  tests/foreman/api/test_audit.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13375 [6.13.z] fixed api audit tests
  tests/foreman/api/test_audit.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13374 [6.12.z] fixed api audit tests
  tests/foreman/api/test_audit.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13266 add automation coverage for BZ 2161993
  robottelo/constants/__init__.py
  tests/foreman/cli/test_repository.py
  tests/foreman/data/ant-7.7.7-1.noarch.rpm
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, Stream, 6.14.z, 6.15.z

#13394 [6.14.z] Using SCA enabled manifest in activation key
  pytest_fixtures/component/activationkey.py
  tests/foreman/api/test_registration.py
  tests/foreman/cli/test_registration.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#13395 [6.15.z] add automation coverage for BZ 2161993
  robottelo/constants/__init__.py
  tests/foreman/cli/test_repository.py
  tests/foreman/data/ant-7.7.7-1.noarch.rpm
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13397 [6.14.z] add automation coverage for BZ 2161993
  robottelo/constants/__init__.py
  tests/foreman/cli/test_repository.py
  tests/foreman/data/ant-7.7.7-1.noarch.rpm
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13378 Fixes for CV Tests
  tests/foreman/api/test_contentview.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13409 [Cherrypick]Test for disabling rh repository with basearch 6.14.z
  tests/foreman/cli/test_repositories.py
Labels: No-CherryPick, 6.14.z

#13410 [Cherrypick]Test for disabling rh repository with basearch 6.13.z
  tests/foreman/cli/test_repositories.py
Labels: No-CherryPick, 6.13.z

#13411 Bump EL8, EL9 versions in leapp upgrade test
  tests/foreman/cli/test_leapp_client.py
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13412 [Cherrypick][Repository Rewrite] Adding test for available_repositories endpoint
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, 6.14.z

#13413 [Cherrypick][Repository Rewrite] Adding test for available_repositories endpoint
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, 6.13.z

#13414 Test for available repo endpoint 6.12.z
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, 6.12.z

#13398 [6.14] bz1699188
  tests/foreman/api/test_ansible.py
Labels: CherryPick, 6.12.z, 6.13.z

#13418 [6.12.z] Bump EL8, EL9 versions in leapp upgrade test
  tests/foreman/cli/test_leapp_client.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13417 [6.15.z] Bump EL8, EL9 versions in leapp upgrade test
  tests/foreman/cli/test_leapp_client.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13406 cli location test fixes
  tests/foreman/cli/test_location.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13415 [6.13.z] Bump EL8, EL9 versions in leapp upgrade test
  tests/foreman/cli/test_leapp_client.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13423 [6.14.z] cli location test fixes
  tests/foreman/cli/test_location.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13422 [6.13.z] cli location test fixes
  tests/foreman/cli/test_location.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13424 [6.15.z] cli location test fixes
  tests/foreman/cli/test_location.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13431 [6.14.z] Fix libvirt/ec2 compute resource tests
  robottelo/host_helpers/cli_factory.py
  tests/foreman/cli/test_computeresource_libvirt.py
  tests/foreman/cli/test_location.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13429 [6.15.z] Fix libvirt/ec2 compute resource tests
  robottelo/host_helpers/cli_factory.py
  tests/foreman/cli/test_computeresource_libvirt.py
  tests/foreman/cli/test_location.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13416 [6.14.z] Bump EL8, EL9 versions in leapp upgrade test
  tests/foreman/cli/test_leapp_client.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13427 keyword argument server config required
  tests/foreman/api/test_subscription.py
Labels: TestFailure, Easy Fix :), No-CherryPick, 6.14.z

#13428 [6.12.z] Fix libvirt/ec2 compute resource tests
  robottelo/host_helpers/cli_factory.py
  tests/foreman/cli/test_computeresource_libvirt.py
  tests/foreman/cli/test_location.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13400 SAT-21433: Enable and sync rhel8_bos repo for rhc tests
  tests/foreman/ui/test_rhc.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13434 [6.15.z] SAT-21433: Enable and sync rhel8_bos repo for rhc tests
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13436 [6.13.z] SAT-21433: Enable and sync rhel8_bos repo for rhc tests
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13433 users and roles test fixes
  tests/foreman/api/test_permission.py
  tests/foreman/api/test_role.py
  tests/foreman/cli/test_role.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13437 [6.14.z] users and roles test fixes
  tests/foreman/api/test_permission.py
  tests/foreman/api/test_role.py
  tests/foreman/cli/test_role.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13442 Fix host-collections tests
  tests/foreman/cli/test_hostcollection.py
Labels: TestFailure, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13447 [6.14.z] Fix host-collections tests
  tests/foreman/cli/test_hostcollection.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13444 [6.13.z] Fix host-collections tests
  tests/foreman/cli/test_hostcollection.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13446 [6.12.z] Fix host-collections tests
  tests/foreman/cli/test_hostcollection.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13435 [6.14.z] SAT-21433: Enable and sync rhel8_bos repo for rhc tests
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13445 [6.15.z] Fix host-collections tests
  tests/foreman/cli/test_hostcollection.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13439 [6.15.z] users and roles test fixes
  tests/foreman/api/test_permission.py
  tests/foreman/api/test_role.py
  tests/foreman/cli/test_role.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13399 cli org test fixes
  tests/foreman/cli/test_organization.py
Labels: TestFailure, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13451 [6.15.z] cli org test fixes
  tests/foreman/cli/test_organization.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13452 [6.14.z] cli org test fixes
  tests/foreman/cli/test_organization.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13453 [6.13.z] cli org test fixes
  tests/foreman/cli/test_organization.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13162 [RFE] Check RHEL Lifecycle status in ContentHost UI
  tests/foreman/ui/test_contenthost.py
Labels: RFE, CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z

#12695 Add test coverage for provisioning with fips_enabled
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_provisioningtemplate.py
Labels: QETestCoverage, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#13454 [6.15.z] [RFE] Check RHEL Lifecycle status in ContentHost UI
  tests/foreman/ui/test_contenthost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13448 [6.15.z] [Comp-Eval] CLI::test_errata Refactor
  tests/foreman/cli/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13464 [6.14.z] CLI::Errata Refactor
  tests/foreman/cli/test_errata.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.14.z
