Repository SatelliteQE/robottelo, pull requests merged in 2023-10, with the labels that each got.

#12764 Missing content ID test
  tests/foreman/api/test_repository.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12784 [6.14.z] Missing content ID test
  tests/foreman/api/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12785 [6.13.z] Missing content ID test
  tests/foreman/api/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12724 Migrate katello-agent tests to REX
  robottelo/cli/factory.py
  robottelo/cli/rex_feature.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/destructive/test_katello_agent.py
Labels: CLI, No-CherryPick, Stream

#11927 First new CV UI Tests
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_contentview_old.py
Labels: CherryPick, 6.13.z, 6.14.z

#12693 Add test using verify checksum on non yum repo in hammer
  tests/foreman/cli/test_repository.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#12776 Add coverage for 1964037 installer cert regeneration
  robottelo/cli/base.py
  tests/foreman/destructive/test_installer.py
Labels: QETestCoverage, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12781 subscription page ui failure fix in robottelo tests
  tests/foreman/ui/test_subscription.py
Labels: UI, TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#12798 [6.12.z] Add customer coverage to health check
  tests/foreman/maintain/test_health.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#12797 [6.13.z] Add customer coverage to health check
  tests/foreman/maintain/test_health.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12802 [6.14.z] Add coverage for 1964037 installer cert regeneration
  robottelo/cli/base.py
  tests/foreman/destructive/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12790 [6.14.z] Bump broker[docker] from 0.4.0 to 0.4.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12806 [6.12.z] Add coverage for 1964037 installer cert regen
  robottelo/cli/base.py
  tests/foreman/destructive/test_installer.py
Labels: No-CherryPick, 6.12.z

#12805 [6.14.z] subscription page ui failure fix in robottelo tests
  tests/foreman/ui/test_subscription.py
Labels: No-CherryPick, 6.14.z

#12794 Flip KA upgrade tests to REX
  conftest.py
  pytest_fixtures/component/katello_agent.py
  tests/upgrades/test_client.py
Labels: Upgrades, No-CherryPick, Stream

#12792 [6.13.z] Bump broker[docker] from 0.4.0 to 0.4.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12791 [6.12.z] Bump broker[docker] from 0.4.0 to 0.4.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12803 [6.14.z] Add coverage for 2055790 to service enable disable
  tests/foreman/maintain/test_service.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12647 Add test for satellite-maintain's self updating ability
  tests/foreman/maintain/test_upgrade.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12807 [6.14.z] Bump redis from 5.0.0 to 5.0.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12808 [6.13.z] Bump redis from 5.0.0 to 5.0.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12809 [6.12.z] Bump redis from 5.0.0 to 5.0.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#12812 [6.14.z] Add test for satellite-maintain's self updating ability
  tests/foreman/maintain/test_upgrade.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12691 Remove stubbed FM case that is no longer needed
  tests/foreman/maintain/test_packages.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12800 [6.13.z] Add coverage for 1964037 installer cert regeneration
  robottelo/cli/base.py
  tests/foreman/destructive/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12467 Audit - Adding coverage for Discovery provisioning via CLI
  robottelo/cli/discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
Labels: QETestCoverage, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12821 [6.14.z] Bump deepdiff from 6.5.0 to 6.6.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12819 [6.13.z] Bump deepdiff from 6.5.0 to 6.6.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12820 [6.12.z] Bump deepdiff from 6.5.0 to 6.6.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12773 Update VMware CR tests
  conf/vmware.yaml.template
  conftest.py
  pytest_fixtures/component/provision_vmware.py
  robottelo/constants/__init__.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/longrun/test_provisioning_computeresource.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: CLI, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12826 [6.14.z] Audit - Adding coverage for Discovery provisioning via CLI
  robottelo/cli/discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12828 [6.13.z] Audit - Adding coverage for Discovery provisioning via CLI
  robottelo/cli/discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12817 Remove KA references from errata tests
  tests/foreman/api/test_errata.py
  tests/foreman/cli/test_errata.py
Labels: No-CherryPick, Stream

#12804 [6.13.z] Add coverage for 2055790 to service enable disable
  tests/foreman/maintain/test_service.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12831 [6.13.z] Fix capsule test by CVV sort
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12832 [6.12.z] Fix capsule test by CVV sort
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12835 [6.14.z] Update VMware CR tests
  conf/vmware.yaml.template
  conftest.py
  pytest_fixtures/component/provision_vmware.py
  robottelo/constants/__init__.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/longrun/test_provisioning_computeresource.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12813 Nailgun ssl cert verification
  conf/server.yaml.template
  robottelo/config/__init__.py
  robottelo/config/validators.py
  robottelo/hosts.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_subscription.py
  tests/foreman/api/test_user.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#12839 [6.12.z] Update VMware tests
  conf/vmware.yaml.template
  conftest.py
  pytest_fixtures/component/provision_vmware.py
  robottelo/constants/__init__.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/longrun/test_provisioning_computeresource.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, 6.12.z

#12843 [6.12.z] Nailgun ssl cert verification
  conf/server.yaml.template
  robottelo/config/__init__.py
  robottelo/config/validators.py
  robottelo/hosts.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_subscription.py
  tests/foreman/api/test_user.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12842 [6.13.z] Nailgun ssl cert verification
  conf/server.yaml.template
  robottelo/config/__init__.py
  robottelo/config/validators.py
  robottelo/hosts.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_subscription.py
  tests/foreman/api/test_user.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12841 [6.14.z] Nailgun ssl cert verification
  conf/server.yaml.template
  robottelo/config/__init__.py
  robottelo/config/validators.py
  robottelo/hosts.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_subscription.py
  tests/foreman/api/test_user.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12844 Change read to read_legacy_ui
  tests/foreman/ui/test_activationkey.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12706 Fixes for stream, 6.14.z; failure ErrataManagement in api:test_errata
  tests/foreman/api/test_errata.py
Labels: No-CherryPick, Stream

#12847 [6.14.z] Change read to read_legacy_ui
  tests/foreman/ui/test_activationkey.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12846 [6.13.z] Change read to read_legacy_ui
  tests/foreman/ui/test_activationkey.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12837 [6.13.z] Update VMware tests
  conf/vmware.yaml.template
  conftest.py
  pytest_fixtures/component/provision_vmware.py
  robottelo/constants/__init__.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/longrun/test_provisioning_computeresource.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, 6.13.z

#12849 Fix lce id option in host registration
  robottelo/hosts.py
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12850 Fixed test_positive_assign_http_proxy_to_products_repositories failure
  tests/foreman/ui/test_http_proxy.py
Labels: UI, Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, Stream, 6.14.z

#12810 Hosts: move from RHEL 7 to RHEL 8 for glob. registration
  tests/foreman/ui/test_host.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#12854 [6.13.z] Fix lce id option in host registration
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12853 [6.12.z] Fix lce id option in host registration
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#12852 [6.14.z] Fix lce id option in host registration
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12856 [6.14.z] Fixed test_positive_assign_http_proxy_to_products_repositories failure
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12855 [6.13.z] Fixed test_positive_assign_http_proxy_to_products_repositories failure
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12857 [6.12.z] Fixed test_positive_assign_http_proxy_to_products_repositories failure
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#12858 [6.14.z] Hosts: move from RHEL 7 to RHEL 8 for glob. registration
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12825 [6.12.z] Remove stubbed FM case that is no longer needed
  tests/foreman/maintain/test_packages.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#12824 [6.14.z] Remove stubbed FM case that is no longer needed
  tests/foreman/maintain/test_packages.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12823 [6.13.z] Remove stubbed FM case that is no longer needed
  tests/foreman/maintain/test_packages.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12859 update case component with correct name
  tests/upgrades/test_hostcontent.py
Labels: Easy Fix :), 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, Stream, 6.14.z

#12620 fixture support for virt-who config api : data_form deploy_type virtwho_config
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_esx_sca.py
  tests/foreman/virtwho/api/test_hyperv.py
  tests/foreman/virtwho/api/test_hyperv_sca.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_kubevirt_sca.py
  tests/foreman/virtwho/api/test_libvirt.py
  tests/foreman/virtwho/api/test_libvirt_sca.py
  tests/foreman/virtwho/api/test_nutanix.py
  tests/foreman/virtwho/api/test_nutanix_sca.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#12862 [6.12.z] update case component with correct name
  tests/upgrades/test_hostcontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#12861 [6.13.z] update case component with correct name
  tests/upgrades/test_hostcontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12860 [6.14.z] update case component with correct name
  tests/upgrades/test_hostcontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12863 [6.11.z] update case component with correct name
  tests/upgrades/test_hostcontent.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#12822 Optional pytest Vault login and code nitpicking
  robottelo/utils/vault.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#12865 [6.14.z] fixture support for virt-who config api : data_form deploy_type virtwho_config
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_esx_sca.py
  tests/foreman/virtwho/api/test_hyperv.py
  tests/foreman/virtwho/api/test_hyperv_sca.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_kubevirt_sca.py
  tests/foreman/virtwho/api/test_libvirt.py
  tests/foreman/virtwho/api/test_libvirt_sca.py
  tests/foreman/virtwho/api/test_nutanix.py
  tests/foreman/virtwho/api/test_nutanix_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12838 Fixing loadbalancer e2e test
  tests/foreman/destructive/test_capsule_loadbalancer.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12872 [6.14.z] Fixing loadbalancer e2e test
  tests/foreman/destructive/test_capsule_loadbalancer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12873 [6.13.z] Fixing loadbalancer e2e test
  tests/foreman/destructive/test_capsule_loadbalancer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12640 fixture support for virt-who config ui : data_form deploy_type virtwho_config
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_esx_sca.py
  tests/foreman/virtwho/ui/test_hyperv.py
  tests/foreman/virtwho/ui/test_hyperv_sca.py
  tests/foreman/virtwho/ui/test_kubevirt.py
  tests/foreman/virtwho/ui/test_kubevirt_sca.py
  tests/foreman/virtwho/ui/test_libvirt.py
  tests/foreman/virtwho/ui/test_libvirt_sca.py
  tests/foreman/virtwho/ui/test_nutanix.py
  tests/foreman/virtwho/ui/test_nutanix_sca.py
Labels: CherryPick, 6.13.z, 6.14.z

#12877 [6.14.z] fixture support for virt-who config ui : data_form deploy_type virtwho_config
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_esx_sca.py
  tests/foreman/virtwho/ui/test_hyperv.py
  tests/foreman/virtwho/ui/test_hyperv_sca.py
  tests/foreman/virtwho/ui/test_kubevirt.py
  tests/foreman/virtwho/ui/test_kubevirt_sca.py
  tests/foreman/virtwho/ui/test_libvirt.py
  tests/foreman/virtwho/ui/test_libvirt_sca.py
  tests/foreman/virtwho/ui/test_nutanix.py
  tests/foreman/virtwho/ui/test_nutanix_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12881 [6.13.z] Coverage for autoprovision and reboot of discovered host
  conftest.py
  pytest_fixtures/component/discovery.py
  tests/foreman/api/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12880 [6.12.z] Coverage for autoprovision and reboot of discovered host
  conftest.py
  pytest_fixtures/component/discovery.py
  tests/foreman/api/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#12851 Update to errata-stream fix, use up to date register method for rhel_contenthost
  robottelo/host_helpers/contenthost_mixins.py
  tests/foreman/api/test_errata.py
Labels: Easy Fix :), No-CherryPick, Stream

#12710 [Repository Rewrite] Upgrade test for large repo sync
  tests/upgrades/test_repository.py
Labels: Upgrades, CherryPick, 6.14.z

#12882 [6.14.z] [Repository Rewrite] Upgrade test for large repo sync
  tests/upgrades/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12883 Fix VMware tests
  robottelo/constants/__init__.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: TestFailure, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12885 [6.14.z] Fix VMware tests
  robottelo/constants/__init__.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12878 Validate testimony for upgrade tests
  Makefile
  tests/upgrades/test_activation_key.py
  tests/upgrades/test_bookmarks.py
  tests/upgrades/test_capsule.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_satellitesync.py
  tests/upgrades/test_syncplan.py
  tests/upgrades/test_usergroup.py
Labels: Upgrades, Framework Changes, CherryPick, 6.12.z, 6.13.z, 6.14.z

#12889 [6.14.z] Validate testimony for upgrade tests
  Makefile
  tests/upgrades/test_activation_key.py
  tests/upgrades/test_bookmarks.py
  tests/upgrades/test_capsule.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_satellitesync.py
  tests/upgrades/test_syncplan.py
  tests/upgrades/test_usergroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12891 [6.13.z] Validate testimony for upgrade tests
  Makefile
  tests/upgrades/test_activation_key.py
  tests/upgrades/test_bookmarks.py
  tests/upgrades/test_capsule.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_satellitesync.py
  tests/upgrades/test_syncplan.py
  tests/upgrades/test_usergroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12890 [6.12.z] Validate testimony for upgrade tests
  Makefile
  tests/upgrades/test_activation_key.py
  tests/upgrades/test_bookmarks.py
  tests/upgrades/test_capsule.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_satellitesync.py
  tests/upgrades/test_syncplan.py
  tests/upgrades/test_usergroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12322 [Repository Rewrite] Added test for publishing invalid repository
  tests/foreman/cli/test_repositories.py
Labels: CherryPick, 6.13.z, 6.14.z

#12893 Fix Puppet tests
  robottelo/hosts.py
Labels: TestFailure, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12898 [6.14.z] Fix Puppet tests
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12899 [6.12.z] Fix Puppet tests
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#12902 Fix typo for organization field in global registration
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_rhcloud_insights.py
Labels: Easy Fix :), CherryPick, 6.12.z, 6.13.z, 6.14.z

#12903 [6.14.z] Fix typo for organization field in global registration
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_rhcloud_insights.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12904 [6.12.z] Fix typo for organization field in global registration
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_rhcloud_insights.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12905 [6.13.z] Fix typo for organization field in global registration
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_rhcloud_insights.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12884 Add gitleaks to pre-commit hooks
  .pre-commit-config.yaml
Labels: No-CherryPick

#12912 [6.14.z] Bump pre-commit from 3.4.0 to 3.5.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12911 [6.13.z] Bump pre-commit from 3.4.0 to 3.5.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12845 Fix packages status
  robottelo/cli/sm_packages.py
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12916 [6.12.z] Fix packages status
  robottelo/cli/sm_packages.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#12917 [6.14.z] Fix packages status
  robottelo/cli/sm_packages.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12888 [Repository Rewrite] Adding test for available_repositories endpoint
  tests/foreman/api/test_repositories.py
Labels: API, CherryPick, 6.12.z, 6.13.z, 6.14.z

#12919 Adding provisioning params to installer
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Stream

#12777 [Repository Rewrite] Test for disabling rh repository with basearch
  tests/foreman/cli/test_repositories.py
Labels: CherryPick, 6.13.z, 6.14.z

#12915 [6.13.z] Fix packages status
  robottelo/cli/sm_packages.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12914 Fixing Discovery tests
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
Labels: CLI, API, CherryPick, 6.12.z, 6.13.z, 6.14.z

#12814 Use sAMAccountName
  tests/foreman/cli/test_ldapauthsource.py
Labels: CherryPick, 6.13.z, 6.14.z

#12935 [6.12.z] Bump pytest-reportportal from 5.2.2 to 5.3.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12933 [6.13.z] Bump pytest-reportportal from 5.2.2 to 5.3.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12934 [6.14.z] Bump pytest-reportportal from 5.2.2 to 5.3.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12929 [6.14.z] Use sAMAccountName
  tests/foreman/cli/test_ldapauthsource.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12930 [6.13.z] Use sAMAccountName
  tests/foreman/cli/test_ldapauthsource.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12901 Add automation for BZ:1994654/SAT-4845
  tests/foreman/ui/test_host.py
Labels: QETestCoverage, No-CherryPick, Stream

#12938 [6.14.z] Bump deepdiff from 6.6.0 to 6.6.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12936 [6.13.z] Bump deepdiff from 6.6.0 to 6.6.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12937 [6.12.z] Bump deepdiff from 6.6.0 to 6.6.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12927 [6.14.z] Fixing Discovery tests
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12918 Fix maintain CLI caching class attributes
  robottelo/cli/sm_packages.py
Labels: Bug, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12942 [6.13.z] Fix maintain CLI caching class attributes
  robottelo/cli/sm_packages.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12941 [6.14.z] Fix maintain CLI caching class attributes
  robottelo/cli/sm_packages.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12940 [6.12.z] Fix maintain CLI caching class attributes
  robottelo/cli/sm_packages.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#12949 [6.13.z] Bump pytest-mock from 3.11.1 to 3.12.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12950 [6.12.z] Bump pytest-mock from 3.11.1 to 3.12.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12951 [6.14.z] Bump pytest-mock from 3.11.1 to 3.12.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12944 [6.12.z] Cherrypick test multiple orgs with same repo
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, 6.12.z

#12848 Fix Container Image Tag test
  tests/foreman/ui/test_containerimagetag.py
Labels: UI, CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#12886 [6.13.z] Fix VMware tests
  robottelo/constants/__init__.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12887 [6.12.z] Fix VMware tests
  robottelo/constants/__init__.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#12867 [6.14.z] Optional pytest Vault login and code nitpicking
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12892 Remove katello-agent from helpers and mixins
  pytest_fixtures/component/repository.py
  robottelo/host_helpers/repository_mixins.py
  robottelo/hosts.py
  testimony.yaml
  tests/foreman/api/test_errata.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_reporttemplates.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/destructive/test_contenthost.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_hostcollection.py
  tests/foreman/ui/test_subscription.py
Labels: No-CherryPick, Stream

#12876 [6.13.z] fixture support for virt-who config ui : data_form deploy_type virtwho_config
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_esx_sca.py
  tests/foreman/virtwho/ui/test_hyperv.py
  tests/foreman/virtwho/ui/test_hyperv_sca.py
  tests/foreman/virtwho/ui/test_kubevirt.py
  tests/foreman/virtwho/ui/test_kubevirt_sca.py
  tests/foreman/virtwho/ui/test_libvirt.py
  tests/foreman/virtwho/ui/test_libvirt_sca.py
  tests/foreman/virtwho/ui/test_nutanix.py
  tests/foreman/virtwho/ui/test_nutanix_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12897 [Upgrades] Add upgrade tests for ProvisioningTemplates
  pytest_fixtures/component/domain.py
  tests/upgrades/test_provisioningtemplate.py
Labels: QETestCoverage, Upgrades, CherryPick, 6.12.z, 6.13.z, 6.14.z

#12957 [6.14.z] Acs test coverage
  pytest_fixtures/component/taxonomy.py
  robottelo/constants/__init__.py
  tests/foreman/ui/test_acs.py
Labels: UI, No-CherryPick

#12868 [6.13.z] Optional pytest Vault login and code nitpicking
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12869 [6.12.z] Optional pytest Vault login and code nitpicking
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12967 [6.14.z] Bump cryptography from 41.0.4 to 41.0.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12968 [6.13.z] Bump cryptography from 41.0.4 to 41.0.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12969 [6.12.z] Bump cryptography from 41.0.4 to 41.0.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12971 [6.12.z] Bump pytest from 7.4.2 to 7.4.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12972 [6.13.z] Bump pytest from 7.4.2 to 7.4.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12909 Fix vault makescripts with capture output
  pytest_plugins/auto_vault.py
  robottelo/utils/vault.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#12977 [6.14.z] Fix vault makescripts with capture output
  pytest_plugins/auto_vault.py
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12976 [6.12.z] Fix vault makescripts with capture output
  pytest_plugins/auto_vault.py
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12975 [6.13.z] Fix vault makescripts with capture output
  pytest_plugins/auto_vault.py
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12923 Fixture collection splitting restructured
  pytest_plugins/fixture_collection.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#12980 [6.13.z] Fixture collection splitting restructured
  pytest_plugins/fixture_collection.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12979 [6.12.z] Fixture collection splitting restructured
  pytest_plugins/fixture_collection.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12974 Remove test_positive_backup_restore_snapshot stub
  tests/foreman/maintain/test_backup_restore.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12973 Add workaround for cpu_mode for EL9 Libvirt tests
  tests/foreman/cli/test_computeresource_libvirt.py
Labels: TestFailure, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12954 [6.14.z] [Upgrades] Add upgrade tests for ProvisioningTemplates
  pytest_fixtures/component/domain.py
  tests/upgrades/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12955 [6.13.z] [Upgrades] Add upgrade tests for ProvisioningTemplates
  pytest_fixtures/component/domain.py
  tests/upgrades/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12953 [6.12.z] [Upgrades] Add upgrade tests for ProvisioningTemplates
  pytest_fixtures/component/domain.py
  tests/upgrades/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12985 [6.14.z] Add workaround for cpu_mode for EL9 Libvirt tests
  tests/foreman/cli/test_computeresource_libvirt.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z
