Repository SatelliteQE/robottelo, pull requests merged in 2023-01, with the labels that each got.

#10390 Parameterizing Azure Test cases
  pytest_fixtures/component/provision_azure.py
  robottelo/api/utils.py
  robottelo/host_helpers/api_factory.py
  tests/foreman/api/test_computeresource_azurerm.py
  tests/foreman/cli/test_computeresource_azurerm.py
  tests/foreman/ui/test_computeresource_azurerm.py
Labels: CLI, UI, API, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z

#10474 [6.13.z] Parameterizing Azure Test cases
  pytest_fixtures/component/provision_azure.py
  robottelo/api/utils.py
  robottelo/host_helpers/api_factory.py
  tests/foreman/api/test_computeresource_azurerm.py
  tests/foreman/cli/test_computeresource_azurerm.py
  tests/foreman/ui/test_computeresource_azurerm.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10473 [6.12.z] Parameterizing Azure Test cases
  pytest_fixtures/component/provision_azure.py
  robottelo/api/utils.py
  robottelo/host_helpers/api_factory.py
  tests/foreman/api/test_computeresource_azurerm.py
  tests/foreman/cli/test_computeresource_azurerm.py
  tests/foreman/ui/test_computeresource_azurerm.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#10475 added the branch ignore in the GHA
  .github/workflows/automerge.yaml
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#10476 [6.11.z] added the branch ignore in the GHA
  .github/workflows/automerge.yaml
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#10479 [6.13.z] Set correct branch for GHA
  .github/workflows/merge_to_master.yml
Labels: No-CherryPick

#10480 [6.12.z] Set correct branch for GHA
  .github/workflows/merge_to_master.yml
Labels: No-CherryPick

#10477 [6.12.z] added the branch ignore in the GHA
  .github/workflows/automerge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#10478 [6.13.z] added the branch ignore in the GHA
  .github/workflows/automerge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#10484 [6.13.z] Fix for filter creation with ak and search criteria
  tests/foreman/ui/test_activationkey.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#10483 [6.12.z] Fix for filter creation with ak and search criteria
  tests/foreman/ui/test_activationkey.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#10487 [6.12.z] Bump sphinx from 5.3.0 to 6.0.0
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#10486 [6.13.z] Bump sphinx from 5.3.0 to 6.0.0
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#10490 [6.13.z] Bump actions/stale from 6 to 7
  .github/workflows/stale.yml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10442 Extend test coverage for BZ#2148813
  tests/foreman/api/test_contentmanagement.py
Labels: CherryPick, 6.12.z, 6.13.z

#10499 [6.13.z] Extend test coverage for BZ#2148813
  tests/foreman/api/test_contentmanagement.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#10503 Attempt to resolve check annotation error
  tests/robottelo/test_func_shared.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#10507 [6.11.z] Attempt to resolve check annotation error
  tests/robottelo/test_func_shared.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10506 [6.13.z] Attempt to resolve check annotation error
  tests/robottelo/test_func_shared.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#10505 [6.12.z] Attempt to resolve check annotation error
  tests/robottelo/test_func_shared.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#10493 CI checks with Python 3.11, removed 3.8
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_request.yml
  setup.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#10514 [6.12.z] Cherry pick of #10493 - CI checks with Python 3.11, removed 3.8
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_request.yml
  setup.py
Labels: dependencies, No-CherryPick, 6.12.z, Failed_AutoCherryPick

#10513 [6.11.z] Cherry pick of #10493 - CI checks with Python 3.11, removed 3.8
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_request.yml
  setup.py
Labels: dependencies, 6.11.z, No-CherryPick, Failed_AutoCherryPick

#10511 [6.12.z] Bump cryptography from 38.0.4 to 39.0.0
  requirements.txt
Labels: dependencies, No-CherryPick, 6.12.z, Failed_AutoCherryPick

#10512 [6.13.z] Cherry pick of #10472 - Bump cryptography from 38.0.4 to 39.0.0
  requirements.txt
Labels: dependencies, No-CherryPick, Failed_AutoCherryPick, 6.13.z

#10517 [6.12.z] Bump deepdiff from 6.2.2 to 6.2.3
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#10516 [6.13.z] Bump deepdiff from 6.2.2 to 6.2.3
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10485 Modify entitlement manifester fixtures for 6.13
  pytest_fixtures/component/taxonomy.py
Labels: CherryPick, 6.13.z

#10523 [6.12.z] Bump mheap/github-action-required-labels from 2 to 3
  .github/workflows/required_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#10524 [6.13.z] Bump mheap/github-action-required-labels from 2 to 3
  .github/workflows/required_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10519 [6.12.z] Bump redis from 4.4.0 to 4.4.2
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#10520 [6.13.z] Bump redis from 4.4.0 to 4.4.2
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10521 [6.12.z] Bump sphinx from 6.0.0 to 6.1.3
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#10522 [6.13.z] Bump sphinx from 6.0.0 to 6.1.3
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10528 [6.12.z] Bump broker[docker] from 0.2.9 to 0.2.10
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#10529 [6.13.z] Bump broker[docker] from 0.2.9 to 0.2.10
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10530 [6.13.z] Bump requests from 2.28.1 to 2.28.2
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10531 [6.12.z] Bump requests from 2.28.1 to 2.28.2
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#10343 [6.11.z] Implementing PXE-less Discovery test
  pytest_fixtures/component/provision_pxe.py
  pytest_fixtures/core/broker.py
  tests/foreman/api/test_discoveredhost.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10525 persistent ansible changes
  tests/foreman/cli/test_ansible.py
  tests/foreman/destructive/test_ansible.py
Labels: No-CherryPick, 6.13.z

#10404 change how client repo is sourced in rex tests
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, 6.13.z

#10500 added the check to wait for PRT status using status API
  .github/workflows/automerge.yaml
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#10537 [6.11.z] added the check to wait for PRT status using status API
  .github/workflows/automerge.yaml
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#10538 [6.12.z] added the check to wait for PRT status using status API
  .github/workflows/automerge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#10539 [6.13.z] added the check to wait for PRT status using status API
  .github/workflows/automerge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#10535 [6.13.z] change how client repo is sourced in rex tests
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#10536 [6.13.z Cherrypick] Persistent ansible.cfg change
  tests/foreman/cli/test_ansible.py
  tests/foreman/destructive/test_ansible.py
Labels: No-CherryPick, 6.13.z

#10465 Add coverage for ansible config report
  tests/foreman/ui/test_ansible.py
Labels: UI, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z

#10497 Ansible_Job api test coverage [e2e]
  tests/foreman/api/test_ansible.py
Labels: API, QETestCoverage, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z

#10549 patch to restart postfix.service
  tests/foreman/ui/test_settings.py
Labels: CherryPick, 6.12.z, 6.13.z

#10559 [6.13.z] patch to restart postfix.service
  tests/foreman/ui/test_settings.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#10482 update repo_options fixture-create a product if not exist
  tests/foreman/api/test_repository.py
Labels: No-CherryPick, 6.12.z

#10563 [6.13z] Bump broker from 0.2.10 to 0.2.11
  requirements.txt
Labels: 6.10.z, 6.11.z, CherryPick, 6.12.z

#10567 [6.12.z] [6.13z] Bump broker from 0.2.10 to 0.2.11
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#10568 [6.11.z] Bump broker from 0.2.10 to 0.2.11
  requirements.txt
Labels: 6.11.z, No-CherryPick

#10558 replacing more cleaner way to handle the index error
  .github/workflows/automerge.yaml
Labels: 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z

#10560 [6.12.z] patch to restart postfix.service
  tests/foreman/ui/test_settings.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#10554 Revert to checking for type bytes in upload_manifest
  robottelo/host_helpers/satellite_mixins.py
Labels: No-CherryPick

#10581 [6.13.z] Update broker to 0.2.12
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10580 [6.12.z] Update broker to 0.2.12
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#10574 [6.12.z] replacing more cleaner way to handle the index error
  .github/workflows/automerge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#10573 [6.13.z] replacing more cleaner way to handle the index error
  .github/workflows/automerge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10585 [6.13.z] Bump pytest from 7.2.0 to 7.2.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10586 [6.12.z] Bump pytest from 7.2.0 to 7.2.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#10583 [6.13.z] Bump sphinx-autoapi from 2.0.0 to 2.0.1
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10582 [6.12.z] Bump sphinx-autoapi from 2.0.0 to 2.0.1
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#10572 [6.11.z] replacing more cleaner way to handle the index error
  .github/workflows/automerge.yaml
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#10571 Removing email and project as a part of new GCE feature plugin
  pytest_fixtures/component/provision_gce.py
  tests/foreman/api/test_computeresource_gce.py
Labels: API, Easy Fix :), CherryPick, 6.13.z

#10590 [6.13.z] Added a skip marker for failing tests of fact component
  tests/foreman/cli/test_fact.py
Labels: Easy Fix :), No-CherryPick, Auto_Cherry_Picked, 6.13.z

#10587 [6.13.z] Bump pre-commit from 2.21.0 to 3.0.2
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#10588 [6.12.z] Bump pre-commit from 2.21.0 to 3.0.2
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#10564 Add coverage for provisioning test
  pytest_fixtures/component/provision_pxe.py
  robottelo/constants/__init__.py
  tests/foreman/api/test_contentmanagement.py
  tests/foreman/api/test_provisioning.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z

#10594 Allow uploading cloned and manifester manifests
  robottelo/host_helpers/satellite_mixins.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#10601 [6.13.z] Allow uploading cloned and manifester manifests
  robottelo/host_helpers/satellite_mixins.py
Labels: Easy Fix :), No-CherryPick, Auto_Cherry_Picked, 6.13.z

#10602 [6.12.z] Allow uploading cloned and manifester manifests
  robottelo/host_helpers/satellite_mixins.py
Labels: Easy Fix :), No-CherryPick, Auto_Cherry_Picked, 6.12.z
