Repository SatelliteQE/robottelo, pull requests merged in 2023-07, with the labels that each got.

#11795 [6.14.z] Bump pytest-reportportal from 5.1.9 to 5.2.0
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11794 [6.13.z] Bump pytest-reportportal from 5.1.9 to 5.2.0
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11793 [6.12.z] Bump pytest-reportportal from 5.1.9 to 5.2.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11792 [6.11.z] Bump pytest-reportportal from 5.1.9 to 5.2.0
  requirements.txt
Labels: dependencies, 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11796 handle the condition for dependancy has brackets []
  .github/workflows/dependency_merge.yml
Labels: No-CherryPick

#11799 katello_host_tools_host fixture fix
  pytest_fixtures/core/contenthosts.py
  tests/foreman/cli/test_host.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11801 [6.13.z] katello_host_tools_host fixture fix
  pytest_fixtures/core/contenthosts.py
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11802 [6.14.z] katello_host_tools_host fixture fix
  pytest_fixtures/core/contenthosts.py
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11786 rex_contenthost now using global registration
  pytest_fixtures/core/contenthosts.py
Labels: CherryPick, 6.13.z, 6.14.z

#11797 Add test for redis type foreman-rails-cache-store
  tests/foreman/installer/test_installer.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#11633 [RFE] test Installable Errata Report Template
  tests/foreman/api/test_reporttemplates.py
Labels: RFE, CherryPick, 6.14.z

#11805 [6.14.z] Add test for redis type foreman-rails-cache-store
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11803 [6.13.z] rex_contenthost now using global registration
  pytest_fixtures/core/contenthosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11760 [6.12.z] Add test for the Capsule sync deadlock issue
  conf/capsule.yaml.template
  conf/flavors.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
  robottelo/host_helpers/api_factory.py
  tests/foreman/destructive/test_capsulecontent.py
Labels: No-CherryPick, 6.12.z, Failed_AutoCherryPick

#11784 [6.14.z] virtwho UI cases to support for Content Host Legacy UI and parametrize to consolidate multiple cases with duplicated steps into one
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_hyperv.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_libvirt.py
  tests/foreman/virtwho/api/test_nutanix.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_esx_sca.py
  tests/foreman/virtwho/cli/test_hyperv.py
  tests/foreman/virtwho/cli/test_hyperv_sca.py
  tests/foreman/virtwho/cli/test_kubevirt.py
  tests/foreman/virtwho/cli/test_kubevirt_sca.py
  tests/foreman/virtwho/cli/test_libvirt.py
  tests/foreman/virtwho/cli/test_libvirt_sca.py
  tests/foreman/virtwho/cli/test_nutanix.py
  tests/foreman/virtwho/cli/test_nutanix_sca.py
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_hyperv.py
  tests/foreman/virtwho/ui/test_kubevirt.py
  tests/foreman/virtwho/ui/test_libvirt.py
  tests/foreman/virtwho/ui/test_nutanix.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11811 update checktime format for contenthost
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: Easy Fix :), CherryPick, 6.13.z, 6.14.z

#11809 virtwho-config:Update whitelist&blacklist
  tests/foreman/virtwho/api/test_esx_sca.py
Labels: Easy Fix :), CherryPick, 6.13.z, 6.14.z

#11812 add Legacy content UI support for nutanix prism central & ahv option modification
  tests/foreman/virtwho/ui/test_nutanix.py
Labels: CherryPick, 6.13.z, 6.14.z

#11814 [6.14.z] update checktime format for contenthost
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11815 [6.13.z] update checktime format for contenthost
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11816 [6.14.z] virtwho-config:Update whitelist&blacklist
  tests/foreman/virtwho/api/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11817 [6.13.z] virtwho-config:Update whitelist&blacklist
  tests/foreman/virtwho/api/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11819 [6.14.z] add Legacy content UI support for nutanix prism central & ahv option modification
  tests/foreman/virtwho/ui/test_nutanix.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11818 [6.13.z] add Legacy content UI support for nutanix prism central & ahv option modification
  tests/foreman/virtwho/ui/test_nutanix.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11729 [6.14 RFE] Upgrade test for enabled repos in sca
  tests/upgrades/test_repository.py
Labels: RFE, Upgrades, CherryPick, 6.14.z

#11380 [6.14 RFE] Custom products disabled by default
  pytest_fixtures/component/repository.py
  tests/foreman/cli/test_repositories.py
  tests/foreman/ui/test_repositories.py
Labels: RFE, CherryPick, 6.14.z

#11610 [6.14 RFE] added test for overriding custom products
  tests/foreman/ui/test_repositories.py
Labels: RFE, CherryPick, 6.14.z

#11821 [6.14.z] [6.14 RFE] Upgrade test for enabled repos in sca
  tests/upgrades/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11572 Tweaks for the Satellite version properties
  pytest_fixtures/component/provision_pxe.py
  robottelo/hosts.py
  tests/foreman/cli/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#11798 fixes in rex packgage job tests
  tests/foreman/cli/test_remoteexecution.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11827 [6.13.z] fixes in rex packgage job tests
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11717 [6.13.z RFE] Added sca override test for Hosts
  pytest_fixtures/component/repository.py
  tests/foreman/ui/test_repositories.py
Labels: RFE, QETestCoverage, No-CherryPick, 6.13.z

#11829 [6.11.z] Bump deepdiff from 6.3.0 to 6.3.1
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#11825 [6.14.z] Tweaks for the Satellite version properties
  pytest_fixtures/component/provision_pxe.py
  robottelo/hosts.py
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11748 Test exercising new Virtualization card
  conf/vmware.yaml.template
  tests/foreman/ui/test_computeresource_vmware.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#11834 [6.14.z] Test exercising new Virtualization card
  conf/vmware.yaml.template
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11785 [6.13.z] virtwho UI cases to support for Content Host Legacy UI and parametrize to consolidate multiple cases with duplicated steps into one
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_hyperv.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_libvirt.py
  tests/foreman/virtwho/api/test_nutanix.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_esx_sca.py
  tests/foreman/virtwho/cli/test_hyperv.py
  tests/foreman/virtwho/cli/test_hyperv_sca.py
  tests/foreman/virtwho/cli/test_kubevirt.py
  tests/foreman/virtwho/cli/test_kubevirt_sca.py
  tests/foreman/virtwho/cli/test_libvirt.py
  tests/foreman/virtwho/cli/test_libvirt_sca.py
  tests/foreman/virtwho/cli/test_nutanix.py
  tests/foreman/virtwho/cli/test_nutanix_sca.py
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_hyperv.py
  tests/foreman/virtwho/ui/test_kubevirt.py
  tests/foreman/virtwho/ui/test_libvirt.py
  tests/foreman/virtwho/ui/test_nutanix.py
Labels: CherryPick, 6.13.z

#11836 [6.14.Z] - Support the --local-files oscap argument
  robottelo/hosts.py
  tests/foreman/longrun/test_oscap.py
Labels: RFE, High Priority, QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z

#11842 [6.11.z] Bump cryptography from 41.0.1 to 41.0.2
  requirements.txt
Labels: 6.11.z, No-CherryPick

#11837 [6.13.z] [6.14.Z] - Support the --local-files oscap argument
  robottelo/hosts.py
  tests/foreman/longrun/test_oscap.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11843 Test fixes for Ansible
  tests/foreman/ui/test_ansible.py
Labels: UI, TestFailure, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11845 [6.14.z] Test fixes for Ansible
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11844 [6.13.z] Test fixes for Ansible
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11828 [6.14.z] fixes in rex packgage job tests
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11766 [Component Audit][Part1]Modify/Delete deprecated registration method
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_registration.py
Labels: 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11850 [6.14.z] [RFE 6.14.z]Added test for overriding custom products 6.14.z
  tests/foreman/ui/test_repositories.py
Labels: RFE, No-CherryPick, 6.14.z

#11848 [6.14.z] [Component Audit][Part1]Modify/Delete deprecated registration method
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11849 [6.13.z] [Component Audit][Part1]Modify/Delete deprecated registration method
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11851 Fix remote db tests
  pytest_fixtures/component/maintain.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11831 Component audit - Modify/Delete CLI OS tests
  robottelo/cli/factory.py
  robottelo/host_helpers/cli_factory.py
  tests/foreman/cli/test_operatingsystem.py
Labels: CLI, CherryPick, 6.12.z, 6.13.z, 6.14.z

#11852 [6.13.z] Fix remote db tests
  pytest_fixtures/component/maintain.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11853 [6.14.z] Fix remote db tests
  pytest_fixtures/component/maintain.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11858 cs tag added for repos test
  tests/foreman/cli/test_repositories.py
Labels: Documentation, Easy Fix :), CherryPick, 6.14.z

#11855 [6.14.z] Component audit - Modify/Delete CLI OS tests
  robottelo/cli/factory.py
  robottelo/host_helpers/cli_factory.py
  tests/foreman/cli/test_operatingsystem.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11856 [6.13.z] Component audit - Modify/Delete CLI OS tests
  robottelo/cli/factory.py
  robottelo/host_helpers/cli_factory.py
  tests/foreman/cli/test_operatingsystem.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11857 [6.12.z] Component audit - Modify/Delete CLI OS tests
  robottelo/cli/factory.py
  robottelo/host_helpers/cli_factory.py
  tests/foreman/cli/test_operatingsystem.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11863 [6.14.z] cs tag added for repos test
  tests/foreman/cli/test_repositories.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11395 Add api/test_rhc.py to test RHCloud Cloud Connector Nailgun support
  tests/foreman/api/test_rhc.py
Labels: API, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11833 [Component Audit] Provisioning templates component refactor
  tests/foreman/api/test_provisioningtemplate.py
  tests/foreman/api/test_template_combination.py
  tests/foreman/cli/test_provisioningtemplate.py
  tests/foreman/ui/test_provisioningtemplate.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11873 [6.14.z] [Component Audit] Provisioning templates component refactor
  tests/foreman/api/test_provisioningtemplate.py
  tests/foreman/api/test_template_combination.py
  tests/foreman/cli/test_provisioningtemplate.py
  tests/foreman/ui/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11874 [6.13.z] [Component Audit] Provisioning templates component refactor
  tests/foreman/api/test_provisioningtemplate.py
  tests/foreman/api/test_template_combination.py
  tests/foreman/cli/test_provisioningtemplate.py
  tests/foreman/ui/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11870 [6.12.z] Add api/test_rhc.py to test RHCloud Cloud Connector Nailgun support
  tests/foreman/api/test_rhc.py
Labels: No-CherryPick

#11869 [6.13.z] Add api/test_rhc.py to test RHCloud Cloud Connector Nailgun support
  tests/foreman/api/test_rhc.py
Labels: No-CherryPick

#11868 [6.14.z] Add api/test_rhc.py to test RHCloud Cloud Connector Nailgun support
  tests/foreman/api/test_rhc.py
Labels: No-CherryPick

#11872 delete policies which are no longer needed
  tests/foreman/cli/test_oscap.py
Labels: TestFailure, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11877 [6.13.z] delete policies which are no longer needed
  tests/foreman/cli/test_oscap.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11882 [6.14.z] Fix the indent of `test_positive_allow_reregistration_when_dmi_uuid_changed`
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11884 [6.13.z] Fix the indent of `test_positive_allow_reregistration_when_dmi_uuid_changed`
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11881 [6.12.z] Fix the indent of `test_positive_allow_reregistration_when_dmi_uuid_changed`
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11886 Remove e2e flag from failing UI test, and apply it to 2 api tests
  tests/foreman/api/test_contentview.py
  tests/foreman/ui/test_contentview.py
Labels: CherryPick, 6.13.z, 6.14.z

#11892 skip-if removed from e2e tests
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#11897 audit_log update event, skip on bz
  tests/foreman/ui/test_audit.py
Labels: CherryPick, 6.14.z

#11878 Deprecate install_katello_ca method in favor of the register method
  robottelo/host_helpers/capsule_mixins.py
  robottelo/hosts.py
Labels: No-CherryPick

#11898 [6.14.z] skip-if removed from e2e tests
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11899 [6.14.z] audit_log update event, skip on bz
  tests/foreman/ui/test_audit.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11895 [6.14.z] Remove e2e flag from failing UI test, and apply it to 2 api tests
  tests/foreman/api/test_contentview.py
  tests/foreman/ui/test_contentview.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11891 [6.11.z] Bump dynaconf[vault] from 3.1.12 to 3.2.0
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11894 Ansible test fixes for selecting only the used role in the test case
  tests/foreman/ui/test_ansible.py
Labels: TestFailure, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11902 [6.13.z] Ansible test fixes for selecting only the used role in the test case
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11901 [6.14.z] Ansible test fixes for selecting only the used role in the test case
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11826 Component audit - Modify/Delete API OS tests
  tests/foreman/api/test_operatingsystem.py
  tests/foreman/api/test_provisioning.py
Labels: API, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11910 Fix remote db tests failing because of session_capsule_configured
  pytest_fixtures/component/maintain.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11912 [6.14.z] Fix remote db tests failing because of session_capsule_configured
  pytest_fixtures/component/maintain.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11911 [6.13.z] Fix remote db tests failing because of session_capsule_configured
  pytest_fixtures/component/maintain.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11913 [6.12.z] Fix remote db tests failing because of session_capsule_configured
  pytest_fixtures/component/maintain.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11904 [6.14.z] Component audit - Modify/Delete API OS tests
  tests/foreman/api/test_operatingsystem.py
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11906 [6.13.z] Component audit - Modify/Delete API OS tests
  tests/foreman/api/test_operatingsystem.py
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11905 [6.12.z] Component audit - Modify/Delete API OS tests
  tests/foreman/api/test_operatingsystem.py
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11769 [6.14.z] Add --f-p-c-pulcpore-hide-guarded-distributions option
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#11918 [6.14.z] Bump pyyaml from 6.0 to 6.0.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11919 [6.12.z] Bump pyyaml from 6.0 to 6.0.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11922 [6.13.z] Bump wrapanapi from 3.5.15 to 3.5.17
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11924 [6.14.z] Bump wrapanapi from 3.5.15 to 3.5.17
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11925 [6.11.z] Bump wrapanapi from 3.5.15 to 3.5.17
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11923 [6.12.z] Bump wrapanapi from 3.5.15 to 3.5.17
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11933 Cherrypick for - Moving the ansible_roles_import test_case to destructive
  tests/foreman/destructive/test_ansible.py
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, 6.12.z

#11930 [6.14.z] Bump pytest-reportportal from 5.2.0 to 5.2.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11932 [6.12.z] Bump pytest-reportportal from 5.2.0 to 5.2.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11931 [6.11.z] Bump pytest-reportportal from 5.2.0 to 5.2.1
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11935 GHA for T2 only reviews
  .github/workflows/t2_reviews.yaml
Labels: No-CherryPick

#11428 Update robottelo image when there's change in Airgun/Nailgun repo
  .github/workflows/merge_to_master.yml
  .github/workflows/update_robottelo_image.yml
Labels: 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#11950 Update robottelo image when there's change in Airgun/Nailgun repo (#11428)
  .github/workflows/merge_to_master.yml
  .github/workflows/update_robottelo_image.yml
Labels: 6.11.z, No-CherryPick

#11947 Update robottelo image when there's change in Airgun/Nailgun repo (#11428)
  .github/workflows/merge_to_master.yml
  .github/workflows/update_robottelo_image.yml
Labels: No-CherryPick, 6.14.z

#11948 Update robottelo image when there's change in Airgun/Nailgun repo (#11428)
  .github/workflows/merge_to_master.yml
  .github/workflows/update_robottelo_image.yml
Labels: No-CherryPick, 6.13.z

#11949 Update robottelo image when there's change in Airgun/Nailgun repo (#11428)
  .github/workflows/merge_to_master.yml
  .github/workflows/update_robottelo_image.yml
Labels: No-CherryPick, 6.12.z

#11939 [6.11.z] Add closed loop BZ#2149030 for Provisioning Templates
  tests/foreman/api/test_provisioningtemplate.py
Labels: API, QETestCoverage, 6.11.z, No-CherryPick

#11941 Fix find-the-parent-prt-comment in GHA
  .github/workflows/auto_cherry_pick.yml
Labels: Easy Fix :), No-CherryPick

#11953 Remove Python 3.9 support from robottelo
  .github/workflows/pull_request.yml
  setup.py
Labels: Framework Changes, 6.11.z, CherryPick, 6.12.z, 6.13.z, 6.14.z

#11954 [6.14.z] Remove Python 3.9 support from robottelo
  .github/workflows/pull_request.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11957 [6.12.z] Remove Python 3.9 support from robottelo
  .github/workflows/pull_request.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11955 [6.13.z] Remove Python 3.9 support from robottelo
  .github/workflows/pull_request.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11971 moving failed to non success status
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#11958 T2 Reviewers Auto Assign for zBranches
  .github/workflows/t2_reviews.yaml
Labels: Framework Changes, No-CherryPick

#11967 [6.11.z] Bump sphinx from 7.0.1 to 7.1.0
  requirements-optional.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11968 [6.12.z] Bump sphinx from 7.0.1 to 7.1.0
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11970 [6.13.z] Bump sphinx from 7.0.1 to 7.1.0
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11969 [6.14.z] Bump sphinx from 7.0.1 to 7.1.0
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#11961 [6.14.z] Sanity Plugin with new sanity tests runs on installer tests satellite
  conftest.py
  pytest_fixtures/component/puppet.py
  pytest_fixtures/core/broker.py
  pytest_fixtures/core/contenthosts.py
  pytest_fixtures/core/sat_cap_factory.py
  pytest_fixtures/core/sys.py
  pytest_fixtures/core/xdist.py
  pytest_plugins/sanity_plugin.py
  robottelo/hosts.py
  robottelo/utils/ohsnap.py
  testimony.yaml
  tests/foreman/api/test_computeresource_gce.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_organization.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_syncplan.py
  tests/foreman/api/test_user.py
  tests/foreman/cli/test_contentcredentials.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_hostcollection.py
  tests/foreman/cli/test_ping.py
  tests/foreman/cli/test_role.py
  tests/foreman/cli/test_user.py
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/installer/test_installer.py
  tests/foreman/sanity/test_bvt.py
Labels: No-CherryPick, 6.14.z

#11952 Adding wait_for to test_positive_service_enable_disable
  tests/foreman/maintain/test_service.py
Labels: CherryPick, 6.14.z

#11980 Ignore the create issue in non satellite version label
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#11976 [Cherry-pick #11885] Add test for foreman-proxy-content-pulpcore-hide-guarded-distributions installer setting
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/destructive/test_clone.py
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick

#11977 Fix double yielding for capsule conf fixture
  pytest_fixtures/core/sat_cap_factory.py
Labels: Easy Fix :), 6.11.z, CherryPick, 6.14.z

#11979 [6.14.z] Adding wait_for to test_positive_service_enable_disable
  tests/foreman/maintain/test_service.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12005 [6.11.z] Fix double yielding for capsule conf fixture
  pytest_fixtures/core/sat_cap_factory.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#12011 [6.13.z] - ignore the create issue in non satellite version label
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick

#12010 [6.14.z]- ignore the create issue in non satellite version label
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick

#12015 [6.14.z] Fix test_content_access_after_stopped_foreman
  tests/foreman/destructive/test_contenthost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12012 [6.12.z] - ignore the create issue in non satellite version label
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick

#12014 Tier2 Reviewers Assignment
  .github/CODEOWNERS
Labels: No-CherryPick

#12021 [6.13.z] new hammer subcommands
  tests/foreman/data/hammer_commands.json
Labels: TestFailure, No-CherryPick, 6.13.z

#12009 Adding test for check-update when system is up to date
  tests/foreman/destructive/test_packages.py
Labels: CherryPick, 6.13.z, 6.14.z

#11893 api endpoints updated
  tests/foreman/endtoend/test_api_endtoend.py
Labels: API, CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#12038 [6.14.z] Bump sphinx from 7.1.0 to 7.1.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12037 [6.13.z] Bump sphinx from 7.1.0 to 7.1.1
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12035 [6.11.z] Bump sphinx from 7.1.0 to 7.1.1
  requirements-optional.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#12036 [6.12.z] Bump sphinx from 7.1.0 to 7.1.1
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12033 [6.13.z] Bump productmd from 1.35 to 1.36
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12031 [6.14.z] Bump productmd from 1.35 to 1.36
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#12030 [6.12.z] Bump productmd from 1.35 to 1.36
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#12026 [6.14.z] api endpoints updated
  tests/foreman/endtoend/test_api_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12020 Don't just take random webhook, search by name
  tests/foreman/ui/test_webhook.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#12024 [6.13.z] Adding test for check-update when system is up to date
  tests/foreman/destructive/test_packages.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#12017 [6.13.z] skip-if removed from e2e tests
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: No-CherryPick, 6.13.z

#12045 [6.14.z] Don't just take random webhook, search by name
  tests/foreman/ui/test_webhook.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12043 [6.13.z] Don't just take random webhook, search by name
  tests/foreman/ui/test_webhook.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#12044 [6.12.z] Don't just take random webhook, search by name
  tests/foreman/ui/test_webhook.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11864 delete policies which are no longer needed
  tests/foreman/cli/test_oscap.py
Labels: CLI, TestFailure, Easy Fix :), No-CherryPick

#11900 new hammer command and log level fix
  tests/foreman/cli/test_hammer.py
  tests/foreman/data/hammer_commands.json
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.14.z

#12047 [6.14.z] new hammer command and log level fix
  tests/foreman/cli/test_hammer.py
  tests/foreman/data/hammer_commands.json
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#12048 [6.13.z] Update sat_ready_rhel fixture to work with osp
  pytest_fixtures/core/contenthosts.py
  pytest_fixtures/core/sat_cap_factory.py
  tests/foreman/destructive/test_clone.py
Labels: No-CherryPick, 6.13.z
