Repository SatelliteQE/robottelo, pull requests merged in 2023-05, with the labels that each got.

#11384 [6.12.z] Bump sphinx from 6.2.1 to 7.0.0
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11383 [6.13.z] Bump sphinx from 6.2.1 to 7.0.0
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11385 update sphinx to 7.0
  requirements-optional.txt
Labels: 6.11.z, No-CherryPick

#11223 skip and reduce tracer host tests
  tests/foreman/api/test_host.py
  tests/foreman/cli/test_host.py
Labels: CherryPick, 6.12.z, 6.13.z

#11086 Rewrite tests to have one assertion per test
  tests/foreman/installer/test_installer.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#11388 [6.12.z] skip and reduce tracer host tests
  tests/foreman/api/test_host.py
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11389 [6.13.z] skip and reduce tracer host tests
  tests/foreman/api/test_host.py
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11375 [6.13.z] Update puppet e2e tests
  tests/foreman/api/test_classparameters.py
  tests/foreman/api/test_environment.py
  tests/foreman/cli/test_classparameters.py
  tests/foreman/cli/test_report.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11391 [6.12.z] Rewrite tests to have one assertion per test
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11392 [6.13.z] Rewrite tests to have one assertion per test
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11401 [6.13.z] Bump broker[docker] from 0.3.0 to 0.3.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11400 [6.12.z] Bump broker[docker] from 0.3.0 to 0.3.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11394 More forgiving BROKER_DIRECTORY behavior
  conf/broker.yaml.template
  robottelo/config/__init__.py
Labels: Framework Changes, 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z

#10428 Added test for expired manifest [Repository Rewrite]
  tests/foreman/api/test_repositories.py
Labels: enhancement, CherryPick, 6.12.z, 6.13.z

#11409 [6.13.z] Added test for expired manifest [Repository Rewrite]
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11403 [6.11.z] More forgiving BROKER_DIRECTORY behavior
  conf/broker.yaml.template
  robottelo/config/__init__.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#11404 [6.12.z] More forgiving BROKER_DIRECTORY behavior
  conf/broker.yaml.template
  robottelo/config/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11405 [6.13.z] More forgiving BROKER_DIRECTORY behavior
  conf/broker.yaml.template
  robottelo/config/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11349 Adding puppet enabled backup and restore
  tests/foreman/maintain/test_backup_restore.py
Labels: QETestCoverage, CherryPick, 6.13.z

#11399 webhook bz coverage added
  tests/foreman/ui/test_webhook.py
Labels: UI, 6.11.z, CherryPick, 6.12.z, 6.13.z

#10547 Create Satellite object based on the Capsule answer file
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/api/test_remoteexecution.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/destructive/test_remoteexecution.py
  tests/foreman/destructive/test_rename.py
  tests/upgrades/test_remoteexecution.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#11398 [6.13.z] Cherrypick ad 2019
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: 6.11.z, CherryPick, 6.12.z

#11422 [6.12.z] [6.13.z] Cherrypick ad 2019
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: No-CherryPick, 6.12.z

#11425 [6.13.z] Bump wrapanapi from 3.5.14 to 3.5.15
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11423 [6.11.z] Bump wrapanapi from 3.5.14 to 3.5.15
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11424 [6.12.z] Bump wrapanapi from 3.5.14 to 3.5.15
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11426 [6.13.z] Bump pre-commit from 3.2.2 to 3.3.1
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11427 [6.12.z] Bump pre-commit from 3.2.2 to 3.3.1
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11420 [6.12] webhook bz coverage added
  tests/foreman/ui/test_webhook.py
Labels: No-CherryPick, 6.12.z

#11411 fix in search bookmark assertion
  tests/foreman/ui/test_bookmarks.py
Labels: UI, 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z

#11414 [6.13.z] Adding puppet enabled backup and restore
  tests/foreman/maintain/test_backup_restore.py
Labels: No-CherryPick, 6.13.z

#11430 [6.13.z] fix in search bookmark assertion
  tests/foreman/ui/test_bookmarks.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11419 [6.13] webhook bz coverage added
  tests/foreman/ui/test_webhook.py
Labels: No-CherryPick, 6.13.z

#11431 [6.12.z] fix in search bookmark assertion
  tests/foreman/ui/test_bookmarks.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11429 [6.11.z] fix in search bookmark assertion
  tests/foreman/ui/test_bookmarks.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#11221 Gce parametrization and entities refactor
  pytest_fixtures/component/provision_gce.py
  tests/foreman/api/test_computeresource_gce.py
  tests/foreman/ui/test_computeresource_gce.py
  tests/upgrades/test_host.py
Labels: UI, API, CherryPick, AutoMerge_Cherry_Picked, 6.13.z

#11435 tags added for bookmarks test
  tests/foreman/ui/test_bookmarks.py
Labels: CherryPick, 6.13.z

#11432 Add closed loop for BZ#1607706
  tests/foreman/api/test_provisioningtemplate.py
Labels: API, QETestCoverage, 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z

#11439 [6.13.z] tags added for bookmarks test
  tests/foreman/ui/test_bookmarks.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11442 [6.12.z] Bump requests from 2.29.0 to 2.30.0
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#9576 Add test and associated mixin
  robottelo/constants/__init__.py
  robottelo/host_helpers/repository_mixins.py
  tests/foreman/ui/test_repository.py
Labels: UI, 6.10.z, 6.11.z, CherryPick, 6.12.z, 6.13.z

#11436 [6.13.z] Gce parametrization and entities refactor
  pytest_fixtures/component/provision_gce.py
  tests/foreman/api/test_computeresource_gce.py
  tests/foreman/ui/test_computeresource_gce.py
  tests/upgrades/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11438 [6.13.z] Add closed loop for BZ#1607706
  tests/foreman/api/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11245 virt-who config cases add create & delete to virtwho_config fixture for CLI/API/UI
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_hyperv.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_libvirt.py
  tests/foreman/virtwho/api/test_libvirt_sca.py
  tests/foreman/virtwho/api/test_nutanix.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_hyperv.py
  tests/foreman/virtwho/cli/test_kubevirt.py
  tests/foreman/virtwho/cli/test_libvirt.py
  tests/foreman/virtwho/cli/test_libvirt_sca.py
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_hyperv.py
  tests/foreman/virtwho/ui/test_kubevirt.py
  tests/foreman/virtwho/ui/test_libvirt.py
  tests/foreman/virtwho/ui/test_nutanix.py
Labels: CherryPick, 6.12.z, 6.13.z

#11448 [6.13.z] virt-who config cases add create & delete to virtwho_config fixture for CLI/API/UI
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_hyperv.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_libvirt.py
  tests/foreman/virtwho/api/test_libvirt_sca.py
  tests/foreman/virtwho/api/test_nutanix.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_hyperv.py
  tests/foreman/virtwho/cli/test_kubevirt.py
  tests/foreman/virtwho/cli/test_libvirt.py
  tests/foreman/virtwho/cli/test_libvirt_sca.py
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_hyperv.py
  tests/foreman/virtwho/ui/test_kubevirt.py
  tests/foreman/virtwho/ui/test_libvirt.py
  tests/foreman/virtwho/ui/test_nutanix.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11457 [6.13.z] Bump sphinx from 7.0.0 to 7.0.1
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11459 [6.11.z] Bump sphinx from 7.0.0 to 7.0.1
  requirements-optional.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11458 [6.12.z] Bump sphinx from 7.0.0 to 7.0.1
  requirements-optional.txt
Labels: No-CherryPick, 6.12.z

#11450 one more bz tag added
  tests/foreman/cli/test_hammer.py
Labels: Documentation, Easy Fix :), CherryPick, 6.13.z

#11460 [6.13.z] one more bz tag added
  tests/foreman/cli/test_hammer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11462 exports added to api paths
  tests/foreman/endtoend/test_api_endtoend.py
Labels: API, CherryPick, 6.12.z, 6.13.z

#11437 test settings change from non-default to default
  tests/foreman/ui/test_settings.py
Labels: UI, CherryPick, 6.13.z

#11354 Remove satellite6-upgrade and fabric imports 🎉 (#11331)
  pytest_plugins/upgrade/scenario_workers.py
  requirements.txt
  robottelo/upgrade_utility.py
  tests/upgrades/conftest.py
Labels: Upgrades, 6.11.z, No-CherryPick

#11463 [6.13.z] exports added to api paths
  tests/foreman/endtoend/test_api_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11464 [6.12.z] exports added to api paths
  tests/foreman/endtoend/test_api_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11356 Remove satellite6-upgrade and fabric imports 🎉 (#11331)
  pytest_plugins/upgrade/scenario_workers.py
  requirements.txt
  robottelo/upgrade_utility.py
  tests/upgrades/conftest.py
Labels: Upgrades, No-CherryPick, 6.13.z

#11355 Remove satellite6-upgrade and fabric imports 🎉 (#11331)
  pytest_plugins/upgrade/scenario_workers.py
  requirements.txt
  robottelo/upgrade_utility.py
  tests/upgrades/conftest.py
Labels: Upgrades, No-CherryPick, 6.12.z

#11461 Add test for filter_applied flag
  tests/foreman/api/test_contentviewfilter.py
Labels: API, No-CherryPick, Stream

#11365 Auto Release Robottelo
  .github/workflows/dispatch_release.yml
Labels: Framework Changes, No-CherryPick

#11471 [6.13.z] Bump broker[docker] from 0.3.1 to 0.3.2
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11472 [6.11.z] Bump broker[docker] from 0.3.1 to 0.3.2
  requirements.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11469 Cherry-pick changes from #11248 missed by #11297
  tests/foreman/cli/test_satellitesync.py
Labels: Easy Fix :), 6.11.z, CherryPick, 6.12.z

#11477 [6.12.z] Cherry-pick changes from #11248 missed by #11297
  tests/foreman/cli/test_satellitesync.py
Labels: Easy Fix :), No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11478 [6.11.z] Cherry-pick changes from #11248 missed by #11297
  tests/foreman/cli/test_satellitesync.py
Labels: Easy Fix :), 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11467 Handle stream versions in version cached_property
  robottelo/hosts.py
Labels: Easy Fix :), No-CherryPick, Stream

#11019 Moving the ansible_roles_import test_case to destructive
  tests/foreman/destructive/test_ansible.py
  tests/foreman/ui/test_ansible.py
Labels: UI, 6.11.z, CherryPick, 6.12.z, 6.13.z

#11481 Updating service enable/disable to test on stream
  tests/foreman/maintain/test_service.py
Labels: Easy Fix :), No-CherryPick, Stream

#11183 Fix host content virtwho
  robottelo/utils/virtwho.py
  tests/foreman/ui/test_contenthost.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#11487 [6.13.z] Fix host content virtwho
  robottelo/utils/virtwho.py
  tests/foreman/ui/test_contenthost.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11490 [6.11.z] Run Autocherrypick on merged PRs
  .github/workflows/auto_cherry_pick.yml
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11485 [6.11.z] Fix host content virtwho
  robottelo/utils/virtwho.py
  tests/foreman/ui/test_contenthost.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11452 [6.12.z] Create Satellite object based on the Capsule answer file
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/destructive/test_remoteexecution.py
  tests/foreman/destructive/test_rename.py
  tests/upgrades/test_remoteexecution.py
Labels: No-CherryPick, 6.12.z

#11451 [6.11.z] Create Satellite object based on the Capsule answer file
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/destructive/test_remoteexecution.py
  tests/foreman/destructive/test_rename.py
  tests/upgrades/test_remoteexecution.py
Labels: 6.11.z, No-CherryPick

#11406 Use pre_configured_capsule fixture to ensure we get the correct Capsule
  tests/upgrades/test_puppet.py
  tests/upgrades/test_remoteexecution.py
Labels: Upgrades, 6.11.z, CherryPick, 6.12.z, 6.13.z

#11495 [6.13] added customerscenario tags
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_contentcredentials.py
  tests/foreman/cli/test_contentcredentials.py
  tests/foreman/virtwho/api/test_nutanix.py
Labels: No-CherryPick, 6.13.z

#11446 Fix incorrect repos set for RHEL 8+ causing ValueError
  robottelo/constants/__init__.py
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/hosts.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#11480 Bump el8 and el9 kickstart versions
  robottelo/constants/__init__.py
Labels: Easy Fix :), 6.11.z, CherryPick, 6.12.z, 6.13.z

#11453 Fix Upgrade Scenarios collection for Teams
  tests/upgrades/test_activation_key.py
  tests/upgrades/test_client.py
  tests/upgrades/test_contentview.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_hostcontent.py
  tests/upgrades/test_performance_tuning.py
  tests/upgrades/test_repository.py
  tests/upgrades/test_satellitesync.py
  tests/upgrades/test_subscription.py
  tests/upgrades/test_syncplan.py
  tests/upgrades/test_virtwho.py
Labels: Urgent Priority, Upgrades, 6.11.z, CherryPick, 6.12.z, 6.13.z

#11506 [6.12.z] Fix Upgrade Scenarios collection for Teams
  tests/upgrades/test_activation_key.py
  tests/upgrades/test_client.py
  tests/upgrades/test_contentview.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_hostcontent.py
  tests/upgrades/test_performance_tuning.py
  tests/upgrades/test_repository.py
  tests/upgrades/test_satellitesync.py
  tests/upgrades/test_subscription.py
  tests/upgrades/test_syncplan.py
  tests/upgrades/test_virtwho.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11508 [6.13.z] Run Autocherrypick on merged PRs
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, 6.13.z

#11509 [6.12.z] Run Autocherrypick on merged PRs
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, 6.12.z

#11494 [6.11.z] Use pre_configured_capsule fixture to ensure we get the correct Capsule
  tests/upgrades/test_puppet.py
  tests/upgrades/test_remoteexecution.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11417 [6.13.z] Create Satellite object based on the Capsule answer file
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/api/test_remoteexecution.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/destructive/test_remoteexecution.py
  tests/foreman/destructive/test_rename.py
  tests/upgrades/test_remoteexecution.py
Labels: No-CherryPick, 6.13.z

#11502 [6.13.z] Bump el8 and el9 kickstart versions
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11503 [6.12.z] Bump el8 and el9 kickstart versions
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11498 [6.13.z] Fix incorrect repos set for RHEL 8+ causing ValueError
  robottelo/constants/__init__.py
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11512 [6.12.z] Fix incorrect repos set for RHEL 8+ causing ValueError
  robottelo/constants/__init__.py
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/hosts.py
Labels: No-CherryPick, 6.12.z

#11511 [6.11.z] Fix incorrect repos set for RHEL 8+ causing ValueError
  robottelo/constants/__init__.py
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/hosts.py
Labels: 6.11.z, No-CherryPick

#11510 [6.13.z] Use pre_configured_capsule fixture to ensure we get the correct Capsule
  tests/upgrades/test_puppet.py
  tests/upgrades/test_remoteexecution.py
Labels: No-CherryPick, 6.13.z

#11513 Fix assertion for test_positive_configure_cloud_connector
  tests/foreman/ui/test_rhc.py
Labels: 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z

#11516 [6.13.z] Fix assertion for test_positive_configure_cloud_connector
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11520 [6.12.z] Bump requests from 2.30.0 to 2.31.0
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11517 [6.11.z] Fix assertion for test_positive_configure_cloud_connector
  tests/foreman/ui/test_rhc.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#11518 [6.12.z] Fix assertion for test_positive_configure_cloud_connector
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#11522 Switch SATELLITE_SERVICES to a list
  tests/foreman/installer/test_installer.py
Labels: 6.11.z, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z

#11523 [6.11.z] Switch SATELLITE_SERVICES to a list
  tests/foreman/installer/test_installer.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked

#11524 [6.13.z] Switch SATELLITE_SERVICES to a list
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11454 Http-Proxy cacert automation coverage
  tests/foreman/api/test_http_proxy.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z

#11445 Fix for PytestAssertRewriteWarning
  pytest_fixtures/component/satellite_auth.py
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/hosts.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#11534 [6.13.z] Bump pytest-reportportal from 5.1.7 to 5.1.8
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11541 [6.13.z] Follow ohsnap repofile redirects
  robottelo/host_helpers/contenthost_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11540 [6.12.z] Follow ohsnap repofile redirects
  robottelo/host_helpers/contenthost_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#11539 [6.11.z] Follow ohsnap repofile redirects
  robottelo/host_helpers/contenthost_mixins.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#11466 [6.13.z] test settings change from non-default to default
  tests/foreman/ui/test_settings.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#11547 Katello-tracer Alligned in CI
  testimony.yaml
  tests/foreman/cli/test_host.py
  tests/foreman/ui/test_host.py
Labels: Easy Fix :), 6.11.z, CherryPick, 6.12.z, 6.13.z

#11550 [6.13.z] Katello-tracer Alligned in CI (#11547)
  testimony.yaml
  tests/foreman/cli/test_host.py
  tests/foreman/ui/test_host.py
Labels: Easy Fix :), No-CherryPick, Failed_AutoCherryPick, 6.13.z

#11551 [6.12.z] Katello-tracer Alligned in CI (#11547)
  testimony.yaml
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, 6.12.z, Failed_AutoCherryPick

#11552 [6.11.z] Katello-tracer Aligned in CI (#11547)
  testimony.yaml
Labels: 6.11.z, No-CherryPick, Failed_AutoCherryPick

#11560 [6.13.z] Bump pytest-xdist from 3.2.1 to 3.3.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11556 Fix Puppet enable test failures
  robottelo/host_helpers/satellite_mixins.py
  tests/foreman/destructive/test_puppetplugin.py
Labels: TestFailure, Easy Fix :), No-CherryPick, Stream

#11555 [6.13.z] Test case updated for RHEL6 client registration
  tests/foreman/api/test_registration.py
  tests/foreman/cli/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#11301 autodetect and add prt tests for dependabot PR's
  .github/dependabot.yml
  .github/dependency_tests.yaml
  .github/workflows/auto_cherry_pick_merge.yaml
  .github/workflows/dependency_merge.yml
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z
