Repository SatelliteQE/robottelo, pull requests merged in 2024-03, with the labels that each got.

#14226 Fix server_config in subscription test
  tests/foreman/api/test_subscription.py
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14235 [6.15.z] Fix server_config in subscription test
  tests/foreman/api/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14236 [6.13.z] Fix server_config in subscription test
  tests/foreman/api/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14233 [6.12.z] Fix server_config in subscription test
  tests/foreman/api/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked, PRT-Passed

#14225 Call function parameters by key-value
  tests/foreman/api/test_role.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14241 [6.15.z] Call function parameters by key-value
  tests/foreman/api/test_role.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14239 [6.13.z] Call function parameters by key-value
  tests/foreman/api/test_role.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#14240 [6.14.z] Call function parameters by key-value
  tests/foreman/api/test_role.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14223 More meaningful parametrization id
  tests/foreman/api/test_webhook.py
Labels: CherryPick, 6.14.z, 6.15.z

#14246 [6.15.z] More meaningful parametrization id
  tests/foreman/api/test_webhook.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14245 [6.14.z] More meaningful parametrization id
  tests/foreman/api/test_webhook.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14237 forgotten target sat in host cli tests
  tests/foreman/cli/test_host.py
Labels: TestFailure, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14248 [6.13.z] Fix pit marker in installer (#14180)
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.13.z

#14249 [6.12.z] Fix pit marker in installer (#14180)
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, 6.12.z, Failed_AutoCherryPick

#14215 Update HTTP Proxy e2e test cases
  tests/foreman/api/test_http_proxy.py
  tests/foreman/cli/test_http_proxy.py
  tests/foreman/ui/test_http_proxy.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14181 [6.15.z] CV already published + single LCE
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#14253 [6.13.z] forgotten target sat in host cli tests
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14252 [6.15.z] forgotten target sat in host cli tests
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14254 [6.14.z] forgotten target sat in host cli tests
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14251 [6.12.z] forgotten target sat in host cli tests
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked, PRT-Passed

#14255 [6.15.z] Bump cryptography from 42.0.2 to 42.0.5
  requirements.txt
Labels: CherryPick, 6.12.z, Failed_AutoCherryPick, 6.13.z, 6.14.z

#14256 [6.14.z] Bump Pytest to 8.0.2
  requirements.txt
Labels: CherryPick, 6.12.z, Failed_AutoCherryPick, 6.13.z

#14262 [6.14.z] Bump cryptography from 42.0.2 to 42.0.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14263 [6.13.z] Bump cryptography from 42.0.2 to 42.0.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14261 [6.12.z] Bump cryptography from 42.0.2 to 42.0.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14265 [6.12.z] Bump Pytest to 8.0.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14069 Fail curl command registration
  tests/foreman/api/test_registration.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#14266 [6.15.z] Fail curl command registration
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14258 [6.14.z] Update HTTP Proxy e2e test cases
  robottelo/constants/__init__.py
  robottelo/host_helpers/repository_mixins.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/cli/test_http_proxy.py
  tests/foreman/ui/test_http_proxy.py
  tests/foreman/ui/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#14259 [6.13.z] Update HTTP Proxy e2e test cases
  robottelo/constants/__init__.py
  robottelo/host_helpers/repository_mixins.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/cli/test_http_proxy.py
  tests/foreman/ui/test_http_proxy.py
  tests/foreman/ui/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#14260 add verify virt-who data is uploaded on satellite post satellite upgrade
  tests/upgrades/test_virtwho.py
Labels: Upgrades, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#14277 [6.14.z] add verify virt-who data is uploaded on satellite post satellite upgrade
  tests/upgrades/test_virtwho.py
Labels: Upgrades, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14278 [6.15.z] add verify virt-who data is uploaded on satellite post satellite upgrade
  tests/upgrades/test_virtwho.py
Labels: Upgrades, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14205 Fix pytest deprecation warning
  pytest_fixtures/component/host.py
  pytest_fixtures/component/puppet.py
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/api/test_contentview.py
  tests/foreman/cli/test_computeresource_libvirt.py
  tests/foreman/cli/test_host.py
  tests/foreman/destructive/test_ldap_authentication.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14269 Wait for product HTTP Proxy update to finish
  tests/foreman/cli/test_http_proxy.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14272 Extend ansible-roles add/remove test for nested HG
  tests/foreman/api/test_ansible.py
Labels: API, QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#14279 Fix test_content_access_after_stopped_foreman
  tests/foreman/destructive/test_contenthost.py
Labels: TestFailure, No-CherryPick, Stream, PRT-Passed

#14283 [6.14.z] Fix pytest deprecation warning
  pytest_fixtures/component/host.py
  pytest_fixtures/component/puppet.py
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/api/test_contentview.py
  tests/foreman/cli/test_computeresource_libvirt.py
  tests/foreman/cli/test_host.py
  tests/foreman/destructive/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14281 [6.13.z] Fix pytest deprecation warning
  pytest_fixtures/component/host.py
  pytest_fixtures/component/puppet.py
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/api/test_contentview.py
  tests/foreman/cli/test_computeresource_libvirt.py
  tests/foreman/cli/test_host.py
  tests/foreman/destructive/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14286 [6.14.z] Wait for product HTTP Proxy update to finish
  tests/foreman/cli/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14284 [6.15.z] Wait for product HTTP Proxy update to finish
  tests/foreman/cli/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14285 [6.13.z] Wait for product HTTP Proxy update to finish
  tests/foreman/cli/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14294 [6.14.z] Bump pytest-reportportal from 5.3.1 to 5.4.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14295 [6.13.z] Bump pytest-reportportal from 5.3.1 to 5.4.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14293 [6.15.z] Bump pytest-reportportal from 5.3.1 to 5.4.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14296 [6.12.z] Bump pytest-reportportal from 5.3.1 to 5.4.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14287 [6.15.z] Extend ansible-roles add/remove test for nested HG
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#13972 CV already published + single LCE
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Stream, PRT-Passed

#14093 remove the PRT labels for new commits
  .github/workflows/prt_labels.yml
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14309 fixed sanity suite, AttributeError due to not matching scope
  robottelo/host_helpers/satellite_mixins.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14297 [6.15.z] Bump pytest from 8.0.2 to 8.1.0
  requirements.txt
Labels: dependencies, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, PRT-Passed

#14304 [6.15.z] remove the PRT labels for new commits
  .github/workflows/prt_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14315 Fix failing ISS tests
  tests/foreman/cli/test_satellitesync.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14318 [6.14.z] Fix failing ISS tests
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14319 [6.13.z] Fix failing ISS tests
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14320 [6.15.z] Fix failing ISS tests
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14324 [6.14.z] Bump redis from 5.0.2 to 5.0.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14325 [6.12.z] Bump redis from 5.0.2 to 5.0.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14327 [6.15.z] Bump redis from 5.0.2 to 5.0.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14326 [6.13.z] Bump redis from 5.0.2 to 5.0.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14330 [6.15.z] Bump pytest from 8.1.0 to 8.1.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#14242 session name for bookmarks
  robottelo/constants/__init__.py
  tests/foreman/ui/test_bookmarks.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Failed

#14207 host delete permissions test
  tests/foreman/api/test_permission.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14335 [6.15.z] host delete permissions test
  tests/foreman/api/test_permission.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14247 Hosts: run 'Manage columns' RFE test also for non-admin user
  pytest_fixtures/component/taxonomy.py
  tests/foreman/ui/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14333 [6.14.z] session name for bookmarks
  robottelo/constants/__init__.py
  tests/foreman/ui/test_bookmarks.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Failed

#14334 [6.15.z] session name for bookmarks
  robottelo/constants/__init__.py
  tests/foreman/ui/test_bookmarks.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Failed

#12939 Capsule N-Minus testing
  conf/capsule.yaml.template
  conf/dynaconf_hooks.py
  conftest.py
  pytest_fixtures/core/sat_cap_factory.py
  pytest_plugins/capsule_n-minus.py
  robottelo/exceptions.py
  robottelo/hosts.py
  tests/foreman/api/test_capsule.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/destructive/test_registration.py
Labels: Framework Changes, CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14338 [6.15.z] Hosts: run 'Manage columns' RFE test also for non-admin user
  pytest_fixtures/component/taxonomy.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14238 Fix manifest file transer for fam
  tests/foreman/sys/test_fam.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Failed

#14337 Fix flaky SyncPlans in cli_factory
  robottelo/cli/syncplan.py
  robottelo/host_helpers/cli_factory.py
  tests/foreman/cli/test_syncplan.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Failed

#14351 [6.15.z] Fix flaky SyncPlans in cli_factory
  robottelo/cli/syncplan.py
  robottelo/host_helpers/cli_factory.py
  tests/foreman/cli/test_syncplan.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14352 [6.14.z] Fix flaky SyncPlans in cli_factory
  robottelo/cli/syncplan.py
  robottelo/host_helpers/cli_factory.py
  tests/foreman/cli/test_syncplan.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14336 Mark fake secret as "notsecret"
  tests/robottelo/test_dependencies.py
Labels: Easy Fix :), CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14306 [6.14.z] remove the PRT labels for new commits
  .github/workflows/prt_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14307 [6.13.z] remove the PRT labels for new commits
  .github/workflows/prt_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14305 [6.12.z] remove the PRT labels for new commits
  .github/workflows/prt_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14358 [6.14.z] Mark fake secret as "notsecret"
  tests/robottelo/test_dependencies.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14360 [6.13.z] Mark fake secret as "notsecret"
  tests/robottelo/test_dependencies.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14356 [6.15.z] [Component Refresh] Component Names are updated
  testimony.yaml
  tests/foreman/api/test_capsule.py
  tests/foreman/api/test_rhc.py
  tests/foreman/api/test_rhcloud_inventory.py
  tests/foreman/cli/test_capsule.py
  tests/foreman/cli/test_installer.py
  tests/foreman/cli/test_rhcloud_inventory.py
  tests/foreman/destructive/test_capsule.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/destructive/test_installer.py
  tests/foreman/destructive/test_katello_certs_check.py
  tests/foreman/destructive/test_packages.py
  tests/foreman/destructive/test_rename.py
  tests/foreman/installer/test_installer.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_backup_restore.py
  tests/foreman/maintain/test_health.py
  tests/foreman/maintain/test_maintenance_mode.py
  tests/foreman/maintain/test_offload_DB.py
  tests/foreman/maintain/test_packages.py
  tests/foreman/maintain/test_service.py
  tests/foreman/maintain/test_upgrade.py
  tests/foreman/sys/test_katello_certs_check.py
  tests/foreman/ui/test_rhc.py
  tests/foreman/ui/test_rhcloud_insights.py
  tests/foreman/ui/test_rhcloud_inventory.py
  tests/upgrades/test_capsule.py
  tests/upgrades/test_performance_tuning.py
  tests/upgrades/test_satellite_maintain.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14355 [6.13.z] [Component Refresh] Component Names are updated
  testimony.yaml
  tests/foreman/api/test_capsule.py
  tests/foreman/api/test_rhc.py
  tests/foreman/api/test_rhcloud_inventory.py
  tests/foreman/cli/test_capsule.py
  tests/foreman/cli/test_installer.py
  tests/foreman/cli/test_rhcloud_inventory.py
  tests/foreman/destructive/test_capsule.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/destructive/test_installer.py
  tests/foreman/destructive/test_katello_certs_check.py
  tests/foreman/destructive/test_packages.py
  tests/foreman/destructive/test_rename.py
  tests/foreman/installer/test_installer.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_backup_restore.py
  tests/foreman/maintain/test_health.py
  tests/foreman/maintain/test_maintenance_mode.py
  tests/foreman/maintain/test_offload_DB.py
  tests/foreman/maintain/test_packages.py
  tests/foreman/maintain/test_service.py
  tests/foreman/maintain/test_upgrade.py
  tests/foreman/sys/test_katello_certs_check.py
  tests/foreman/ui/test_rhc.py
  tests/foreman/ui/test_rhcloud_insights.py
  tests/foreman/ui/test_rhcloud_inventory.py
  tests/upgrades/test_capsule.py
  tests/upgrades/test_performance_tuning.py
  tests/upgrades/test_satellite_maintain.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14367 [6.14.z][Component Refresh] Component Names are updated (#14268)
  testimony.yaml
  tests/foreman/api/test_capsule.py
  tests/foreman/api/test_rhc.py
  tests/foreman/api/test_rhcloud_inventory.py
  tests/foreman/cli/test_capsule.py
  tests/foreman/cli/test_installer.py
  tests/foreman/cli/test_rhcloud_inventory.py
  tests/foreman/destructive/test_capsule.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/destructive/test_installer.py
  tests/foreman/destructive/test_katello_certs_check.py
  tests/foreman/destructive/test_packages.py
  tests/foreman/destructive/test_rename.py
  tests/foreman/installer/test_installer.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_backup_restore.py
  tests/foreman/maintain/test_health.py
  tests/foreman/maintain/test_maintenance_mode.py
  tests/foreman/maintain/test_offload_DB.py
  tests/foreman/maintain/test_packages.py
  tests/foreman/maintain/test_service.py
  tests/foreman/maintain/test_upgrade.py
  tests/foreman/sys/test_katello_certs_check.py
  tests/foreman/ui/test_rhc.py
  tests/foreman/ui/test_rhcloud_insights.py
  tests/foreman/ui/test_rhcloud_inventory.py
  tests/upgrades/test_capsule.py
  tests/upgrades/test_performance_tuning.py
  tests/upgrades/test_satellite_maintain.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#14368 [6.15.z] Update Ansible tests to reflect the new split Ansible components
  testimony.yaml
  tests/foreman/api/test_ansible.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/destructive/test_ansible.py
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_jobinvocation.py
  tests/foreman/ui/test_remoteexecution.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.15.z

#14365 [6.14.z] Update Ansible tests to reflect the new split Ansible components
  testimony.yaml
  tests/foreman/api/test_ansible.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/destructive/test_ansible.py
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_jobinvocation.py
  tests/foreman/ui/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14370 [6.13.z] Capsule N-Minus testing (#12939)
  conf/capsule.yaml.template
  conf/dynaconf_hooks.py
  conftest.py
  pytest_fixtures/core/sat_cap_factory.py
  pytest_plugins/capsule_n-minus.py
  robottelo/exceptions.py
  robottelo/hosts.py
  tests/foreman/api/test_capsule.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/destructive/test_registration.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.13.z

#14372 [6.12.z] Capsule N-Minus testing (#12939)
  conf/capsule.yaml.template
  conf/dynaconf_hooks.py
  conftest.py
  pytest_fixtures/core/sat_cap_factory.py
  pytest_plugins/capsule_n-minus.py
  robottelo/exceptions.py
  robottelo/hosts.py
Labels: No-CherryPick, 6.12.z, Failed_AutoCherryPick

#14343 [6.14.z] Capsule N-Minus testing
  conf/capsule.yaml.template
  conf/dynaconf_hooks.py
  conftest.py
  pytest_fixtures/core/sat_cap_factory.py
  pytest_plugins/capsule_n-minus.py
  robottelo/exceptions.py
  robottelo/hosts.py
  tests/foreman/api/test_capsule.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/destructive/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Failed

#14374 [6.12.z] Update Ansible tests to reflect the new split Ansible components
  testimony.yaml
  tests/foreman/api/test_ansible.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/destructive/test_ansible.py
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_jobinvocation.py
  tests/foreman/ui/test_remoteexecution.py
Labels: No-CherryPick, 6.12.z, Failed_AutoCherryPick

#14108 [6.15.z] Updates to requirements.txt
  requirements.txt
Labels: No-CherryPick, 6.15.z, PRT-Failed

#14107 [6.14.z] Updates to requirements.txt
  requirements.txt
Labels: No-CherryPick, 6.14.z

#14106 [6.13.z] Updates to requirements.txt
  requirements.txt
Labels: No-CherryPick, 6.13.z

#14105 [6.12.z] Updates to requirements.txt
  requirements.txt
Labels: No-CherryPick, 6.12.z

#14275 Broker dependency updated to resolve ssh2-python limitation/packagever issue
  requirements.txt
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14384 [6.15.z] Broker dependency updated to resolve ssh2-python limitation/packagever issue
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14381 [6.14.z] Broker dependency updated to resolve ssh2-python limitation/packagever issue
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14383 [6.13.z] Broker dependency updated to resolve ssh2-python limitation/packagever issue
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14382 [6.12.z] Broker dependency updated to resolve ssh2-python limitation/packagever issue
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14379 simplify time expression assertions
  tests/foreman/cli/test_remoteexecution.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14158 Close-loop bz2209968
  robottelo/utils/datafactory.py
  tests/foreman/ui/test_jobinvocation.py
Labels: No-CherryPick, PRT-Passed

#14380 component name changes
  testimony.yaml
  tests/foreman/api/test_ldapauthsource.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/cli/test_sso.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
  tests/foreman/sys/test_dynflow.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14386 [6.15.z] simplify time expression assertions
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14387 [6.13.z] component name changes
  testimony.yaml
  tests/foreman/api/test_ldapauthsource.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/cli/test_sso.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
  tests/foreman/sys/test_dynflow.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14388 [6.15.z] component name changes
  testimony.yaml
  tests/foreman/api/test_ldapauthsource.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/cli/test_sso.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
  tests/foreman/sys/test_dynflow.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14389 [6.14.z] component name changes
  testimony.yaml
  tests/foreman/api/test_ldapauthsource.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/cli/test_sso.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
  tests/foreman/sys/test_dynflow.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14375 update fixture name as per expected feature
  tests/foreman/api/test_subscription.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, PRT-Passed

#14392 [6.15.z] update fixture name as per expected feature
  tests/foreman/api/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14394 changes in test_positive_run_job_on_host_converted_to_pull_provider
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#14396 [6.15.z] changes in test_positive_run_job_on_host_converted_to_pull_provider
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14395 [6.14.z] changes in test_positive_run_job_on_host_converted_to_pull_provider
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14314 remove log check causing false negatives
  tests/foreman/installer/test_installer.py
Labels: CherryPick, 6.14.z, 6.15.z

#14353 Add test for Webpack 5 presence
  tests/foreman/sys/test_webpack.py
Labels: No-CherryPick, PRT-Passed

#14393 change a way to upload content into satellite
  tests/foreman/api/test_repository.py
Labels: TestFailure, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#14371 Skip orphan cleanup case for n_minus scenario
  tests/foreman/api/test_capsulecontent.py
Labels: Easy Fix :), CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14408 [6.14.z] Skip orphan cleanup case for n_minus scenario
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14406 [6.13.z] Skip orphan cleanup case for n_minus scenario
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14066 Assertion Error, time delta/format in 'wait_for_sync()', of capsule content 'last_sync_time'
  robottelo/host_helpers/capsule_mixins.py
  tests/foreman/api/test_capsulecontent.py
Labels: CherryPick, Stream, 6.14.z, 6.15.z, PRT-Passed

#14409 [6.15.z] Skip orphan cleanup case for n_minus scenario
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14270 Add posibility to filter tests that require manifester
  pytest_plugins/markers.py
  tests/foreman/conftest.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14036 addFinalizer in test body
  tests/foreman/api/test_computeresource_libvirt.py
  tests/foreman/api/test_discoveryrule.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_parameters.py
  tests/foreman/cli/test_classparameters.py
  tests/foreman/cli/test_computeresource_osp.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_hammer.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_subnet.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_health.py
  tests/foreman/maintain/test_maintenance_mode.py
  tests/foreman/maintain/test_packages.py
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_computeresource_gce.py
  tests/foreman/ui/test_computeresource_libvirt.py
  tests/upgrades/test_contentview.py
  tests/upgrades/test_host.py
  tests/upgrades/test_provisioningtemplate.py
  tests/upgrades/test_subscription.py
  tests/upgrades/test_usergroup.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14156 [6.15.z] Integrate FAM pipeline into robottelo
  robottelo/constants/__init__.py
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Failed

#14157 [6.14.z] Integrate FAM pipeline into robottelo
  robottelo/constants/__init__.py
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Failed

#14391 [6.12.z] component name changes
  testimony.yaml
  tests/foreman/api/test_ldapauthsource.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/cli/test_sso.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
  tests/foreman/sys/test_dynflow.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: No-CherryPick, 6.12.z

#14422 [6.15.z] addFinalizer in test body
  tests/foreman/api/test_computeresource_libvirt.py
  tests/foreman/api/test_discoveryrule.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_parameters.py
  tests/foreman/cli/test_classparameters.py
  tests/foreman/cli/test_computeresource_osp.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_hammer.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_subnet.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_health.py
  tests/foreman/maintain/test_maintenance_mode.py
  tests/foreman/maintain/test_packages.py
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_computeresource_gce.py
  tests/foreman/ui/test_computeresource_libvirt.py
  tests/upgrades/test_contentview.py
  tests/upgrades/test_host.py
  tests/upgrades/test_provisioningtemplate.py
  tests/upgrades/test_subscription.py
  tests/upgrades/test_usergroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14415 [6.15.z] Add posibility to filter tests that require manifester
  pytest_plugins/markers.py
  tests/foreman/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14418 [6.14.z] Add posibility to filter tests that require manifester
  pytest_plugins/markers.py
  tests/foreman/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14416 [6.13.z] Add posibility to filter tests that require manifester
  pytest_plugins/markers.py
  tests/foreman/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14417 [6.12.z] Add posibility to filter tests that require manifester
  pytest_plugins/markers.py
  tests/foreman/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14410 [6.14.z] remove log check causing false negatives
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#14401 [6.15.z] remove log check causing false negatives
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14404 [6.14.z] change a way to upload content into satellite
  tests/foreman/api/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14423 Workaround for some ext auth tests for PR13737 which broke CSV handling
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/cli/test_ldapauthsource.py
Labels: CherryPick, 6.15.z, PRT-Passed

#14316 validate that cv warning to force promote
  tests/foreman/cli/test_contentview.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, PRT-Passed

#14435 [6.15.z] validate that cv warning to force promote
  tests/foreman/cli/test_contentview.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14434 [6.15.z] Add a test case to read Capsules via non-admin user
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14413 [6.14.z] Eval CapsuleContent::API Assertion Errors, time delta/format in 'wait_for_sync()'
  robottelo/host_helpers/capsule_mixins.py
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, 6.14.z, PRT-Passed

#14442 [6.12.z] Bump dynaconf[vault] from 3.2.4 to 3.2.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z, PRT-Passed

#14440 [6.14.z] Bump dynaconf[vault] from 3.2.4 to 3.2.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#14426 [6.15.z] Workaround for some ext auth tests for PR13737 which broke CSV handling
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/cli/test_ldapauthsource.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#14444 Fix module_hostgroup fixture
  tests/foreman/api/test_discoveryrule.py
Labels: TestFailure, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14446 [6.13] addFinalizer in test body
  tests/foreman/api/test_computeresource_libvirt.py
  tests/foreman/api/test_discoveryrule.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_parameters.py
  tests/foreman/cli/test_classparameters.py
  tests/foreman/cli/test_computeresource_osp.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_hammer.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_subnet.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_health.py
  tests/foreman/maintain/test_maintenance_mode.py
  tests/foreman/maintain/test_packages.py
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_computeresource_gce.py
  tests/foreman/ui/test_computeresource_libvirt.py
  tests/upgrades/test_contentview.py
  tests/upgrades/test_host.py
  tests/upgrades/test_provisioningtemplate.py
  tests/upgrades/test_subscription.py
  tests/upgrades/test_usergroup.py
Labels: No-CherryPick, 6.13.z

#14447 [6.12.z] addFinalizer in test body
  tests/foreman/api/test_computeresource_libvirt.py
  tests/foreman/api/test_parameters.py
  tests/foreman/cli/test_computeresource_osp.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_hammer.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_subnet.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_health.py
  tests/foreman/maintain/test_maintenance_mode.py
  tests/foreman/maintain/test_packages.py
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_computeresource_gce.py
  tests/foreman/ui/test_computeresource_libvirt.py
  tests/upgrades/test_contentview.py
  tests/upgrades/test_host.py
  tests/upgrades/test_provisioningtemplate.py
  tests/upgrades/test_subscription.py
  tests/upgrades/test_usergroup.py
Labels: No-CherryPick, 6.12.z

#13895 [6.14.z] fix in test_permission
  tests/foreman/destructive/test_auth.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14450 [6.15.z] Add a case to export/import entities with long names
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#14412 [6.15.z] Eval CapsuleContent::API Assertion Errors, time delta/format in 'wait_for_sync()'
  robottelo/host_helpers/capsule_mixins.py
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14443 [6.15.z] Bump dynaconf[vault] from 3.2.4 to 3.2.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#14232 duplicate bookmark negative test fix
  robottelo/constants/__init__.py
  tests/foreman/ui/test_bookmarks.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Failed

#14454 [6.14.z] duplicate bookmark negative test fix
  robottelo/constants/__init__.py
  tests/foreman/ui/test_bookmarks.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Failed

#14452 [6.13.z] duplicate bookmark negative test fix
  robottelo/constants/__init__.py
  tests/foreman/ui/test_bookmarks.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Failed

#14399 Bump Broker to 0.4.9
  requirements.txt
Labels: dependencies, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14460 [6.14.z] Bump Broker to 0.4.9
  requirements.txt
Labels: No-CherryPick, 6.14.z
