Repository SatelliteQE/robottelo, pull requests merged in 2024-01, with the labels that each got.

#13582 [6.15.z] Bump pytest from 7.4.3 to 7.4.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13163 Add CLI tests for Capsule Content Counts
  robottelo/cli/capsule.py
  tests/foreman/cli/test_capsulecontent.py
Labels: CLI, CherryPick, Stream, 6.15.z

#13559 [6.13.z] Add Capsule Provisioning test
  conftest.py
  pytest_fixtures/component/provision_capsule_pxe.py
  pytest_plugins/fixture_markers.py
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13461 [6.13] bz1699188
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick

#13584 [6.15.z] Add CLI tests for Capsule Content Counts
  robottelo/cli/capsule.py
  tests/foreman/cli/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13575 [6.14.z] Add test for show_unsupported_templates setting
  tests/foreman/ui/test_settings.py
Labels: No-CherryPick, Failed_AutoCherryPick, AutoMerge_Cherry_Picked, 6.14.z

#13576 [6.13.z] Add test for show_unsupported_templates setting
  tests/foreman/ui/test_settings.py
Labels: No-CherryPick, Failed_AutoCherryPick, AutoMerge_Cherry_Picked, 6.13.z

#13577 [6.12.z] Add test for show_unsupported_templates setting
  tests/foreman/ui/test_settings.py
Labels: No-CherryPick, 6.12.z, Failed_AutoCherryPick, AutoMerge_Cherry_Picked

#13587 [6.15.z] Add ISS Network Sync class and basic scenario
  robottelo/cli/org.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.15.z

#13588 [6.14.z] Add ISS Network Sync class and basic scenario
  robottelo/cli/org.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#13043 Markers as test property in reports
  pytest_plugins/metadata_markers.py
  tests/foreman/virtwho/ui/test_nutanix_sca.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13500 [6.13.z] Use rsync to copy /var/lib/pulp after satellite-clone
  pytest_fixtures/component/repository.py
  tests/foreman/destructive/test_clone.py
Labels: No-CherryPick, 6.13.z

#13316 [6.12.z] Add closed loop for BZ#1841048
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13488 Add test for fapolicyd installation
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/hosts.py
  tests/foreman/installer/test_installer.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13597 [6.15.z] Add test for fapolicyd installation
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/hosts.py
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13592 [6.15.z] Markers as test property in reports
  pytest_plugins/metadata_markers.py
  tests/foreman/virtwho/ui/test_nutanix_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13593 [6.14.z] Markers as test property in reports
  pytest_plugins/metadata_markers.py
  tests/foreman/virtwho/ui/test_nutanix_sca.py
Labels: No-CherryPick, 6.14.z

#13591 [6.13.z] Markers as test property in reports
  pytest_plugins/metadata_markers.py
  tests/foreman/virtwho/ui/test_nutanix_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13601 [6.12.z] Markers as test property in reports (#13043)
  pytest_plugins/metadata_markers.py
Labels: No-CherryPick, 6.12.z

#13599 Fixing the missing markers as independent properties
  pytest_plugins/metadata_markers.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13507 Add coverage for HTTP Proxy capsule install
  tests/foreman/installer/test_installer.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13583 Test capsule without registration module
  tests/foreman/api/test_registration.py
Labels: QETestCoverage, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13611 [6.14.z] Test capsule without registration module
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13612 [6.15.z] Test capsule without registration module
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13609 [6.15.z] Add coverage for HTTP Proxy capsule install
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13618 Change team to pheonix-subscriptions to match the Hosts-Content team
  tests/foreman/ui/test_host.py
Labels: CherryPick, 6.15.z

#13606 [6.15.z] Fixing the missing markers as independent properties
  pytest_plugins/metadata_markers.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13605 [6.14.z] Fixing the missing markers as independent properties
  pytest_plugins/metadata_markers.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13604 [6.13.z] Fixing the missing markers as independent properties
  pytest_plugins/metadata_markers.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13603 [6.12.z] Fixing the missing markers as independent properties
  pytest_plugins/metadata_markers.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13621 Correct Casecomponent in upgrades/test_classparameter.py
  tests/upgrades/test_classparameter.py
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13625 [6.15.z] Correct Casecomponent in upgrades/test_classparameter.py
  tests/upgrades/test_classparameter.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13628 [6.12.z] Bump flake8 from 6.1.0 to 7.0.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13629 [6.14.z] Bump flake8 from 6.1.0 to 7.0.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13631 [6.13.z] Bump flake8 from 6.1.0 to 7.0.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13630 [6.15.z] Bump flake8 from 6.1.0 to 7.0.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13537 [6.15] Prepare for SCA only deprecation 6.15
  tests/foreman/ui/test_organization.py
Labels: No-CherryPick, 6.15.z

#13624 [6.14.z] Correct Casecomponent in upgrades/test_classparameter.py
  tests/upgrades/test_classparameter.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13623 [6.13.z] Correct Casecomponent in upgrades/test_classparameter.py
  tests/upgrades/test_classparameter.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13622 [6.12.z] Correct Casecomponent in upgrades/test_classparameter.py
  tests/upgrades/test_classparameter.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13620 Add a test for parameter precedence on the host
  tests/foreman/api/test_parameters.py
Labels: QETestCoverage, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13463 [6.15] eol banner
  tests/foreman/ui/test_eol_banner.py
Labels: No-CherryPick, 6.15.z

#13636 [6.14.z] Add a test for parameter precedence on the host
  tests/foreman/api/test_parameters.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13637 [6.15.z] Add a test for parameter precedence on the host
  tests/foreman/api/test_parameters.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13506 Add coverage for BZ#2112098
  tests/foreman/cli/test_satellitesync.py
Labels: CLI, QETestCoverage, CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13642 Fix test AK create with CV
  tests/foreman/cli/test_activationkey.py
Labels: CLI, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#13644 [6.15.z] Fix test AK create with CV
  tests/foreman/cli/test_activationkey.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13645 [6.13] users and roles test fixes
  tests/foreman/api/test_permission.py
  tests/foreman/api/test_role.py
  tests/foreman/cli/test_role.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.13.z

#13646 [6.12] users and roles test fixes
  tests/foreman/api/test_permission.py
  tests/foreman/api/test_role.py
  tests/foreman/cli/test_role.py
Labels: No-CherryPick, 6.12.z, AutoMerge_Cherry_Picked

#13635 [6.13.z] Add a test for parameter precedence on the host
  tests/foreman/api/test_parameters.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13616 Update manifest fixture in registration test to resolve conflict
  tests/foreman/api/test_registration.py
  tests/foreman/cli/test_registration.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13647 fix assert_job_invocation_status calls
  tests/foreman/cli/test_remoteexecution.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13648 fixing a forgotten make_job_invocaiton call
  tests/foreman/cli/test_remoteexecution.py
Labels: TestFailure, Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13654 [6.15.z] Update manifest fixture in registration test to resolve conflict
  tests/foreman/api/test_registration.py
  tests/foreman/cli/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13661 Small fix for SyncPlan test
  tests/foreman/cli/test_syncplan.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13664 [6.14.z] Small fix for SyncPlan test
  tests/foreman/cli/test_syncplan.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13662 [6.15.z] Small fix for SyncPlan test
  tests/foreman/cli/test_syncplan.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13665 [6.13.z] Small fix for SyncPlan test
  tests/foreman/cli/test_syncplan.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13663 [6.12.z] Small fix for SyncPlan test
  tests/foreman/cli/test_syncplan.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#13659 [6.15.z] fixing a forgotten make_job_invocaiton call
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13649 Cherrypick of 6.15 tests to 6.15.z
  tests/foreman/ui/test_host.py
Labels: No-CherryPick

#13658 [6.14.z] fixing a forgotten make_job_invocaiton call
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13657 [6.13.z] fixing a forgotten make_job_invocaiton call
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13273 Removing the direct Airgun imports from robottelo
  pytest_fixtures/core/ui.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_bookmarks.py
  tests/foreman/ui/test_branding.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_contentview_old.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_discoveryrule.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_ldap_authentication.py
  tests/foreman/ui/test_lifecycleenvironment.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_role.py
  tests/foreman/ui/test_settings.py
  tests/foreman/ui/test_subscription.py
  tests/foreman/ui/test_user.py
  tests/foreman/virtwho/conftest.py
  tests/foreman/virtwho/ui/test_esx.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13671 [6.14.z] Add coverage for BZ#2112098
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#13668 Removing stubbed marker
  tests/foreman/api/test_discoveryrule.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13687 [6.13.z] Removing stubbed marker
  tests/foreman/api/test_discoveryrule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13685 [6.14.z] Removing stubbed marker
  tests/foreman/api/test_discoveryrule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13686 [6.15.z] Removing stubbed marker
  tests/foreman/api/test_discoveryrule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13655 [6.15.z] fix assert_job_invocation_status calls
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13491 Add Ruff rule group B (flake8-bugbear)
  pyproject.toml
  robottelo/cli/base.py
  robottelo/cli/hammer.py
  robottelo/host_helpers/api_factory.py
  robottelo/host_helpers/capsule_mixins.py
  robottelo/host_helpers/cli_factory.py
  robottelo/host_helpers/repository_mixins.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/host_helpers/ui_factory.py
  robottelo/hosts.py
  robottelo/utils/decorators/func_locker.py
  robottelo/utils/decorators/func_shared/shared.py
  robottelo/utils/ohsnap.py
  robottelo/utils/virtwho.py
  tests/foreman/api/test_acs.py
  tests/foreman/api/test_ansible.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_media.py
  tests/foreman/api/test_notifications.py
  tests/foreman/api/test_organization.py
  tests/foreman/api/test_partitiontable.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_webhook.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_model.py
  tests/foreman/cli/test_partitiontable.py
  tests/foreman/cli/test_ping.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_report.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_role.py
  tests/foreman/destructive/test_capsulecontent.py
  tests/foreman/destructive/test_discoveredhost.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_remoteexecution.py
  tests/foreman/installer/test_installer.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_health.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_hostcollection.py
  tests/foreman/ui/test_sync.py
  tests/robottelo/test_func_shared.py
  tests/robottelo/test_report.py
Labels: Framework Changes, CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13670 Cherrypick discovery fixes
  tests/foreman/api/test_discoveryrule.py
Labels: No-CherryPick, 6.15.z

#13407 [Cherrypick]Prepare for sca web ui 6.15.z
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_organization.py
  tests/foreman/ui/test_subscription.py
Labels: No-CherryPick, 6.15.z

#13669 [6.15.z] Add coverage for BZ#2112098
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.15.z

#13692 [6.15.z] Add Ruff rule group B (flake8-bugbear)
  pyproject.toml
  robottelo/cli/base.py
  robottelo/cli/hammer.py
  robottelo/host_helpers/api_factory.py
  robottelo/host_helpers/capsule_mixins.py
  robottelo/host_helpers/cli_factory.py
  robottelo/host_helpers/repository_mixins.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/host_helpers/ui_factory.py
  robottelo/hosts.py
  robottelo/utils/decorators/func_locker.py
  robottelo/utils/decorators/func_shared/shared.py
  robottelo/utils/ohsnap.py
  robottelo/utils/virtwho.py
  tests/foreman/api/test_acs.py
  tests/foreman/api/test_ansible.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_media.py
  tests/foreman/api/test_notifications.py
  tests/foreman/api/test_organization.py
  tests/foreman/api/test_partitiontable.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_webhook.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_model.py
  tests/foreman/cli/test_partitiontable.py
  tests/foreman/cli/test_ping.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_report.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_role.py
  tests/foreman/destructive/test_capsulecontent.py
  tests/foreman/destructive/test_discoveredhost.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_remoteexecution.py
  tests/foreman/installer/test_installer.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_health.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_hostcollection.py
  tests/foreman/ui/test_sync.py
  tests/robottelo/test_func_shared.py
  tests/robottelo/test_report.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.15.z

#13632 virtwho config hammer deploy option name organization-title and location-id support
  pytest_fixtures/component/virtwho_config.py
  robottelo/utils/virtwho.py
  tests/foreman/virtwho/cli/test_esx_sca.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#13705 [6.12.z] Bump kentaro-m/auto-assign-action from 1.2.5 to 1.2.6
  .github/workflows/auto_assignment.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13707 [6.12] fixing a forgotten make_job_invocaiton call
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, 6.12.z, AutoMerge_Cherry_Picked

#13708 Fix domain read in discovery auto provision test
  tests/foreman/ui/test_discoveredhost.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13703 [6.15.z] Bump kentaro-m/auto-assign-action from 1.2.5 to 1.2.6
  .github/workflows/auto_assignment.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13712 [6.15.z] Fix domain read in discovery auto provision test
  tests/foreman/ui/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13711 [6.14.z] Fix domain read in discovery auto provision test
  tests/foreman/ui/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13695 [6.14.z] Add Ruff rule group B (flake8-bugbear)
  pyproject.toml
  robottelo/cli/base.py
  robottelo/cli/hammer.py
  robottelo/host_helpers/api_factory.py
  robottelo/host_helpers/capsule_mixins.py
  robottelo/host_helpers/cli_factory.py
  robottelo/host_helpers/repository_mixins.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/host_helpers/ui_factory.py
  robottelo/hosts.py
  robottelo/utils/decorators/func_locker.py
  robottelo/utils/decorators/func_shared/shared.py
  robottelo/utils/ohsnap.py
  robottelo/utils/virtwho.py
  tests/foreman/api/test_acs.py
  tests/foreman/api/test_ansible.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_media.py
  tests/foreman/api/test_notifications.py
  tests/foreman/api/test_organization.py
  tests/foreman/api/test_partitiontable.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_webhook.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_model.py
  tests/foreman/cli/test_partitiontable.py
  tests/foreman/cli/test_ping.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_report.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_role.py
  tests/foreman/destructive/test_capsulecontent.py
  tests/foreman/destructive/test_discoveredhost.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_remoteexecution.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_health.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_hostcollection.py
  tests/foreman/ui/test_sync.py
  tests/robottelo/test_func_shared.py
  tests/robottelo/test_report.py
Labels: Framework Changes, No-CherryPick, 6.14.z

#13696 [6.13.z] Add Ruff rule group B (flake8-bugbear)
  pyproject.toml
  robottelo/cli/base.py
  robottelo/cli/hammer.py
  robottelo/host_helpers/api_factory.py
  robottelo/host_helpers/capsule_mixins.py
  robottelo/host_helpers/cli_factory.py
  robottelo/host_helpers/repository_mixins.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/host_helpers/ui_factory.py
  robottelo/hosts.py
  robottelo/utils/decorators/func_locker.py
  robottelo/utils/decorators/func_shared/shared.py
  robottelo/utils/ohsnap.py
  robottelo/utils/virtwho.py
  tests/foreman/api/test_acs.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_media.py
  tests/foreman/api/test_organization.py
  tests/foreman/api/test_partitiontable.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_webhook.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_model.py
  tests/foreman/cli/test_partitiontable.py
  tests/foreman/cli/test_ping.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_report.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_role.py
  tests/foreman/destructive/test_capsulecontent.py
  tests/foreman/destructive/test_discoveredhost.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_remoteexecution.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_health.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_hostcollection.py
  tests/foreman/ui/test_sync.py
  tests/robottelo/test_func_shared.py
  tests/robottelo/test_report.py
Labels: Framework Changes, No-CherryPick, 6.13.z

#13715 Removing changes associated with Bugbear rule B019
  pyproject.toml
  robottelo/host_helpers/cli_factory.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
Labels: Bug, Urgent Priority, Framework Changes, CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13716 [6.15.z] Removing changes associated with Bugbear rule B019
  pyproject.toml
  robottelo/host_helpers/cli_factory.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13717 [6.13.z] Removing changes associated with Bugbear rule B019
  pyproject.toml
  robottelo/host_helpers/cli_factory.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13718 [6.14.z] Removing changes associated with Bugbear rule B019
  pyproject.toml
  robottelo/host_helpers/cli_factory.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13697 [6.12.z] Add Ruff rule group B (flake8-bugbear)
  pyproject.toml
  robottelo/cli/base.py
  robottelo/cli/hammer.py
  robottelo/host_helpers/api_factory.py
  robottelo/host_helpers/capsule_mixins.py
  robottelo/host_helpers/cli_factory.py
  robottelo/host_helpers/repository_mixins.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/host_helpers/ui_factory.py
  robottelo/hosts.py
  robottelo/utils/decorators/func_locker.py
  robottelo/utils/decorators/func_shared/shared.py
  robottelo/utils/ohsnap.py
  robottelo/utils/virtwho.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_media.py
  tests/foreman/api/test_organization.py
  tests/foreman/api/test_partitiontable.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_role.py
  tests/foreman/api/test_webhook.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_model.py
  tests/foreman/cli/test_partitiontable.py
  tests/foreman/cli/test_ping.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_report.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_role.py
  tests/foreman/destructive/test_capsulecontent.py
  tests/foreman/destructive/test_discoveredhost.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_remoteexecution.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_health.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_hostcollection.py
  tests/foreman/ui/test_sync.py
  tests/robottelo/test_func_shared.py
  tests/robottelo/test_report.py
Labels: Framework Changes, No-CherryPick, 6.12.z

#13714 fixing the incorrect recording video url
  robottelo/hosts.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#13720 [6.14.z] fixing the incorrect recording video url
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13722 [6.15.z] fixing the incorrect recording video url
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13721 [6.13.z] fixing the incorrect recording video url
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13723 [6.12.z] Removing changes associated with Bugbear rule B019
  pyproject.toml
  robottelo/host_helpers/cli_factory.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13731 [6.13.z] Bump jinja2 from 3.1.2 to 3.1.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13737 Non tabular output denied for CSV conversion
  robottelo/cli/hammer.py
Labels: Urgent Priority, Framework Changes, CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z, Critical Severity

#13744 [6.15.z] Non tabular output denied for CSV conversion
  robottelo/cli/hammer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13745 [6.14.z] Non tabular output denied for CSV conversion
  robottelo/cli/hammer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13743 [6.13.z] Non tabular output denied for CSV conversion
  robottelo/cli/hammer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13747 [6.13.z] Increasing the timeout for mac collection
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/ui/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13748 [6.15.z] Increasing the timeout for mac collection
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/ui/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13756 [6.15.z] Fixes in cli_factory
  robottelo/cli/repository.py
  robottelo/host_helpers/cli_factory.py
Labels: No-CherryPick, 6.15.z

#13758 [6.13.z] Fixes in cli_factory
  robottelo/cli/repository.py
  robottelo/host_helpers/cli_factory.py
Labels: No-CherryPick, 6.13.z

#13759 [6.12.z] Fixes in cli_factory
  robottelo/cli/repository.py
  robottelo/host_helpers/cli_factory.py
Labels: No-CherryPick, 6.12.z

#13760 Add missing on_premises_provisioning marker for capsule provisioning test
  tests/foreman/api/test_provisioning.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13755 [6.15.z] Refactor and simplify ping test
  tests/foreman/cli/test_ping.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13757 [6.14.z] Fixes in cli_factory
  robottelo/cli/repository.py
  robottelo/host_helpers/cli_factory.py
Labels: No-CherryPick, 6.14.z

#13762 [6.15.z] Add missing on_premises_provisioning marker for capsule provisioning test
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13761 [6.14.z] Add missing on_premises_provisioning marker for capsule provisioning test
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13763 [6.13.z] Add missing on_premises_provisioning marker for capsule provisioning test
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13544 Add CU scenario for puma worker count
  tests/foreman/destructive/test_installer.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13765 [6.14.z] Add CU scenario for puma worker count
  tests/foreman/destructive/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13749 [6.14.z] Increasing the timeout for mac collection
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/ui/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13702 [6.15.z] virtwho config hammer deploy option name organization-title and location-id support
  pytest_fixtures/component/virtwho_config.py
  robottelo/utils/virtwho.py
  tests/foreman/virtwho/cli/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13701 [6.14.z] virtwho config hammer deploy option name organization-title and location-id support
  pytest_fixtures/component/virtwho_config.py
  robottelo/utils/virtwho.py
  tests/foreman/virtwho/cli/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13700 [6.13.z] virtwho config hammer deploy option name organization-title and location-id support
  pytest_fixtures/component/virtwho_config.py
  robottelo/utils/virtwho.py
  tests/foreman/virtwho/cli/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13732 [6.15.z] Bump jinja2 from 3.1.2 to 3.1.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13733 [6.14.z] Bump jinja2 from 3.1.2 to 3.1.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13673 [6.13.z] Add coverage for BZ#2112098
  robottelo/cli/org.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.13.z

#13684 [6.14.z] - Removing the direct Airgun imports from robottelo
  pytest_fixtures/core/ui.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_bookmarks.py
  tests/foreman/ui/test_branding.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_discoveryrule.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_ldap_authentication.py
  tests/foreman/ui/test_lifecycleenvironment.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_role.py
  tests/foreman/ui/test_settings.py
  tests/foreman/ui/test_subscription.py
  tests/foreman/ui/test_user.py
  tests/foreman/virtwho/conftest.py
  tests/foreman/virtwho/ui/test_esx.py
Labels: No-CherryPick, 6.14.z

#13678 [6.12.z] Add coverage for BZ#2112098
  robottelo/cli/org.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, 6.12.z, Failed_AutoCherryPick

#13713 Cleanup video recording
  conf/ui.yaml.template
  pytest_plugins/video_cleanup.py
  robottelo/hosts.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#13740 [6.13.z] - Removing the direct Airgun imports from robottelo
  pytest_fixtures/core/ui.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_bookmarks.py
  tests/foreman/ui/test_branding.py
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_dashboard.py
  tests/foreman/ui/test_discoveryrule.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_ldap_authentication.py
  tests/foreman/ui/test_lifecycleenvironment.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_role.py
  tests/foreman/ui/test_settings.py
  tests/foreman/ui/test_subscription.py
  tests/foreman/ui/test_user.py
  tests/foreman/virtwho/conftest.py
  tests/foreman/virtwho/ui/test_esx.py
Labels: No-CherryPick

#13771 [6.15.z] Cleanup video recording
  conf/ui.yaml.template
  pytest_plugins/video_cleanup.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13770 [6.14.z] Cleanup video recording
  conf/ui.yaml.template
  pytest_plugins/video_cleanup.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13769 [6.13.z] Cleanup video recording
  conf/ui.yaml.template
  pytest_plugins/video_cleanup.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13768 http proxy create location option support
  robottelo/utils/virtwho.py
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_esx_sca.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_esx_sca.py
  tests/foreman/virtwho/ui/test_esx.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#13766 [6.13.z] Add CU scenario for puma worker count
  tests/foreman/destructive/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13773 [6.15.z] http proxy create location option support
  robottelo/utils/virtwho.py
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_esx_sca.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_esx_sca.py
  tests/foreman/virtwho/ui/test_esx.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13774 [6.14.z] http proxy create location option support
  robottelo/utils/virtwho.py
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_esx_sca.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_esx_sca.py
  tests/foreman/virtwho/ui/test_esx.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13775 [6.13.z] http proxy create location option support
  robottelo/utils/virtwho.py
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_esx_sca.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_esx_sca.py
  tests/foreman/virtwho/ui/test_esx.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13772 Add module_sync_kickstart_content to fixture_markers.py
  pytest_fixtures/component/provisioning_template.py
  pytest_plugins/fixture_markers.py
  tests/foreman/api/test_provisioningtemplate.py
  tests/foreman/cli/test_bootdisk.py
  tests/foreman/destructive/test_infoblox.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13754 Adding fix for discoveryrule UI
  tests/foreman/ui/test_discoveryrule.py
Labels: UI, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13780 [6.13.z] Adding fix for discoveryrule UI
  tests/foreman/ui/test_discoveryrule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13781 [6.15.z] Adding fix for discoveryrule UI
  tests/foreman/ui/test_discoveryrule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13602 Component Evaluation - add RHEL 8 and 9 host versions
  tests/foreman/ui/test_host.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#13783 [6.14.z] Component Evaluation - add RHEL 8 and 9 host versions
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13296 [Customer Case]Adding test for invalid release version
  tests/foreman/cli/test_activationkey.py
Labels: CLI, CherryPick, 6.14.z, 6.15.z

#13784 adding logic to remove passed tests video url from junit xml
  pytest_plugins/video_cleanup.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13789 [6.15.z] adding logic to remove passed tests video url from junit xml
  pytest_plugins/video_cleanup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13787 [6.14.z] adding logic to remove passed tests video url from junit xml
  pytest_plugins/video_cleanup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13790 [6.13.z] adding logic to remove passed tests video url from junit xml
  pytest_plugins/video_cleanup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13788 [6.12.z] adding logic to remove passed tests video url from junit xml
  pytest_plugins/video_cleanup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13776 [6.15.z] Add module_sync_kickstart_content to fixture_markers.py
  pytest_fixtures/component/provisioning_template.py
  pytest_plugins/fixture_markers.py
  tests/foreman/api/test_provisioningtemplate.py
  tests/foreman/cli/test_bootdisk.py
  tests/foreman/destructive/test_infoblox.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13589 Add test case for ISS export with history ID
  robottelo/cli/content_export.py
  tests/foreman/cli/test_satellitesync.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13793 [6.14.z] Add test case for ISS syncable CV export/import
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13792 [6.15.z] Add test case for ISS syncable CV export/import
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13796 [6.14.z] Add test case for ISS export with history ID
  robottelo/cli/content_export.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13794 [6.13.z] Add test case for ISS export with history ID
  robottelo/cli/content_export.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13782 [6.15.z] Component Evaluation - add RHEL 8 and 9 host versions
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z
