Repository SatelliteQE/robottelo, pull requests merged in 2024-08, with the labels that each got.

#15162 test timeout_to_kill
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15607 removing attach and auto-attach related items from cli hosts
  tests/foreman/cli/test_host.py
Labels: No-CherryPick

#15828 [6.14.z] Bump manifester from 0.2.6 to 0.2.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#15827 [6.13.z] Bump manifester from 0.2.6 to 0.2.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#15829 [6.15.z] Bump manifester from 0.2.6 to 0.2.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#15822 [6.14.z] CSV formatting fixes
  robottelo/cli/hammer.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/destructive/test_auth.py
Labels: CLI, No-CherryPick, 6.14.z, PRT-Passed

#15823 [6.15.z] CSV formatting fixes
  pytest_fixtures/component/satellite_auth.py
  robottelo/cli/hammer.py
  tests/foreman/cli/test_ldapauthsource.py
  tests/foreman/destructive/test_auth.py
Labels: CLI, No-CherryPick, 6.15.z, PRT-Passed

#15733 Add test for VMware image based provisioning
  pytest_fixtures/component/provision_vmware.py
  tests/foreman/cli/test_computeresource_vmware.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#15811 Add automation for BZ 2168494
  conftest.py
  pytest_fixtures/component/leapp_client.py
  tests/foreman/ui/test_leapp_client.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#15842 Add manifester_inventory to ignored files
  .gitignore
Labels: Easy Fix :), CherryPick, 6.13.z, 6.14.z, 6.15.z

#15846 Fix PR #15726 for missing unpushed changes
  tests/upgrades/test_capsule.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14940 [6.16]Podman Push - Podman Push Create and CV tests
  tests/foreman/api/test_docker.py
Labels: No-CherryPick, Stream, PRT-Passed

#15843 [6.15.z] Add manifester_inventory to ignored files
  .gitignore
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15850 CE-yum and docker repos support download policy
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Stream, PRT-Passed

#15856 [6.13.z] Bump broker[docker,hussh,podman] from 0.5.1 to 0.5.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15855 [6.14.z] Bump broker[docker,hussh,podman] from 0.5.1 to 0.5.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15857 [6.15.z] Bump broker[docker,hussh,podman] from 0.5.1 to 0.5.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15858 [6.14.z] Bump wrapanapi from 3.6.0 to 3.6.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#15859 [6.15.z] Bump wrapanapi from 3.6.0 to 3.6.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#15862 capsule upgrade playbook test adjustments
  tests/foreman/api/test_remoteexecution.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#15865 [6.15.z] capsule upgrade playbook test adjustments
  tests/foreman/api/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15866 [6.13.z] capsule upgrade playbook test adjustments
  tests/foreman/api/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15860 [6.13.z] Bump wrapanapi from 3.6.0 to 3.6.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#15869 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15868 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15874 [6.14.z] Bump pyyaml from 6.0.1 to 6.0.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15875 [6.13.z] Bump pyyaml from 6.0.1 to 6.0.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15847 [6.15.z] Fix PR #15726 for missing unpushed changes
  tests/upgrades/test_capsule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#15848 [6.14.z] Fix PR #15726 for missing unpushed changes
  tests/upgrades/test_capsule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#15849 [6.13.z] Fix PR #15726 for missing unpushed changes
  tests/upgrades/test_capsule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#15845 [6.14.z] Add manifester_inventory to ignored files
  .gitignore
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15841 [6.13.z] Bump flake8 from 7.1.0 to 7.1.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15839 [6.14.z] Bump flake8 from 7.1.0 to 7.1.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15840 [6.15.z] Bump flake8 from 7.1.0 to 7.1.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15873 [6.15.z] Bump pyyaml from 6.0.1 to 6.0.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15844 [6.13.z] Add manifester_inventory to ignored files
  .gitignore
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15824 Add Satellite Network Type Attribute to Results
  pytest_plugins/metadata_markers.py
Labels: Framework Changes, CherryPick, 6.15.z

#15876 [6.15.z] Add Satellite Network Type Attribute to Results
  pytest_plugins/metadata_markers.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15395 Remove use of install_katello_ca with register_contenthost
  pytest_fixtures/component/rh_cloud.py
  robottelo/hosts.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_http_proxy.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/endtoend/test_api_endtoend.py
  tests/foreman/endtoend/test_cli_endtoend.py
  tests/foreman/installer/test_installer.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_hostcontent.py
  tests/upgrades/test_repository.py
  tests/upgrades/test_subscription.py
Labels: No-CherryPick, Stream, PRT-Failed

#15818 Add end-to-end test for facts
  robottelo/host_helpers/contenthost_mixins.py
  tests/foreman/cli/test_fact.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#15888 [6.14.z] Add end-to-end test for facts
  robottelo/host_helpers/contenthost_mixins.py
  tests/foreman/cli/test_fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#15887 [6.15.z] Add end-to-end test for facts
  robottelo/host_helpers/contenthost_mixins.py
  tests/foreman/cli/test_fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15891 Remove satellite6-upgrade traces from .gitignore
  .gitignore
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#15894 [6.15.z] Remove satellite6-upgrade traces from .gitignore
  .gitignore
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15895 [6.14.z] Remove satellite6-upgrade traces from .gitignore
  .gitignore
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15893 [6.13.z] Remove satellite6-upgrade traces from .gitignore
  .gitignore
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15896 Bump broker to 0.5.3
  requirements.txt
Labels: Urgent Priority, dependencies, CherryPick, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#15861 fix in computeresource_rhev
  tests/foreman/cli/test_computeresource_rhev.py
Labels: Easy Fix :), No-CherryPick, Stream, PRT-Failed

#15899 [6.15.z] Bump broker to 0.5.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#15897 [6.13.z] Bump broker to 0.5.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#15898 [6.14.z] Bump broker to 0.5.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#15890 updated the gha to handle extras e.g. broker[docker,hussh,podman]
  .github/workflows/dependency_merge.yml
Labels: No-CherryPick

#15886 Update package install in registration test
  tests/foreman/ui/test_registration.py
Labels: TestFailure, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#15900 [6.15.z] Update package install in registration test
  tests/foreman/ui/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#15795 [RFE] Updating all Repository tests to be SCA only
  tests/foreman/api/test_product.py
  tests/foreman/api/test_repositories.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_repository_set.py
  tests/foreman/cli/test_repositories.py
  tests/foreman/cli/test_repository_set.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/destructive/test_repository.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
  tests/upgrades/test_repository.py
Labels: RFE, No-CherryPick, Stream

#15882 Comp Eval-Combine all possible scenarios from api product and api repository
  robottelo/utils/datafactory.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_repository.py
Labels: No-CherryPick, Stream, PRT-Passed

#15812 [Task 1 - Customer Scenario Checks] Replacing Migrated BZs docstrings token to Jira based
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_computeresource_vmware.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_oscap.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_report.py
  tests/foreman/destructive/test_clone.py
  tests/foreman/destructive/test_fm_upgrade.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_discoveredhost.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
  tests/foreman/ui/test_subscription.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#15906 Set organization and location in end_to_end test
  tests/foreman/ui/test_registration.py
Labels: TestFailure, No-CherryPick, 6.13.z, PRT-Passed

#15883 Remove cpu_mode option from Libvirt provisioning tests
  tests/foreman/cli/test_computeresource_libvirt.py
  tests/foreman/data/hammer_commands.json
  tests/foreman/ui/test_computeresource_libvirt.py
Labels: No-CherryPick, Stream, PRT-Failed

#15740 Add coverage for VMware NVME controllers
  tests/foreman/api/test_computeresource_vmware.py
Labels: QETestCoverage, No-CherryPick, Stream, PRT-Passed

#15802 Check ansible playbook after job schedule...
  tests/foreman/api/test_ansible.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#15916 [6.15.z] Check ansible playbook after job schedule...
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15915 [6.14.z] Check ansible playbook after job schedule...
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#15920 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15921 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15919 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15911 pit marker for oscap
  tests/foreman/cli/test_oscap_tailoringfiles.py
  tests/foreman/longrun/test_oscap.py
Labels: No-CherryPick

#15912 [Comp Eval] Remove extra docker test
  tests/foreman/ui/test_repository.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.14.z, 6.15.z

#15770 Config report following both the failed and successful job runs.
  tests/foreman/ui/test_ansible.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#15928 [6.15.z] Config report following both the failed and successful job runs.
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15870 Add coverage for katello-ca certificate refresh
  tests/foreman/api/test_registration.py
Labels: QETestCoverage, No-CherryPick, Stream, PRT-Passed

#15877 Remove flake8
  docs/code_standards.rst
  docs/committing.rst
  requirements-optional.txt
  tests/foreman/endtoend/test_api_endtoend.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#15929 [6.14.z] Config report following both the failed and successful job runs.
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#15936 [6.15.z] Remove flake8
  docs/code_standards.rst
  docs/committing.rst
  requirements-optional.txt
  tests/foreman/endtoend/test_api_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#15935 [6.14.z] Remove flake8
  docs/code_standards.rst
  docs/committing.rst
  requirements-optional.txt
  tests/foreman/endtoend/test_api_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#15934 [6.13.z] Remove flake8
  docs/code_standards.rst
  docs/committing.rst
  requirements-optional.txt
  tests/foreman/endtoend/test_api_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#15926 [6.15.z] [Comp Eval] Remove extra docker test
  tests/foreman/ui/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#15925 [6.14.z] [Comp Eval] Remove extra docker test
  tests/foreman/ui/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#15924 Remove virt-who plugin non_sca cases for SCA-compliant
  tests/foreman/virtwho/api/test_esx.py
  tests/foreman/virtwho/api/test_hyperv.py
  tests/foreman/virtwho/api/test_kubevirt.py
  tests/foreman/virtwho/api/test_libvirt.py
  tests/foreman/virtwho/api/test_nutanix.py
  tests/foreman/virtwho/cli/test_esx.py
  tests/foreman/virtwho/cli/test_hyperv.py
  tests/foreman/virtwho/cli/test_kubevirt.py
  tests/foreman/virtwho/cli/test_libvirt.py
  tests/foreman/virtwho/cli/test_nutanix.py
  tests/foreman/virtwho/ui/test_esx.py
  tests/foreman/virtwho/ui/test_hyperv.py
  tests/foreman/virtwho/ui/test_kubevirt.py
  tests/foreman/virtwho/ui/test_libvirt.py
  tests/foreman/virtwho/ui/test_nutanix.py
Labels: No-CherryPick, Stream

#15922 Add a test case for export/import large file repo
  conf/repos.yaml.template
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick

#15913 Add test coverage for Manage packages feature
  pytest_fixtures/core/contenthosts.py
  pytest_plugins/fixture_markers.py
  tests/foreman/ui/test_host.py
Labels: UI, No-CherryPick, Stream

#15892 PIT markers for Interoperability Testing: CapsuleContent
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/ui/test_capsulecontent.py
Labels: CherryPick, Stream, 6.15.z

#15833 Add hdm to installer's UPSTREAM_SPECIFIC_MODULES & fix comparison
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick

#15946 [6.13.z] Bump ruff from 0.5.7 to 0.6.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15945 [6.15.z] Bump ruff from 0.5.7 to 0.6.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15943 [6.15.z] PIT markers for Interoperability Testing: CapsuleContent (#15892)
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/ui/test_capsulecontent.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#15933 Verify port 8443 is disabled on default capsule installation
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Stream, PRT-Passed

#15955 [6.14.z] Bump ruff from 0.6.0 to 0.6.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15956 [6.13.z] Bump ruff from 0.6.0 to 0.6.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15957 [6.15.z] Bump ruff from 0.6.0 to 0.6.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15942 Update ui.yaml.template to match the production config
  conf/ui.yaml.template
Labels: No-CherryPick

#15940 pit marker for webhook test
  tests/foreman/cli/test_webhook.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#15961 [6.15.z] pit marker for webhook test
  tests/foreman/cli/test_webhook.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15962 [6.14.z] pit marker for webhook test
  tests/foreman/cli/test_webhook.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15963 [6.13.z] pit marker for webhook test
  tests/foreman/cli/test_webhook.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15958 FAM: only setup libvirt for tests that need them
  robottelo/constants/__init__.py
  tests/foreman/sys/test_fam.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Failed

#15871 Add tests for multi-CV hosts
  pytest_fixtures/component/contentview.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Stream

#15595 Automate a stubbed test to install Ansible collection from galaxy
  tests/foreman/cli/test_ansible.py
  tests/foreman/ui/test_ansible.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#15973 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15974 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15975 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15964 passing ipv6 params valued for direct Host calls
  pytest_plugins/video_cleanup.py
  robottelo/hosts.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#15949 search syntax fixes in host tests
  tests/foreman/cli/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#15880 Add tests for multiCV assignment with Hammer
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Stream, PRT-Passed

#15951 [6.13.z cp] Config report following both the failed and successful job runs.
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, 6.13.z, PRT-Passed

#15952 Add test coverage for ansible-playbook job with nonexisting_module
  tests/foreman/api/test_ansible.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#15979 [6.15.z] passing ipv6 params valued for direct Host calls
  pytest_plugins/video_cleanup.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15977 [6.14.z] passing ipv6 params valued for direct Host calls
  pytest_plugins/video_cleanup.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15986 [6.14.z] Add test coverage for ansible-playbook job with nonexisting_module
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#15987 [6.15.z] Add test coverage for ansible-playbook job with nonexisting_module
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15645 [6.14.z] Retry/Rerun PR Autocherrypick post merge
  .github/workflows/auto_cherry_pick_merged.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15644 [6.13.z] Retry/Rerun PR Autocherrypick post merge
  .github/workflows/auto_cherry_pick_merged.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15643 [6.15.z] Retry/Rerun PR Autocherrypick post merge
  .github/workflows/auto_cherry_pick_merged.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15983 Check for certs tar existence in Capsule backup
  tests/foreman/maintain/test_backup_restore.py
Labels: No-CherryPick, Stream, PRT-Passed

#15950 Remove Best Practices Guide - moved to wiki
  BEST_PRACTICES.md
Labels: Documentation, No-CherryPick, maintenance

#15990 Select activation key explicitly because of SAT-27348
  tests/foreman/ui/test_registration.py
Labels: TestFailure, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#15995 [6.16.z] Select activation key explicitly because of SAT-27348
  tests/foreman/ui/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#15878 Jira replacing bz for customer scenarios check
  .github/workflows/weekly.yml
  Makefile
  conf/dynaconf_hooks.py
  robottelo/utils/issue_handlers/jira.py
  scripts/customer_scenarios.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#15932 Satisfy validators, enable template config validation
  .github/workflows/pull_request.yml
  conf/capsule.yaml.template
  conf/gce.yaml.template
  conf/rh_cloud.yaml.template
  robottelo/config/__init__.py
  settings.sample.yaml
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#15881 adding the support for ipv4 and ipv6 parameterization for Container and VM
  pytest_fixtures/core/contenthosts.py
  pytest_plugins/fixture_markers.py
  robottelo/hosts.py
  robottelo/ssh.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#15509 [6.13.z] Add tests for Facts component
  robottelo/host_helpers/contenthost_mixins.py
  tests/foreman/cli/test_fact.py
  tests/foreman/ui/test_fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#15996 Remove ansible role assign and remove stubbed tests
  tests/foreman/ui/test_ansible.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#15993 [6.15.z] FAM: only setup libvirt for tests that need them (#15958)
  robottelo/constants/__init__.py
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, 6.15.z, PRT-Failed

#16008 [6.16.z] Remove ansible role assign and remove stubbed tests
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#16009 [6.14.z] Remove ansible role assign and remove stubbed tests
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#16010 [6.13.z] Remove ansible role assign and remove stubbed tests
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#15992 [6.16.z] FAM: only setup libvirt for tests that need them (#15958)
  robottelo/constants/__init__.py
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, PRT-Failed, 6.16.z

#15968 [6.14.z] FAM: only setup libvirt for tests that need them
  robottelo/constants/__init__.py
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Failed

#16013 Fixing the sha field
  .github/workflows/auto_cherry_pick_merged.yaml
Labels: dependencies, CherryPick, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16015 [6.15.z] Fixing the sha field
  .github/workflows/auto_cherry_pick_merged.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16014 [6.14.z] Fixing the sha field
  .github/workflows/auto_cherry_pick_merged.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16017 [6.13.z] Fixing the sha field
  .github/workflows/auto_cherry_pick_merged.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16016 [6.16.z] Fixing the sha field
  .github/workflows/auto_cherry_pick_merged.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#15788 [6.14.z] Fix failing registration tests
  tests/foreman/api/test_registration.py
  tests/foreman/ui/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#15989 Fix search syntax fixes forgotten in
  tests/foreman/cli/test_host.py
Labels: CherryPick, 6.16.z

#16021 [6.16.z] Fix search syntax fixes forgotten in
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#16020 Fix reporttemplate test
  tests/foreman/cli/test_reporttemplates.py
Labels: CherryPick, 6.16.z

#15984 Fix cli host tests by applying pattern from similar test
  tests/foreman/cli/test_host.py
Labels: CherryPick, 6.16.z

#16018 [6.16.z] Remove Best Practices Guide - moved to wiki
  BEST_PRACTICES.md
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16019 [6.15.z] Remove Best Practices Guide - moved to wiki
  BEST_PRACTICES.md
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16007 [6.16] add test for bulk Hostgroup change
  tests/foreman/ui/test_host.py
Labels: CherryPick, Stream, 6.16.z

#15931 Remove install_katello_ca for good
  pytest_fixtures/core/contenthosts.py
  robottelo/hosts.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.16.z

#16028 [6.16.z] Remove install_katello_ca for good
  pytest_fixtures/core/contenthosts.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#15908 [6.15.z][Task 1 - Customer Scenario Checks] Replacing Migrated BZs docstrings token to Jira based
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_computeresource_vmware.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_report.py
  tests/foreman/destructive/test_clone.py
  tests/foreman/destructive/test_fm_upgrade.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_discoveredhost.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.15.z

#15651 Add PIT markers to ACS and ISS components
  tests/foreman/cli/test_acs.py
  tests/foreman/cli/test_satellitesync.py
Labels: CherryPick, 6.14.z, 6.15.z, PRT-Failed, 6.16.z

#16032 Fix sanitized_issue_data helper of jira issue handler
  robottelo/utils/issue_handlers/jira.py
Labels: CherryPick, 6.13.z, Stream, 6.14.z, 6.15.z, 6.16.z

#15884 [6.16]Add test for podman push on capsule
  tests/foreman/api/test_capsulecontent.py
Labels: CherryPick, Stream, PRT-Passed, 6.16.z

#15909 [6.14.z][Task 1 - Customer Scenario Checks] Replacing Migrated BZs docstrings token to Jira based
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_report.py
  tests/foreman/destructive/test_clone.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#15910 [6.13.z][Task 1 - Customer Scenario Checks] Replacing Migrated BZs docstrings token to Jira based
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_report.py
  tests/foreman/destructive/test_clone.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.13.z

#16034 [6.14.z] Add PIT markers to ACS and ISS components
  tests/foreman/cli/test_acs.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Failed
