Repository SatelliteQE/robottelo, pull requests merged in 2024-04, with the labels that each got.

#14567 Move RHCloud tests to team Phoenix-subscriptions
  tests/foreman/api/test_rhc.py
  tests/foreman/api/test_rhcloud_inventory.py
  tests/foreman/cli/test_rhcloud_inventory.py
  tests/foreman/ui/test_rhc.py
  tests/foreman/ui/test_rhcloud_insights.py
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14580 [6.13.z] Move RHCloud tests to team Phoenix-subscriptions
  tests/foreman/api/test_rhc.py
  tests/foreman/api/test_rhcloud_inventory.py
  tests/foreman/cli/test_rhcloud_inventory.py
  tests/foreman/ui/test_rhc.py
  tests/foreman/ui/test_rhcloud_insights.py
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14579 [6.14.z] Move RHCloud tests to team Phoenix-subscriptions
  tests/foreman/api/test_rhc.py
  tests/foreman/api/test_rhcloud_inventory.py
  tests/foreman/cli/test_rhcloud_inventory.py
  tests/foreman/ui/test_rhc.py
  tests/foreman/ui/test_rhcloud_insights.py
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14582 [6.12.z] Move RHCloud tests to team Phoenix-subscriptions
  tests/foreman/api/test_rhc.py
  tests/foreman/api/test_rhcloud_inventory.py
  tests/foreman/cli/test_rhcloud_inventory.py
  tests/foreman/ui/test_rhc.py
  tests/foreman/ui/test_rhcloud_insights.py
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14581 [6.15.z] Move RHCloud tests to team Phoenix-subscriptions
  tests/foreman/api/test_rhc.py
  tests/foreman/api/test_rhcloud_inventory.py
  tests/foreman/cli/test_rhcloud_inventory.py
  tests/foreman/ui/test_rhc.py
  tests/foreman/ui/test_rhcloud_insights.py
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14143 host name & value updated with subnet
  tests/foreman/api/test_subnet.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#14586 [6.14.z] host name & value updated with subnet
  tests/foreman/api/test_subnet.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14585 [6.15.z] host name & value updated with subnet
  tests/foreman/api/test_subnet.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14558 zStream Checks for Python 3.12
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  robottelo/cli/base.py
  robottelo/cli/subscription.py
  tests/robottelo/test_cli.py
  tests/robottelo/test_cli_method_calls.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#14572 cu-case-katello-reimport-scenario
  robottelo/constants/__init__.py
  tests/foreman/cli/test_subscription.py
  tests/foreman/data/expired-manifest.zip
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#14590 [6.14.z] cu-case-katello-reimport-scenario
  robottelo/constants/__init__.py
  tests/foreman/cli/test_subscription.py
  tests/foreman/data/expired-manifest.zip
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14525 [6.15.z] ErrataManagement UI: Update show_count, and errata_tab_pagination cases
  tests/foreman/ui/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14571 [6.14.z] Add case for special chars in HTTP proxy password
  pytest_fixtures/component/http_proxy.py
  robottelo/host_helpers/api_factory.py
  robottelo/hosts.py
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14595 [6.14.z] Bump pytest-order from 1.2.0 to 1.2.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14594 [6.12.z] Bump pytest-order from 1.2.0 to 1.2.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14596 [6.13.z] Bump pytest-order from 1.2.0 to 1.2.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14597 [6.15.z] Bump pytest-order from 1.2.0 to 1.2.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14583 Fix foreman service test
  tests/foreman/maintain/test_service.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14601 [6.14.z] zStream Checks for Python 3.12 (#14558)
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  robottelo/cli/base.py
  robottelo/cli/subscription.py
  tests/robottelo/test_cli.py
  tests/robottelo/test_cli_method_calls.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#14600 [6.14.z] Fix foreman service test
  tests/foreman/maintain/test_service.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14598 [6.15.z] Fix foreman service test
  tests/foreman/maintain/test_service.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14602 [6.13.z] zStream Checks for Python 3.12 (#14558)
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  robottelo/cli/base.py
  robottelo/cli/subscription.py
  tests/robottelo/test_cli.py
  tests/robottelo/test_cli_method_calls.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.13.z

#14599 [6.13.z] Fix foreman service test
  tests/foreman/maintain/test_service.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14603 [6.12.z] zStream Checks for Python 3.12 (#14558)
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  robottelo/cli/base.py
  robottelo/cli/subscription.py
  tests/robottelo/test_cli.py
  tests/robottelo/test_cli_method_calls.py
Labels: No-CherryPick, 6.12.z, Failed_AutoCherryPick

#14577 Move TestAnsibleREX CLI tests to Ansible module
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_remoteexecution.py
Labels: CLI, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14604 [6.15.z] cu-case-katello-reimport-scenario
  robottelo/constants/__init__.py
  tests/foreman/cli/test_subscription.py
  tests/foreman/data/expired-manifest.zip
Labels: No-CherryPick, Failed_AutoCherryPick, AutoMerge_Cherry_Picked, 6.15.z

#14608 Docker repos now support on demand policy
  tests/foreman/api/test_repository.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14610 [6.15.z] Docker repos now support on demand policy
  tests/foreman/api/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14317 Update Platform tests that have hard coded content host versions
  pytest_fixtures/core/contenthosts.py
  pytest_plugins/fixture_markers.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/maintain/test_upgrade.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14612 [6.14.z] Update Platform tests that have hard coded content host versions
  pytest_fixtures/core/contenthosts.py
  pytest_plugins/fixture_markers.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/maintain/test_upgrade.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14617 [6.13.z] Update Platform tests that have hard coded content host versions
  pytest_fixtures/core/contenthosts.py
  pytest_plugins/fixture_markers.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/maintain/test_upgrade.py
Labels: No-CherryPick, 6.13.z, PRT-Passed

#14494 Errata with swidtags setup and modular update
  tests/foreman/api/test_errata.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.14.z, 6.15.z

#14618 [6.15.z] Errata with swidtags setup and modular update
  tests/foreman/api/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14609 [6.15.z] Move TestAnsibleREX CLI tests to Ansible module
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#14611 [6.14.z] Move TestAnsibleREX CLI tests to Ansible module
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z, PRT-Passed

#14616 [6.15.z] Update Platform tests that have hard coded content host versions
  pytest_fixtures/core/contenthosts.py
  pytest_plugins/fixture_markers.py
  robottelo/constants/__init__.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/maintain/test_upgrade.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#14477 Verify a variable created and added to the host
  tests/foreman/ui/test_ansible.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14622 [6.15.z] Verify a variable created and added to the host
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14625 [6.14.z] Repair setup for package w/ swidtag, install and modular update
  tests/foreman/api/test_errata.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14621 cu-case-verify-worker-hosts-queue-1-service-has-proceed
  tests/foreman/cli/test_errata.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#14627 [6.15.z] cu-case-verify-worker-hosts-queue-1-service-has-proceed
  tests/foreman/cli/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14626 Move ansible API tests to Ansible-Cfgmgmt and REX classes
  tests/foreman/api/test_ansible.py
Labels: API, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14385 addition of auto-branching process as part of github action
  .github/workflows/auto_branching.yml
Labels: No-CherryPick

#14634 [6.14.z] Move ansible API tests to Ansible-Cfgmgmt and REX classes
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14569 Make test parametrization more readable
  tests/foreman/api/test_repository.py
Labels: CherryPick, 6.14.z, 6.15.z

#14642 [6.15.z] Make test parametrization more readable
  tests/foreman/api/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14623 [6.13.z] Verify a variable created and added to the host
  pytest_fixtures/component/activationkey.py
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14624 [6.14.z] Verify a variable created and added to the host
  pytest_fixtures/component/activationkey.py
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14644 [6.14.z] Make test parametrization more readable (#14569)
  tests/foreman/api/test_repository.py
Labels: No-CherryPick, 6.14.z

#14649 [6.12.z] Bump testimony from 2.3.0 to 2.4.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14652 [6.15.z] Bump testimony from 2.3.0 to 2.4.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14650 [6.13.z] Bump testimony from 2.3.0 to 2.4.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14647 [6.13.z] Test capsule without registration module
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.13.z, PRT-Passed

#14651 [6.14.z] Bump testimony from 2.3.0 to 2.4.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14542 bookmark entities reduced parametrization
  robottelo/constants/__init__.py
  tests/foreman/api/test_bookmarks.py
  tests/foreman/ui/test_bookmarks.py
  tests/upgrades/test_bookmarks.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13999 cli e2e fix
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: CLI, TestFailure, No-CherryPick, PRT-Passed

#14592 notifications: new test for notification_recipients endpoint
  tests/foreman/api/test_notifications.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#14659 [6.15.z] bookmark entities reduced parametrization
  robottelo/constants/__init__.py
  tests/foreman/api/test_bookmarks.py
  tests/foreman/ui/test_bookmarks.py
  tests/upgrades/test_bookmarks.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14535 Make oscap profile configurable in settings file
  conf/oscap.yaml.template
  pytest_fixtures/component/oscap.py
  robottelo/config/validators.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14661 [6.13.z] bookmark entities reduced parametrization
  robottelo/constants/__init__.py
  tests/foreman/api/test_bookmarks.py
  tests/foreman/ui/test_bookmarks.py
  tests/upgrades/test_bookmarks.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14646 HTTP Proxy UI fixes
  tests/foreman/ui/test_http_proxy.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#14669 [6.15.z] HTTP Proxy UI fixes
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14664 [6.15.z] Make oscap profile configurable in settings file
  conf/oscap.yaml.template
  pytest_fixtures/component/oscap.py
  robottelo/config/validators.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14665 [6.14.z] Make oscap profile configurable in settings file
  conf/oscap.yaml.template
  pytest_fixtures/component/oscap.py
  robottelo/config/validators.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14666 [6.13.z] Make oscap profile configurable in settings file
  conf/oscap.yaml.template
  pytest_fixtures/component/oscap.py
  robottelo/config/validators.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14667 [6.12.z] Make oscap profile configurable in settings file
  conf/oscap.yaml.template
  pytest_fixtures/component/oscap.py
  robottelo/config/validators.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14679 Make tests SCA-Compliant
  tests/foreman/api/test_registration.py
  tests/foreman/cli/test_logging.py
Labels: No-CherryPick, PRT-Passed

#14675 DRPM removal, SRPM fix
  robottelo/constants/repos.py
  tests/foreman/api/test_notifications.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#14540 Add filter for ldap related tests
  pytest_plugins/markers.py
  tests/foreman/conftest.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14663 [6.15.z] notifications: new test for notification_recipients endpoint
  tests/foreman/api/test_notifications.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#14685 [6.15.z] DRPM removal, SRPM fix
  robottelo/constants/repos.py
  tests/foreman/api/test_notifications.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14688 [6.12.z] Add filter for ldap related tests
  pytest_plugins/markers.py
  tests/foreman/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14668 [6.14.z] HTTP Proxy UI fixes
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14641 [6.12.z] Remove test_positive_matcher_field_highlight
  tests/foreman/ui/test_remoteexecution.py
Labels: Easy Fix :), No-CherryPick, 6.12.z, Failed_AutoCherryPick

#14640 [6.13.z] Remove test_positive_matcher_field_highlight
  tests/foreman/ui/test_remoteexecution.py
Labels: Easy Fix :), No-CherryPick, Failed_AutoCherryPick, 6.13.z

#14639 [6.14.z] Remove test_positive_matcher_field_highlight
  tests/foreman/ui/test_remoteexecution.py
Labels: Easy Fix :), No-CherryPick, Failed_AutoCherryPick, 6.14.z

#14638 [6.15.z] Remove test_positive_matcher_field_highlight
  tests/foreman/ui/test_remoteexecution.py
Labels: Easy Fix :), No-CherryPick, Failed_AutoCherryPick, 6.15.z

#14690 [6.15.z] Add filter for ldap related tests
  pytest_plugins/markers.py
  tests/foreman/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14689 [6.13.z] Add filter for ldap related tests
  pytest_plugins/markers.py
  tests/foreman/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14691 [6.14.z] DRPM removal, SRPM fix
  robottelo/constants/repos.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14692 Safely bump ruff-pre-commit to v0.3.0
  .pre-commit-config.yaml
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14697 [6.15.z] Safely bump ruff-pre-commit to v0.3.0
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14698 [6.14.z] notifications: new test for notification_recipients endpoint
  tests/foreman/api/test_notifications.py
Labels: No-CherryPick, PRT-Passed

#14674 notifications: no long tasks email for certain users
  tests/foreman/api/test_notifications.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#14682 [6.15.z] Bump deepdiff from 6.7.1 to 7.0.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#14681 [6.13.z] Bump deepdiff from 6.7.1 to 7.0.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14684 [6.12.z] Bump deepdiff from 6.7.1 to 7.0.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked, PRT-Passed

#14699 [6.15.z] notifications: no long tasks email for certain users
  tests/foreman/api/test_notifications.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14701 Fix teardown of bootdisk tests with request.addfinalizer
  tests/foreman/cli/test_bootdisk.py
Labels: CLI, TestFailure, Easy Fix :), CherryPick, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14708 [6.13.z] Safely bump ruff-pre-commit to v0.3.0
  .pre-commit-config.yaml
Labels: No-CherryPick, Failed_AutoCherryPick, 6.13.z

#14710 [6.15.z] Fix teardown of bootdisk tests with request.addfinalizer
  tests/foreman/cli/test_bootdisk.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14709 [6.13.z] Fix teardown of bootdisk tests with request.addfinalizer
  tests/foreman/cli/test_bootdisk.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14711 [6.14.z] Fix teardown of bootdisk tests with request.addfinalizer
  tests/foreman/cli/test_bootdisk.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14706 [6.14.z] Safely bump ruff-pre-commit to v0.3.0
  .pre-commit-config.yaml
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#14693 Fix Capsule.install when used w/o kwargs
  robottelo/hosts.py
  tests/foreman/api/test_capsule.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14715 [6.14.z] Fix Capsule.install when used w/o kwargs
  robottelo/hosts.py
  tests/foreman/api/test_capsule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14673 SAT-23362-update-fixture-as-per-new-feature(6.16)
  robottelo/constants/__init__.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repositories.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
Labels: TestFailure, Easy Fix :), No-CherryPick, Stream, PRT-Passed

#14713 [6.13.z] Fix Capsule.install when used w/o kwargs
  robottelo/hosts.py
  tests/foreman/api/test_capsule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14717 Remove pre-commit GitHub Action from our CI/CQ
  .github/workflows/pull_request.yml
  .pre-commit-config.yaml
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14727 [6.15.z] Remove pre-commit GitHub Action from our CI/CQ (#14717)
  .github/workflows/pull_request.yml
  .pre-commit-config.yaml
Labels: No-CherryPick, 6.15.z

#14726 [6.14.z] Remove pre-commit GitHub Action from our CI/CQ (#14717)
  .github/workflows/pull_request.yml
  .pre-commit-config.yaml
Labels: No-CherryPick, 6.14.z

#14725 [6.13.z] Remove pre-commit GitHub Action from our CI/CQ (#14717)
  .github/workflows/pull_request.yml
  .pre-commit-config.yaml
Labels: No-CherryPick, 6.13.z

#14723 [6.15.z] Coverage of BZ#2245081 ansible callback on capsule
  pytest_fixtures/core/sat_cap_factory.py
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14001 Test failures fixes for ui/test_registration.py
  pytest_fixtures/component/activationkey.py
  tests/foreman/ui/test_registration.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14729 [6.15.z] Test failures fixes for ui/test_registration.py
  pytest_fixtures/component/activationkey.py
  tests/foreman/ui/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14676 Fix tests failing on enabling satellite/capsule module
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/hosts.py
  tests/foreman/destructive/test_clone.py
  tests/foreman/installer/test_installer.py
  tests/foreman/sys/test_katello_certs_check.py
Labels: No-CherryPick, Stream, PRT-Passed

#14707 Update PRT Label Remove
  .github/workflows/prt_labels.yml
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14605 Move TestAnsibleREX UI tests to Ansible module
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_remoteexecution.py
Labels: UI, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14731 [6.15.z] Update PRT Label Remove
  .github/workflows/prt_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14732 [6.14.z] Update PRT Label Remove
  .github/workflows/prt_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14734 [6.12.z] Update PRT Label Remove
  .github/workflows/prt_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#14736 [6.15.z] Move TestAnsibleREX UI tests to Ansible module
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14738 comp audit - use global registration method
  tests/foreman/cli/test_repository.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, Stream, 6.14.z, 6.15.z, PRT-Passed

#14718 [6.14.z] notifications: no long tasks email for certain users
  tests/foreman/api/test_notifications.py
Labels: No-CherryPick, PRT-Passed

#14741 [6.15.z] comp audit - use global registration method
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14742 [6.14.z] comp audit - use global registration method
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14743 [6.13.z] comp audit - use global registration method
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14635 [6.15.z] Move ansible API tests to Ansible-Cfgmgmt and REX classes
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14739 [6.14.z] Move TestAnsibleREX UI tests to Ansible module
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_remoteexecution.py
Labels: No-CherryPick, Failed_AutoCherryPick, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14740 [6.13.z] Move TestAnsibleREX UI tests to Ansible module
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_remoteexecution.py
Labels: No-CherryPick, Failed_AutoCherryPick, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14677 [RFE] Should not be able to publish the content-view, while repository sync in-progress
  tests/foreman/api/test_contentview.py
Labels: RFE, CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z

#14620 Ensure correct finalizer order
  tests/foreman/api/test_parameters.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14746 [6.14.z] Ensure correct finalizer order
  tests/foreman/api/test_parameters.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14747 [6.13.z] Ensure correct finalizer order
  tests/foreman/api/test_parameters.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#14745 [6.15.z] Ensure correct finalizer order
  tests/foreman/api/test_parameters.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14497 content host set location to Default Location
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: Easy Fix :), CherryPick, 6.13.z, 6.14.z, 6.15.z

#14752 [6.15.z] content host set location to Default Location
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14750 [6.14.z] content host set location to Default Location
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14751 [6.13.z] content host set location to Default Location
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14703 Fix ssh command usage
  robottelo/cli/base.py
  tests/robottelo/test_cli.py
Labels: No-CherryPick, PRT-Passed

#14637 [6.13.z] Move ansible API tests to Ansible-Cfgmgmt and REX classes
  tests/foreman/api/test_ansible.py
Labels: API, No-CherryPick, Failed_AutoCherryPick, 6.13.z

#14758 [6.13.z] Assert installer status when enabling OpenSCAP
  tests/foreman/api/test_capsule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#14759 [6.14.z] Assert installer status when enabling OpenSCAP
  tests/foreman/api/test_capsule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14762 [6.15.z] updated hammer commands tree
  tests/foreman/data/hammer_commands.json
Labels: CLI, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14757 [6.15.z] Assert installer status when enabling OpenSCAP
  tests/foreman/api/test_capsule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14764 [6.12.z] Fix Capsule.install when used w/o kwargs
  robottelo/hosts.py
Labels: No-CherryPick, 6.12.z, Failed_AutoCherryPick

#14748 Fix and update capsule certificate validation
  tests/foreman/destructive/test_katello_certs_check.py
Labels: No-CherryPick, Stream, PRT-Passed

#14761 Flip entitlement to SCA in destructive caps content
  tests/foreman/destructive/test_capsulecontent.py
Labels: No-CherryPick, PRT-Failed

#14775 virt-who config SCA-compliant
  tests/upgrades/test_virtwho.py
Labels: CherryPick, 6.14.z, 6.15.z

#14776 [6.15.z] virt-who config SCA-compliant
  tests/upgrades/test_virtwho.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14777 [6.14.z] virt-who config SCA-compliant
  tests/upgrades/test_virtwho.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14784 Flip SyncPlan tests to SCA
  tests/foreman/api/test_syncplan.py
  tests/foreman/cli/test_syncplan.py
Labels: Easy Fix :), No-CherryPick, PRT-Passed

#14783 Remove the sub-man status
  tests/foreman/api/test_convert2rhel.py
  tests/foreman/cli/test_registration.py
Labels: TestFailure, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14782 Add some randomness to CV publish break down
  tests/foreman/destructive/test_contentview.py
Labels: CherryPick, 6.15.z, PRT-Passed

#14793 [6.15.z] Bump sphinx from 7.2.6 to 7.3.4
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14794 [6.12.z] Bump sphinx from 7.2.6 to 7.3.4
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14795 [6.14.z] Bump sphinx from 7.2.6 to 7.3.4
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14792 [6.13.z] Bump sphinx from 7.2.6 to 7.3.4
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14796 6.15.z Cherrypick Test_Fixes_and_SCA_enbaled_manifest
  tests/foreman/cli/test_registration.py
Labels: No-CherryPick, PRT-Passed

#14779 [6.15.z] Add coverage for BZ1964539
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed
