Repository SatelliteQE/robottelo, pull requests merged in 2024-02, with the labels that each got.

#13969 [6.14.z] Bump kentaro-m/auto-assign-action from 1.2.6 to 2.0.0
  .github/workflows/auto_assignment.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13967 [6.13.z] Bump kentaro-m/auto-assign-action from 1.2.6 to 2.0.0
  .github/workflows/auto_assignment.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13968 [6.12.z] Bump kentaro-m/auto-assign-action from 1.2.6 to 2.0.0
  .github/workflows/auto_assignment.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#13966 [6.15.z] Bump kentaro-m/auto-assign-action from 1.2.6 to 2.0.0
  .github/workflows/auto_assignment.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13971 Fix SRPMs label in hammer repository info
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_satellitesync.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13960 test errata application with pull-mqtt rex
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13975 [6.15.z] Fix SRPMs label in hammer repository info
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13976 [6.15.z] test errata application with pull-mqtt rex
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13977 [6.15.z] [TestFix] Replacing 'content' with 'file' option in reporttemplate create
  tests/foreman/cli/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13978 [6.14.z] [TestFix] Replacing 'content' with 'file' option in reporttemplate create
  tests/foreman/cli/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13981 Fix virtwho UI cases failed for _GeneratorContextManager object has no attribute virtwho_configure
  tests/foreman/virtwho/conftest.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#13986 [6.15.z] Fix UI AC repo test
  tests/foreman/ui/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13985 [6.15.z] Fix virtwho UI cases failed for _GeneratorContextManager object has no attribute virtwho_configure
  tests/foreman/virtwho/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13984 [6.14.z] Fix virtwho UI cases failed for _GeneratorContextManager object has no attribute virtwho_configure
  tests/foreman/virtwho/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#13614 Fix and update installer ping test
  tests/foreman/installer/test_installer.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13988 [6.15.z] Fix and update installer ping test
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13982 added bz tag to oscap longrun test
  tests/foreman/longrun/test_oscap.py
Labels: CherryPick, 6.15.z

#13974 Fix registration test cases
  pytest_fixtures/component/activationkey.py
  tests/foreman/api/test_registration.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_registration.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z

#13987 job invocation with credentials added
  robottelo/host_helpers/cli_factory.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#13990 [6.15.z] added bz tag to oscap longrun test
  tests/foreman/longrun/test_oscap.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#13992 [6.15.z] job invocation with credentials added
  robottelo/host_helpers/cli_factory.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13596 [Customer Case] Adding test for overriding repos no select all
  tests/foreman/ui/test_repositories.py
Labels: CherryPick, 6.15.z

#13877 Modify VMware tests to run on VMware8
  conf/vmware.yaml.template
  pytest_fixtures/component/provision_vmware.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#13809 remove the all nailgun imports from UI folder
  tests/foreman/ui/test_architecture.py
  tests/foreman/ui/test_audit.py
  tests/foreman/ui/test_computeprofiles.py
  tests/foreman/ui/test_computeresource.py
  tests/foreman/ui/test_computeresource_ec2.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_containerimagetag.py
  tests/foreman/ui/test_domain.py
  tests/foreman/ui/test_hardwaremodel.py
  tests/foreman/ui/test_hostgroup.py
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_modulestreams.py
  tests/foreman/ui/test_organization.py
  tests/foreman/ui/test_oscappolicy.py
  tests/foreman/ui/test_oscaptailoringfile.py
  tests/foreman/ui/test_package.py
  tests/foreman/ui/test_product.py
  tests/foreman/ui/test_reporttemplates.py
  tests/foreman/ui/test_sync.py
  tests/foreman/ui/test_syncplan.py
  tests/foreman/ui/test_templatesync.py
  tests/foreman/ui/test_usergroup.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#13993 [6.14.z] job invocation with credentials added
  robottelo/host_helpers/cli_factory.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13997 [6.15.z] Modify VMware tests to run on VMware8
  conf/vmware.yaml.template
  pytest_fixtures/component/provision_vmware.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13998 [6.14.z] Modify VMware tests to run on VMware8
  conf/vmware.yaml.template
  pytest_fixtures/component/provision_vmware.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14000 [6.15.z] Fix language setting
  tests/foreman/ui/test_user.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13928 fixes for CLI post-eval failures
  tests/foreman/cli/test_errata.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#14002 [6.15.z] fixes for CLI post-eval failures
  tests/foreman/cli/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14003 always expression was missing in the PR checking
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14005 Skip Capsule provisioning test
  tests/foreman/api/test_provisioning.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14008 [6.15.z] Skip Capsule provisioning test
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14006 [6.14.z] Skip Capsule provisioning test
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14007 [6.13.z] Skip Capsule provisioning test
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#13996 [6.15.z] [Customer Case] Adding test for overriding repos no select all
  tests/foreman/ui/test_repositories.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#12793 Add Python 3.12 to supported versions
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  requirements.txt
  robottelo/cli/base.py
  robottelo/cli/subscription.py
  tests/robottelo/test_cli.py
  tests/robottelo/test_cli_method_calls.py
Labels: Framework Changes, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z

#13947 making dependency_merge.yml same as other z-stream branches
  .github/workflows/dependency_merge.yml
Labels: No-CherryPick, 6.15.z

#13915 added test_positive_host_registration_with_non_admin_user
  tests/foreman/api/test_registration.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#14011 [6.15.z] added test_positive_host_registration_with_non_admin_user
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14012 [6.14.z] added test_positive_host_registration_with_non_admin_user
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13735 Coverage:Bug 2158702
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: QETestCoverage, CherryPick, 6.13.z, 6.14.z, 6.15.z

#14010 Fix scope mismatch issue for VMware tests
  pytest_fixtures/component/provision_vmware.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14013 [6.15.z] Coverage:Bug 2158702
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14018 [6.14.z] Fix scope mismatch issue for VMware tests
  pytest_fixtures/component/provision_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14019 [6.15.z] Fix scope mismatch issue for VMware tests
  pytest_fixtures/component/provision_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14014 [6.14.z] Coverage:Bug 2158702
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14015 [6.13.z] Coverage:Bug 2158702
  tests/foreman/virtwho/ui/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14020 Temporarily add docker and paramiko deps
  requirements.txt
Labels: Bug, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14021 [6.12.z] Temporarily add docker and paramiko deps
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#14023 [6.13.z] Temporarily add docker and paramiko deps
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#14022 [6.14.z] Temporarily add docker and paramiko deps
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14024 [6.15.z] Temporarily add docker and paramiko deps
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14031 [6.12.z] Bump pre-commit from 3.6.0 to 3.6.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14032 [6.14.z] Bump pre-commit from 3.6.0 to 3.6.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14030 [6.13.z] Bump pre-commit from 3.6.0 to 3.6.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#13979 preserving PRT result as part of github comment & PRT pass/fail label
  .github/workflows/prt_result.yml
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14033 [6.15.z] Bump pre-commit from 3.6.0 to 3.6.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14027 Add test for BZ:2193010 in provisioning templates
  tests/foreman/api/test_provisioningtemplate.py
Labels: QETestCoverage, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#14025 Add test coverage for BZ:2192939
  robottelo/hosts.py
  tests/foreman/cli/test_report.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14047 [6.13.z] Add test coverage for BZ:2192939
  robottelo/hosts.py
  tests/foreman/cli/test_report.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#14046 [6.15.z] Add test coverage for BZ:2192939
  robottelo/hosts.py
  tests/foreman/cli/test_report.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14045 [6.14.z] Add test coverage for BZ:2192939
  robottelo/hosts.py
  tests/foreman/cli/test_report.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#13450 Created Registration test module and moved relevant tests from host.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_registration.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14049 [6.15.z] Created Registration test module and moved relevant tests from host.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13923 Remove BZ check which is migrated to Jira and Add new BZ check causing selinux denials
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: TestFailure, CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14057 [6.15.z] - preserving PRT result as part of github comment & PRT pass/fail label…
  .github/workflows/prt_result.yml
Labels: No-CherryPick, 6.15.z

#14038 [6.14.z] preserving PRT result as part of github comment & PRT pass/fail label
  .github/workflows/prt_result.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14037 [6.13.z] preserving PRT result as part of github comment & PRT pass/fail label
  .github/workflows/prt_result.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14052 [6.14.z Cherrypick PR#13450] Move Registration test cases
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_registration.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z

#14054 [6.13.z] Remove BZ check which is migrated to Jira and Add new BZ check causing selinux denials
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14053 [6.14.z] Remove BZ check which is migrated to Jira and Add new BZ check causing selinux denials
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14063 Rename test to reflect it tests proxy id
  tests/foreman/cli/test_realm.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13994 Errata coverage for CV Incremental Update
  tests/foreman/api/test_errata.py
Labels: CherryPick, Stream, 6.15.z

#14064 [6.15.z] Rename test to reflect it tests proxy id
  tests/foreman/cli/test_realm.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14065 [6.15.z] Errata coverage for CV Incremental Update
  tests/foreman/api/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14061 Make docstring more understandable. Lower importance.
  tests/foreman/cli/test_auth.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#14060 Make things clear in docstring
  tests/foreman/cli/test_auth.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#14058 Test unassigning with multiple policies present
  tests/foreman/ui/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14073 [6.15.z] Test unassigning with multiple policies present
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14072 [6.15.z] Make things clear in docstring
  tests/foreman/cli/test_auth.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13970 setup_org_for_a_rh_repo fix
  robottelo/host_helpers/cli_factory.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#13421 Vertical menu search test
  tests/foreman/ui/test_search.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14074 Move HTTP Proxy tests under correct component
  testimony.yaml
  tests/foreman/api/test_http_proxy.py
  tests/foreman/cli/test_http_proxy.py
  tests/foreman/ui/test_http_proxy.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#13387 [6.13.z] Update yum repo for ACSes
  robottelo/constants/repos.py
Labels: No-CherryPick, Auto_Cherry_Picked, Stale, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14080 [6.15.z] Move HTTP Proxy tests under correct component
  testimony.yaml
  tests/foreman/api/test_http_proxy.py
  tests/foreman/cli/test_http_proxy.py
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14081 [6.14.z] Move HTTP Proxy tests under correct component
  testimony.yaml
  tests/foreman/api/test_http_proxy.py
  tests/foreman/cli/test_http_proxy.py
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14082 [6.13.z] Move HTTP Proxy tests under correct component
  testimony.yaml
  tests/foreman/api/test_http_proxy.py
  tests/foreman/cli/test_http_proxy.py
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14079 [6.15.z] [Test Fix] test_negative_generate_hostpkgcompare_nonexistent_host
  tests/foreman/cli/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#14078 [6.14.z] [Test Fix] test_negative_generate_hostpkgcompare_nonexistent_host
  tests/foreman/cli/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#14026 Fix registration test cases
  pytest_fixtures/component/activationkey.py
  tests/foreman/api/test_registration.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_registration.py
Labels: No-CherryPick, 6.13.z, PRT-Failed

#14071 [6.15.z] Make docstring more understandable. Lower importance.
  tests/foreman/cli/test_auth.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#13949 Fix parametrization in test_positive_reboot_all_pxe_hosts
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_discoveredhost.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Failed

#14035 create report template w/o name
  tests/foreman/api/test_reporttemplates.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14089 [6.14.z] create report template w/o name
  tests/foreman/api/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14087 [6.13.z] create report template w/o name
  tests/foreman/api/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14088 [6.15.z] create report template w/o name
  tests/foreman/api/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14004 Test for the change host's content source feature
  robottelo/hosts.py
  tests/foreman/ui/test_host.py
Labels: CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#14083 [6.15.z] Fix parametrization in test_positive_reboot_all_pxe_hosts
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Failed

#14084 [6.14.z] Fix parametrization in test_positive_reboot_all_pxe_hosts
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Failed

#14085 [6.13.z] Fix parametrization in test_positive_reboot_all_pxe_hosts
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Failed

#14091 [6.14.z] Test for the change host's content source feature
  robottelo/hosts.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14092 [6.13.z] Add support to run VMware tests on VMware8
  conf/vmware.yaml.template
  pytest_fixtures/component/provision_vmware.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.13.z, PRT-Passed

#14096 moving from module_entitlement_manifest_org to module_sca_manifest_org
  tests/foreman/api/test_repository.py
Labels: CherryPick, 6.15.z, PRT-Passed

#14097 [6.15.z] moving from module_entitlement_manifest_org to module_sca_manifest_org
  tests/foreman/api/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14067 Bump Broker to 0.4.5
  requirements.txt
Labels: dependencies, CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14095 [E2E] Recalculate applicability before UI session, fix navigation failure
  tests/foreman/ui/test_errata.py
Labels: Easy Fix :), CherryPick, Stream, 6.15.z, PRT-Passed

#14110 [6.15.z] [E2E] Recalculate applicability before UI session, fix navigation failure
  tests/foreman/ui/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14121 [6.14.z] Bump pre-commit from 3.6.1 to 3.6.2
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14120 [6.12.z] Bump pre-commit from 3.6.1 to 3.6.2
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14119 [6.13.z] Bump pre-commit from 3.6.1 to 3.6.2
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14122 [6.15.z] Bump pre-commit from 3.6.1 to 3.6.2
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14125 [6.15.z] Bump pytest from 8.0.0 to 8.0.1
  requirements.txt
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14130 Update test to use sca enabled manifest
  tests/foreman/api/test_repositories.py
Labels: TestFailure, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14131 [6.15.z] Update test to use sca enabled manifest
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14129 [6.14.z] Fix useless asserts in installer tests
  tests/foreman/destructive/test_installer.py
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#14128 [6.15.z] Fix useless asserts in installer tests
  tests/foreman/destructive/test_installer.py
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#14127 [6.13.z] Fix useless asserts in installer tests
  tests/foreman/destructive/test_installer.py
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#14077 [6.15.z] Vertical menu search test
  tests/foreman/ui/test_search.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14134 Remove enable_tools_repo and enable_rhel_repo methods
  robottelo/host_helpers/contenthost_mixins.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14136 [6.12.z] Remove enable_tools_repo and enable_rhel_repo methods
  robottelo/host_helpers/contenthost_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14138 [6.14.z] Remove enable_tools_repo and enable_rhel_repo methods
  robottelo/host_helpers/contenthost_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14137 [6.13.z] Remove enable_tools_repo and enable_rhel_repo methods
  robottelo/host_helpers/contenthost_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14135 [6.15.z] Remove enable_tools_repo and enable_rhel_repo methods
  robottelo/host_helpers/contenthost_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14132 deleted tc's by considering recommendation present in repositories co…
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, Stream, 6.14.z, 6.15.z

#14146 [6.14.z] ISS fix for CVV sorting issue
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14145 [6.13.z] ISS fix for CVV sorting issue
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#14144 [6.15.z] ISS fix for CVV sorting issue
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14028 Integrate FAM pipeline into robottelo
  robottelo/constants/__init__.py
  tests/foreman/sys/test_fam.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Failed

#14153 [6.14.z] deleted tc's by considering recommendation present in repositories component audit
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#14154 [6.15.z] deleted tc's by considering recommendation present in repositories component audit
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.15.z

#14133 SCA refactor of Subscription HTTP proxy test
  robottelo/host_helpers/api_factory.py
  tests/foreman/api/test_http_proxy.py
Labels: No-CherryPick, PRT-Passed

#14159 [6.13.z] Fix discovery rule test
  tests/foreman/api/test_discoveryrule.py
Labels: Easy Fix :), No-CherryPick, 6.13.z, PRT-Passed

#14070 Add a new test for password reset to user-specified password
  tests/foreman/destructive/test_auth.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14161 [6.15.z] Add a new test for password reset to user-specified password
  tests/foreman/destructive/test_auth.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14165 [6.13.z] Bump pytest-fixturecollection from 0.1.1 to 0.1.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14163 [6.12.z] Bump pytest-fixturecollection from 0.1.1 to 0.1.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14164 [6.15.z] Bump pytest-fixturecollection from 0.1.1 to 0.1.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14166 [6.14.z] Bump pytest-fixturecollection from 0.1.1 to 0.1.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14017 Force keyscan to use ipv4
  pytest_fixtures/component/templatesync.py
  tests/foreman/cli/test_templatesync.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14179 correct component names and description
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
  tests/foreman/ui/test_repository.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14183 [6.14.z] correct component names and description
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
  tests/foreman/ui/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14184 [6.15.z] correct component names and description
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
  tests/foreman/ui/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14180 Fix pit marker in installer
  tests/foreman/installer/test_installer.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#14185 [6.15.z] Fix pit marker in installer
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14175 [6.14.z] Force keyscan to use ipv4
  pytest_fixtures/component/templatesync.py
  tests/foreman/cli/test_templatesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14177 [6.15.z] Force keyscan to use ipv4
  pytest_fixtures/component/templatesync.py
  tests/foreman/cli/test_templatesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14176 [6.12.z] Force keyscan to use ipv4
  pytest_fixtures/component/templatesync.py
  tests/foreman/cli/test_templatesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked, PRT-Passed

#14189 [6.13] correct component names and description
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
  tests/foreman/ui/test_repository.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.13.z

#13211 eol banner
  tests/foreman/ui/test_eol_banner.py
Labels: No-CherryPick, PRT-Passed
