Repository SatelliteQE/robottelo, pull requests merged in 2024-05, with the labels that each got.

#14822 [stream] fixes for combined session failures, Errata UI
  tests/foreman/ui/test_errata.py
Labels: CherryPick, Stream, 6.14.z, 6.15.z, PRT-Passed

#14929 [6.15.z] [stream] fixes for combined session failures, Errata UI
  tests/foreman/ui/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14926 [Stream] Errata-UI: Fix test_positive_host_content_library
  tests/foreman/ui/test_errata.py
Labels: CherryPick, Stream, 6.15.z, PRT-Passed

#14932 [6.15.z] Errata-UI: Fix test_positive_host_content_library
  tests/foreman/ui/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14465 Add test coverage for BZ#2250397
  tests/foreman/cli/test_registration.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#14934 [6.15.z] Add test coverage for BZ#2250397
  tests/foreman/cli/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14086 Test leapp upgrade with non-admin user BZ#2257302
  robottelo/hosts.py
  tests/foreman/cli/test_leapp_client.py
Labels: QETestCoverage, No-CherryPick, PRT-Failed

#14927 [6.15.z] CC Automation/Comp Eval coverage - promote CCV with specific registry_name
  tests/foreman/api/test_contentview.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#14928 [6.14.z] CC Automation/Comp Eval coverage - promote CCV with specific registry_name
  tests/foreman/api/test_contentview.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#14678 CV Eval - Deletion
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_contentviewversion.py
  tests/foreman/api/test_docker.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_contentviewfilter.py
  tests/foreman/cli/test_docker.py
Labels: CherryPick, 6.14.z, 6.15.z

#14941 [Stream Fix] Remove escaped quotation mark from valid_name list
  robottelo/utils/datafactory.py
Labels: TestFailure, CherryPick, 6.13.z, Stream, 6.14.z, 6.15.z

#14950 [6.15.z] [Stream Fix] Remove escaped quotation mark from valid_name list
  robottelo/utils/datafactory.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14952 [6.14.z] [Stream Fix] Remove escaped quotation mark from valid_name list
  robottelo/utils/datafactory.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14951 [6.13.z] [Stream Fix] Remove escaped quotation mark from valid_name list
  robottelo/utils/datafactory.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#14955 [6.14.z] Bump jinja2 from 3.1.3 to 3.1.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14956 [6.13.z] Bump jinja2 from 3.1.3 to 3.1.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14957 [6.12.z] Bump jinja2 from 3.1.3 to 3.1.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14958 [6.15.z] Bump jinja2 from 3.1.3 to 3.1.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14960 [6.12.z] Bump cryptography from 42.0.5 to 42.0.6
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14961 [6.14.z] Bump cryptography from 42.0.5 to 42.0.6
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14962 [6.15.z] Bump cryptography from 42.0.5 to 42.0.6
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14959 [6.13.z] Bump cryptography from 42.0.5 to 42.0.6
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14914 Add test coverage for BZ:2166466
  tests/foreman/destructive/test_ansible.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14964 [6.15.z] Add test coverage for BZ:2166466
  tests/foreman/destructive/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14963 [6.14.z] Add test coverage for BZ:2166466
  tests/foreman/destructive/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14965 [6.13.z] Add test coverage for BZ:2166466
  tests/foreman/destructive/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14670 Make default_os name and major versions configurable
  conf/supportability.yaml
  pytest_fixtures/component/os.py
  robottelo/config/validators.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14843 6.15.z update scope of fixtures from hosts-content longrun test_inc_updates
  tests/foreman/longrun/test_inc_updates.py
Labels: No-CherryPick, 6.15.z, PRT-Failed

#14866 Copy config files for FAM to server
  conf/fam.yaml.template
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/sys/test_fam.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#14971 [6.15.z] Copy config files for FAM to server
  conf/fam.yaml.template
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14972 [6.14.z] Copy config files for FAM to server
  conf/fam.yaml.template
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#14980 [6.15.z] Bump cryptography from 42.0.6 to 42.0.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14979 [6.14.z] Bump cryptography from 42.0.6 to 42.0.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#14982 [6.13.z] Bump cryptography from 42.0.6 to 42.0.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14981 [6.12.z] Bump cryptography from 42.0.6 to 42.0.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#14985 [6.13.z] make oscap tests run on rhel9 backend (#14716)
  conf/oscap.yaml.template
  pytest_fixtures/component/oscap.py
  robottelo/constants/__init__.py
  tests/foreman/cli/test_oscap.py
  tests/foreman/ui/test_oscapcontent.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14983 [6.15.z] make oscap tests run on rhel9 backend (#14716)
  conf/oscap.yaml.template
  pytest_fixtures/component/oscap.py
  robottelo/constants/__init__.py
  tests/foreman/cli/test_oscap.py
  tests/foreman/ui/test_oscapcontent.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#14924 [6.13.z] added scap constant
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Failed

#14922 [6.15.z] added scap constant
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Failed

#14923 [6.14.z] added scap constant
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14645 Fix TOTP generation. Fix what commit a5a5cd9e5e broke.
  tests/foreman/destructive/test_ldap_authentication.py
Labels: CherryPick, 6.15.z, PRT-Passed

#14991 removed the non-used Colored box object
  robottelo/constants/__init__.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14994 [6.13.z] removed the non-used Colored box object
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#14995 [6.14.z] removed the non-used Colored box object
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#14993 [6.12.z] removed the non-used Colored box object
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#14702 Mark UI tests as end-to-end for Rocket Team Components
  tests/foreman/cli/test_leapp_client.py
  tests/foreman/ui/test_computeprofiles.py
  tests/foreman/ui/test_computeresource.py
  tests/foreman/ui/test_computeresource_azurerm.py
  tests/foreman/ui/test_computeresource_ec2.py
  tests/foreman/ui/test_computeresource_gce.py
  tests/foreman/ui/test_computeresource_libvirt.py
  tests/foreman/ui/test_config_group.py
  tests/foreman/ui/test_discoveryrule.py
  tests/foreman/ui/test_operatingsystem.py
  tests/foreman/ui/test_puppetclass.py
  tests/foreman/ui/test_puppetenvironment.py
  tests/foreman/ui/test_smartclassparameter.py
  tests/foreman/ui/test_subnet.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Failed

#15001 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  tests/foreman/cli/test_computeresource_libvirt.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15000 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  tests/foreman/cli/test_computeresource_libvirt.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15008 [6.13.z] Bump tenacity from 8.2.3 to 8.3.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15011 [6.15.z] Bump tenacity from 8.2.3 to 8.3.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15009 [6.14.z] Bump tenacity from 8.2.3 to 8.3.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15010 [6.12.z] Bump tenacity from 8.2.3 to 8.3.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#15006 [6.15.z] [Customer Case] Test for creating a host with lce specified
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#14704 [Comp Eval] Updating to test on multiple hosts and fixing test failures
  robottelo/host_helpers/cli_factory.py
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/cli/test_reporttemplates.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z

#15014 [6.15.z] [Comp Eval] Updating to test on multiple hosts and fixing test failures
  robottelo/host_helpers/cli_factory.py
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/cli/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#15013 fix typo in test_host
  tests/foreman/cli/test_host.py
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#15007 Bump el9 kickstart version to 9.4
  robottelo/constants/__init__.py
  tests/foreman/cli/test_leapp_client.py
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#15016 [6.12.z] fix typo in test_host
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#15017 [6.14.z] fix typo in test_host
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#15015 [6.13.z] fix typo in test_host
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#15018 [6.15.z] fix typo in test_host
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#14942 Gracious message when vault is not reachable
  robottelo/utils/vault.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#15023 [6.14.z] Gracious message when vault is not reachable
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15024 [6.15.z] Gracious message when vault is not reachable
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15025 [6.12.z] Gracious message when vault is not reachable
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#15026 [6.13.z] Gracious message when vault is not reachable
  robottelo/utils/vault.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15030 [6.12.z] [pre-commit.ci] pre-commit autoupdate (#14781)
  .pre-commit-config.yaml
  robottelo/host_helpers/api_factory.py
  tests/foreman/cli/test_computeresource_libvirt.py
Labels: No-CherryPick, 6.12.z

#14999 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  robottelo/host_helpers/api_factory.py
  tests/foreman/cli/test_computeresource_libvirt.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#14167 [Comp Eval] Updating fixture to SCA and Fixing failing tests
  tests/foreman/ui/test_reporttemplates.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15040 [6.14.z] Bump pre-commit from 3.7.0 to 3.7.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15039 [6.15.z] Bump pre-commit from 3.7.0 to 3.7.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15041 [6.13.z] Bump pre-commit from 3.7.0 to 3.7.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15042 [6.12.z] Bump pre-commit from 3.7.0 to 3.7.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z

#15028 [6.13.z] Bump el9 kickstart version to 9.4
  robottelo/constants/__init__.py
  tests/foreman/cli/test_leapp_client.py
Labels: Easy Fix :), No-CherryPick, Failed_AutoCherryPick, 6.13.z

#15029 [6.12.z] Bump el9 kickstart version to 9.4
  robottelo/constants/__init__.py
  tests/foreman/cli/test_leapp_client.py
Labels: Easy Fix :), No-CherryPick, 6.12.z, Failed_AutoCherryPick

#15027 [6.15.z] Bump el9 kickstart version to 9.4
  robottelo/constants/__init__.py
  tests/foreman/cli/test_leapp_client.py
Labels: Easy Fix :), No-CherryPick, Failed_AutoCherryPick, 6.15.z

#15032 [Comp Eval] Change CV CLI/API tests to use SCA Org
  tests/foreman/api/test_contentview.py
  tests/foreman/cli/test_contentview.py
Labels: No-CherryPick, Stream

#15036 [6.15.z] 6.15 cv delete
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_contentviewversion.py
  tests/foreman/api/test_docker.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_contentviewfilter.py
  tests/foreman/cli/test_docker.py
Labels: No-CherryPick

#15037 [6.14.z] Deleting all test cases marked as such in CV Eval
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_contentviewversion.py
  tests/foreman/api/test_docker.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_contentviewfilter.py
  tests/foreman/cli/test_docker.py
Labels: No-CherryPick, 6.14.z

#14034 Replace old method of registration with global registration in robottelo
  pytest_fixtures/component/activationkey.py
  pytest_fixtures/component/contentview.py
  robottelo/hosts.py
  tests/foreman/api/test_convert2rhel.py
  tests/foreman/api/test_hostcollection.py
  tests/foreman/api/test_registration.py
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/api/test_subscription.py
  tests/foreman/cli/test_activationkey.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_hostcollection.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_reporttemplates.py
  tests/foreman/cli/test_subscription.py
  tests/foreman/destructive/test_registration.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_reporttemplates.py
  tests/foreman/ui/test_subscription.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#15055 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#15054 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#15052 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#15053 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#15020 [6.14.z] Bump el9 kickstart version to 9.4
  robottelo/constants/__init__.py
  tests/foreman/cli/test_leapp_client.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Failed

#15044 Add preconversion check for convert2rhel
  tests/foreman/api/test_convert2rhel.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#14308 code coverage bug2063218
  robottelo/utils/virtwho.py
  tests/foreman/virtwho/api/test_nutanix.py
  tests/foreman/virtwho/cli/test_esx_sca.py
  tests/foreman/virtwho/cli/test_nutanix.py
  tests/foreman/virtwho/ui/test_nutanix.py
  tests/foreman/virtwho/ui/test_nutanix_sca.py
Labels: CherryPick, 6.15.z

#15059 [6.15.z] code coverage bug2063218
  robottelo/utils/virtwho.py
  tests/foreman/virtwho/api/test_nutanix.py
  tests/foreman/virtwho/cli/test_esx_sca.py
  tests/foreman/virtwho/cli/test_nutanix.py
  tests/foreman/virtwho/ui/test_nutanix.py
  tests/foreman/virtwho/ui/test_nutanix_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15048 Add Phoenix team based codeowners
  .github/CODEOWNERS
Labels: CherryPick, 6.14.z, 6.15.z

#15060 [6.15.z] Add Phoenix team based codeowners
  .github/CODEOWNERS
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#14883 Update tests for satellite-maintain update command
  robottelo/cli/sm_update.py
  tests/foreman/maintain/test_upgrade.py
Labels: No-CherryPick, Stream, PRT-Passed

#15062 Add negative test case for ipv6 enabled in boot options
  robottelo/cli/sm_update.py
  tests/foreman/destructive/test_fm_upgrade.py
Labels: CherryPick, 6.15.z

#15067 [6.15.z] Add negative test for ipv6 update check
  tests/foreman/destructive/test_fm_upgrade.py
Labels: No-CherryPick, 6.15.z

#14977 hosts export selectable columns
  tests/foreman/ui/test_host.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#15049 Automate BZ 2250732
  tests/foreman/cli/test_ansible.py
Labels: CherryPick, 6.15.z, PRT-Passed

#15070 [6.15.z] hosts export selectable columns
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15022 Add test coverage for BZ:1982698
  tests/foreman/api/test_ansible.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#15071 [6.15.z] Automate BZ 2250732
  tests/foreman/cli/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#15073 [6.15.z] Add test coverage for BZ:1982698
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#15072 [6.13.z] Add test coverage for BZ:1982698
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#15075 [6.15.z] Customer Case Automation - repo ids not being displayed
  robottelo/cli/contentview.py
  tests/foreman/cli/test_contentview.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15035 Add test coverage for BZ:1931489
  tests/foreman/api/test_ansible.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#14273 codecoverage bug2173870
  robottelo/utils/virtwho.py
  tests/foreman/virtwho/cli/test_esx_sca.py
Labels: CherryPick, 6.14.z, 6.15.z

#15080 [6.15.z] codecoverage bug2173870
  robottelo/utils/virtwho.py
  tests/foreman/virtwho/cli/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#15077 [6.15.z] Add test coverage for BZ:1931489
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15078 [6.14.z] Add test coverage for BZ:1931489
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#15083 Remove nailgun.entities imports in tests/foreman/endtoend
  tests/foreman/endtoend/test_api_endtoend.py
Labels: CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#15089 [6.15.z] Remove nailgun.entities imports in tests/foreman/endtoend
  tests/foreman/endtoend/test_api_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15087 [6.13.z] Remove nailgun.entities imports in tests/foreman/endtoend
  tests/foreman/endtoend/test_api_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#15082 [6.15.z] HTTP Proxy customer cases update
  pytest_fixtures/component/http_proxy.py
  tests/foreman/cli/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15081 [6.14.z] HTTP Proxy customer cases update
  pytest_fixtures/component/http_proxy.py
  tests/foreman/cli/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#15086 [6.14.z] Remove nailgun.entities imports in tests/foreman/endtoend
  tests/foreman/endtoend/test_api_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#15091 Update tests to use fixed mask
  tests/foreman/cli/test_subnet.py
Labels: TestFailure, Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#15012 Remove RHEL6 supportability from robottelo
  conf/supportability.yaml
Labels: Easy Fix :), CherryPick, 6.12.z, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z

#15095 [6.14.z] Update tests to use fixed mask
  tests/foreman/cli/test_subnet.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#15096 [6.13.z] Update tests to use fixed mask
  tests/foreman/cli/test_subnet.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#15097 [6.13.z] Remove RHEL6 supportability from robottelo
  conf/supportability.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#15099 [6.15.z] Remove RHEL6 supportability from robottelo
  conf/supportability.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#15100 [6.14.z] Remove RHEL6 supportability from robottelo
  conf/supportability.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#15098 [6.12.z] Remove RHEL6 supportability from robottelo
  conf/supportability.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#15092 removed unnecessary line
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#15094 [6.15.z] Update tests to use fixed mask
  tests/foreman/cli/test_subnet.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15101 [6.15.z] removed unnecessary line
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#15102 [6.14.z] removed unnecessary line
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#15093 [6.12.z] Update tests to use fixed mask
  tests/foreman/cli/test_subnet.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked, PRT-Passed

#15065 [6.15.z] Make default_os name and major versions configurable
  conf/supportability.yaml
  pytest_fixtures/component/os.py
  robottelo/config/validators.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.15.z, PRT-Passed

#15108 [6.15.z] Bump pytest from 8.2.0 to 8.2.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#15109 [6.12.z] Bump pytest from 8.2.0 to 8.2.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.12.z, PRT-Passed

#15106 [6.13.z] Bump pytest from 8.2.0 to 8.2.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#15107 [6.14.z] Bump pytest from 8.2.0 to 8.2.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#14986 Check that host statuses honor taxonomy permissions
  tests/foreman/ui/test_host.py
Labels: CherryPick, 6.15.z, PRT-Passed

#14376 Fix number of imported templates
  robottelo/constants/__init__.py
  tests/foreman/api/test_templatesync.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15112 [6.15.z] Fix number of imported templates
  robottelo/constants/__init__.py
  tests/foreman/api/test_templatesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15111 [6.15.z] templatesync test fixes
  tests/foreman/cli/test_templatesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#14877 katello_host_tools_host no disable sca
  robottelo/cli/host.py
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, PRT-Passed

#15090 Add test for syncable export with restrictive permissions
  tests/foreman/cli/test_satellitesync.py
Labels: CherryPick, 6.15.z, PRT-Passed

#15115 [6.15.z] Add test for syncable export with restrictive permissions
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#15124 [6.15.z] Bump sphinx-autoapi from 3.0.0 to 3.1.0
  pytest_fixtures/component/repository.py
  requirements-optional.txt
  robottelo/cli/base.py
  robottelo/host_helpers/api_factory.py
  robottelo/host_helpers/repository_mixins.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
  robottelo/utils/datafactory.py
  robottelo/utils/report_portal/portal.py
  tests/foreman/api/test_notifications.py
  tests/foreman/api/test_permission.py
  tests/foreman/cli/test_oscap.py
  tests/foreman/longrun/test_oscap.py
Labels: dependencies, No-CherryPick, 6.15.z

#15123 [6.14.z] Bump sphinx-autoapi from 3.0.0 to 3.1.0
  pytest_fixtures/component/repository.py
  requirements-optional.txt
  robottelo/cli/base.py
  robottelo/host_helpers/api_factory.py
  robottelo/host_helpers/repository_mixins.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
  robottelo/utils/datafactory.py
  robottelo/utils/report_portal/portal.py
  tests/foreman/api/test_notifications.py
  tests/foreman/api/test_permission.py
  tests/foreman/cli/test_oscap.py
  tests/foreman/longrun/test_oscap.py
Labels: dependencies, No-CherryPick, 6.14.z

#15121 [6.12.z] Bump sphinx-autoapi from 3.0.0 to 3.1.0
  pytest_fixtures/component/repository.py
  requirements-optional.txt
  robottelo/cli/base.py
  robottelo/host_helpers/repository_mixins.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
  robottelo/utils/datafactory.py
  robottelo/utils/report_portal/portal.py
  tests/foreman/api/test_permission.py
  tests/foreman/cli/test_oscap.py
  tests/foreman/longrun/test_oscap.py
Labels: dependencies, No-CherryPick, 6.12.z

#15129 [6.14.z] Bump requests from 2.31.0 to 2.32.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Failed

#15128 [6.15.z] Bump requests from 2.31.0 to 2.32.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Failed

#15084 Remove nailgun.entities imports in pytest_fixtures
  pytest_fixtures/component/computeprofile.py
  pytest_fixtures/component/host.py
  pytest_fixtures/component/hostgroup.py
  pytest_fixtures/component/os.py
  pytest_fixtures/component/oscap.py
  pytest_fixtures/component/provisioning_template.py
  pytest_fixtures/component/repository.py
  pytest_fixtures/component/satellite_auth.py
  pytest_fixtures/component/subnet.py
  pytest_fixtures/component/user.py
  pytest_fixtures/component/user_role.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z, PRT-Failed

#15068 Add test case for CCV promotion to a non-default LCE
  tests/foreman/cli/test_contentview.py
Labels: CherryPick, 6.15.z, PRT-Passed

#15122 [6.13.z] Bump sphinx-autoapi from 3.0.0 to 3.1.0
  pytest_fixtures/component/repository.py
  requirements-optional.txt
  robottelo/cli/base.py
  robottelo/host_helpers/api_factory.py
  robottelo/host_helpers/repository_mixins.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
  robottelo/utils/datafactory.py
  robottelo/utils/report_portal/portal.py
  tests/foreman/api/test_permission.py
  tests/foreman/cli/test_oscap.py
  tests/foreman/longrun/test_oscap.py
Labels: dependencies, No-CherryPick, 6.13.z

#15135 [6.15.z] Add test case for CCV promotion to a non-default LCE
  tests/foreman/cli/test_contentview.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#15138 Fix assertions in file repo tests
  tests/foreman/cli/test_repository.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed

#15142 [6.15.z] Fix assertions in file repo tests
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15141 [6.13.z] Fix assertions in file repo tests
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#15140 [6.14.z] Fix assertions in file repo tests
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed
