Repository SatelliteQE/robottelo, pull requests merged in 2024-10, with the labels that each got.

#16541 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16504 [6.16.z] Update dependancy-merge workflow as for other z-stream branches
  .github/workflows/dependency_merge.yml
Labels: No-CherryPick, 6.16.z

#16423 Fetch pre_upgrade data based on node properties
  tests/upgrades/conftest.py
Labels: CherryPick, 6.14.z, 6.15.z, 6.16.z

#16550 [6.16.z] Fetch pre_upgrade data based on node properties
  tests/upgrades/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16554 [6.15.z] Remove CSV parser workaround
  robottelo/cli/hammer.py
  robottelo/cli/repository.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#16382 Fix username for AD and IDM. Fix session contexts.
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z

#16559 [6.15.z] Fix username for AD and IDM. Fix session contexts.
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#16560 [6.16.z] Fix username for AD and IDM. Fix session contexts.
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/ui/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16497 [RHCloud] Update configure_rhai_client registration
  pytest_fixtures/component/rh_cloud.py
  robottelo/hosts.py
  tests/foreman/cli/test_http_proxy.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, PRT-Passed, 6.16.z

#16553 avoiding host details will be seen in the test result
  tests/foreman/installer/test_installer.py
Labels: CherryPick, 6.14.z, 6.15.z, 6.16.z

#16548 Fix possible KeyError and remove debug statement
  tests/foreman/cli/test_contentview.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, 6.16.z

#16563 [6.16.z] avoiding host details will be seen in the test result
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16564 [6.15.z] avoiding host details will be seen in the test result
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16568 [6.16.z] Fix possible KeyError and remove debug statement
  tests/foreman/cli/test_contentview.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16557 Fix AD setup on RHEL 9. Use packages documentation calls for in the given version.
  robottelo/hosts.py
Labels: CherryPick, 6.15.z, PRT-Passed, 6.16.z

#16571 [6.16.z] Fix AD setup on RHEL 9. Use packages documentation calls for in the given version.
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#16566 Customer Case testing for database issues
  tests/foreman/api/test_contentview.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#16574 [6.16.z] Cherrypick configure insights client
  pytest_fixtures/component/rh_cloud.py
  robottelo/hosts.py
  tests/foreman/cli/test_http_proxy.py
Labels: No-CherryPick, Failed_AutoCherryPick, PRT-Passed, 6.16.z

#16582 [6.16.z] Bump redis from 5.1.0 to 5.1.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16581 [6.15.z] Bump redis from 5.1.0 to 5.1.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16583 [6.14.z] Bump redis from 5.1.0 to 5.1.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16584 [6.13.z] Bump redis from 5.1.0 to 5.1.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16585 [6.14.z] Bump ruff from 0.6.8 to 0.6.9
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16588 [6.16.z] Bump ruff from 0.6.8 to 0.6.9
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16590 [6.16.z] Bump pre-commit from 3.8.0 to 4.0.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16592 [6.14.z] Bump pre-commit from 3.8.0 to 4.0.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16587 [6.15.z] Bump ruff from 0.6.8 to 0.6.9
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16586 [6.13.z] Bump ruff from 0.6.8 to 0.6.9
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16593 Enable repos for long failing hostCollection UI tests
  tests/foreman/ui/test_hostcollection.py
Labels: UI, No-CherryPick, 6.15.z, PRT-Passed

#16594 Update is_open_jira issue handler functionality
  robottelo/utils/issue_handlers/jira.py
Labels: CherryPick, Stream, 6.14.z, 6.15.z, 6.16.z

#16547 [Customer Case] Adding test for syncing inventory with missing ip
  tests/foreman/cli/test_rhcloud_inventory.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, PRT-Passed, 6.16.z

#16601 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16602 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16604 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16603 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16599 [6.16.z] [Customer Case] Adding test for syncing inventory with missing ip
  tests/foreman/cli/test_rhcloud_inventory.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16549 changes to use the beaker urls for running upstream sanity
  conf/capsule.yaml.template
  conf/dynaconf_hooks.py
  conf/server.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
  tests/foreman/installer/test_installer.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#16572 Combine discovery reboot and reboot_all test
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_discoveredhost.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, 6.16.z

#16613 [6.14.z] Combine discovery reboot and reboot_all test
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#16612 [6.15.z] Combine discovery reboot and reboot_all test
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#16616 [6.14.z] Bump pre-commit from 4.0.0 to 4.0.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16615 [6.16.z] Bump pre-commit from 4.0.0 to 4.0.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16424 [6.15.z] improve installer tests compatibility with pit (#15308)
  conf/capsule.yaml.template
  conf/robottelo.yaml.template
  conf/server.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/hosts.py
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Failed_AutoCherryPick, PRT-Passed

#16431 Automate test_positive_ansible_variables_imported_with_roles
  robottelo/cli/ansible.py
  robottelo/cli/host.py
  robottelo/hosts.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/ui/test_ansible.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#16621 [6.16.z] Automate test_positive_ansible_variables_imported_with_roles
  robottelo/cli/ansible.py
  robottelo/cli/host.py
  robottelo/hosts.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16619 [6.13.z] Update customer BZ in docstring
  tests/foreman/cli/test_fact.py
Labels: No-CherryPick, 6.13.z

#16556 Automate puppet-agent8 testing by parametrizing existing puppet tests
  conf/dynaconf_hooks.py
  robottelo/hosts.py
  tests/foreman/cli/test_report.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16626 [6.14.z] Update customer BZ in docstring
  tests/foreman/cli/test_fact.py
Labels: No-CherryPick, 6.14.z, PRT-Passed

#16489 Automate test_positive_ansible_variables_installed_with_collection
  tests/foreman/cli/test_ansible.py
  tests/foreman/ui/test_ansible.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#16630 [6.16.z] Automate test_positive_ansible_variables_installed_with_collection
  tests/foreman/cli/test_ansible.py
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16546 negative test for regular rex run
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#16505 Sanitize test_installer_modules_check
  tests/foreman/installer/test_installer.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16636 [6.16.z] negative test for regular rex run
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16637 [6.16.z] Sanitize test_installer_modules_check
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16609 [6.16.z] changes to use the beaker urls for running upstream sanity
  conf/capsule.yaml.template
  conf/dynaconf_hooks.py
  conf/server.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16638 Revert "Bump thollander/actions-comment-pull-request from 2 to 3"
  .github/workflows/auto_branching.yml
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/auto_cherry_pick_merged.yaml
  .github/workflows/prt_result.yml
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#15834 [6.15.z] Add automation for BZ 2168494
  conftest.py
  pytest_fixtures/component/leapp_client.py
  tests/foreman/ui/test_leapp_client.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Failed

#15836 [6.14.z] Add automation for BZ 2168494
  conftest.py
  pytest_fixtures/component/leapp_client.py
  tests/foreman/ui/test_leapp_client.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Failed

#15835 [6.13.z] Add automation for BZ 2168494
  conftest.py
  pytest_fixtures/component/leapp_client.py
  tests/foreman/ui/test_leapp_client.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Failed

#16627 [6.16.z] Automate puppet-agent8 testing by parametrizing existing puppet tests
  robottelo/hosts.py
  tests/foreman/cli/test_report.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.16.z

#16644 [6.13.z] Add test coverage for ansible-playbook job with nonexisting_module
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#16649 [6.14.z] Bump sphinx from 8.0.2 to 8.1.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16648 [6.16.z] Bump sphinx from 8.0.2 to 8.1.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16650 [6.15.z] Bump sphinx from 8.0.2 to 8.1.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16647 [6.13.z] Bump sphinx from 8.0.2 to 8.1.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16643 [6.14.z] Automate test_positive_ansible_variables_imported_with_roles
  robottelo/cli/ansible.py
  robottelo/cli/host.py
  robottelo/hosts.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/ui/test_ansible.py
Labels: QETestCoverage, No-CherryPick, Failed_AutoCherryPick, 6.14.z, PRT-Passed

#16628 [6.14.z] Automate test_positive_ansible_variables_installed_with_collection
  tests/foreman/cli/test_ansible.py
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#16639 Add network type option for Host checkout
  pytest_fixtures/component/leapp_client.py
  tests/foreman/ui/test_errata.py
Labels: TestFailure, Easy Fix :), No-CherryPick, Stream, PRT-Failed

#16623 [6.15.z] - changes to use the beaker urls for running upstream sanity (#16549)
  conf/capsule.yaml.template
  conf/dynaconf_hooks.py
  conf/server.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#16624 [6.14.z ] - changes to use the beaker urls for running upstream sanity (#16549)
  conf/capsule.yaml.template
  conf/dynaconf_hooks.py
  conf/server.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
Labels: No-CherryPick, PRT-Failed

#16625 [6.13.z] - changes to use the beaker urls for running upstream sanity (#16549)
  conf/capsule.yaml.template
  conf/dynaconf_hooks.py
  conf/server.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
Labels: No-CherryPick, PRT-Passed

#16516 update subscription_status_label to subscription_facet_attribute
  tests/upgrades/test_virtwho.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#16658 [6.16.z] update subscription_status_label to subscription_facet_attribute
  tests/upgrades/test_virtwho.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#16661 [6.14.z] Bump sphinx from 8.1.0 to 8.1.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16664 [6.16.z] Bump sphinx from 8.1.0 to 8.1.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16663 [6.13.z] Bump sphinx from 8.1.0 to 8.1.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16662 [6.15.z] Bump sphinx from 8.1.0 to 8.1.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16667 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16669 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16668 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16672 avoiding the ohsnap repo url incase of nightly
  tests/foreman/installer/test_installer.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#16641 parse package details page link and validate plus sign
  robottelo/host_helpers/cli_factory.py
  tests/foreman/ui/test_package.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.16.z

#16679 Add test for host with .ics domain name
  tests/foreman/ui/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#16674 [6.16.z] avoiding the ohsnap repo url incase of nightly
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#16675 [6.15.z] avoiding the ohsnap repo url incase of nightly
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Failed

#16595 [6.16.z] Update is_open_jira issue handler functionality
  robottelo/utils/issue_handlers/jira.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16596 [6.15.z] Update is_open_jira issue handler functionality
  robottelo/utils/issue_handlers/jira.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16597 [6.14.z] Update is_open_jira issue handler functionality
  robottelo/utils/issue_handlers/jira.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16684 Actions comment pull request bump fix
  .github/workflows/auto_branching.yml
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/auto_cherry_pick_merged.yaml
  .github/workflows/prt_result.yml
Labels: dependencies, CherryPick, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16681 [6.16.z] Add network type option for Host checkout
  pytest_fixtures/component/leapp_client.py
  tests/foreman/ui/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#16703 [6.16.z] Bump ruff from 0.6.9 to 0.7.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16702 [6.14.z] Bump ruff from 0.6.9 to 0.7.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16698 Update verifies jira in FDI validation test
  tests/foreman/cli/test_discoveredhost.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z

#16704 [6.16.z] Update verifies jira in FDI validation test
  tests/foreman/cli/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16096 [6.13.z] add & remove ansible role
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, 6.13.z, PRT-Passed

#16238 CV UI - E2E Testing for regular and Composite CVs
  tests/foreman/ui/test_contentview.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#16710 [6.14.z] Bump cryptography from 43.0.1 to 43.0.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16711 [6.16.z] Bump cryptography from 43.0.1 to 43.0.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16712 [6.13.z] Bump cryptography from 43.0.1 to 43.0.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16694 use packaged pytest, not some venv
  tests/foreman/sys/test_fam.py
Labels: CherryPick, Stream, 6.14.z, 6.15.z, PRT-Failed, 6.16.z

#16714 Revert "Fetch pre_upgrade data based on node properties"
  tests/upgrades/conftest.py
Labels: Urgent Priority, CherryPick, AutoMerge_Cherry_Picked, 6.15.z, 6.16.z

#16715 [6.16.z] use packaged pytest, not some venv
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16717 [6.15.z] use packaged pytest, not some venv
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16718 Revert "[6.16.z] Fetch pre_upgrade data based on node properties"
  tests/upgrades/conftest.py
Labels: Urgent Priority, No-CherryPick, 6.16.z

#16719 Revert "[6.15.z] Fetch pre_upgrade data based on node properties"
  tests/upgrades/conftest.py
Labels: Urgent Priority, No-CherryPick, 6.15.z

#16683 reorder and improve clone test to match docs
  tests/foreman/destructive/test_clone.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#16720 [6.16.z] reorder and improve clone test to match docs
  tests/foreman/destructive/test_clone.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16725 [6.15.z] Bump pytest-reportportal from 5.4.2 to 5.4.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16724 [6.16.z] Bump pytest-reportportal from 5.4.2 to 5.4.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16727 [6.14.z] Bump pytest-reportportal from 5.4.2 to 5.4.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16477 Fix Upgrade scenarios
  tests/upgrades/test_discovery.py
  tests/upgrades/test_provisioningtemplate.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#16733 [6.16.z] Fix Upgrade scenarios
  tests/upgrades/test_discovery.py
  tests/upgrades/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16732 [6.13.z] Fix Upgrade scenarios
  tests/upgrades/test_discovery.py
  tests/upgrades/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#16657 Add a test to verify default location set for registered host
  tests/foreman/cli/test_registration.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16736 [6.16.z] Add a test to verify default location set for registered host
  tests/foreman/cli/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16731 [6.15.z] Fix Upgrade scenarios
  tests/upgrades/test_discovery.py
  tests/upgrades/test_provisioningtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15453 [6.15.z] Add OS Parameters to end to end test
  tests/foreman/api/test_operatingsystem.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#16726 [6.13.z] Bump pytest-reportportal from 5.4.2 to 5.4.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16745 [6.15.z] Bump pytest-reportportal from 5.4.3 to 5.4.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16746 [6.14.z] Bump pytest-reportportal from 5.4.3 to 5.4.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16747 [6.13.z] Bump pytest-reportportal from 5.4.3 to 5.4.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16748 [6.16.z] Bump pytest-reportportal from 5.4.3 to 5.4.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16730 [6.13.z] eol version check (#13253)
  conf/subscription.yaml.template
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  tests/foreman/api/test_eol_banner.py
Labels: No-CherryPick, 6.13.z, PRT-Passed

#16729 [6.13.z] eol banner
  tests/foreman/ui/test_eol_banner.py
Labels: No-CherryPick, 6.13.z

#16753 Remove reverse proxy assertion code from test_capsule_installation
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Stream

#16754 Satellite version validation skip for nightly
  tests/foreman/installer/test_installer.py
Labels: CherryPick, 6.13.z, Stream, 6.14.z, 6.15.z, 6.16.z

#16755 [6.16.z] Satellite version validation skip for nightly
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16756 [6.14.z] Satellite version validation skip for nightly
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#15863 add test for capsule update playbook
  tests/foreman/api/test_remoteexecution.py
Labels: No-CherryPick, PRT-Passed

#16728 prepare puppet classes needed for FAM tests in setup_fam
  tests/foreman/sys/test_fam.py
Labels: CherryPick, 6.13.z, Stream, 6.14.z, 6.15.z, 6.16.z

#16752 Update ACS validation messages
  tests/foreman/cli/test_acs.py
Labels: No-CherryPick, Stream, PRT-Passed

#16762 [6.16.z] prepare puppet classes needed for FAM tests in setup_fam
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16760 [6.15.z] prepare puppet classes needed for FAM tests in setup_fam
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16763 [6.14.z] prepare puppet classes needed for FAM tests in setup_fam
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick

#14111 [POC] New-Style Upgrade Tests
  conf/upgrade.yaml.template
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
  robottelo/utils/shared_resource.py
  tests/new_upgrades/__init__.py
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_contentview.py
  tests/new_upgrades/test_repository.py
  tests/robottelo/test_shared_resource.py
Labels: in progress, enhancement, High Complexity, Upgrades, Framework Changes, CherryPick, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16283 Migrate Old CV UI coverage (Upgrade)
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_contentview_old.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.16.z

#16640 Fix cli yum repo authentication test
  robottelo/utils/datafactory.py
  tests/foreman/cli/test_repository.py
Labels: CherryPick, 6.14.z, 6.15.z, 6.16.z

#16769 [6.16.z] Fix cli yum repo authentication test
  robottelo/utils/datafactory.py
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#16771 [6.15.z] Fix cli yum repo authentication test
  robottelo/utils/datafactory.py
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#16776 [6.16.z] Bump ruff from 0.7.0 to 0.7.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16780 [6.16.z] Bump redis from 5.1.1 to 5.2.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16782 [6.14.z] Bump redis from 5.1.1 to 5.2.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16778 [6.14.z] Bump ruff from 0.7.0 to 0.7.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16692 New improvements and fixes to pytest req updates plugin
  pytest_plugins/requirements/req_updater.py
  pytest_plugins/requirements/update_requirements.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16785 [6.14.z] New improvements and fixes to pytest req updates plugin
  pytest_plugins/requirements/req_updater.py
  pytest_plugins/requirements/update_requirements.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16786 [6.16.z] New improvements and fixes to pytest req updates plugin
  pytest_plugins/requirements/req_updater.py
  pytest_plugins/requirements/update_requirements.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16787 [6.15.z] New improvements and fixes to pytest req updates plugin
  pytest_plugins/requirements/req_updater.py
  pytest_plugins/requirements/update_requirements.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16788 [6.13.z] New improvements and fixes to pytest req updates plugin
  pytest_plugins/requirements/req_updater.py
  pytest_plugins/requirements/update_requirements.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16558 [Sanity Testing] Capsule Sanity Testing for capsule sync
  pytest_fixtures/core/sat_cap_factory.py
  pytest_fixtures/core/xdist.py
  robottelo/hosts.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/installer/test_installer.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#16803 [6.16.z] Bump sphinx-autoapi from 3.3.2 to 3.3.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z
