Repository SatelliteQE/robottelo, pull requests merged in 2024-09, with the labels that each got.

#16151 [6.15.z] CP CapsuleContent Cover BZ 2186765
  tests/foreman/cli/test_capsulecontent.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#16177 [6.15.z] Bump sphinx-autoapi from 3.3.0 to 3.3.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16180 [6.13.z] Bump sphinx-autoapi from 3.3.0 to 3.3.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16179 [6.14.z] Bump sphinx-autoapi from 3.3.0 to 3.3.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16178 [6.16.z] Bump sphinx-autoapi from 3.3.0 to 3.3.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16183 [6.14.z] Bump deepdiff from 7.0.1 to 8.0.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#16170 Fix bind name
  tests/foreman/destructive/test_ldap_authentication.py
Labels: CherryPick, 6.15.z, PRT-Passed, 6.16.z

#16173 [6.16.z] [RFE] Updating Subscription Management to be SCA Only
  pytest_fixtures/component/taxonomy.py
  robottelo/host_helpers/cli_factory.py
  robottelo/hosts.py
  tests/foreman/api/test_subscription.py
  tests/foreman/cli/test_subscription.py
  tests/foreman/ui/test_subscription.py
  tests/upgrades/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#16067 [6.16.z] Merge repo create and delete test cases
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16185 Add wait_for to see published repo files
  tests/foreman/cli/test_artifacts.py
Labels: CherryPick, PRT-Passed, 6.16.z

#16189 [6.16.z] Add wait_for to see published repo files
  tests/foreman/cli/test_artifacts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16186 [6.16.z] Fix bind name
  tests/foreman/destructive/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#16187 [6.15.z] Fix bind name
  tests/foreman/destructive/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#16068 test rex with su password
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Stream, PRT-Passed

#16182 [6.16.z] Bump deepdiff from 7.0.1 to 8.0.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Failed, 6.16.z

#16181 [6.15.z] Bump deepdiff from 7.0.1 to 8.0.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#16191 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16193 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16190 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16192 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16090 Update host registration hammer command to use repo_data option over deprecated repo and repo_gpg_key_url option and test the new option
  robottelo/hosts.py
  tests/foreman/api/test_remoteexecution.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#16194 [6.16.z] Update host registration hammer command to use repo_data option over deprecated repo and repo_gpg_key_url option and test the new option
  robottelo/hosts.py
  tests/foreman/api/test_remoteexecution.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#15959 Small improvements for podman api tests
  tests/foreman/api/test_docker.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#16195 [6.16.z] Small improvements for podman api tests
  tests/foreman/api/test_docker.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16169 cvv incremental update and cv publish duration fix
  robottelo/cli/contentview.py
  tests/foreman/longrun/test_inc_updates.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, PRT-Passed, 6.16.z

#16197 [6.15.z] cvv incremental update and cv publish duration fix
  robottelo/cli/contentview.py
  tests/foreman/longrun/test_inc_updates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#15308 improve installer tests compatibility with pit
  conf/capsule.yaml.template
  conf/robottelo.yaml.template
  conf/server.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/hosts.py
  tests/foreman/installer/test_installer.py
Labels: CherryPick, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#16201 [6.16.z] [RFE] Remove remaining and unused fixtures around sca only
  pytest_fixtures/component/taxonomy.py
  robottelo/host_helpers/api_factory.py
  tests/foreman/cli/test_contentaccess.py
  tests/foreman/cli/test_host.py
  tests/foreman/ui/test_activationkey.py
  tests/upgrades/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16202 [6.16.z] adding the support for ipv4 and ipv6 parameterization for Container and VM
  pytest_fixtures/core/contenthosts.py
  pytest_plugins/fixture_markers.py
  robottelo/hosts.py
  robottelo/ssh.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16040 [6.16.z] [6.16]Add test for podman push on capsule
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16022 Fix test_positive_health_check_by_tags
  tests/foreman/maintain/test_health.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.16.z

#16204 [6.16.z] Fix test_positive_health_check_by_tags
  tests/foreman/maintain/test_health.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16206 [6.14.z] Bump cryptography from 43.0.0 to 43.0.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16207 [6.13.z] Bump cryptography from 43.0.0 to 43.0.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16209 [6.15.z] Bump cryptography from 43.0.0 to 43.0.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16208 [6.16.z] Bump cryptography from 43.0.0 to 43.0.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16210 adding customerscenario tags
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Stream

#16198 [6.16.z] improve installer tests compatibility with pit
  conf/capsule.yaml.template
  conf/robottelo.yaml.template
  conf/server.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/config/validators.py
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/hosts.py
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#16211 Fix for teardown failures
  robottelo/hosts.py
Labels: CherryPick, PRT-Passed, 6.16.z

#16134 [6.15.z] Check ipa command failure reason, improve logging. Logout first before attempting login.
  robottelo/hosts.py
  tests/foreman/cli/test_ldapauthsource.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#16212 [6.16.z] Fix for teardown failures
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16213 [6.16] search syntax fixes in host tests
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, PRT-Passed, 6.16.z

#16215 Update occurences of repo option in register to use repo_data
  pytest_fixtures/core/contenthosts.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16216 [6.16.z] Update occurences of repo option in register to use repo_data
  pytest_fixtures/core/contenthosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16026 [6.16.z] Fix cli host tests by applying pattern from similar test
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#16218 Fix SATELLITE_VERSION and SAT_NON_GA_VERSIONS in constants
  robottelo/constants/__init__.py
Labels: No-CherryPick, PRT-Passed, 6.16.z

#16203 Start using uv
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  Dockerfile
  scripts/config_helpers.py
  scripts/customer_scenarios.py
  scripts/fixture_cli.py
  scripts/tokenize_customer_scenario.py
  scripts/validate_config.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16223 [6.13.z] Start using uv
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  Dockerfile
  scripts/config_helpers.py
  scripts/customer_scenarios.py
  scripts/fixture_cli.py
  scripts/tokenize_customer_scenario.py
  scripts/validate_config.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16222 [6.14.z] Start using uv
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  Dockerfile
  scripts/config_helpers.py
  scripts/customer_scenarios.py
  scripts/fixture_cli.py
  scripts/tokenize_customer_scenario.py
  scripts/validate_config.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16221 [6.15.z] Start using uv
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  Dockerfile
  scripts/config_helpers.py
  scripts/customer_scenarios.py
  scripts/fixture_cli.py
  scripts/tokenize_customer_scenario.py
  scripts/validate_config.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16224 [6.16.z] Start using uv
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  Dockerfile
  scripts/config_helpers.py
  scripts/customer_scenarios.py
  scripts/fixture_cli.py
  scripts/tokenize_customer_scenario.py
  scripts/validate_config.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16196 [6.16.z] cvv incremental update and cv publish duration fix
  robottelo/cli/contentview.py
  tests/foreman/longrun/test_inc_updates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#15991 Fix cli contenthost tests
  tests/foreman/cli/test_contentview.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#16226 [6.16.z] Fix cli contenthost tests
  tests/foreman/cli/test_contentview.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16219 add teardown condition to execute other test seamlessly
  tests/foreman/cli/test_subscription.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.16.z

#16228 [6.16.z] add teardown condition to execute other test seamlessly
  tests/foreman/cli/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#15927 Add test for VMware PXE discovery provisioning
  pytest_fixtures/component/provision_vmware.py
  tests/foreman/api/test_computeresource_vmware.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#16229 [6.16.z] Add test for VMware PXE discovery provisioning
  pytest_fixtures/component/provision_vmware.py
  tests/foreman/api/test_computeresource_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16235 [6.15.z] Bump ruff from 0.6.3 to 0.6.4
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16236 [6.13.z] Bump ruff from 0.6.3 to 0.6.4
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16237 [6.14.z] Bump ruff from 0.6.3 to 0.6.4
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16243 [6.16.z] Mark test_positive_configure_cloud_connector for PIT
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16242 [6.15.z] Mark test_positive_configure_cloud_connector for PIT
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16241 [6.14.z] Mark test_positive_configure_cloud_connector for PIT
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16240 updated bz skip to jira skip
  tests/foreman/ui/test_hostgroup.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16247 [6.15.z] updated bz skip to jira skip
  tests/foreman/ui/test_hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16246 [6.16.z] updated bz skip to jira skip
  tests/foreman/ui/test_hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16245 [6.13.z] updated bz skip to jira skip
  tests/foreman/ui/test_hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16248 Base robottelo image on fedora/python-312
  Dockerfile
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16250 [6.16.z] Base robottelo image on fedora/python-312
  Dockerfile
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16252 [6.15.z] Base robottelo image on fedora/python-312
  Dockerfile
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16251 [6.14.z] Base robottelo image on fedora/python-312
  Dockerfile
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16249 [6.13.z] Base robottelo image on fedora/python-312
  Dockerfile
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#15960 Adapt api reporttemplate tests to removal of host statuses
  tests/foreman/api/test_reporttemplates.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#16253 [6.16.z] Adapt api reporttemplate tests to removal of host statuses
  tests/foreman/api/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16225 Move SAT_NON_GA_VERSIONS constant to robottelo config
  .github/workflows/auto_branching.yml
  conf/robottelo.yaml.template
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  tests/foreman/maintain/test_advanced.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, Stream, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#16258 [6.16.z] Move SAT_NON_GA_VERSIONS constant to robottelo config (#16225)
  conf/robottelo.yaml.template
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  tests/foreman/maintain/test_advanced.py
Labels: No-CherryPick, PRT-Passed, 6.16.z

#16259 [6.15.z] Move SAT_NON_GA_VERSIONS constant to robottelo config (#16225)
  conf/robottelo.yaml.template
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  tests/foreman/maintain/test_advanced.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#16260 [6.14.z] Move SAT_NON_GA_VERSIONS constant to robottelo config (#16225)
  conf/robottelo.yaml.template
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  tests/foreman/maintain/test_advanced.py
Labels: No-CherryPick, 6.14.z, PRT-Passed

#16220 Fix AK tests assertion errors
  tests/foreman/cli/test_activationkey.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Failed, 6.16.z

#16025 Fixing rh cloud rhai failures
  pytest_fixtures/component/rh_cloud.py
Labels: Easy Fix :), No-CherryPick, Stream, PRT-Failed

#16264 [6.16.z] Fix AK tests assertion errors
  tests/foreman/cli/test_activationkey.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.16.z

#16265 Small test fix for manage columns
  tests/foreman/ui/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16266 [6.16.z] Small test fix for manage columns
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16269 [6.13.z] Bump pytest-reportportal from 5.4.1 to 5.4.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16271 [6.15.z] Bump pytest-reportportal from 5.4.1 to 5.4.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16272 [6.14.z] Bump pytest-reportportal from 5.4.1 to 5.4.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16275 adding jira skip for org label issue
  tests/foreman/ui/test_organization.py
Labels: CherryPick, 6.16.z

#16261 using custom org for user timezone test
  tests/foreman/cli/test_organization.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16281 [6.16.z] using custom org for user timezone test
  tests/foreman/cli/test_organization.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16234 [6.16.z] Bump ruff from 0.6.3 to 0.6.4
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16287 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16286 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16288 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16289 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16290 Adjust rhel version under test
  tests/foreman/ui/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#16291 [6.16.z] Adjust rhel version under test
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#16293 [6.16] Small Workaround for Manage Columns test for All Hosts page
  tests/foreman/ui/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#16294 [6.16.z] [6.16] Small Workaround for Manage Columns test for All Hosts page
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#16297 [6.14.z] Bump broker[docker,hussh,podman] from 0.5.3 to 0.5.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16298 [6.15.z] Bump broker[docker,hussh,podman] from 0.5.3 to 0.5.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16299 [6.13.z] Bump broker[docker,hussh,podman] from 0.5.3 to 0.5.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16296 [6.16.z] Bump broker[docker,hussh,podman] from 0.5.3 to 0.5.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16277 [6.16.z] adding jira skip for org label issue
  tests/foreman/ui/test_organization.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16278 [6.13.z] using custom org for user timezone test
  tests/foreman/cli/test_organization.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z, PRT-Passed

#16214 Avoid calling decode on str
  tests/foreman/destructive/test_rename.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16302 [6.14.z] Avoid calling decode on str
  tests/foreman/destructive/test_rename.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#16301 [6.15.z] Avoid calling decode on str
  tests/foreman/destructive/test_rename.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#16304 [6.16.z] Avoid calling decode on str
  tests/foreman/destructive/test_rename.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16303 [6.13.z] Avoid calling decode on str
  tests/foreman/destructive/test_rename.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#16306 [6.16.z] Add tests for multiCV assignment with Hammer
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, PRT-Failed, 6.16.z

#16273 [6.15.z] Fix AK tests assertion errors (#16220)
  tests/foreman/cli/test_activationkey.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#16309 [6.16.z] api changes for 6.16
  tests/foreman/endtoend/test_api_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16311 [6.13.z] Bump pytest from 8.3.2 to 8.3.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#16312 [6.15.z] Bump pytest from 8.3.2 to 8.3.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#16267 Fix test interference
  tests/foreman/cli/test_host.py
Labels: CherryPick, PRT-Failed, 6.16.z

#16314 [6.16.z] Bump pytest from 8.3.2 to 8.3.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#16316 hammer commands updated for 6.16
  tests/foreman/data/hammer_commands.json
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16317 [6.16.z] hammer commands updated for 6.16
  tests/foreman/data/hammer_commands.json
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16315 [6.16.z] Fix test interference
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Failed, 6.16.z

#16318 Fix hostCollection UI e2e test
  tests/foreman/ui/test_hostcollection.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z

#16320 [6.15.z] Fix hostCollection UI e2e test
  tests/foreman/ui/test_hostcollection.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#16319 [6.16.z] Fix hostCollection UI e2e test
  tests/foreman/ui/test_hostcollection.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#16322 Fix long failing hostCollection test_negative_hosts_limit test
  tests/foreman/ui/test_hostcollection.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z

#16300 removing repository entity from bookmarks tests
  robottelo/constants/__init__.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16323 [6.15.z] Fix long failing hostCollection test_negative_hosts_limit test
  tests/foreman/ui/test_hostcollection.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#16324 [6.16.z] Fix long failing hostCollection test_negative_hosts_limit test
  tests/foreman/ui/test_hostcollection.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16325 [6.15.z] removing repository entity from bookmarks tests
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Failed

#16326 [6.14.z] removing repository entity from bookmarks tests
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Failed

#16327 [6.13.z] removing repository entity from bookmarks tests
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Failed

#16328 [6.16.z] removing repository entity from bookmarks tests
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Failed, 6.16.z

#15801 Disable SCA for test using subscriptions
  tests/foreman/api/test_hostcollection.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#16334 [6.14.z] Bump broker[docker,hussh,podman] from 0.5.4 to 0.5.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16332 [6.15.z] Bump broker[docker,hussh,podman] from 0.5.4 to 0.5.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16333 [6.13.z] Bump broker[docker,hussh,podman] from 0.5.4 to 0.5.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16338 [6.14.z] Bump manifester from 0.2.7 to 0.2.8
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#16337 [6.15.z] Bump manifester from 0.2.7 to 0.2.8
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#16335 [6.13.z] Bump manifester from 0.2.7 to 0.2.8
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#16336 [6.16.z] Bump manifester from 0.2.7 to 0.2.8
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#16331 [6.16.z] Bump broker[docker,hussh,podman] from 0.5.4 to 0.5.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16339 Do not store extraheader http auth in git config
  .github/workflows/update_robottelo_image.yml
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16345 Change from module to function fixtures
  tests/foreman/ui/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16341 [6.14.z] Do not store extraheader http auth in git config
  .github/workflows/update_robottelo_image.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16343 [6.16.z] Do not store extraheader http auth in git config
  .github/workflows/update_robottelo_image.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16344 [6.13.z] Do not store extraheader http auth in git config
  .github/workflows/update_robottelo_image.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16346 [6.16.z] Change from module to function fixtures
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#16340 Fix pxeless discovery test
  pytest_fixtures/component/provision_pxe.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#16356 [6.15.z] Bump ruff from 0.6.4 to 0.6.5
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#16358 [6.13.z] Bump ruff from 0.6.4 to 0.6.5
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#16359 [6.14.z] Bump ruff from 0.6.4 to 0.6.5
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z
