Repository SatelliteQE/robottelo, pull requests merged in 2025-01, with the labels that each got.

#17232 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#17233 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17235 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17107 Extend ISS mixed content export case with flatpak and import
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Stream, PRT-Passed

#16990 check links on EOL banner
  tests/foreman/ui/test_eol_banner.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17234 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#17245 [6.14.z] Bump ruff from 0.8.4 to 0.8.5
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17246 Update RHEL9 version for Leapp client
  pytest_fixtures/component/leapp_client.py
  tests/foreman/cli/test_leapp_client.py
  tests/foreman/ui/test_leapp_client.py
Labels: Easy Fix :), No-CherryPick, Failed_AutoCherryPick, 6.13.z

#16682 [6.15.z] Add network type option for Host checkout
  pytest_fixtures/component/leapp_client.py
  tests/foreman/ui/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Failed

#17181 Add rhel10 support in registration tests
  tests/foreman/api/test_registration.py
  tests/foreman/cli/test_fact.py
  tests/foreman/cli/test_registration.py
  tests/foreman/ui/test_fact.py
  tests/foreman/ui/test_registration.py
Labels: No-CherryPick, Stream, PRT-Passed

#17238 [6.15.z] Update API e2e test to use RegistrationCommand entity to register
  tests/foreman/endtoend/test_api_endtoend.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, 6.14.z, PRT-Passed

#17237 [6.13.z] Bump el9 kickstart version to 9.5
  robottelo/constants/__init__.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.13.z

#17252 [6.14.z] Bump ruff from 0.8.5 to 0.8.6
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17247 [6.13.z]Update API e2e test to use RegistrationCommand entity to register
  tests/foreman/endtoend/test_api_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#17248 [6.14.z] Update API e2e test to use RegistrationCommand entity to register
  tests/foreman/endtoend/test_api_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#16879 Test template sync using proxy
  pytest_fixtures/component/http_proxy.py
  robottelo/host_helpers/capsule_mixins.py
  tests/foreman/api/test_templatesync.py
  tests/foreman/cli/test_templatesync.py
  tests/foreman/ui/test_templatesync.py
Labels: No-CherryPick, PRT-Passed

#16930 Fix and extend the RH recommended repos case
  robottelo/constants/__init__.py
  tests/foreman/ui/test_repository.py
Labels: CherryPick, 6.15.z, PRT-Failed, 6.16.z

#17183 Fix legacy errata upgrade scenario tests
  robottelo/host_helpers/satellite_mixins.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_repository.py
  tests/upgrades/test_subscription.py
Labels: CherryPick, 6.14.z, 6.15.z, 6.16.z

#17197 Add test cases for pulpcore flatpak endpoint
  robottelo/constants/__init__.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/cli/test_flatpak.py
Labels: No-CherryPick, Stream, PRT-Failed

#17240 Split export and import SAT instances in ISS
  robottelo/host_helpers/satellite_mixins.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick

#17260 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  tests/robottelo/test_decorators.py
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17262 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  tests/robottelo/test_decorators.py
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#17261 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  tests/robottelo/test_decorators.py
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z

#17263 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  tests/robottelo/test_decorators.py
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17196 Update set_infrastructure _type for RHCloud
  robottelo/hosts.py
Labels: Framework Changes, CherryPick, AutoMerge_Cherry_Picked, Stream, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#17265 [6.15.z] Update set_infrastructure _type for RHCloud
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#17266 [6.14.z] Update set_infrastructure _type for RHCloud
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#17268 [6.16.z] Fix and extend the RH recommended repos case
  robottelo/constants/__init__.py
  tests/foreman/ui/test_repository.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17264 Update rhc tests to use manifest with satqe prefix
  conf/rh_cloud.yaml.template
  tests/foreman/ui/test_rhc.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.13.z, Stream, 6.14.z, 6.15.z, 6.16.z

#17273 [6.15.z] Fix and extend the RH recommended repos case
  robottelo/constants/__init__.py
  tests/foreman/ui/test_repository.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#16764 [6.16.z] [POC] New-Style Upgrade Tests
  conf/upgrade.yaml.template
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
  robottelo/utils/shared_resource.py
  tests/new_upgrades/__init__.py
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_contentview.py
  tests/new_upgrades/test_repository.py
  tests/robottelo/test_shared_resource.py
Labels: No-CherryPick, Auto_Cherry_Picked, Stale, PRT-Passed, 6.16.z

#16765 [6.15.z] [POC] New-Style Upgrade Tests
  conf/upgrade.yaml.template
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
  robottelo/utils/shared_resource.py
  tests/new_upgrades/__init__.py
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_contentview.py
  tests/new_upgrades/test_repository.py
  tests/robottelo/test_shared_resource.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#16767 [6.14.z] [POC] New-Style Upgrade Tests
  conf/upgrade.yaml.template
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
  robottelo/utils/shared_resource.py
  tests/new_upgrades/__init__.py
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_contentview.py
  tests/new_upgrades/test_repository.py
  tests/robottelo/test_shared_resource.py
Labels: No-CherryPick, Auto_Cherry_Picked, Stale, 6.14.z, PRT-Passed

#15402 [6.15.z] verify host owner name after host registration
  tests/foreman/cli/test_registration.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#17229 Correction in yaml value
  tests/foreman/api/test_classparameters.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17275 [6.16.z] Correction in yaml value
  tests/foreman/api/test_classparameters.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17276 Skip GCE test
  tests/foreman/api/test_computeresource_gce.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, 6.16.z

#17270 [6.16.z] Update rhc tests to use manifest with satqe prefix
  conf/rh_cloud.yaml.template
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#17269 [6.13.z] Update rhc tests to use manifest with satqe prefix
  conf/rh_cloud.yaml.template
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.13.z

#17271 [6.15.z] Update rhc tests to use manifest with satqe prefix
  conf/rh_cloud.yaml.template
  tests/foreman/ui/test_rhc.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#17267 [6.16.z] Update set_infrastructure _type for RHCloud
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.16.z

#17280 [6.16.z] Add test for subnet disk image download
  tests/foreman/cli/test_bootdisk.py
Labels: No-CherryPick, PRT-Passed, 6.16.z

#17281 [6.15.z] Add test for subnet disk image download
  tests/foreman/cli/test_bootdisk.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#17282 [6.14.z] Add test for subnet disk image download
  tests/foreman/cli/test_bootdisk.py
Labels: No-CherryPick, 6.14.z, PRT-Passed

#17136 Add tests for Libvirt secureboot provisioning
  pytest_fixtures/component/provision_pxe.py
  pytest_fixtures/component/provision_vmware.py
  tests/foreman/api/test_computeresource_libvirt.py
  tests/foreman/cli/test_computeresource_libvirt.py
  tests/foreman/ui/test_computeresource_libvirt.py
Labels: QETestCoverage, No-CherryPick, Stream, PRT-Failed

#17283 [6.15.z cherrypick]Skip GCE test
  tests/foreman/api/test_computeresource_gce.py
Labels: No-CherryPick, 6.15.z

#17284 [6.16.z cherrypick]Skip GCE test
  tests/foreman/api/test_computeresource_gce.py
Labels: No-CherryPick, 6.16.z

#17285 [6.14.z cherrypick]Skip GCE test
  tests/foreman/api/test_computeresource_gce.py
Labels: No-CherryPick, 6.14.z

#17152 updated curl to register host with name param instead id
  tests/foreman/ui/test_registration.py
Labels: QETestCoverage, No-CherryPick

#17274 Add rhsc9 repo to constants to fix tests using sat.REPOS
  robottelo/constants/__init__.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#17289 [6.16.z] Add rhsc9 repo to constants to fix tests using sat.REPOS
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17293 [6.14.z] Bump ruff from 0.8.6 to 0.9.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#16909 [6.16.z] Add tests for ansible-tower/AAP integration with Satellite
  conf/ansible.yaml.template
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/cli/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.16.z

#17300 [6.14.z] Bump deepdiff from 8.0.1 to 8.1.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#17299 [6.15.z] Bump deepdiff from 8.0.1 to 8.1.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#17301 [6.13.z] Bump deepdiff from 8.0.1 to 8.1.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#17315 [6.16.z] reboot not working for discovery host, added workaround
  tests/foreman/api/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#17314 [6.16.z] Update fact name for fetching fqdn fact
  tests/foreman/ui/test_fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17311 [6.14.z] Update fact name for fetching fqdn fact
  tests/foreman/ui/test_fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#17312 [6.15.z] Update fact name for fetching fqdn fact
  tests/foreman/ui/test_fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#17204 Mark one RHSSO test for PIT server
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/destructive/test_ldapauthsource.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, 6.16.z

#17321 [6.16.z] Mark one RHSSO test for PIT server
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/destructive/test_ldapauthsource.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17323 [6.15.z] Mark one RHSSO test for PIT server
  pytest_fixtures/component/satellite_auth.py
  tests/foreman/destructive/test_ldapauthsource.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#17328 [6.15.z] Bump apypie from 0.5.0 to 0.6.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17329 [6.16.z] Bump apypie from 0.5.0 to 0.6.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#17239 [6.16.z] check links on EOL banner
  tests/foreman/ui/test_eol_banner.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17330 Fix rails cache store test in installer
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Stream

#16766 [6.13.z] [POC] New-Style Upgrade Tests
  conf/upgrade.yaml.template
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
  robottelo/utils/shared_resource.py
  tests/new_upgrades/__init__.py
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_contentview.py
  tests/new_upgrades/test_repository.py
  tests/robottelo/test_shared_resource.py
Labels: No-CherryPick, Auto_Cherry_Picked, Stale, 6.13.z, PRT-Passed

#17310 Fix VMware compute profile test
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, Stream, PRT-Failed

#17333 [6.16.z] Update target os name due to RHELC-1737
  robottelo/utils/issue_handlers/__init__.py
  tests/foreman/api/test_convert2rhel.py
Labels: No-CherryPick, Failed_AutoCherryPick, PRT-Passed, 6.16.z

#17189 Fix long failing reporting API tests
  tests/foreman/api/test_reporttemplates.py
Labels: API, No-CherryPick, Stream, PRT-Passed

#17297 Added retries ensuring better handling of delays
  tests/foreman/api/test_computeresource_vmware.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#17309 Fix failing IPv6 puppet tests for RHEL7 host
  robottelo/hosts.py
Labels: No-CherryPick, Stream, PRT-Passed

#17335 [6.16.z] Added retries ensuring better handling of delays
  tests/foreman/api/test_computeresource_vmware.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
Labels: No-CherryPick, PRT-Passed, 6.16.z

#17207 Add e2e test case for flatpak
  pytest_fixtures/core/contenthosts.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/cli/test_flatpak.py
Labels: No-CherryPick, Stream, PRT-Passed

#17339 [cp 6.15] Extend search time for discoveryhost mac6.15
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#17341 [cp 6.14] Added retries ensuring better handling of delays
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_discoveredhost.py
Labels: No-CherryPick, 6.14.z, PRT-Passed

#17337 add new scenario - remove all cv envs from ak
  tests/foreman/cli/test_activationkey.py
Labels: No-CherryPick, Stream, PRT-Passed

#17143 Add ELS option for convert2rhel for EL7
  pytest_fixtures/component/taxonomy.py
  robottelo/constants/__init__.py
  tests/foreman/api/test_convert2rhel.py
Labels: QETestCoverage, No-CherryPick, Stream, PRT-Failed

#17345 Fix key error for RHEL 10 provisioning template tests
  pytest_fixtures/component/provisioning_template.py
Labels: No-CherryPick, Stream

#17350 [6.15.z] Bump manifester from 0.2.8 to 0.2.9
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#17349 [6.14.z] Bump manifester from 0.2.8 to 0.2.9
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#17352 [6.13.z] Bump manifester from 0.2.8 to 0.2.9
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#17360 [6.16.z] Bump python-box from 7.3.0 to 7.3.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#17359 [6.15.z] Bump python-box from 7.3.0 to 7.3.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#17361 [6.13.z] Bump python-box from 7.3.0 to 7.3.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#17362 [6.14.z] Bump python-box from 7.3.0 to 7.3.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#17366 [6.15.z] Bump broker[docker,hussh,podman] from 0.5.7 to 0.6.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Failed

#17365 [6.14.z] Bump broker[docker,hussh,podman] from 0.5.7 to 0.6.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Failed

#17363 [6.13.z] Bump broker[docker,hussh,podman] from 0.5.7 to 0.6.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Failed

#17154 Add test checking needs publish banner on cv index page
  tests/foreman/ui/test_contentview.py
Labels: CherryPick, Stream, PRT-Passed, 6.16.z

#17376 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  conf/dynaconf_hooks.py
  pytest_fixtures/core/contenthosts.py
  pytest_fixtures/core/reporting.py
  pytest_fixtures/core/xdist.py
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_hostcollection.py
  tests/foreman/api/test_hostgroup.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_notifications.py
  tests/foreman/api/test_ping.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_provisioning_puppet.py
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_syncplan.py
  tests/foreman/cli/test_acs.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_classparameters.py
  tests/foreman/cli/test_container_management.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_fact.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_organization.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_reporttemplates.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/destructive/test_contentview.py
  tests/foreman/destructive/test_discoveredhost.py
  tests/foreman/destructive/test_katello_certs_check.py
  tests/foreman/destructive/test_rename.py
  tests/foreman/longrun/test_inc_updates.py
  tests/foreman/maintain/test_backup_restore.py
  tests/foreman/maintain/test_health.py
  tests/foreman/sys/test_pulp3_filesystem.py
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_capsulecontent.py
  tests/foreman/ui/test_computeprofiles.py
  tests/foreman/ui/test_domain.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_provisioningtemplate.py
  tests/foreman/ui/test_rhc.py
  tests/foreman/ui/test_search.py
  tests/foreman/ui/test_subnet.py
  tests/foreman/ui/test_subscription.py
  tests/foreman/ui/test_syncplan.py
  tests/robottelo/test_hammer.py
  tests/upgrades/test_capsule.py
  tests/upgrades/test_errata.py
Labels: dependencies, No-CherryPick, 6.15.z, maintenance

#17375 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  conf/dynaconf_hooks.py
  pytest_fixtures/core/contenthosts.py
  pytest_fixtures/core/reporting.py
  pytest_fixtures/core/xdist.py
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_errata.py
  tests/foreman/api/test_hostcollection.py
  tests/foreman/api/test_hostgroup.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_notifications.py
  tests/foreman/api/test_ping.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_provisioning_puppet.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_syncplan.py
  tests/foreman/cli/test_acs.py
  tests/foreman/cli/test_classparameters.py
  tests/foreman/cli/test_container_management.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_fact.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_organization.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_reporttemplates.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/destructive/test_discoveredhost.py
  tests/foreman/destructive/test_katello_certs_check.py
  tests/foreman/destructive/test_rename.py
  tests/foreman/longrun/test_inc_updates.py
  tests/foreman/maintain/test_backup_restore.py
  tests/foreman/maintain/test_health.py
  tests/foreman/sys/test_pulp3_filesystem.py
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_computeprofiles.py
  tests/foreman/ui/test_domain.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_provisioningtemplate.py
  tests/foreman/ui/test_rhc.py
  tests/foreman/ui/test_subnet.py
  tests/foreman/ui/test_subscription.py
  tests/foreman/ui/test_syncplan.py
  tests/robottelo/test_hammer.py
  tests/upgrades/test_capsule.py
  tests/upgrades/test_errata.py
Labels: dependencies, No-CherryPick, 6.14.z, maintenance

#17378 Narrow down host's subscription status check
  robottelo/hosts.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#17380 [6.16.z] Narrow down host's subscription status check
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17379 [6.14.z] Narrow down host's subscription status check
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#17381 [6.15.z] Narrow down host's subscription status check
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#17384 Prevent satellite-installer false negative
  tests/foreman/installer/test_installer.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#17393 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17391 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17404 [6.15.z] Bump navmazing from 1.2.2 to 1.3.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#17402 [6.14.z] Bump navmazing from 1.2.2 to 1.3.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#17401 [6.13.z] Bump navmazing from 1.2.2 to 1.3.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#17403 [6.16.z] Bump navmazing from 1.2.2 to 1.3.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#17387 [6.16.z] Prevent satellite-installer false negative
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#17411 [6.16.z] Bump dynaconf[vault] from 3.2.6 to 3.2.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#17409 [6.15.z] Bump dynaconf[vault] from 3.2.6 to 3.2.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#17408 [6.13.z] Bump dynaconf[vault] from 3.2.6 to 3.2.7
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#16789 preparation for new yggdrasil
  tests/foreman/api/test_remoteexecution.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/destructive/test_registration.py
Labels: No-CherryPick, Stream, PRT-Passed

#17348 negative assertions for rex effective user tests
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.16.z

#17412 fixture to get expected permissions
  conftest.py
  pytest_fixtures/component/permissions.py
  tests/foreman/api/test_permission.py
  tests/foreman/ui/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#17422 Fix Capsule test case for non-admin user
  tests/foreman/api/test_capsulecontent.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, PRT-Passed, 6.16.z

#17426 [6.16.z] Fix Capsule test case for non-admin user
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17425 [6.15.z] Fix Capsule test case for non-admin user
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#17421 update rh satellite capsule version to rhel9 from rhel7
  robottelo/constants/__init__.py
  tests/foreman/ui/test_package.py
Labels: TestFailure, Upgrades, No-CherryPick, 6.16.z

#17413 Add a case for active_only box on the sync_status page
  tests/foreman/ui/test_sync.py
Labels: CherryPick, PRT-Passed, 6.16.z

#17424 [6.14] fixture to get expected permissions
  conftest.py
  pytest_fixtures/component/permissions.py
  tests/foreman/api/test_permission.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, PRT-Passed

#17423 [6.15] fixture to get expected permissions
  conftest.py
  pytest_fixtures/component/permissions.py
  tests/foreman/api/test_permission.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, PRT-Passed

#17434 [6.16.z] more future-proof scap profile selected
  robottelo/constants/__init__.py
  tests/foreman/longrun/test_oscap.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17439 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17440 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17043 test rex using values from global parameters
  conftest.py
  pytest_fixtures/component/global_params.py
  pytest_fixtures/component/settings.py
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Stream

#17433 [6.16.z] Add a case for active_only box on the sync_status page
  tests/foreman/ui/test_sync.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#17446 [6.14.z] Bump wrapanapi from 3.6.6 to 3.7.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17447 [6.15.z] Bump wrapanapi from 3.6.6 to 3.7.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17443 Remove rhsc7 check from robottelo
  robottelo/constants/__init__.py
  robottelo/host_helpers/cli_factory.py
  robottelo/hosts.py
  tests/foreman/ui/test_package.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#17450 [6.16.z] Remove rhsc7 check from robottelo
  robottelo/host_helpers/cli_factory.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17458 [6.14.z] Fix legacy errata upgrade scenario tests (#17183)
  robottelo/host_helpers/satellite_mixins.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_subscription.py
Labels: No-CherryPick, 6.14.z

#17460 [6.16.z] Fix legacy errata upgrade scenario tests (#17183)
  robottelo/host_helpers/satellite_mixins.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_repository.py
  tests/upgrades/test_subscription.py
Labels: No-CherryPick, 6.16.z

#17457 [6.15.z] Fix legacy errata upgrade scenario tests (#17183)
  robottelo/host_helpers/satellite_mixins.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_subscription.py
Labels: No-CherryPick, 6.15.z

#17405 Add Python 3.13 for PR checks in GHA
  .github/workflows/auto_branching.yml
  .github/workflows/pull_request.yml
Labels: Framework Changes, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, 6.16.z

#17453 [6.14.z] Bump broker[docker,hussh,podman] from 0.6.3 to 0.6.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#17455 [6.16.z] Bump broker[docker,hussh,podman] from 0.6.3 to 0.6.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Failed, 6.16.z

#17456 [6.15.z] Bump broker[docker,hussh,podman] from 0.6.3 to 0.6.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Failed

#17454 [6.13.z] Bump broker[docker,hussh,podman] from 0.6.3 to 0.6.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Failed

#17385 Updated the fixture for rhel_ver to correctly fetch the appropriate kickstart repository
  pytest_fixtures/component/provisioning_template.py
Labels: Easy Fix :), No-CherryPick, Stream, PRT-Passed

#17469 Fix ProvisioningTemplate test for RHEL10
  tests/foreman/api/test_provisioningtemplate.py
Labels: TestFailure, Easy Fix :), No-CherryPick, Stream, PRT-Passed

#17467 Fix ansible tests by using proxy for connecting to ansible-galaxy
  tests/foreman/api/test_ansible.py
  tests/foreman/cli/test_ansible.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z
