Repository SatelliteQE/robottelo, pull requests merged in 2025-04, with the labels that each got.

#18057 Increase wait_for_connection timeout for leapp hosts on reboot
  pytest_fixtures/component/leapp_client.py
  robottelo/hosts.py
  tests/foreman/cli/test_leapp_client.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z, 6.17.z

#17945 test task search by start date
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z

#18101 [6.17.z] test task search by start date
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18100 [6.17.z] Increase wait_for_connection timeout for leapp hosts on reboot
  pytest_fixtures/component/leapp_client.py
  robottelo/hosts.py
  tests/foreman/cli/test_leapp_client.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18084 [6.17.z] SAT-29623: User last login time is not updated when login with external authentication
  tests/foreman/ui/test_ldap_authentication.py
Labels: No-CherryPick, PRT-Passed

#18103 [6.16.z Cherrypick] Increase wait_for_connection timeout for leapp hosts on reboot
  pytest_fixtures/component/leapp_client.py
  robottelo/hosts.py
  tests/foreman/cli/test_leapp_client.py
Labels: TestFailure, No-CherryPick, PRT-Passed, 6.16.z

#18035 [Customer Case] Test for compliance policies
  tests/foreman/api/test_rhcloud_inventory.py
Labels: Tier 1 ACK, CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, 6.16.z, 6.17.z

#18113 [6.14.z] Bump pytest-cov from 6.0.0 to 6.1.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#18114 [6.16.z] Bump pytest-cov from 6.0.0 to 6.1.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18112 [6.15.z] Bump pytest-cov from 6.0.0 to 6.1.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18115 [6.17.z] Bump pytest-cov from 6.0.0 to 6.1.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18102 [6.17] updating hammer commands list
  tests/foreman/data/hammer_commands.json
Labels: TestFailure, No-CherryPick, 6.17.z

#17987 Update certificate key usage to match documentation
  tests/foreman/data/openssl.cnf
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z

#18117 [6.17.z] Update certificate key usage to match documentation
  tests/foreman/data/openssl.cnf
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18098 Add content attributes to ansible inventory report
  tests/foreman/cli/test_reporttemplates.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#18118 [6.17.z] Add content attributes to ansible inventory report
  tests/foreman/cli/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18119 [6.16.z] Add content attributes to ansible inventory report
  tests/foreman/cli/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#18120 [6.15.z] Add content attributes to ansible inventory report
  tests/foreman/cli/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#18028 [6.15.z] fixes in scap policy tests
  tests/foreman/ui/test_oscappolicy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#18125 [6.15.z] Bump tenacity from 9.0.0 to 9.1.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18124 [6.16.z] Bump tenacity from 9.0.0 to 9.1.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18126 [6.17.z] Bump tenacity from 9.0.0 to 9.1.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18097 [6.16.z] Add permissions for foreman_statistics plugin
  pytest_fixtures/component/permissions.py
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18096 [6.17.z] Add permissions for foreman_statistics plugin
  pytest_fixtures/component/permissions.py
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18095 updating hammer commands list
  tests/foreman/data/hammer_commands.json
Labels: No-CherryPick, PRT-Failed

#18130 [6.16.z] Fix HTTP proxy insights tests
  pytest_fixtures/component/http_proxy.py
  tests/foreman/cli/test_http_proxy.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#18131 [6.15.z] Fix HTTP proxy insights tests
  pytest_fixtures/component/http_proxy.py
  tests/foreman/cli/test_http_proxy.py
Labels: CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#18139 enable ipv6 proxy when running the redhat_manifest test
  tests/foreman/sys/test_fam.py
Labels: CherryPick, PRT-Passed, 6.17.z

#18141 [6.17.z] enable ipv6 proxy when running the redhat_manifest test
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.17.z

#18122 SAT-28552 system purpose SLA attribute
  pytest_fixtures/component/virtwho_config.py
  tests/foreman/virtwho/cli/test_esx_sca.py
Labels: CherryPick, PRT-Passed, 6.17.z

#18105 Fix Satellite installer IPv6 tests
  tests/foreman/installer/test_installer.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z

#18146 [6.17.z] Fix Satellite installer IPv6 tests
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#18144 [6.17.z] SAT-28552 system purpose SLA attribute
  pytest_fixtures/component/virtwho_config.py
  tests/foreman/virtwho/cli/test_esx_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.17.z

#18156 [6.14.z] Bump pytest-cov from 6.1.0 to 6.1.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#18155 [6.15.z] Bump pytest-cov from 6.1.0 to 6.1.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18157 [6.16.z] Bump pytest-cov from 6.1.0 to 6.1.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18161 [6.17.z] Bump apypie from 0.7.0 to 0.7.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18160 [6.16.z] Bump apypie from 0.7.0 to 0.7.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18158 [6.15.z] Bump apypie from 0.7.0 to 0.7.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18030 [6.14.z] fixes in scap policy tests
  tests/foreman/ui/test_oscappolicy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#17550 populate future date subscription in satellite
  pytest_fixtures/component/taxonomy.py
  tests/foreman/ui/test_subscription.py
Labels: CherryPick, Stream, PRT-Passed, 6.17.z

#18140 Add post-provisioning build status assertion
  tests/foreman/api/test_provisioning.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.16.z, 6.17.z

#18163 [6.17.z] populate future date subscription in satellite
  pytest_fixtures/component/taxonomy.py
  tests/foreman/ui/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18164 [6.16.z] Add post-provisioning build status assertion
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#18165 [6.17.z] Add post-provisioning build status assertion
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#17841 update package name during checking config report
  tests/foreman/ui/test_ansible.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, Stream, 6.14.z, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#18167 [6.17.z] update package name during checking config report
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18168 [6.16.z] update package name during checking config report
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#18175 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18173 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18174 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#18121 custom workdir procedure adjusted for the new yggdrasil
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18170 [6.15.z] update package name during checking config report
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#18128 Extend http proxy test with Test Connection
  tests/foreman/ui/test_http_proxy.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18178 [6.17.z] Extend http proxy test with Test Connection
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18013 Update the jira card in test and firmware_type.
  tests/foreman/ui/test_computeresource_vmware.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#18145 [Customer Case] Test for insights global parameters
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.17.z

#18184 [6.17.z] [Customer Case] Test for insights global parameters
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18186 Update the jira card in test
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#18189 Docstring_fix_changeContentSource
  tests/foreman/ui/test_host.py
Labels: Easy Fix :), CherryPick, 6.14.z, 6.15.z, 6.16.z, 6.17.z

#18179 [6.16.z] Add AAP2.5 parameterization in AAP provisioning callback tests
  tests/foreman/cli/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Failed, 6.16.z

#18193 [6.14.z] Docstring_fix_changeContentSource
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#18191 [6.15.z] Docstring_fix_changeContentSource
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18190 [6.17.z] Docstring_fix_changeContentSource
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18188 SAT-30970 - verify f-m service restart works after enabling debug mode on Satellite
  tests/foreman/maintain/test_service.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z

#18195 [6.17.z] SAT-30970 - verify f-m service restart works after enabling debug mode on Satellite
  tests/foreman/maintain/test_service.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#17842 Fix Ansible tests
  tests/foreman/api/test_ansible.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#18187 Update the jira card in test
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, 6.14.z

#18172 neccessary fixture in test definition
  pytest_fixtures/component/virtwho_config.py
  tests/foreman/virtwho/api/test_esx_sca.py
  tests/foreman/virtwho/api/test_hyperv_sca.py
  tests/foreman/virtwho/api/test_libvirt_sca.py
  tests/foreman/virtwho/cli/test_esx_sca.py
  tests/foreman/virtwho/cli/test_hyperv_sca.py
  tests/foreman/virtwho/cli/test_libvirt_sca.py
  tests/foreman/virtwho/ui/test_esx_sca.py
  tests/foreman/virtwho/ui/test_hyperv_sca.py
  tests/foreman/virtwho/ui/test_libvirt_sca.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18200 [6.17.z] neccessary fixture in test definition
  pytest_fixtures/component/virtwho_config.py
  tests/foreman/virtwho/api/test_esx_sca.py
  tests/foreman/virtwho/api/test_hyperv_sca.py
  tests/foreman/virtwho/api/test_libvirt_sca.py
  tests/foreman/virtwho/cli/test_esx_sca.py
  tests/foreman/virtwho/cli/test_hyperv_sca.py
  tests/foreman/virtwho/cli/test_libvirt_sca.py
  tests/foreman/virtwho/ui/test_esx_sca.py
  tests/foreman/virtwho/ui/test_hyperv_sca.py
  tests/foreman/virtwho/ui/test_libvirt_sca.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#18058 Errata 6.17.0 signoff fixes
  robottelo/constants/__init__.py
  robottelo/host_helpers/api_factory.py
  tests/foreman/api/test_errata.py
  tests/foreman/cli/test_errata.py
  tests/foreman/ui/test_errata.py
Labels: CherryPick, Stream, PRT-Passed, 6.16.z, 6.17.z

#18133 Insights e2e test updates
  pytest_fixtures/component/rh_cloud.py
  tests/foreman/ui/test_rhcloud_insights.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18143 Relax component fixtures tiering
  .github/CODEOWNERS
Labels: CherryPick, 6.15.z, 6.16.z, 6.17.z

#18212 [6.15.z] Relax component fixtures tiering
  .github/CODEOWNERS
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18210 [6.16.z] Relax component fixtures tiering
  .github/CODEOWNERS
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18166 Fix IPv6 issues in IDM and AD setup
  conf/ldap.yaml.template
  pytest_fixtures/component/satellite_auth.py
  robottelo/config/validators.py
  robottelo/hosts.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18214 [6.17.z] Fix IPv6 issues in IDM and AD setup
  conf/ldap.yaml.template
  pytest_fixtures/component/satellite_auth.py
  robottelo/config/validators.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18219 [6.14.z] Fix test_positive_rename_satellite to assert old hostname absence better
  tests/foreman/destructive/test_rename.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#18211 [6.17.z] Relax component fixtures tiering
  .github/CODEOWNERS
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18222 Lowercase HTTP proxy in UI tests
  tests/foreman/ui/test_http_proxy.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18216 [6.15.z] Fix test_positive_rename_satellite to assert old hostname absence better
  tests/foreman/destructive/test_rename.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#18185 Update the jira card in test
  tests/foreman/ui/test_computeresource_vmware.py
Labels: No-CherryPick, PRT-Passed, 6.16.z

#18213 Fix test_purge_pulp_tasks by removing jq dependency
  tests/foreman/cli/test_repositories.py
Labels: Easy Fix :), CherryPick, PRT-Passed, 6.16.z, 6.17.z

#18230 [6.16.z] Fix test_purge_pulp_tasks by removing jq dependency
  tests/foreman/cli/test_repositories.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#18223 [6.17.z] Lowercase HTTP proxy in UI tests
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18229 [6.17.z] Fix test_purge_pulp_tasks by removing jq dependency
  tests/foreman/cli/test_repositories.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.17.z

#18203 [6.17.z] Errata 6.17.0 signoff fixes
  robottelo/constants/__init__.py
  robottelo/host_helpers/api_factory.py
  tests/foreman/api/test_errata.py
  tests/foreman/cli/test_errata.py
  tests/foreman/ui/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.17.z

#18215 new yggdrasil rhel10 only
  robottelo/hosts.py
Labels: Easy Fix :), CherryPick, PRT-Passed, 6.16.z, 6.17.z

#18234 [6.17.z] new yggdrasil rhel10 only
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18233 [6.16.z] new yggdrasil rhel10 only
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#18217 [6.17.z] Fix test_positive_rename_satellite to assert old hostname absence better
  tests/foreman/destructive/test_rename.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18209 [6.17.z] Insights e2e test updates
  pytest_fixtures/component/rh_cloud.py
  tests/foreman/ui/test_rhcloud_insights.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#18241 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18242 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#18243 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18244 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18247 ACS - remove invalid parametrization combination (rhui-file)
  tests/foreman/api/test_acs.py
  tests/foreman/cli/test_acs.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, 6.16.z, 6.17.z

#18249 [6.17.z] ACS - remove invalid parametrization combination (rhui-file)
  tests/foreman/api/test_acs.py
  tests/foreman/cli/test_acs.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#18248 [6.16.z] ACS - remove invalid parametrization combination (rhui-file)
  tests/foreman/api/test_acs.py
  tests/foreman/cli/test_acs.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#18250 [6.15.z] ACS - remove invalid parametrization combination (rhui-file)
  tests/foreman/api/test_acs.py
  tests/foreman/cli/test_acs.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#18218 [6.16.z] Fix test_positive_rename_satellite to assert old hostname absence better
  tests/foreman/destructive/test_rename.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#18228 [6.17.z] Bump productmd from 1.43 to 1.44
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18225 [6.16.z] Bump productmd from 1.43 to 1.44
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18227 [6.15.z] Bump productmd from 1.43 to 1.44
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18226 [6.14.z] Bump productmd from 1.43 to 1.44
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#18246 Correct permissions for snapshot plugin
  robottelo/constants/__init__.py
Labels: CherryPick, 6.16.z, 6.17.z

#18245 Ensure all permissions for certain resource type are found
  tests/foreman/api/test_permission.py
Labels: CherryPick, 6.16.z, 6.17.z

#18261 [6.17.z] dashboard asserts updated
  tests/foreman/ui/test_dashboard.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18260 missing cs tags
  tests/foreman/cli/test_ansible.py
Labels: Easy Fix :), CherryPick, 6.16.z, 6.17.z

#18254 [6.16.z] Correct permissions for snapshot plugin
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18255 [6.17.z] Correct permissions for snapshot plugin
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18257 [6.16.z] Ensure all permissions for certain resource type are found
  tests/foreman/api/test_permission.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18258 [6.17.z] Ensure all permissions for certain resource type are found
  tests/foreman/api/test_permission.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18264 [6.16.z] missing cs tags
  tests/foreman/cli/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18263 [6.17.z] missing cs tags
  tests/foreman/cli/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18274 [6.14.z] Bump broker[docker,hussh,podman] from 0.6.7 to 0.6.8
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#18272 [6.15.z] Bump broker[docker,hussh,podman] from 0.6.7 to 0.6.8
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#18273 [6.17.z] Bump broker[docker,hussh,podman] from 0.6.7 to 0.6.8
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Failed, 6.17.z

#18275 [6.16.z] Bump broker[docker,hussh,podman] from 0.6.7 to 0.6.8
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Failed, 6.16.z

#18279 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#18278 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18280 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18281 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18251 Retrieve the correct host info from the inventories.
  tests/foreman/cli/test_ansible.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, Stream, 6.16.z, 6.17.z

#18283 [6.17.z] Retrieve the correct host info from the inventories.
  tests/foreman/cli/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18259 Check UI reaction to subscription_connection_enabled setting
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: No-CherryPick, Stream, PRT-Passed

#18284 Skip oVirt/RHV tests on IPv6 setups
  tests/foreman/sys/test_fam.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.17.z

#18288 [6.17.z] Skip oVirt/RHV tests on IPv6 setups
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#18291 [6.16.z] Remove test_positive_capsule_certs_generate_with_special_char (#17521)
  .github/CODEOWNERS
  tests/foreman/destructive/test_capsule.py
Labels: No-CherryPick, 6.16.z

#18295 [6.17.z] add coverage for SAT-28826
  tests/foreman/longrun/test_oscap.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#16772 Convert activation key upgrade scenario to new format
  .github/CODEOWNERS
  tests/new_upgrades/test_activation_key.py
Labels: Upgrades, CherryPick, 6.14.z, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#18299 [6.17.z] Convert activation key upgrade scenario to new format
  .github/CODEOWNERS
  tests/new_upgrades/test_activation_key.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18256 Add a test case for loadbalanced container content
  tests/foreman/destructive/test_capsule_loadbalancer.py
Labels: No-CherryPick, Stream, PRT-Passed

#18290 Add a test case for podman login without password
  pytest_fixtures/core/contenthosts.py
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Stream

#18231 Using Broker.multi_manager to fix ansible test checkout for multiple hosts
  tests/foreman/api/test_ansible.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18287 Fix ansible provisioning callback test
  tests/foreman/cli/test_ansible.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z, 6.17.z

#18310 [6.17.z] Using Broker.multi_manager to fix ansible test checkout for multiple hosts
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18253 Use rex_contenthosts fixture in ansible verbosity test
  pytest_fixtures/core/contenthosts.py
  tests/foreman/ui/test_ansible.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#18312 [6.16.z] Fix ansible provisioning callback test
  tests/foreman/cli/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#18311 [6.17.z] Fix ansible provisioning callback test
  tests/foreman/cli/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18317 [6.14.z] Use rex_contenthosts fixture in ansible verbosity test
  pytest_fixtures/core/contenthosts.py
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z, PRT-Passed

#18315 [6.16.z] Use rex_contenthosts fixture in ansible verbosity test
  pytest_fixtures/core/contenthosts.py
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#18316 [6.17.z] Use rex_contenthosts fixture in ansible verbosity test
  pytest_fixtures/core/contenthosts.py
  tests/foreman/ui/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18308 use "StrictHostKeyChecking accept-new" instead of ssh-keyscan
  robottelo/host_helpers/satellite_mixins.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#18322 [6.17.z] use "StrictHostKeyChecking accept-new" instead of ssh-keyscan
  robottelo/host_helpers/satellite_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18323 [SAT-22655] Test ContentHost query with Bool
  tests/foreman/ui/test_contenthost.py
Labels: No-CherryPick, Stream, PRT-Passed

#18330 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#18329 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18332 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18331 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z
