Repository SatelliteQE/robottelo, pull requests merged in 2025-08, with the labels that each got.

#19094 [6.17.z] Run tracer tests against el10
  conf/repos.yaml.template
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19035 Automate test to set parameters in subnet.
  tests/foreman/cli/test_subnet.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#19099 [6.17.z] Automate test to set parameters in subnet.
  tests/foreman/cli/test_subnet.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19076 [6.17.z] Remove no_http_proxy parameter in HTTP Proxy testing
  pytest_fixtures/component/http_proxy.py
  robottelo/hosts.py
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#19106 Test Change Owner Fix
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Stream, PRT-Passed

#19117 Update team designation from Phoenix-content to Artemis (#19000)
  tests/foreman/api/test_acs.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_contentcredentials.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_lifecycleenvironment.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_repositories.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_repository_set.py
  tests/foreman/cli/test_acs.py
  tests/foreman/cli/test_artifacts.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_container_management.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_contentviewfilter.py
  tests/foreman/cli/test_docker.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_flatpak.py
  tests/foreman/cli/test_lifecycleenvironment.py
  tests/foreman/cli/test_ostreebranch.py
  tests/foreman/cli/test_product.py
  tests/foreman/cli/test_repositories.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_repository_set.py
  tests/foreman/cli/test_syncplan.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/destructive/test_capsulecontent.py
  tests/foreman/destructive/test_contentview.py
  tests/foreman/destructive/test_repository.py
  tests/foreman/sys/test_pulp3_filesystem.py
  tests/foreman/ui/test_acs.py
  tests/foreman/ui/test_capsulecontent.py
  tests/foreman/ui/test_containerimagetag.py
  tests/foreman/ui/test_contentcredentials.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_contentview_old.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_lifecycleenvironment.py
  tests/foreman/ui/test_modulestreams.py
  tests/foreman/ui/test_package.py
  tests/foreman/ui/test_product.py
  tests/foreman/ui/test_repositories.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
  tests/foreman/ui/test_syncplan.py
  tests/new_upgrades/test_contentview.py
  tests/new_upgrades/test_errata.py
  tests/new_upgrades/test_repository.py
  tests/new_upgrades/test_satellitesync.py
  tests/new_upgrades/test_syncplan.py
  tests/upgrades/test_contentview.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_repository.py
  tests/upgrades/test_satellitesync.py
  tests/upgrades/test_syncplan.py
Labels: No-CherryPick, 6.17.z

#19118 Update team designation from Phoenix-content to Artemis (#19000)
  tests/foreman/api/test_acs.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_contentcredentials.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_lifecycleenvironment.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_repositories.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_repository_set.py
  tests/foreman/cli/test_acs.py
  tests/foreman/cli/test_artifacts.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_container_management.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_contentviewfilter.py
  tests/foreman/cli/test_docker.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_lifecycleenvironment.py
  tests/foreman/cli/test_ostreebranch.py
  tests/foreman/cli/test_product.py
  tests/foreman/cli/test_repositories.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_repository_set.py
  tests/foreman/cli/test_syncplan.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/destructive/test_capsulecontent.py
  tests/foreman/destructive/test_contentview.py
  tests/foreman/destructive/test_repository.py
  tests/foreman/sys/test_pulp3_filesystem.py
  tests/foreman/ui/test_acs.py
  tests/foreman/ui/test_capsulecontent.py
  tests/foreman/ui/test_containerimagetag.py
  tests/foreman/ui/test_contentcredentials.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_contentview_old.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_lifecycleenvironment.py
  tests/foreman/ui/test_modulestreams.py
  tests/foreman/ui/test_package.py
  tests/foreman/ui/test_product.py
  tests/foreman/ui/test_repositories.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
  tests/foreman/ui/test_syncplan.py
  tests/new_upgrades/test_contentview.py
  tests/new_upgrades/test_errata.py
  tests/new_upgrades/test_repository.py
  tests/new_upgrades/test_satellitesync.py
  tests/new_upgrades/test_syncplan.py
  tests/upgrades/test_contentview.py
  tests/upgrades/test_errata.py
  tests/upgrades/test_repository.py
  tests/upgrades/test_satellitesync.py
  tests/upgrades/test_syncplan.py
Labels: No-CherryPick, 6.16.z

#19108 Remove new_host_ui fixture
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Stream, PRT-Passed

#19135 [6.15.z] Bump redis from 6.2.0 to 6.3.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19131 Omit http_proxy_policy='none' for repository on IPv6
  tests/foreman/api/test_http_proxy.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z

#19124 Fix backup/restore tests for mismatched fixture issue
  pytest_fixtures/component/maintain.py
  tests/foreman/maintain/test_backup_restore.py
Labels: No-CherryPick, Stream, PRT-Failed

#19109 Make non-proxy traffic blocking fixture IPv6 ready
  pytest_fixtures/core/sys.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z

#19141 [6.17.z] Make non-proxy traffic blocking fixture IPv6 ready
  pytest_fixtures/core/sys.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18816 Add cert-based login parametrization for flatpak
  tests/foreman/cli/test_flatpak.py
Labels: No-CherryPick, Stream, PRT-Passed

#19162 [6.15.z] Bump ruff from 0.12.7 to 0.12.8
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19154 [6.16.z] Fix deploy_configure_by_script for Virtwho tests
  robottelo/utils/virtwho.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.16.z

#19152 [6.15.z] Fix deploy_configure_by_script for Virtwho tests
  robottelo/utils/virtwho.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Failed

#19163 Fix virtwho tests failing on subscription-manager registration
  pytest_fixtures/component/virtwho_config.py
  robottelo/utils/virtwho.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#19165 [6.17.z] Fix virtwho tests failing on subscription-manager registration
  pytest_fixtures/component/virtwho_config.py
  robottelo/utils/virtwho.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#19170 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19169 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19161 [6.15.z] Bump redis from 6.3.0 to 6.4.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19173 [6.16.z] Bump pre-commit from 4.2.0 to 4.3.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19174 [6.17.z] Bump pre-commit from 4.2.0 to 4.3.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19125 fix RHC Recommendation UI Test
  tests/foreman/ui/test_rhcloud_insights.py
Labels: No-CherryPick, Stream, PRT-Failed

#19183 [6.17.z] Remove Virt-whoConfigurePlugin from non_satCI_components
  pytest_plugins/marker_deselection.py
Labels: No-CherryPick, 6.17.z

#19093 API test case for job-template
  tests/foreman/api/test_jobtemplate.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, 6.16.z, 6.17.z

#19184 Add a test case for flatpak app install via Capsule and CV
  pytest_fixtures/component/flatpak.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_flatpak.py
Labels: No-CherryPick, Stream, PRT-Passed

#18985 Extend flatpak remotes test with remote details page inspection
  tests/foreman/ui/test_flatpak.py
Labels: No-CherryPick, Stream, PRT-Passed

#19197 [6.15.z] Backport of #19187
  .pre-commit-config.yaml
Labels: No-CherryPick, 6.15.z

#19167 Fix IoP foreman-maintain tests failing on podman login
  pytest_fixtures/component/rh_cloud.py
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
Labels: No-CherryPick, Stream, PRT-Passed

#19196 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19140 6.17 tracer fixes
  tests/foreman/ui/test_host.py
Labels: TestFailure, No-CherryPick, PRT-Passed, 6.17.z

#19112 test mcp client authentication
  pytest_fixtures/component/mcp.py
  tests/foreman/sys/test_mcp.py
Labels: No-CherryPick, Stream

#19111 Add backup/restore test for Insights on Prem Satellite
  tests/foreman/maintain/test_backup_restore.py
Labels: No-CherryPick, Stream, PRT-Passed

#19208 Extend the podman cert auth test case for capsules
  tests/foreman/cli/test_container_management.py
Labels: No-CherryPick, Stream, PRT-Passed

#19058 test condensed usage report
  .github/CODEOWNERS
  pytest_fixtures/component/usage_report.py
  robottelo/cli/sm_report.py
  robottelo/constants/__init__.py
  robottelo/host_helpers/satellite_mixins.py
  tests/foreman/cli/test_usage_report.py
  tests/foreman/data/usage_report.yml
  tests/foreman/data/usage_report_condensed.yml
Labels: No-CherryPick, Stream, PRT-Passed

#19212 Remove manage_crond setup from test_positive_maintenance_mode
  pytest_fixtures/component/maintain.py
  tests/foreman/maintain/test_maintenance_mode.py
Labels: No-CherryPick, Stream, PRT-Passed

#19216 [6.15.z] Bump ruff from 0.12.8 to 0.12.9
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19217 [6.17.z] Bump ruff from 0.12.8 to 0.12.9
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19219 6.17.z: Sync GHA dependencies with master branch
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/auto_cherry_pick_merge.yaml
  .github/workflows/auto_cherry_pick_merged.yaml
  .github/workflows/dependency_merge.yml
  .github/workflows/pull_request.yml
  .github/workflows/update_robottelo_image.yml
  .github/workflows/weekly.yml
Labels: No-CherryPick, 6.17.z

#19220 6.16.z: Sync GHA dependencies with master branch
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/auto_cherry_pick_merge.yaml
  .github/workflows/auto_cherry_pick_merged.yaml
  .github/workflows/dependency_merge.yml
  .github/workflows/pull_request.yml
  .github/workflows/update_robottelo_image.yml
  .github/workflows/weekly.yml
Labels: No-CherryPick, 6.16.z

#19221 6.15.z: Sync GHA dependencies with master branch
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/auto_cherry_pick_merge.yaml
  .github/workflows/auto_cherry_pick_merged.yaml
  .github/workflows/dependency_merge.yml
  .github/workflows/pull_request.yml
  .github/workflows/update_robottelo_image.yml
  .github/workflows/weekly.yml
Labels: No-CherryPick, 6.15.z

#19235 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19236 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19238 Log warning on OS/Sat version get failure
  robottelo/hosts.py
Labels: CherryPick, 6.15.z, 6.16.z, 6.17.z

#19240 [6.17.z] Log warning on OS/Sat version get failure
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19242 [6.15.z] Backport of #19238
  robottelo/hosts.py
Labels: No-CherryPick, 6.15.z

#19249 [6.17.z] sca E2E fix
  tests/foreman/api/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#19250 [6.16.z] sca E2E fix
  tests/foreman/api/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#19248 Fix ansible module installation test
  robottelo/constants/__init__.py
Labels: No-CherryPick, Stream, PRT-Passed

#19253 [6.15.z] Bump requests from 2.32.4 to 2.32.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#19139 Verify that content source field automatically populates when creating new host from hostgroup
  tests/foreman/ui/test_hostgroup.py
Labels: No-CherryPick, Stream, PRT-Passed

#19260 [6.17.z] Bump betelgeuse from 1.11.0 to 1.12.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19245 Fix ACS IPv6 bulk tests with ACS HTTP proxy
  tests/foreman/api/test_acs.py
  tests/foreman/cli/test_acs.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19261 [6.17.z] Fix ACS IPv6 bulk tests with ACS HTTP proxy
  tests/foreman/api/test_acs.py
  tests/foreman/cli/test_acs.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19265 [6.15.z] Bump ruff from 0.12.9 to 0.12.10
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19267 [6.17.z] Bump ruff from 0.12.9 to 0.12.10
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19256 Update test for PF5 and test EditorModal
  tests/foreman/ui/test_partitiontable.py
Labels: No-CherryPick, PRT-Passed

#19273 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19275 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19270 Removing check for mac-address as its no longer valid use case as per SAT-27056
  tests/foreman/cli/test_fact.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.16.z, 6.17.z

#19279 [6.17.z] Removing check for mac-address as its no longer valid use case as per SAT-27056
  tests/foreman/cli/test_fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19276 Fix use of workflow arg in module_unconfigured_satellite
  conf/server.yaml.template
  pytest_fixtures/core/sat_cap_factory.py
Labels: No-CherryPick

#19269 [SAT-32710] Coverage
  tests/foreman/cli/test_subscription.py
Labels: QETestCoverage, No-CherryPick, Stream, PRT-Passed

#19297 [6.17.z] Bump ruff from 0.12.10 to 0.12.11
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19298 [6.16.z] Bump ruff from 0.12.10 to 0.12.11
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19291 Added test for Settings info CLI command
  robottelo/cli/settings.py
  tests/foreman/cli/test_settings.py
Labels: CLI, No-CherryPick, Stream

#19299 Details from job invocation page has been changed
  tests/foreman/ui/test_hostcollection.py
Labels: TestFailure, No-CherryPick, Stream, PRT-Passed

#19288 Scope flatpak remote-ls for particular remote and fix uninstall
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_flatpak.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Stream, PRT-Passed

#19301 fix KeyError included container image tags
  tests/foreman/cli/test_repository.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#19303 [6.16.z] fix KeyError included container image tags
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#19286 Automate SAT-36449 and remove IOP parametrization
  tests/foreman/ui/test_rhcloud_insights.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z, 6.17.z
