Repository SatelliteQE/robottelo, pull requests merged in 2025-06, with the labels that each got.

#18585 update urn for azure image
  robottelo/constants/__init__.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.16.z, 6.17.z

#18587 [6.17.z] Convert Puppet upgrade scenario to new format
  tests/new_upgrades/test_puppet.py
Labels: Upgrades, No-CherryPick, PRT-Passed, 6.17.z

#18589 [6.15.z] Convert Puppet upgrade scenario to new format
  tests/new_upgrades/test_puppet.py
Labels: Upgrades, No-CherryPick, 6.15.z

#18501 [6.15.z] Convert classparameter upgrade scenario
  tests/new_upgrades/test_classparameter.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#17904 Adapt robottelo to dualstack deployments
  conf/capsule.yaml.template
  conf/content_host.yaml.template
  conf/migrations.py
  conf/server.yaml.template
  pytest_fixtures/component/leapp_client.py
  pytest_fixtures/component/provision_pxe.py
  pytest_fixtures/core/contenthosts.py
  pytest_fixtures/core/sat_cap_factory.py
  pytest_plugins/fixture_markers.py
  pytest_plugins/markers.py
  pytest_plugins/metadata_markers.py
  pytest_plugins/video_cleanup.py
  robottelo/config/validators.py
  robottelo/enums.py
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
  robottelo/ssh.py
  robottelo/utils/ohsnap.py
  tests/foreman/api/test_ansible.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_templatesync.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_fact.py
  tests/foreman/cli/test_templatesync.py
  tests/foreman/destructive/test_infoblox.py
  tests/foreman/installer/test_installer.py
  tests/foreman/sys/test_fam.py
  tests/foreman/ui/test_discoveryrule.py
  tests/foreman/ui/test_errata.py
  tests/robottelo/test_enum.py
Labels: enhancement, Framework Changes, No-CherryPick, PRT-Failed

#18597 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18599 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#18600 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18603 [6.15.z] Backport of #17904
  conf/capsule.yaml.template
  conf/content_host.yaml.template
  conf/migrations.py
  conf/server.yaml.template
  pytest_fixtures/component/leapp_client.py
  pytest_fixtures/core/contenthosts.py
  pytest_fixtures/core/sat_cap_factory.py
  pytest_plugins/fixture_markers.py
  pytest_plugins/markers.py
  pytest_plugins/metadata_markers.py
  pytest_plugins/video_cleanup.py
  robottelo/config/validators.py
  robottelo/enums.py
  robottelo/host_helpers/contenthost_mixins.py
  robottelo/hosts.py
  robottelo/ssh.py
  robottelo/utils/ohsnap.py
  tests/foreman/ui/test_errata.py
  tests/robottelo/test_enum.py
Labels: No-CherryPick, 6.15.z

#18593 Add support and parametrization for GR based cert setup
  robottelo/hosts.py
  tests/foreman/cli/test_container_management.py
Labels: No-CherryPick, Stream

#18609 [6.15.z] Backport of #18606
  conf/content_host.yaml.template
Labels: No-CherryPick, 6.15.z

#18502 [6.17.z] Convert classparameter upgrade scenario
  tests/new_upgrades/test_classparameter.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18620 [6.17.z] [Interop fix] Fetch interface as per rhel version
  tests/foreman/ui/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18613 Add test coverage to validate ansible check mode feature
  tests/foreman/api/test_ansible.py
Labels: QETestCoverage, No-CherryPick, Stream, PRT-Passed

#18455 [6.17.z] Convert REX upgrade scenario to new format
  .github/CODEOWNERS
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_remoteexecution.py
Labels: Upgrades, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18605 Make flatpak_contenthost parametrizable
  pytest_fixtures/core/contenthosts.py
  pytest_plugins/fixture_markers.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_flatpak.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Stream, PRT-Passed

#18520 http proxy helpers adjusted for ipv6
  robottelo/host_helpers/capsule_mixins.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18637 [6.17.z] http proxy helpers adjusted for ipv6
  robottelo/host_helpers/capsule_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18640 Skip Bootdisk+Secureboot provisioning for VMware
  tests/foreman/api/test_computeresource_vmware.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.17.z

#18642 [6.17.z] Skip Bootdisk+Secureboot provisioning for VMware
  tests/foreman/api/test_computeresource_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#18627 Remove ovirt from downstream foreman installer modules
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Stream

#18645 Remove 6.14.z from dependabot PR labels
  .github/dependabot.yml
Labels: No-CherryPick, maintenance

#18641 Use Conversionsappliance component for Convert2RHEL tests
  testimony.yaml
  tests/foreman/api/test_convert2rhel.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, 6.16.z, 6.17.z

#18647 [6.16.z] Use Conversionsappliance component for Convert2RHEL tests
  testimony.yaml
  tests/foreman/api/test_convert2rhel.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#18648 [6.15.z] Use Conversionsappliance component for Convert2RHEL tests
  testimony.yaml
  tests/foreman/api/test_convert2rhel.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#18643 fix ipv6 test version selection
  tests/upgrades/test_errata.py
  tests/upgrades/test_subscription.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Failed, 6.17.z

#18615 [6.14.z Cherry-Pick] Add a jira issue cache mechanism (#18220)
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  .gitignore
  conf/jira.yaml.template
  robottelo/config/validators.py
  robottelo/utils/issue_handlers/jira.py
  scripts/populate_jira_cache.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_report.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
Labels: No-CherryPick, 6.14.z

#18617 [6.16.z Cherry-Pick] Add a jira issue cache mechanism (#18220)
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  .gitignore
  conf/jira.yaml.template
  robottelo/config/validators.py
  robottelo/utils/issue_handlers/jira.py
  scripts/populate_jira_cache.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_computeresource_vmware.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_oscap.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_remoteexecution.py
  tests/foreman/cli/test_report.py
  tests/foreman/destructive/test_fm_upgrade.py
  tests/foreman/destructive/test_installer.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_capsulecontent.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_discoveredhost.py
  tests/foreman/ui/test_eol_banner.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
Labels: No-CherryPick, 6.15.z

#18616 [6.15.z Cherry-Pick] Add a jira issue cache mechanism (#18220)
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  .gitignore
  conf/jira.yaml.template
  robottelo/config/validators.py
  robottelo/utils/issue_handlers/jira.py
  scripts/populate_jira_cache.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_computeresource_vmware.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_errata.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_report.py
  tests/foreman/destructive/test_fm_upgrade.py
  tests/foreman/longrun/test_oscap.py
  tests/foreman/ui/test_computeresource_vmware.py
  tests/foreman/ui/test_discoveredhost.py
  tests/foreman/ui/test_errata.py
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
Labels: No-CherryPick, 6.15.z

#18646 hammer upgrade testset reduced
  tests/foreman/cli/test_hammer.py
Labels: CherryPick, 6.15.z, 6.16.z, 6.17.z

#18654 [6.15.z] hammer upgrade testset reduced
  tests/foreman/cli/test_hammer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18655 [6.17.z] hammer upgrade testset reduced
  tests/foreman/cli/test_hammer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18623 adding infra hosts to default location
  tests/foreman/cli/test_remoteexecution.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#18633 [6.14.z] Bump pytest from 8.3.5 to 8.4.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#18663 [6.17.z] Fix capsule KS test with non-beta RHEL10
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18667 [6.17.z] Bump requests from 2.32.3 to 2.32.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.17.z

#18669 [6.16.z] Bump requests from 2.32.3 to 2.32.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#18668 [6.15.z] Bump requests from 2.32.3 to 2.32.4
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#18348 [6.15.z] Convert errata upgrade scenario 6.15.z
  robottelo/utils/shared_resource.py
  tests/new_upgrades/test_errata.py
Labels: Upgrades, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#18651 [6.17.z] fix ipv6 test version selection
  tests/upgrades/test_errata.py
  tests/upgrades/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.17.z

#18448 [6.15.z] Convert content host scenario to new format
  tests/new_upgrades/test_hostcontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#18673 [6.17.z] Add test_positive_install_iop_custom_certs to test IoP with custom SSL certs
  tests/foreman/cli/test_rhcloud_inventory.py
Labels: No-CherryPick, PRT-Passed, 6.17.z

#17698 [6.16.z] Convert bookmarks upgrade scenarios to new format
  tests/new_upgrades/test_bookmarks.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#18671 adding capsule to tftp and template
  pytest_fixtures/component/provision_pxe.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Failed, 6.17.z

#18672 Simplify the PRT-Passed label removal
  .github/workflows/prt_labels.yml
Labels: Easy Fix :), CherryPick, 6.15.z, 6.16.z, 6.17.z

#18677 [6.16.z] Simplify the PRT-Passed label removal
  .github/workflows/prt_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18679 [6.17.z] Simplify the PRT-Passed label removal
  .github/workflows/prt_labels.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18686 [6.17.z] Convert host upgrade scenario to new format
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18685 [6.16.z] Convert host upgrade scenario to new format
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#18676 [6.17.z] adding capsule to tftp and template
  pytest_fixtures/component/provision_pxe.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.17.z

#18694 [6.17.z] Errata CLI hosts dualstack environment: use defined host network type
  tests/foreman/cli/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#18708 [6.17.z] Bump pytest-reportportal from 5.5.0 to 5.5.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18709 [6.15.z] Bump pytest-reportportal from 5.5.0 to 5.5.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18699 Update module_sync_kickstart_content fixture
  pytest_fixtures/component/provisioning_template.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18710 [6.17.z] Update module_sync_kickstart_content fixture
  pytest_fixtures/component/provisioning_template.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18715 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18716 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18711 [6.15.z] Sync requirements with master branch
  requirements-optional.txt
Labels: No-CherryPick, 6.15.z, PRT-Failed

#18700 [Test Fix][ISS]Add rhel9 appstream repo to test
  tests/foreman/cli/test_satellitesync.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, Stream, 6.16.z, 6.17.z

#18718 [6.16.z] [Test Fix][ISS]Add rhel9 appstream repo to test
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#17191 Fix oldap data structure in test
  tests/foreman/ui/test_ldap_authentication.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#18722 [6.15.z] Fix oldap data structure in test
  tests/foreman/ui/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#18670 Fix ansible test teardown - test_positive_read_facts_with_filter
  tests/foreman/api/test_ansible.py
Labels: CherryPick, 6.15.z, 6.16.z, 6.17.z

#18720 fix Subscription Connection Test
  tests/foreman/ui/test_rhcloud_inventory.py
Labels: No-CherryPick, Stream, PRT-Passed

#18657 [6.17.z] adding infra hosts to default location
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18733 [6.16.z Cherrypick]Fix ansible test teardown - test_positive_read_facts_with_filter
  tests/foreman/api/test_ansible.py
Labels: No-CherryPick, PRT-Failed, 6.16.z

#18739 Update FDI test assertion due to Bug:SAT-34778
  tests/foreman/cli/test_discoveredhost.py
Labels: TestFailure, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#18681 [6.17.z] Fix apache id and keytab creating command for SAT-34783
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18738 [6.17.z] Fix Flatpak repos provided by RH index
  robottelo/constants/__init__.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_flatpak.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18743 [6.17.z] Pagination Test Refactor
  tests/foreman/ui/test_contenthost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18110 SAT-30138: Media drop-down is visible in child host group with synced content
  pytest_fixtures/component/hostgroup.py
  pytest_fixtures/component/provisioning_template.py
  tests/foreman/ui/test_hostgroup.py
Labels: No-CherryPick

#18751 [6.16.z] Convert sync plan upgrade scenario to new format
  .github/CODEOWNERS
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_syncplan.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#18755 [6.15.z] Convert sync plan upgrade scenario to new format
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_syncplan.py
Labels: Upgrades, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#18723 [6.17.z] Fix oldap data structure in test
  tests/foreman/ui/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#18760 [6.15.z] Bump ruff from 0.11.13 to 0.12.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18746 Try to fix flaky reporting test #2
  tests/foreman/api/test_reporttemplates.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z

#18737 [6.15.z Cherrypick] Fix Discovery Provisioning Tests
  tests/foreman/cli/test_discoveredhost.py
Labels: No-CherryPick, 6.15.z, PRT-Failed

#18748 Fix test_positive_generate_capsule_certs_using_absolute_path
  tests/foreman/destructive/test_katello_certs_check.py
Labels: No-CherryPick, Stream, PRT-Passed

#18762 [6.17.z] Fix VMware pxe-discovery test
  tests/foreman/api/test_computeresource_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.17.z

#18767 Fix ACS IPv6 tests with ACS HTTP proxy
  tests/foreman/api/test_acs.py
  tests/foreman/cli/test_acs.py
Labels: CherryPick, PRT-Passed, 6.17.z

#18772 [6.17.z] Fix ACS IPv6 tests with ACS HTTP proxy
  tests/foreman/api/test_acs.py
  tests/foreman/cli/test_acs.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.17.z

#18766 [6.15.z Cherrypick] Update FDI test assertion due to Bug:SAT-34778
  tests/foreman/cli/test_discoveredhost.py
Labels: No-CherryPick, 6.15.z

#18777 fix katello-tracer ipv6 for rhel version 7,8,9
  pytest_fixtures/core/contenthosts.py
  tests/foreman/cli/test_host.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z

#18779 [6.17.z] fix katello-tracer ipv6 for rhel version 7,8,9
  pytest_fixtures/core/contenthosts.py
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#18781 stream ipv6 ui fix for tracer
  tests/foreman/ui/test_host.py
Labels: TestFailure, No-CherryPick, Stream, PRT-Passed

#18783 [6.17.z] Setup RHSSO for the test
  robottelo/hosts.py
  tests/foreman/destructive/test_ldap_authentication.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18116 Remove RHV/Ovirt tests
  tests/foreman/cli/test_computeresource_rhev.py
  tests/foreman/ui/test_computeresource.py
Labels: No-CherryPick, Stream

#18790 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18792 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18791 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18785 Update VMware cli tests to use storage pod
  tests/foreman/cli/test_computeresource_vmware.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Failed, 6.16.z, 6.17.z

#18786 AK E2E UI test fix
  tests/foreman/ui/test_activationkey.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.16.z, 6.17.z

#18800 [6.17.z] Remove VDC Tests
  robottelo/constants/__init__.py
  tests/foreman/ui/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18799 [6.17.z] AK E2E UI test fix
  tests/foreman/ui/test_activationkey.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#18794 [6.17.z] Update VMware cli tests to use storage pod
  tests/foreman/cli/test_computeresource_vmware.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.17.z

#18802 Remove workaround for JobTemplate clone for ansible tests
  tests/foreman/api/test_ansible.py
Labels: QETestCoverage, No-CherryPick, Stream, PRT-Passed

#18584 [6.15.z] sys_purpose test fix
  tests/foreman/cli/test_activationkey.py
Labels: No-CherryPick, 6.15.z

#18804 Convert usergroup upgrade scenario to new format
  .github/CODEOWNERS
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_usergroup.py
Labels: Upgrades, CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#18817 [6.17.z] Fix Oracle8 test : Set RHEL kernel
  tests/foreman/api/test_convert2rhel.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18824 [6.17.z] Bump ruff from 0.12.0 to 0.12.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18823 [6.16.z] Bump ruff from 0.12.0 to 0.12.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18820 [6.15.z] Use helper functions to setup repositories in satellite-clone (#18770)
  tests/foreman/destructive/test_clone.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.15.z

#18828 [6.17.z] Remove pool attachment since we are SCA now
  robottelo/constants/__init__.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18830 [6.15.z] Remove pool attachment since we are SCA now (#18826)
  robottelo/hosts.py
Labels: No-CherryPick, 6.15.z

#18842 [6.17.z] Skip FAM tests relying on non-existent setups
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.17.z

#18844 [6.16.z] Skip FAM tests relying on non-existent setups (#18756)
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, 6.16.z

#18846 [6.15.z] Skip FAM tests relying on non-existent setups (#18756)
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, 6.15.z

#18847 Skip FAM compute_profile_ovirt due to removed support in 6.18+
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Stream

#18845 IPv6 AK UI test fix
  tests/foreman/ui/test_activationkey.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z
