Repository SatelliteQE/robottelo, pull requests merged in 2025-02, with the labels that each got.

#17478 missing customerscenario tag for rex
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Stream

#17482 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17484 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17481 adding blocked-by for negative host test
  tests/foreman/cli/test_host.py
Labels: CherryPick, Stream, 6.14.z, 6.15.z, 6.16.z

#17488 [6.15.z] adding blocked-by for negative host test
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17487 [6.14.z] adding blocked-by for negative host test
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17486 [6.16.z] adding blocked-by for negative host test
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#17500 [6.15.z] Bump deepdiff from 8.1.1 to 8.2.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#17502 [6.16.z] Bump deepdiff from 8.1.1 to 8.2.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#17501 [6.14.z] Bump deepdiff from 8.1.1 to 8.2.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#17499 [6.13.z] Bump deepdiff from 8.1.1 to 8.2.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.13.z, PRT-Passed

#17493 [6.16.z] Use _broker_facts instead of _broker_args for provisioning tests
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_computeresource_vmware.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_provisioning_puppet.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/ui/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#17497 [6.14.z] Use _broker_facts instead of _broker_args for provisioning t…
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_provisioning_puppet.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/ui/test_discoveredhost.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#17496 [6.15.z] Use _broker_facts instead of _broker_args for provisioning tests
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_provisioning_puppet.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/ui/test_discoveredhost.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.15.z

#17437 org/loc create with all users tests adjusted
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#17506 [6.16.z] org/loc create with all users tests adjusted
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17505 [6.15.z] org/loc create with all users tests adjusted
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#17507 [6.14.z] org/loc create with all users tests adjusted
  tests/foreman/ui/test_location.py
  tests/foreman/ui/test_organization.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#17406 non existent APIResponseError
  robottelo/exceptions.py
  robottelo/host_helpers/api_factory.py
Labels: CherryPick, 6.14.z, 6.15.z, 6.16.z

#17503 Fix _broker_args for target_vm_firmware fact
  pytest_fixtures/component/provision_pxe.py
Labels: Easy Fix :), No-CherryPick, Stream

#17504 Fix long failing AK CLI tests
  tests/foreman/cli/test_activationkey.py
Labels: No-CherryPick, Stream, PRT-Passed

#17510 [6.16.z] non existent APIResponseError
  robottelo/exceptions.py
  robottelo/host_helpers/api_factory.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#17509 [6.14.z] non existent APIResponseError
  robottelo/exceptions.py
  robottelo/host_helpers/api_factory.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17511 less fragile string comparison in negative domain test
  tests/foreman/cli/test_domain.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#17512 [6.15.z] less fragile string comparison in negative domain test
  tests/foreman/cli/test_domain.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#17514 [6.14.z] less fragile string comparison in negative domain test
  tests/foreman/cli/test_domain.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#17338 RHBK support
  conf/rhbk.yaml.template
  pytest_fixtures/component/satellite_auth.py
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/api/test_templatesync.py
  tests/foreman/cli/test_templatesync.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
  tests/foreman/ui/test_templatesync.py
Labels: CherryPick, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#17475 [6.16.z] Fix ansible tests by using proxy for connecting to ansible-galaxy
  tests/foreman/api/test_ansible.py
  tests/foreman/cli/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.16.z

#17491 [6.14] Mark one RHSSO test for PIT server
  pytest_fixtures/component/satellite_auth.py
  robottelo/config/validators.py
  tests/foreman/destructive/test_ldapauthsource.py
Labels: No-CherryPick, PRT-Passed

#17520 Add issue SAT-26076 to convert2rhel tests
  tests/foreman/api/test_convert2rhel.py
Labels: Easy Fix :), No-CherryPick, Stream

#17290 [Pheonix Subs] Fix AK creation in ui/test_activationkey.py
  tests/foreman/ui/test_activationkey.py
Labels: No-CherryPick, Stream, PRT-Passed

#17521 Remove test_positive_capsule_certs_generate_with_special_char
  .github/CODEOWNERS
  tests/foreman/destructive/test_capsule.py
Labels: No-CherryPick, Stream, PRT-Passed

#17055 adjusting oscap tests for rhel10
  robottelo/constants/__init__.py
  tests/foreman/longrun/test_oscap.py
Labels: No-CherryPick, Stream, PRT-Passed

#17524 [6.14.z] Add Python 3.13 for PR checks in GHA
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17523 [6.15.z] Add Python 3.13 for PR checks in GHA
  .github/workflows/pull_request.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17465 Add support for invalidating users JWTs
  tests/foreman/ui/test_user.py
Labels: No-CherryPick, Stream, PRT-Passed

#17024 remove user to prevent ForeignKeyViolation
  tests/foreman/api/test_ansible.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#17490 Update flatpak REX templates names
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_flatpak.py
Labels: No-CherryPick, Stream, PRT-Passed

#17543 [6.15.z] Bump pytest-ibutsu from 2.2.4 to 2.3.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17545 [6.14.z] Bump pytest-ibutsu from 2.2.4 to 2.3.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17214 Add tests for VMware secureboot provisioning
  pytest_fixtures/component/provision_vmware.py
  tests/foreman/api/test_computeresource_vmware.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/ui/test_computeresource_vmware.py
Labels: QETestCoverage, No-CherryPick, Stream, PRT-Failed

#17442 adding blocked-by in RHV tests for SAT-30627
  tests/foreman/ui/test_computeresource.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.14.z, 6.15.z, 6.16.z

#17546 [6.16.z] adding blocked-by in RHV tests for SAT-30627
  tests/foreman/ui/test_computeresource.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#17548 [6.15.z] adding blocked-by in RHV tests for SAT-30627
  tests/foreman/ui/test_computeresource.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#17547 [6.14.z] adding blocked-by in RHV tests for SAT-30627
  tests/foreman/ui/test_computeresource.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#17532 [6.15] RHBK support (#17338)
  conf/rhbk.yaml.template
  pytest_fixtures/component/satellite_auth.py
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
Labels: No-CherryPick, PRT-Passed

#17531 [6.16] RHBK support (#17338)
  conf/rhbk.yaml.template
  pytest_fixtures/component/satellite_auth.py
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  robottelo/hosts.py
  tests/foreman/destructive/test_ldap_authentication.py
  tests/foreman/destructive/test_ldapauthsource.py
Labels: No-CherryPick, PRT-Passed

#17549 Fix test_negative_ipv6_update_check
  tests/foreman/destructive/test_fm_upgrade.py
Labels: No-CherryPick, Stream, PRT-Passed

#17544 [6.16.z] Bump pytest-ibutsu from 2.2.4 to 2.3.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#17552 [Customer Case]Reregister Host with removed consumer certs
  tests/foreman/cli/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.16.z

#17553 [6.16.z] [Customer Case]Reregister Host with removed consumer certs
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17515 assertion skip for SAT-30898
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Stream, PRT-Passed

#17528 [6.14.z] Sync requirements with master branch
  .github/workflows/auto_cherry_pick_merge.yaml
  .github/workflows/dependency_merge.yml
  requirements-optional.txt
Labels: dependencies, No-CherryPick, 6.14.z, PRT-Passed

#17527 [6.15.z] Sync requirements with master branch
  .github/workflows/auto_cherry_pick_merge.yaml
  .github/workflows/dependency_merge.yml
  requirements-optional.txt
Labels: dependencies, No-CherryPick, 6.15.z, PRT-Failed

#17526 [6.16.z] Sync requirements with master branch
  .pre-commit-config.yaml
  requirements-optional.txt
  requirements.txt
Labels: dependencies, No-CherryPick, PRT-Passed, 6.16.z

#17560 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#17561 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17564 [6.15.z] Bump sphinx-autoapi from 3.4.0 to 3.5.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17565 [6.14.z] Bump sphinx-autoapi from 3.4.0 to 3.5.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17566 [6.16.z] Bump sphinx-autoapi from 3.4.0 to 3.5.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#16606 host should successfully reg with setup_insights=true
  tests/foreman/ui/test_registration.py
Labels: No-CherryPick, Stream, PRT-Passed

#17556 Add a default location to the non-admin user to support Ansible role synchronization.
  tests/foreman/cli/test_ansible.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, Stream, 6.14.z, 6.15.z, PRT-Passed, 6.16.z

#17572 [6.14.z] Add a default location to the non-admin user to support Ansible role synchronization.
  tests/foreman/cli/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#17573 [6.15.z] Add a default location to the non-admin user to support Ansible role synchronization.
  tests/foreman/cli/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#17537 Verify the content type of flatpak manifests
  robottelo/constants/__init__.py
  tests/foreman/cli/test_flatpak.py
Labels: No-CherryPick, Stream, PRT-Passed

#17571 Fix provisioning tests
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_provisioning_puppet.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/ui/test_discoveredhost.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, 6.16.z

#17577 [6.16.z] Fix provisioning tests
  pytest_fixtures/component/provision_pxe.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/api/test_provisioning_puppet.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/ui/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#17575 Add workaround for SAT-30807 to use proxy for connecting to ansible-galaxy
  robottelo/hosts.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/ui/test_ansible.py
Labels: TestFailure, No-CherryPick, Stream, PRT-Passed

#17555 Add support for Registration Tokens
  tests/foreman/api/test_registration.py
Labels: API, No-CherryPick, Stream, PRT-Passed

#17581 Fix remaining provisioning tests failing due to missing _broker_facts
  tests/foreman/api/test_computeresource_vmware.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/ui/test_discoveredhost.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, 6.16.z

#17584 [6.16.z] Fix remaining provisioning tests failing due to missing _broker_facts
  tests/foreman/api/test_computeresource_vmware.py
  tests/foreman/api/test_discoveredhost.py
  tests/foreman/api/test_provisioning.py
  tests/foreman/cli/test_discoveredhost.py
  tests/foreman/ui/test_discoveredhost.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#17580 [6.16.z] Add ELS option for convert2rhel for EL7
  pytest_fixtures/component/taxonomy.py
  robottelo/constants/__init__.py
  tests/foreman/api/test_convert2rhel.py
Labels: QETestCoverage, No-CherryPick, PRT-Failed, 6.16.z

#17464 Add a configurable wait period for shared resource
  conf/robottelo.yaml.template
  robottelo/config/validators.py
  robottelo/utils/shared_resource.py
Labels: Easy Fix :), CherryPick, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#17588 Another set of AK CLI fixes
  tests/foreman/cli/test_activationkey.py
Labels: No-CherryPick, Stream, PRT-Passed

#17589 Fix some Docker CLI tests
  tests/foreman/cli/test_docker.py
Labels: No-CherryPick, Stream, PRT-Passed

#17468 Add Hammer support for invalidating users JWTs
  robottelo/cli/user.py
  tests/foreman/cli/test_registration.py
Labels: No-CherryPick, Stream, PRT-Passed

#17595 Fix failing provisioning tests due to the sat workflow update
  pytest_fixtures/component/provision_capsule_pxe.py
  pytest_fixtures/component/provision_pxe.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, 6.16.z

#17596 [6.15.z] Fix failing provisioning tests due to the sat workflow update
  pytest_fixtures/component/provision_capsule_pxe.py
  pytest_fixtures/component/provision_pxe.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#17598 [6.14.z] Fix failing provisioning tests due to the sat workflow update
  pytest_fixtures/component/provision_capsule_pxe.py
  pytest_fixtures/component/provision_pxe.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#17597 [6.16.z] Fix failing provisioning tests due to the sat workflow update
  pytest_fixtures/component/provision_capsule_pxe.py
  pytest_fixtures/component/provision_pxe.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#17599 [6.14.z] Add a configurable wait period for shared resource
  conf/robottelo.yaml.template
  robottelo/config/validators.py
  robottelo/utils/shared_resource.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.14.z

#17600 [6.15.z] Add a configurable wait period for shared resource (#17464)
  conf/robottelo.yaml.template
  robottelo/config/validators.py
  robottelo/utils/shared_resource.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.15.z

#17606 [6.14.z] Bump dynaconf[vault] from 3.2.7 to 3.2.9
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#17605 [6.16.z] Bump dynaconf[vault] from 3.2.7 to 3.2.9
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#17607 [6.15.z] Bump dynaconf[vault] from 3.2.7 to 3.2.9
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#17586 Set Capsule autosync explicitly
  tests/foreman/cli/test_capsulecontent.py
Labels: No-CherryPick, Stream, PRT-Passed

#17466 [6.16] test rex using values from global parameters
  conftest.py
  pytest_fixtures/component/global_params.py
  pytest_fixtures/component/settings.py
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, PRT-Passed, 6.16.z

#17610 vmware provision test, missing customerscenario tag
  tests/foreman/cli/test_computeresource_vmware.py
Labels: No-CherryPick, Stream

#17609 RFE: extended test for new job_invocations detail page, vol. 2
  tests/foreman/ui/test_remoteexecution.py
Labels: No-CherryPick, Stream, PRT-Passed

#17601 [6.16.z] Add a configurable wait period for shared resource (#17464)
  conf/robottelo.yaml.template
  robottelo/config/validators.py
  robottelo/utils/shared_resource.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.16.z

#17602 [CustomerCase] Test Errata type "Other", with inclusive CV Filter, verify content counts
  .pre-commit-config.yaml
  tests/foreman/api/test_errata.py
Labels: No-CherryPick, Stream, PRT-Passed

#16869 pull mode rex survives leapp upgrade
  pytest_fixtures/component/leapp_client.py
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/constants/__init__.py
  tests/foreman/cli/test_leapp_client.py
  tests/foreman/ui/test_leapp_client.py
Labels: No-CherryPick, Stream, PRT-Passed

#17432 Extend mixed content export import with consume
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, PRT-Passed

#17614 Add coverage checking that upload-content doesn't work with docker
  tests/foreman/cli/test_docker.py
Labels: Easy Fix :), No-CherryPick, Stream

#17617 [6.16.z] Bump sphinx-autoapi from 3.5.0 to 3.6.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#17618 [6.15.z] Bump sphinx-autoapi from 3.5.0 to 3.6.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17621 [6.16.z] Bump dynaconf[vault] from 3.2.9 to 3.2.10
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#17622 [6.15.z] Bump dynaconf[vault] from 3.2.9 to 3.2.10
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#17620 [6.14.z] Bump dynaconf[vault] from 3.2.9 to 3.2.10
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#17153 Add test coverage for SAT-28860
  pytest_fixtures/component/http_proxy.py
  robottelo/host_helpers/api_factory.py
  tests/foreman/ui/test_http_proxy.py
Labels: QETestCoverage, No-CherryPick, Stream, PRT-Failed

#17613 Fix puppet tests by using proxy for connecting to puppet forgeapis
  robottelo/hosts.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.16.z

#17619 [6.14.z] Bump sphinx-autoapi from 3.5.0 to 3.6.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17623 [6.16.z] Fix puppet tests by using proxy for connecting to puppet forgeapis
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#17479 Update provisioning tests for IPv6 provisoning
  pytest_fixtures/component/provision_pxe.py
  pytest_plugins/infra_dependent_markers.py
  pytest_plugins/marker_deselection.py
  robottelo/host_helpers/satellite_mixins.py
  tests/foreman/api/test_provisioning.py
Labels: No-CherryPick, Stream

#17612 Fix assertion for installing katello-ca cert and updating rhel_contenthost fixture to test default rhel version
  tests/foreman/cli/test_registration.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, 6.16.z

#17489 Fix deployment in Interop testing
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/hosts.py
  tests/foreman/installer/test_installer.py
Labels: CherryPick, PRT-Passed, 6.16.z

#17627 [6.14.z cherrypick] Fix assertion for installing katello-ca cert and updating rhel_contenthost fixture to test default rhel version]
  tests/foreman/cli/test_registration.py
Labels: TestFailure, No-CherryPick, 6.14.z, PRT-Failed

#17628 [6.16.z] Fix deployment in Interop testing
  pytest_fixtures/core/sat_cap_factory.py
  robottelo/hosts.py
  tests/foreman/installer/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#17003 RHEL10 Clients coverage, rhel7 & 8 hosts bumped
  pytest_fixtures/core/contenthosts.py
  robottelo/constants/__init__.py
  tests/foreman/api/test_ansible.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_errata.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_reporttemplates.py
Labels: No-CherryPick, Stream, PRT-Failed

#17632 [6.15.z Cherrypick]Fix assertion for installing katello-ca cert and updating rhel_contenthost fixture to test default rhel version
  tests/foreman/cli/test_registration.py
Labels: No-CherryPick, 6.15.z, PRT-Failed

#17630 [6.16.z Cherrypick]Fix assertion for installing katello-ca cert and updating rhel_contenthost fixture to test default rhel version
  tests/foreman/cli/test_registration.py
Labels: No-CherryPick, PRT-Failed, 6.16.z

#17369 Use custom content for RHEL10 until SAT-29721 is resolved
  conf/repos.yaml.template
  pytest_fixtures/component/provision_pxe.py
  robottelo/constants/__init__.py
Labels: TestFailure, No-CherryPick, PRT-Failed

#17415 [RHEL10,9,8] Cover restrict repos by host OS, RHEL major versions
  tests/foreman/api/test_subscription.py
Labels: CherryPick, Stream, 6.15.z, PRT-Failed, 6.16.z

#17641 [6.14.z] Bump wrapanapi from 3.7.0 to 3.7.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z

#17640 [6.15.z] Bump wrapanapi from 3.7.0 to 3.7.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17642 [6.16.z] Bump wrapanapi from 3.7.0 to 3.7.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#17631 AK UI test fix
  tests/foreman/ui/test_activationkey.py
Labels: UI, No-CherryPick, Stream

#17629 Add issue SAT-5118 to test_positive_set_default_http_proxy
  tests/foreman/ui/test_http_proxy.py
Labels: Easy Fix :), No-CherryPick, Stream

#17576 Add a test case for flatpak CV scoping
  robottelo/constants/__init__.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_flatpak.py
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Stream, PRT-Passed

#17647 Auto branching: Add randomness to branch name
  .github/workflows/auto_branching.yml
Labels: No-CherryPick

#17646 [master]: Changes for new 6.17.z branch
  .github/dependabot.yml
  conf/robottelo.yaml.template
  robottelo/constants/__init__.py
Labels: No-CherryPick, PRT-Failed

#17648 [6.17.z]: Changes for 6.17.z new branch
  .github/dependabot.yml
  .github/workflows/auto_branching.yml
  .github/workflows/dispatch_release.yml
  requirements.txt
  robottelo/constants/__init__.py
Labels: No-CherryPick

#17645 Qualify the container image names to localhost
  conf/content_host.yaml.template
Labels: TestFailure, No-CherryPick

#17657 Fix typo in capsule_setup helper
  robottelo/hosts.py
Labels: TestFailure, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z, 6.17.z

#17660 customerscenario tag for docker test
  tests/foreman/cli/test_docker.py
Labels: CherryPick, Stream, 6.17.z

#17662 [6.17.z] Fix configure_kea_dhcp6_server fixture for IPv4
  pytest_fixtures/component/provision_pxe.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#17519 less flakiness in rex module
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#17658 [6.17.z] Fix typo in capsule_setup helper
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.17.z

#17665 [6.16.z] less flakiness in rex module
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#17664 [6.15.z] less flakiness in rex module
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#17668 [6.17.z] Bump broker[docker,hussh,podman] from 0.6.4 to 0.6.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Failed, 6.17.z

#17670 [6.15.z] Bump broker[docker,hussh,podman] from 0.6.4 to 0.6.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#17669 [6.16.z] Bump broker[docker,hussh,podman] from 0.6.4 to 0.6.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Failed, 6.16.z

#17367 Add IPv6 support in Centos/Oracle Host checkout
  pytest_fixtures/core/contenthosts.py
  tests/foreman/api/test_convert2rhel.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Failed, 6.16.z, 6.17.z

#17671 [6.14.z] Bump broker[docker,hussh,podman] from 0.6.4 to 0.6.5
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.14.z, PRT-Passed

#17635 ReportTemplates Coverage for RHEL10 hosts
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/cli/test_reporttemplates.py
Labels: No-CherryPick, Stream, PRT-Passed

#17673 [6.17.z] Add IPv6 support in Centos/Oracle Host checkout
  pytest_fixtures/core/contenthosts.py
  tests/foreman/api/test_convert2rhel.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.17.z

#17676 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#17677 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#17678 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#17637 [6.16.z] [RHEL10,9,8] Cover restrict repos by host OS, RHEL major versions
  tests/foreman/api/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#17636 [6.15.z] [RHEL10,9,8] Cover restrict repos by host OS, RHEL major versions
  tests/foreman/api/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#17570 Make container content related settings configurable
  conf/container.yaml.template
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_container_management.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_contentviewfilter.py
  tests/foreman/cli/test_docker.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_containerimagetag.py
  tests/foreman/ui/test_contentview_old.py
  tests/foreman/ui/test_http_proxy.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
  tests/new_upgrades/test_repository.py
  tests/upgrades/test_repository.py
Labels: CherryPick, 6.14.z, 6.15.z, 6.16.z, 6.17.z

#17684 [6.17.z] Make container content related settings configurable
  conf/container.yaml.template
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_container_management.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_contentviewfilter.py
  tests/foreman/cli/test_docker.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_containerimagetag.py
  tests/foreman/ui/test_contentview_old.py
  tests/foreman/ui/test_http_proxy.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
  tests/new_upgrades/test_repository.py
  tests/upgrades/test_repository.py
Labels: No-CherryPick

#17690 Make container content related settings configurable (#17570)
  conf/container.yaml.template
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_container_management.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_contentviewfilter.py
  tests/foreman/cli/test_docker.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_containerimagetag.py
  tests/foreman/ui/test_contentview.py
  tests/foreman/ui/test_http_proxy.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
Labels: No-CherryPick

#17663 [6.17.z] less flakiness in rex module
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#17687 [6.17.z] CP ReportTemplates Coverage for RHEL10 hosts
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/cli/test_reporttemplates.py
Labels: No-CherryPick, AutoMerge_Cherry_Picked, 6.17.z

#17689 6.15.z container settings
  conf/container.yaml.template
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  tests/foreman/api/test_capsulecontent.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_contentviewfilter.py
  tests/foreman/api/test_docker.py
  tests/foreman/api/test_http_proxy.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_capsulecontent.py
  tests/foreman/cli/test_container_management.py
  tests/foreman/cli/test_contentview.py
  tests/foreman/cli/test_contentviewfilter.py
  tests/foreman/cli/test_docker.py
  tests/foreman/cli/test_repository.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/cli/test_vm_install_products_package.py
  tests/foreman/ui/test_activationkey.py
  tests/foreman/ui/test_containerimagetag.py
  tests/foreman/ui/test_contentview_old.py
  tests/foreman/ui/test_http_proxy.py
  tests/foreman/ui/test_repository.py
  tests/foreman/ui/test_sync.py
Labels: No-CherryPick

#17686 [6.14] less flakiness in rex module
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, 6.14.z, PRT-Passed

#17340 Fix IPv6 Infoblox tests
  tests/foreman/destructive/test_infoblox.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z
