Repository SatelliteQE/robottelo, pull requests merged in 2025-07, with the labels that each got.

#18854 Update the New team names for old team-rocket components
  .github/CODEOWNERS
  tests/foreman/api/test_ansible.py
  tests/foreman/api/test_classparameters.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_environment.py
  tests/foreman/api/test_parameters.py
  tests/foreman/api/test_provisioning_puppet.py
  tests/foreman/api/test_registration.py
  tests/foreman/api/test_settings.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_classparameters.py
  tests/foreman/cli/test_environment.py
  tests/foreman/cli/test_fact.py
  tests/foreman/cli/test_globalparam.py
  tests/foreman/cli/test_leapp_client.py
  tests/foreman/cli/test_logging.py
  tests/foreman/cli/test_puppetclass.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_report.py
  tests/foreman/cli/test_settings.py
  tests/foreman/destructive/test_ansible.py
  tests/foreman/destructive/test_puppetplugin.py
  tests/foreman/destructive/test_registration.py
  tests/foreman/sys/test_pulp3_filesystem.py
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_config_group.py
  tests/foreman/ui/test_fact.py
  tests/foreman/ui/test_leapp_client.py
  tests/foreman/ui/test_puppetclass.py
  tests/foreman/ui/test_puppetenvironment.py
  tests/foreman/ui/test_registration.py
  tests/foreman/ui/test_settings.py
  tests/foreman/ui/test_smartclassparameter.py
  tests/new_upgrades/test_classparameter.py
  tests/new_upgrades/test_puppet.py
  tests/upgrades/test_classparameter.py
  tests/upgrades/test_puppet.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, 6.16.z, 6.17.z

#18864 [6.16.z] Update components for rocket team
  tests/foreman/api/test_ansible.py
  tests/foreman/api/test_classparameters.py
  tests/foreman/api/test_contentview.py
  tests/foreman/api/test_environment.py
  tests/foreman/api/test_parameters.py
  tests/foreman/api/test_provisioning_puppet.py
  tests/foreman/api/test_registration.py
  tests/foreman/api/test_settings.py
  tests/foreman/cli/test_ansible.py
  tests/foreman/cli/test_classparameters.py
  tests/foreman/cli/test_environment.py
  tests/foreman/cli/test_fact.py
  tests/foreman/cli/test_globalparam.py
  tests/foreman/cli/test_leapp_client.py
  tests/foreman/cli/test_logging.py
  tests/foreman/cli/test_puppetclass.py
  tests/foreman/cli/test_registration.py
  tests/foreman/cli/test_report.py
  tests/foreman/cli/test_settings.py
  tests/foreman/destructive/test_ansible.py
  tests/foreman/destructive/test_puppetplugin.py
  tests/foreman/destructive/test_registration.py
  tests/foreman/sys/test_pulp3_filesystem.py
  tests/foreman/ui/test_ansible.py
  tests/foreman/ui/test_config_group.py
  tests/foreman/ui/test_fact.py
  tests/foreman/ui/test_leapp_client.py
  tests/foreman/ui/test_puppetclass.py
  tests/foreman/ui/test_puppetenvironment.py
  tests/foreman/ui/test_registration.py
  tests/foreman/ui/test_settings.py
  tests/foreman/ui/test_smartclassparameter.py
  tests/new_upgrades/test_classparameter.py
  tests/new_upgrades/test_puppet.py
  tests/upgrades/test_classparameter.py
  tests/upgrades/test_puppet.py
Labels: No-CherryPick, 6.16.z

#18872 [6.17.z] Fix capsule repos constant name
  robottelo/hosts.py
Labels: Easy Fix :), No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#18870 [6.16.z] Fix capsule repos constant name
  robottelo/hosts.py
Labels: Easy Fix :), No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#18871 [6.15.z] Fix capsule repos constant name
  robottelo/hosts.py
Labels: Easy Fix :), No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#18877 [6.17.z] Update team component ownership
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_reporttemplates.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_reporttemplates.py
  tests/new_upgrades/test_satellitesync.py
  tests/upgrades/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#18876 [6.15.z] Update team component ownership
  tests/foreman/api/test_reporttemplates.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_reporttemplates.py
  tests/foreman/cli/test_satellitesync.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_reporttemplates.py
  tests/new_upgrades/test_satellitesync.py
  tests/upgrades/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#18787 Convert Subscription upgrade scenario to new format
  .github/CODEOWNERS
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_subscription.py
Labels: Upgrades, CherryPick, AutoMerge_Cherry_Picked, 6.15.z, 6.16.z, 6.17.z

#18888 [6.15.z] Update Platform team's component ownership
  testimony.yaml
  tests/foreman/api/test_capsule.py
  tests/foreman/cli/test_abrt.py
  tests/foreman/cli/test_bootstrap_script.py
  tests/foreman/cli/test_capsule.py
  tests/foreman/cli/test_installer.py
  tests/foreman/destructive/test_capsule_loadbalancer.py
  tests/foreman/destructive/test_clone.py
  tests/foreman/destructive/test_fm_upgrade.py
  tests/foreman/destructive/test_foreman_service.py
  tests/foreman/destructive/test_installer.py
  tests/foreman/destructive/test_katello_certs_check.py
  tests/foreman/destructive/test_leapp_satellite.py
  tests/foreman/destructive/test_packages.py
  tests/foreman/destructive/test_rename.py
  tests/foreman/installer/test_installer.py
  tests/foreman/maintain/test_advanced.py
  tests/foreman/maintain/test_backup_restore.py
  tests/foreman/maintain/test_health.py
  tests/foreman/maintain/test_maintenance_mode.py
  tests/foreman/maintain/test_offload_DB.py
  tests/foreman/maintain/test_packages.py
  tests/foreman/maintain/test_service.py
  tests/foreman/maintain/test_upgrade.py
  tests/foreman/sys/test_fam.py
  tests/foreman/sys/test_katello_certs_check.py
  tests/foreman/ui/test_branding.py
  tests/new_upgrades/test_capsule.py
  tests/new_upgrades/test_performance_tuning.py
  tests/upgrades/test_capsule.py
  tests/upgrades/test_performance_tuning.py
Labels: No-CherryPick, 6.15.z

#18897 [6.15.z] Update team component ownership: Phoenix-content -> Endeavor
  tests/foreman/api/test_http_proxy.py
  tests/foreman/cli/test_http_proxy.py
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.15.z

#18896 [6.16.z] Update team component ownership: Phoenix-content -> Endeavor
  tests/foreman/api/test_http_proxy.py
  tests/foreman/cli/test_http_proxy.py
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.16.z

#18895 [6.17.z] Update team component ownership: Phoenix-content -> Endeavor
  tests/foreman/api/test_http_proxy.py
  tests/foreman/cli/test_http_proxy.py
  tests/foreman/ui/test_http_proxy.py
Labels: No-CherryPick, Failed_AutoCherryPick, 6.17.z

#18878 Add support of RHEL9 to RHEL10 Leapp client upgrade
  pytest_fixtures/component/leapp_client.py
  tests/foreman/cli/test_leapp_client.py
Labels: QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, 6.17.z

#18901 [6.17.z] Add support of RHEL9 to RHEL10 Leapp client upgrade
  pytest_fixtures/component/leapp_client.py
  tests/foreman/cli/test_leapp_client.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18902 fixing a typo in capsule mixins
  robottelo/host_helpers/capsule_mixins.py
Labels: TestFailure, Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18906 [6.17.z] fixing a typo in capsule mixins
  robottelo/host_helpers/capsule_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18907 [6.17] former Endeavour components moved to new owners
  tests/foreman/api/test_architecture.py
  tests/foreman/api/test_host.py
  tests/foreman/api/test_hostgroup.py
  tests/foreman/api/test_media.py
  tests/foreman/api/test_partitiontable.py
  tests/foreman/cli/test_architecture.py
  tests/foreman/cli/test_domain.py
  tests/foreman/cli/test_hammer.py
  tests/foreman/cli/test_host.py
  tests/foreman/cli/test_hostgroup.py
  tests/foreman/cli/test_medium.py
  tests/foreman/cli/test_model.py
  tests/foreman/cli/test_partitiontable.py
  tests/foreman/cli/test_ping.py
  tests/foreman/destructive/test_host.py
  tests/foreman/destructive/test_ping.py
  tests/foreman/endtoend/test_cli_endtoend.py
  tests/foreman/ui/test_architecture.py
  tests/foreman/ui/test_domain.py
  tests/foreman/ui/test_hardwaremodel.py
  tests/foreman/ui/test_host.py
  tests/foreman/ui/test_hostgroup.py
  tests/foreman/ui/test_media.py
  tests/foreman/ui/test_partitiontable.py
Labels: No-CherryPick, 6.17.z

#18913 [6.16.z] Bump ruff from 0.12.1 to 0.12.2
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18914 [6.17.z] Bump ruff from 0.12.1 to 0.12.2
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18920 [6.15.z] Bump productmd from 1.45 to 1.46
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18922 [6.17.z] Bump productmd from 1.45 to 1.46
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18180 Load scenario_workers plugin conditionally
  conftest.py
  pytest_plugins/upgrade/scenario_workers.py
  tests/upgrades/conftest.py
Labels: Framework Changes, CherryPick, 6.15.z, PRT-Passed, maintenance, 6.16.z, 6.17.z

#18931 [6.16.z] Load scenario_workers plugin conditionally
  conftest.py
  pytest_plugins/upgrade/scenario_workers.py
  tests/upgrades/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#18936 Fix host asserts for CV and LCE
  tests/foreman/cli/test_host.py
Labels: TestFailure, No-CherryPick, Stream, PRT-Passed

#18939 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18940 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18944 [6.17.z] Bump productmd from 1.46 to 1.47
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18934 Fix CLI e2e test, make it more recent, remove need for future updates
  robottelo/constants/__init__.py
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: TestFailure, CherryPick, PRT-Passed, 6.17.z

#18945 [6.17.z] Fix CLI e2e test, make it more recent, remove need for future updates
  robottelo/constants/__init__.py
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18950 [6.15.z] Update CLI e2e test, make it more recent, remove need for future updates
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#18892 Remove obsolete or unused pytest markers
  pytest_plugins/infra_dependent_markers.py
  pytest_plugins/marker_deselection.py
  tests/foreman/cli/test_organization.py
  tests/foreman/longrun/test_oscap.py
Labels: Framework Changes, CherryPick, PRT-Passed, 6.17.z

#18946 Skip FM upgrade test as IPv6 can't be disabled on IPv6-only setup
  tests/foreman/destructive/test_fm_upgrade.py
Labels: TestFailure, CherryPick, 6.17.z

#18953 [6.17.z] Skip FM upgrade test as IPv6 can't be disabled on IPv6-only setup
  tests/foreman/destructive/test_fm_upgrade.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18959 [6.16.z] Bump productmd from 1.47 to 1.48
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18960 [6.15.z] Bump productmd from 1.47 to 1.48
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18961 [6.17.z] Bump productmd from 1.47 to 1.48
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18967 Fix of test_host CLI test
  tests/foreman/cli/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z

#18969 [6.17.z] Fix of test_host CLI test
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#18964 [6.17.z] Bump pytest-reportportal from 5.5.1 to 5.5.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18971 [6.16.z] Convert Subscription upgrade scenario to new format
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_subscription.py
Labels: Upgrades, No-CherryPick, PRT-Passed, 6.16.z

#18956 [6.15.z] Convert usergroup upgrade scenario
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_usergroup.py
Labels: Upgrades, No-CherryPick, 6.15.z

#18970 [6.17.z] Convert Subscription upgrade scenario to new format
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_subscription.py
Labels: Upgrades, No-CherryPick, PRT-Passed, 6.17.z

#18935 Fix parametrization of multiple content host fixtures
  pytest_plugins/fixture_markers.py
Labels: Bug, CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#18976 [6.17.z] Fix parametrization of multiple content host fixtures (#18935)
  pytest_plugins/fixture_markers.py
Labels: No-CherryPick, 6.17.z

#18977 [6.16.z] Fix parametrization of multiple content host fixtures (#18935)
  pytest_plugins/fixture_markers.py
Labels: No-CherryPick, 6.16.z

#18927 new items in the usage report
  .github/CODEOWNERS
  tests/foreman/data/usage_report.yml
Labels: No-CherryPick, Stream

#18982 [6.17.z] Bump wrapanapi from 3.7.1 to 3.7.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18984 [6.16.z] Bump wrapanapi from 3.7.1 to 3.7.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18983 [6.15.z] Bump wrapanapi from 3.7.1 to 3.7.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18979 Fix flatpak-remote organization scoping
  tests/foreman/cli/test_flatpak.py
Labels: Easy Fix :), No-CherryPick, Stream, PRT-Passed

#18987 [6.17.z] Bump ruff from 0.12.2 to 0.12.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18988 [6.16.z] Bump ruff from 0.12.2 to 0.12.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18989 [6.15.z] Bump ruff from 0.12.2 to 0.12.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18993 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#18994 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#18997 [6.16.z] Add setup and teardown for Capsule and Satellite objects
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#19003 [6.16.z] Bump pytest-services from 2.2.1 to 2.2.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19004 [6.17.z] Bump pytest-services from 2.2.1 to 2.2.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19005 [6.17.z] test_host_status_honors_taxonomies fix
  pytest_fixtures/component/lce.py
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#17530 Fix Composite CV
  tests/foreman/ui/test_settings.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z, 6.17.z

#19014 [6.15.z] Bump ruff from 0.12.3 to 0.12.4
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19015 [6.16.z] Bump ruff from 0.12.3 to 0.12.4
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19018 [6.16.z] Rename ContainerManagement-Content to ContainerImageManagement
  testimony.yaml
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_container_management.py
  tests/foreman/ui/test_containerimagetag.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#19022 [6.17.z] remove gce test form build sanity tests
  tests/foreman/api/test_computeresource_gce.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19023 [6.16.z] remove gce test form build sanity tests
  tests/foreman/api/test_computeresource_gce.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19032 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19010 Remove bugzilla handler code and add support for handling all jira projects
  .env.example
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  Makefile
  conf/bugzilla.yaml.template
  docs/index.rst
  pytest_plugins/issue_handlers.py
  pytest_plugins/markers.py
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  robottelo/utils/issue_handlers/README.md
  robottelo/utils/issue_handlers/__init__.py
  robottelo/utils/issue_handlers/bugzilla.py
  robottelo/utils/issue_handlers/jira.py
  robottelo/utils/version.py
  scripts/customer_scenarios.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_computeresource_vmware.py
  tests/foreman/cli/test_repository.py
  tests/robottelo/test_issue_handlers.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, 6.16.z, 6.17.z

#19042 [6.15.z] Remove bugzilla handler code and add support for handling all jira projects
  .env.example
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  Makefile
  conf/bugzilla.yaml.template
  docs/index.rst
  pytest_plugins/issue_handlers.py
  pytest_plugins/markers.py
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  robottelo/utils/issue_handlers/README.md
  robottelo/utils/issue_handlers/__init__.py
  robottelo/utils/issue_handlers/bugzilla.py
  robottelo/utils/issue_handlers/jira.py
  robottelo/utils/version.py
  scripts/customer_scenarios.py
  tests/foreman/api/test_product.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
  tests/robottelo/test_issue_handlers.py
Labels: No-CherryPick, 6.15.z

#19041 [6.17.z] Remove bugzilla handler code and add support for handling all jira projects
  .env.example
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  Makefile
  conf/bugzilla.yaml.template
  docs/index.rst
  pytest_plugins/issue_handlers.py
  pytest_plugins/markers.py
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  robottelo/utils/issue_handlers/README.md
  robottelo/utils/issue_handlers/__init__.py
  robottelo/utils/issue_handlers/bugzilla.py
  robottelo/utils/issue_handlers/jira.py
  robottelo/utils/version.py
  scripts/customer_scenarios.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
  tests/robottelo/test_issue_handlers.py
Labels: No-CherryPick, 6.17.z

#19040 [6.16.z] Remove bugzilla handler code and add support for handling all jira projects
  .env.example
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
  Makefile
  conf/bugzilla.yaml.template
  docs/index.rst
  pytest_plugins/issue_handlers.py
  pytest_plugins/markers.py
  robottelo/config/validators.py
  robottelo/constants/__init__.py
  robottelo/utils/issue_handlers/README.md
  robottelo/utils/issue_handlers/__init__.py
  robottelo/utils/issue_handlers/bugzilla.py
  robottelo/utils/issue_handlers/jira.py
  robottelo/utils/version.py
  scripts/customer_scenarios.py
  tests/foreman/api/test_repository.py
  tests/foreman/cli/test_repository.py
  tests/robottelo/test_issue_handlers.py
Labels: No-CherryPick, 6.16.z

#19030 Change Owner/Org/Loc test coverage
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Stream, PRT-Passed

#18972 [6.15.z] Convert Subscription upgrade scenario to new format
  tests/new_upgrades/conftest.py
  tests/new_upgrades/test_subscription.py
Labels: Upgrades, No-CherryPick, 6.15.z

#19053 [6.17.z] Bump ruff from 0.12.4 to 0.12.5
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19054 [6.15.z] Bump ruff from 0.12.4 to 0.12.5
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19060 [6.15.z] Bump broker[docker,hussh,podman] from 0.6.11 to 0.6.12
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19048 Test new default mirroring policy options
  robottelo/constants/__init__.py
  tests/foreman/api/test_repository.py
  tests/foreman/api/test_settings.py
Labels: No-CherryPick, Stream

#19066 recommendation sync CLI test fix
  tests/foreman/cli/test_rhcloud_inventory.py
Labels: Easy Fix :), No-CherryPick, Stream

#19067 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19069 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19072 [6.17.z] Bump ruff from 0.12.5 to 0.12.7
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19071 [6.15.z] Bump ruff from 0.12.5 to 0.12.7
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19075 [6.17.z] Golden Ticket Removal
  tests/foreman/cli/test_subscription.py
  tests/foreman/ui/test_subscription.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19046 Remove no_http_proxy parameter in HTTP Proxy testing
  pytest_fixtures/component/http_proxy.py
  robottelo/hosts.py
  tests/foreman/ui/test_http_proxy.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z

#19043 Two Settings UI test fixes
  tests/foreman/ui/test_settings.py
Labels: CherryPick, 6.16.z, 6.17.z
