Repository SatelliteQE/robottelo, pull requests merged in 2025-09, with the labels that each got.

#19309 Use fixtures.pulpproject.org instead of repos.fedorapeople.org for FAM
  tests/foreman/sys/test_fam.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed, 6.16.z, 6.17.z

#19290 [6.17.z] Fix CLI e2e test, by incorporating changes from SAT-35580
  tests/foreman/endtoend/test_cli_endtoend.py
Labels: TestFailure, No-CherryPick, PRT-Passed, 6.17.z

#19314 Use fixtures.pulpproject.org instead of repos.fedorapeople.org for FAM
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Failed_AutoCherryPick, PRT-Passed, 6.16.z

#19300 enable Satellite proxy if we have no ipv4 networking
  tests/foreman/sys/test_fam.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19317 [6.17.z] remediate multiple hosts extension and IOP parametrization removal
  tests/foreman/ui/test_rhcloud_insights.py
Labels: No-CherryPick, PRT-Passed, 6.17.z

#19328 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19327 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19323 New hosts used by default
  tests/foreman/destructive/test_ldap_authentication.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19330 Skip Discovery rule test for IPv6-only run
  tests/foreman/ui/test_discoveryrule.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, 6.17.z

#19333 [6.17.z] Skip Discovery rule test for IPv6-only run
  tests/foreman/ui/test_discoveryrule.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#19335 [master]: Changes for new 6.18.z branch
  .github/dependabot.yml
  conf/robottelo.yaml.template
  robottelo/constants/__init__.py
Labels: No-CherryPick

#19336 [6.18.z]: Changes for 6.18.z new branch
  .github/dependabot.yml
  .github/workflows/auto_branching.yml
  .github/workflows/dispatch_release.yml
  requirements.txt
  robottelo/constants/__init__.py
Labels: No-CherryPick

#19304 [6.15.z] fix KeyError included container image tags
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Failed

#19352 Add new dependency_merge_zstream GHA for zstream branches
  .github/workflows/auto_branching.yml
  .github/workflows/dependency_merge_zstream.yml
Labels: enhancement, No-CherryPick

#19334 Extend ISS syncable import test with imports history check
  tests/foreman/cli/test_satellitesync.py
Labels: CherryPick, PRT-Passed, 6.18.z

#19362 [6.17.z] Fix assertions and skip IPv6 in FM DHCP config test
  tests/foreman/maintain/test_health.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19337 [6.18.z] Fix for test_negative_installer_invalid_dns_forwarder failure on jenkins
  tests/foreman/destructive/test_installer.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19346 [6.18.z] Automate stubbed test for Hostname facts setting
  tests/foreman/cli/test_settings.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19364 [6.15.z] Get rid of bogus lines in output
  tests/foreman/destructive/test_auth.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#19376 [6.17.z] Bump deepdiff from 8.6.0 to 8.6.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.17.z

#19342 [6.18.z] Bump fastmcp from 2.11.3 to 2.12.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19374 [6.16.z] Bump deepdiff from 8.6.0 to 8.6.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#19262 [SAT-28495] Rolling ContentViews API automation
  robottelo/host_helpers/cli_factory.py
  tests/foreman/api/test_contentview.py
Labels: CherryPick, PRT-Failed, 6.18.z

#19388 [6.15.z] Bump pytest-mock from 3.14.1 to 3.15.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19391 [6.18.z] Bump pytest-mock from 3.14.1 to 3.15.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19390 [6.16.z] Bump pytest-mock from 3.14.1 to 3.15.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19392 [6.17.z] Bump actions/stale from 9 to 10
  .github/workflows/stale.yml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19394 [6.15.z] Bump actions/stale from 9 to 10
  .github/workflows/stale.yml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19398 [6.16.z] Bump actions/setup-python from 5 to 6
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19397 [6.18.z] Bump actions/setup-python from 5 to 6
  .github/workflows/pull_request.yml
  .github/workflows/weekly.yml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19407 [6.17.z] recommendation sync CLI test fix
  tests/foreman/cli/test_rhcloud_inventory.py
Labels: Easy Fix :), No-CherryPick, 6.17.z

#19410 Remove CODEOWNERS file from 6.18.z
  .github/CODEOWNERS
Labels: No-CherryPick, 6.18.z

#19382 [6.18.z] [SAT-28495] Rolling ContentViews API automation
  robottelo/host_helpers/cli_factory.py
  tests/foreman/api/test_contentview.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19414 [6.18.z] Bump ruff from 0.12.11 to 0.12.12
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19415 [6.15.z] Bump ruff from 0.12.11 to 0.12.12
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19354 [6.18.z] Extend ISS syncable import test with imports history check
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.18.z

#19418 Host Group Test Fix
  tests/foreman/ui/test_hostgroup.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z, 6.18.z

#19419 [6.17.z] Host Group Test Fix
  tests/foreman/ui/test_hostgroup.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19423 [6.18.z] SAT-20253 - hammer import keeps org and loc
  robottelo/cli/job_template.py
  tests/foreman/cli/test_jobtemplate.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19421 [6.15.z] remove_check_for_mac_address
  tests/foreman/cli/test_fact.py
Labels: No-CherryPick, 6.15.z, PRT-Passed

#19425 [6.17.z] Automate stubbed testcase to export report
  tests/foreman/api/test_reporttemplates.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19435 [6.16.z] Bump pytest-cov from 6.2.1 to 6.3.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19433 [6.15.z] Bump pytest-cov from 6.2.1 to 6.3.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19422 Get rid of direct LCE assign on CV create
  tests/foreman/cli/test_errata.py
Labels: No-CherryPick, Stream, PRT-Passed

#19366 [6.16.z] Get rid of bogus lines in output
  tests/foreman/destructive/test_auth.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#19445 disable insights in api_register() so it is the same as in register()
  robottelo/hosts.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.15.z, 6.16.z, 6.17.z, 6.18.z

#19443 facts test fix
  tests/foreman/ui/test_fact.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.18.z

#19451 [6.18.z] facts test fix
  tests/foreman/ui/test_fact.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19455 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19452 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19453 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19457 [6.17.z] Bump pytest-cov from 6.3.0 to 7.0.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19459 [6.16.z] Bump pytest-cov from 6.3.0 to 7.0.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19447 [6.17.z] disable insights in api_register() so it is the same as in register()
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19350 [6.18.z] Add new test for FAM with Kerberos (#19056)
  robottelo/constants/__init__.py
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Failed_AutoCherryPick, PRT-Passed

#19436 hosts subscribed property extension
  robottelo/hosts.py
Labels: CherryPick, Stream, 6.15.z, 6.16.z, 6.17.z, 6.18.z

#19470 [6.15.z] hosts subscribed property extension
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19473 [6.17.z] hosts subscribed property extension
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19471 [6.18.z] hosts subscribed property extension
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19461 [6.16.z] api_register_disable_insights
  robottelo/hosts.py
Labels: No-CherryPick, PRT-Passed, 6.16.z

#19469 [6.18.z] Check expected tasks for repo protection changes
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19331 Configure IPv6 system proxy to reach container registry to enable IoP
  robottelo/constants/__init__.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
Labels: TestFailure, CherryPick, PRT-Passed, 6.18.z

#19348 Fix job invocation and reading its status correctly
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_hostcollection.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.18.z

#19481 [6.18.z] API Registration Test Install from repo fix
  tests/foreman/ui/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19480 [6.18.z] Configure IPv6 system proxy to reach container registry to enable IoP
  robottelo/constants/__init__.py
  robottelo/host_helpers/satellite_mixins.py
  robottelo/hosts.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Failed, 6.18.z

#19508 [6.18.z] Remove stubb tests covered with test_provisioning.py::test_rhel_pxe_provisioning
  tests/foreman/api/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19525 [6.18.z] Fix failure due to different organization/location assignment
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19529 skip host_errata_info test for FAM
  tests/foreman/sys/test_fam.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.18.z

#19530 [6.18.z] skip host_errata_info test for FAM
  tests/foreman/sys/test_fam.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19537 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19540 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19526 Cover SAT-36783 in cockpit test
  tests/foreman/destructive/test_host.py
Labels: No-CherryPick, Stream

#19543 Adding network parameter in new upgrade's checkout fixtures module
  tests/new_upgrades/conftest.py
Labels: Upgrades, CherryPick, 6.16.z, 6.17.z, 6.18.z

#19547 [6.16.z] Adding network parameter in new upgrade's checkout fixtures module
  tests/new_upgrades/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19548 [6.18.z] Adding network parameter in new upgrade's checkout fixtures module
  tests/new_upgrades/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19558 [6.16.z] Bump pytest-mock from 3.15.0 to 3.15.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19557 [6.18.z] Bump pytest-mock from 3.15.0 to 3.15.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19563 [6.17.z] Bump manifester from 0.2.11 to 0.2.12
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.17.z

#19562 [6.15.z] Bump manifester from 0.2.11 to 0.2.12
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Passed

#19568 [6.18.z] Remove conditions for an unfixed bug
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19566 [6.16.z] Remove conditions for an unfixed bug
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#19560 destructive registration test fix
  tests/foreman/destructive/test_registration.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.18.z

#19243 Fix to read all details page
  tests/foreman/ui/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.18.z

#19572 [6.18.z] Fix to read all details page
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19574 [6.16.z] Fix test_positive_sync_kickstart_check_os
  tests/foreman/api/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.16.z

#19545 Update sat_maintain fixture to work with module_synced_repos fixture
  pytest_fixtures/component/maintain.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.18.z

#19561 [6.16.z] Bump manifester from 0.2.11 to 0.2.12
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, PRT-Failed, 6.16.z

#19552 [6.18.z] Update test_positive_install_iop_custom_certs for 6.18
  conf/rh_cloud.yaml.template
  tests/foreman/cli/test_rhcloud_inventory.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19583 [6.18.z] Bump ruff from 0.13.0 to 0.13.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19584 [6.15.z] Bump ruff from 0.13.0 to 0.13.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19585 [6.17.z] Bump ruff from 0.13.0 to 0.13.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19586 [6.16.z] Bump ruff from 0.13.0 to 0.13.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19589 [6.18.z] Fix and harden test_unprotected_status_repo_create_and_update
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19592 Add multiple libvirt image UUIDs to fam.yaml template
  conf/fam.yaml.template
Labels: Easy Fix :), CherryPick, 6.15.z, 6.16.z, 6.17.z, 6.18.z

#19590 [6.16.z] Fix and harden test_unprotected_status_repo_create_and_update
  tests/foreman/api/test_repositories.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.16.z

#19594 [6.18.z] Add multiple libvirt image UUIDs to fam.yaml template
  conf/fam.yaml.template
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19593 [6.15.z] Add multiple libvirt image UUIDs to fam.yaml template
  conf/fam.yaml.template
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#18282 [6.16.z] Retrieve the correct host info from the inventories.
  tests/foreman/cli/test_ansible.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.16.z

#19569 [6.18.z] Cover SAT-36783 in cockpit test (#19526)
  tests/foreman/destructive/test_host.py
Labels: No-CherryPick, PRT-Passed, 6.18.z

#19601 [6.18.z] Setup HTTP Proxy for f-m Satellite
  pytest_fixtures/component/maintain.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19581 Add test for content view environment endpoint
  tests/foreman/api/test_contentview.py
Labels: API, CherryPick, PRT-Passed, 6.16.z, 6.17.z, 6.18.z

#19600 Fix and improve libvirt image CRUD test
  tests/foreman/cli/test_computeresource_libvirt.py
Labels: TestFailure, QETestCoverage, CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19598 skip list available repositories test case due to Jira SAT-38447
  tests/foreman/cli/test_repository_set.py
Labels: TestFailure, CherryPick, Stream, PRT-Passed, 6.16.z, 6.17.z, 6.18.z

#19614 [6.15.z] Bump pytest-ibutsu from 2.3.1 to 3.1.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19616 [6.17.z] Bump pytest-ibutsu from 2.3.1 to 3.1.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19613 [6.16.z] Bump pytest-ibutsu from 2.3.1 to 3.1.0
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19532 Add a test case for ISS export format inheritance
  tests/foreman/cli/test_satellitesync.py
Labels: CherryPick, 6.18.z

#19623 [6.18.z] Add a test case for ISS export format inheritance
  tests/foreman/cli/test_satellitesync.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19626 report items renamed
  tests/foreman/data/usage_report.yml
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19635 [6.18.z] Fix test_negative_synchronize_private_registry_wrong_repo
  tests/foreman/api/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19632 [6.18.z] report items renamed
  tests/foreman/data/usage_report.yml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19652 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19653 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19631 [6.18.z] Updating hammer commands list
  tests/foreman/data/hammer_commands.json
Labels: No-CherryPick, 6.18.z

#19680 [6.18.z] Remove is_open from api/test_capsulecontent
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19679 [6.17.z] Remove is_open from api/test_capsulecontent
  tests/foreman/api/test_capsulecontent.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19685 [6.16.z] Bump pytest-ibutsu from 3.1.0 to 3.1.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19687 [6.17.z] Bump pytest-ibutsu from 3.1.0 to 3.1.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19686 [6.18.z] Bump pytest-ibutsu from 3.1.0 to 3.1.1
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19283 Add possibility to configure ansible role names in settings
  conf/ansible.yaml.template
  robottelo/config/validators.py
  tests/foreman/api/test_ansible.py
  tests/foreman/cli/test_ansible.py
Labels: CherryPick, 6.15.z, 6.16.z, 6.17.z, 6.18.z

#19664 [6.18.z] Remove polarion-test-run-upload.sh and polarion-test-case-upload.sh scripts
  pytest_plugins/requirements/req_updater.py
  requirements.txt
  scripts/polarion-test-case-upload.sh
  scripts/polarion-test-run-upload.sh
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19661 [6.17.z] Remove polarion-test-run-upload.sh and polarion-test-case-upload.sh scripts
  pytest_plugins/requirements/req_updater.py
  requirements.txt
  scripts/polarion-test-case-upload.sh
  scripts/polarion-test-run-upload.sh
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#19693 applyErratum Fix
  tests/foreman/ui/test_host.py
Labels: Easy Fix :), CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.18.z

#19272 Add e2e test for IoP vulnerability service
  pytest_fixtures/component/rh_cloud.py
  tests/foreman/ui/test_rhcloud_insights_vulnerability.py
Labels: QETestCoverage, No-CherryPick, Stream, PRT-Failed

#19531 [6.18.z] Add e2e test for IoP vulnerability service
  pytest_fixtures/component/rh_cloud.py
  tests/foreman/ui/test_rhcloud_insights_vulnerability.py
Labels: QETestCoverage, No-CherryPick, PRT-Failed, 6.18.z

#19671 Fixing remaining changes of PR-19543
  tests/new_upgrades/conftest.py
Labels: Upgrades, CherryPick, 6.15.z, 6.16.z, 6.17.z, 6.18.z

#19694 [6.18.z] applyErratum Fix
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19702 Cleanup of UI tests for Hosts component
  tests/foreman/ui/test_host.py
Labels: CherryPick, Stream, 6.18.z

#19701 different task description parsing
  tests/foreman/cli/test_logging.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19716 [6.18.z] different task description parsing
  tests/foreman/cli/test_logging.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19676 parameterisation for recommended repository test
  robottelo/constants/__init__.py
  tests/foreman/ui/test_repository.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z, 6.18.z

#19721 Changes to force a package profile upload
  tests/foreman/cli/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.18.z

#19725 [6.18.z] Changes to force a package profile upload
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19726 Refactor Hosts CLI PackageApplicability Tests
  tests/foreman/cli/test_host.py
Labels: CLI, CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.18.z

#19723 [6.18.z] coverage for posix ldap group membership
  tests/foreman/cli/test_ldapauthsource.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Failed, 6.18.z

#19738 [6.16.z] Bump pyyaml from 6.0.2 to 6.0.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19737 [6.17.z] Bump pyyaml from 6.0.2 to 6.0.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19739 [6.15.z] Bump pyyaml from 6.0.2 to 6.0.3
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19741 [6.18.z] Bump ruff from 0.13.1 to 0.13.2
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19743 [6.16.z] Bump ruff from 0.13.1 to 0.13.2
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19744 [6.15.z] Bump ruff from 0.13.1 to 0.13.2
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.15.z

#19742 [6.17.z] Bump ruff from 0.13.1 to 0.13.2
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19698 [6.16.z] Fixing remaining changes of PR-19543
  tests/new_upgrades/conftest.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19675 [6.17.z] Fixing scenarios test cases hanging issues
  robottelo/utils/shared_resource.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19755 [6.17.z] Bump pytest-ibutsu from 3.1.1 to 3.1.2
  requirements.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19761 Refactor CLI Errata Tests for Hosts component
  tests/foreman/cli/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.18.z

#19765 Fix test_content_validation_on_download
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z, 6.18.z

#19764 Reflect team changes in upgrades test ownership (#19573)
  tests/new_upgrades/test_capsulecontent.py
  tests/new_upgrades/test_computeresource_gce.py
  tests/new_upgrades/test_hostgroup.py
  tests/upgrades/test_capsulecontent.py
  tests/upgrades/test_computeresource_gce.py
  tests/upgrades/test_hostgroup.py
Labels: No-CherryPick, 6.16.z

#19769 fix grep commmand
  tests/foreman/cli/test_repository.py
Labels: TestFailure, CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z, 6.18.z

#19773 [6.17.z] fix grep commmand
  tests/foreman/cli/test_repository.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z
