Repository SatelliteQE/robottelo, pull requests merged in 2025-10, with the labels that each got.

#19796 remove PackageGroup Tests
  tests/foreman/ui/test_contenthost.py
Labels: CherryPick, Stream, 6.18.z

#19789 SAT-28485 Test to schedule a job in the past
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.18.z

#19798 [6.18.z] SAT-28485 Test to schedule a job in the past
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19628 Updating hammer commands list
  tests/foreman/data/hammer_commands.json
Labels: TestFailure, No-CherryPick, PRT-Passed

#19700 assertion fix on dashboard test
  tests/foreman/ui/test_dashboard.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19804 [6.17.z] block HWmodel test bcs of SAT-38893
  tests/foreman/ui/test_hardwaremodel.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19806 [6.18.z] block HWmodel test bcs of SAT-38893
  tests/foreman/ui/test_hardwaremodel.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19808 Fix test_cleanup_orphaned_content
  tests/foreman/api/test_capsulecontent.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19800 Narrow down test_selinux_status for pulp services only
  .github/CODEOWNERS
  tests/foreman/sys/test_pulp3_filesystem.py
Labels: CherryPick, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z, 6.18.z

#19822 [6.18.z] Remove CLI REX test from Hosts
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19825 [6.18.z] Remove outdated duplicate Host CLI test
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19827 [6.16.z] removeOutdatedDuplicateHostCliTest
  tests/foreman/cli/test_host.py
Labels: No-CherryPick, 6.16.z

#19829 [6.17.z] removing hosts from bookmark entities
  robottelo/constants/__init__.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.17.z

#19622 [6.18.z] Rework some assertions to match the data recieved from satellite
  tests/foreman/ui/test_errata.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19837 [6.16.z] Bump ruff from 0.13.2 to 0.13.3
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19845 [6.18.z] Fix test_ccv_inc_update_autopublish
  tests/foreman/cli/test_contentview.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19846 [6.17.z] Fix test_ccv_inc_update_autopublish
  tests/foreman/cli/test_contentview.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.17.z

#19222 job invocation: update for new job details page
  tests/foreman/ui/test_remoteexecution.py
Labels: CherryPick, PRT-Passed, 6.18.z

#19849 conversion to pull provider not for rhel10
  tests/foreman/cli/test_remoteexecution.py
Labels: CherryPick, Stream, 6.17.z, 6.18.z

#19864 [6.17.z] Exclude requirements from spellcheck
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19861 [6.16.z] Exclude requirements from spellcheck
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19858 Pin astroid to <4.0.0 to fix sphinx-autoapi compatibility
  requirements-optional.txt
Labels: CherryPick, 6.15.z, 6.16.z, 6.17.z, 6.18.z

#19867 [6.16.z] Pin astroid to <4.0.0 to fix sphinx-autoapi compatibility
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19865 [6.18.z] Pin astroid to <4.0.0 to fix sphinx-autoapi compatibility
  requirements-optional.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19850 Fix status code while Validation failed with content host registration
  tests/foreman/cli/test_host.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.18.z

#19852 skip session tests on SAT-38951
  tests/foreman/cli/test_auth.py
Labels: CherryPick, 6.18.z

#19859 Fix Registration API E2E test
  tests/foreman/api/test_registration.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.18.z

#19848 SAT-34258 Coverage
  tests/foreman/cli/test_registration.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, PRT-Passed, 6.17.z, 6.18.z

#19873 [6.18.z] skip session tests on SAT-38951
  tests/foreman/cli/test_auth.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19857 [6.17.z] conversion to pull provider not for rhel10
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19856 [6.18.z] conversion to pull provider not for rhel10
  tests/foreman/cli/test_remoteexecution.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19874 [6.18.z] Fix Registration API E2E test
  tests/foreman/api/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19870 Fix Registration CLI E2E test
  tests/foreman/cli/test_registration.py
Labels: CherryPick, AutoMerge_Cherry_Picked, Stream, 6.18.z

#19877 [6.18.z] Fix Registration CLI E2E test
  tests/foreman/cli/test_registration.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19834 Add destination server testing to ISS incremental export test
  tests/foreman/cli/test_satellitesync.py
Labels: CLI, CherryPick, 6.18.z

#19077 [6.17.z] Two Settings UI test fixes
  tests/foreman/ui/test_settings.py
Labels: No-CherryPick, Auto_Cherry_Picked, PRT-Passed, 6.17.z

#19886 [6.16.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19884 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19883 [6.18.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.18.z

#19896 [6.18.z] Fix flaky UI updateDeletePackage Test
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19897 [6.17.z] [SAT-26559] Incremental Update on a Version contained in a CompositeCV
  pytest_fixtures/component/repository.py
  tests/foreman/api/test_contentview.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#19892 [6.18.z] Bump sphinx-autoapi from 3.6.0 to 3.6.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z

#19893 [6.16.z] Bump sphinx-autoapi from 3.6.0 to 3.6.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#19894 [6.15.z] Bump sphinx-autoapi from 3.6.0 to 3.6.1
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#19909 [6.17.z] Bump ruff from 0.13.3 to 0.14.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.17.z

#19912 [6.16.z] Bump ruff from 0.13.3 to 0.14.0
  requirements-optional.txt
Labels: dependencies, No-CherryPick, Auto_Cherry_Picked, 6.16.z

#19918 Remove old ContentHost Module_stream test
  tests/foreman/ui/test_contenthost.py
  tests/foreman/ui/test_host.py
Labels: CherryPick, Stream, 6.18.z

#19920 [6.18.z] Fix FM maintenance-mode test for IoP
  tests/foreman/maintain/test_maintenance_mode.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, PRT-Passed, 6.18.z

#19923 [6.18.z] Fix Hosts UI E2E test
  tests/foreman/ui/test_host.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.18.z
